// Generated by HLC 4.2.5 (HL v4)
#ifndef INC_iron__object__FrustumPlane
#define INC_iron__object__FrustumPlane
typedef struct _iron__object__$FrustumPlane *iron__object__$FrustumPlane;
typedef struct _iron__object__FrustumPlane *iron__object__FrustumPlane;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <iron/math/Vec4.h>


struct _iron__object__$FrustumPlane {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _iron__object__FrustumPlane {
	hl_type *$type;
	iron__math__Vec4 normal;
	double constant;
};
#endif

