// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/object/MorphTarget.h>
#include <iron/data/TMorphTarget.h>
#include <hl/types/ArrayObj.h>
kha__arrays__ByteArrayPrivate kha_arrays__Float32Array_Float32Array_Impl___new(int);
#include <hl/natives.h>
extern String s$_morph_pos_png;
String String___add__(String,String);
extern hl_type t$fun_13f431a;
void iron_data_Data_getImage(String,vclosure*,bool*,String);
extern String s$_morph_nor_png;
extern hl_type t$haxe_ds_StringMap;
void haxe_ds_StringMap_new(haxe__ds__StringMap);
extern hl_type t$_i32;
void haxe_ds_StringMap_set(haxe__ds__StringMap,String,vdynamic*);

void iron_object_MorphTarget_new__$1(iron__object__MorphTarget r0,kha__Image r1) {
	if( !r1 ) goto label$1ef03f6_1_3;
	if( r0 == NULL ) hl_null_access();
	r0->morphDataPos = r1;
	label$1ef03f6_1_3:
	return;
}

void iron_object_MorphTarget_new__$2(iron__object__MorphTarget r0,kha__Image r1) {
	if( !r1 ) goto label$1ef03f6_2_3;
	if( r0 == NULL ) hl_null_access();
	r0->morphDataNor = r1;
	label$1ef03f6_2_3:
	return;
}

void iron_object_MorphTarget_new(iron__object__MorphTarget r0,iron__data__TMorphTarget r1) {
	bool *r18;
	String r15, r16;
	hl__types__ArrayObj r19;
	haxe__ds__StringMap r2;
	iron__object__MorphTarget r4;
	kha__arrays__ByteArrayPrivate r6, r7;
	float r11;
	vclosure *r17;
	vdynamic *r20, *r22;
	varray *r21;
	vbyte *r12;
	int r3, r8, r9, r10, r13, r14;
	r2 = NULL;
	r0->morphMap = r2;
	r3 = 0;
	r0->morphBlockSize = r3;
	r3 = 0;
	r0->morphImageSize = r3;
	r3 = 0;
	r0->numMorphTargets = r3;
	r4 = r0;
	if( r1 == NULL ) hl_null_access();
	r6 = r1->morph_target_defaults;
	if( r6 == NULL ) hl_null_access();
	r3 = r6->byteArrayLength;
	r8 = 2;
	r3 = r3 >> r8;
	r7 = kha_arrays__Float32Array_Float32Array_Impl___new(r3);
	r0->morphWeights = r7;
	r3 = 0;
	r7 = r0->morphWeights;
	if( r7 == NULL ) hl_null_access();
	r8 = r7->byteArrayLength;
	r9 = 2;
	r8 = r8 >> r9;
	label$1ef03f6_3_23:
	if( r3 >= r8 ) goto label$1ef03f6_3_43;
	r9 = r3;
	++r3;
	r7 = r0->morphWeights;
	if( r6 == NULL ) hl_null_access();
	r12 = r6->self;
	r10 = r6->byteArrayOffset;
	r14 = 4;
	r13 = r9 * r14;
	r10 = r10 + r13;
	r11 = hl_kinc_bytearray_getfloat32(r12,r10);
	if( r7 == NULL ) hl_null_access();
	r12 = r7->self;
	r10 = r7->byteArrayOffset;
	r14 = 4;
	r13 = r9 * r14;
	r10 = r10 + r13;
	hl_kinc_bytearray_setfloat32(r12,r10,r11);
	goto label$1ef03f6_3_23;
	label$1ef03f6_3_43:
	if( r1 == NULL ) hl_null_access();
	r11 = r1->morph_scale;
	r0->scaling = r11;
	r11 = r1->morph_offset;
	r0->offset = r11;
	r3 = r1->num_morph_targets;
	r0->numMorphTargets = r3;
	r3 = r1->morph_img_size;
	r0->morphImageSize = r3;
	r3 = r1->morph_block_size;
	r0->morphBlockSize = r3;
	r15 = r1->morph_target_data_file;
	r16 = (String)s$_morph_pos_png;
	r15 = String___add__(r15,r16);
	r17 = hl_alloc_closure_ptr(&t$fun_13f431a,iron_object_MorphTarget_new__$1,r4);
	r18 = NULL;
	r16 = NULL;
	iron_data_Data_getImage(r15,r17,r18,r16);
	r15 = r1->morph_target_data_file;
	r16 = (String)s$_morph_nor_png;
	r15 = String___add__(r15,r16);
	r17 = hl_alloc_closure_ptr(&t$fun_13f431a,iron_object_MorphTarget_new__$2,r4);
	r18 = NULL;
	r16 = NULL;
	iron_data_Data_getImage(r15,r17,r18,r16);
	r2 = (haxe__ds__StringMap)hl_alloc_obj(&t$haxe_ds_StringMap);
	haxe_ds_StringMap_new(r2);
	r0->morphMap = r2;
	r3 = 0;
	r8 = 0;
	r19 = r1->morph_target_ref;
	label$1ef03f6_3_74:
	if( r19 == NULL ) hl_null_access();
	r10 = r19->length;
	if( r8 >= r10 ) goto label$1ef03f6_3_92;
	r10 = r19->length;
	if( ((unsigned)r8) < ((unsigned)r10) ) goto label$1ef03f6_3_82;
	r15 = NULL;
	goto label$1ef03f6_3_85;
	label$1ef03f6_3_82:
	r21 = r19->array;
	r20 = ((vdynamic**)(r21 + 1))[r8];
	r15 = (String)r20;
	label$1ef03f6_3_85:
	++r8;
	r2 = r0->morphMap;
	if( r2 == NULL ) hl_null_access();
	r22 = hl_alloc_dynamic(&t$_i32);
	r22->v.i = r3;
	haxe_ds_StringMap_set(r2,r15,((vdynamic*)r22));
	++r3;
	goto label$1ef03f6_3_74;
	label$1ef03f6_3_92:
	return;
}

