// Generated by HLC 4.2.5 (HL v4)
#ifndef INC_iron__object__Uniforms
#define INC_iron__object__Uniforms
typedef struct _iron__object__$Uniforms *iron__object__$Uniforms;
typedef struct _iron__object__Uniforms *iron__object__Uniforms;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <iron/math/Mat4.h>
#include <iron/math/Mat3.h>
#include <iron/math/Vec4.h>
#include <iron/math/Quat.h>
#include <hl/types/ArrayObj.h>
#include <kha/graphics4/VertexBuffer.h>
#include <kha/Image.h>
#include <kha/graphics4/PipelineState.h>
#include <kha/math/FastMatrix3.h>
#include <kha/math/FastMatrix4.h>
#include <kha/graphics4/IndexBuffer.h>
#include <kha/arrays/ByteArrayPrivate.h>
#include <kha/graphics4/CubeMap.h>
#include <iron/data/ShaderContext.h>
#include <iron/object/Object.h>
#include <iron/RenderTarget.h>
#include <iron/data/TShaderConstant.h>
#include <iron/data/MaterialContext.h>
#include <iron/data/MaterialData.h>
#include <iron/data/TBindConstant.h>


struct _iron__object__$Uniforms {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	iron__math__Mat4 biasMat;
	iron__math__Mat4 helpMat;
	iron__math__Mat4 helpMat2;
	iron__math__Mat3 helpMat3;
	iron__math__Vec4 helpVec;
	iron__math__Vec4 helpVec2;
	iron__math__Quat helpQuat;
	hl__types__ArrayObj externalTextureLinks;
	hl__types__ArrayObj externalMat4Links;
	hl__types__ArrayObj externalVec4Links;
	hl__types__ArrayObj externalVec3Links;
	hl__types__ArrayObj externalVec2Links;
	hl__types__ArrayObj externalFloatLinks;
	hl__types__ArrayObj externalFloatsLinks;
	hl__types__ArrayObj externalIntLinks;
	vdynamic* posUnpack;
	vdynamic* texUnpack;
	int defaultFilter;
	vclosure* setContextConstants;
	vclosure* setObjectConstants;
	vclosure* bindRenderTarget;
	vclosure* setContextConstant;
	vclosure* setObjectConstant;
	vclosure* setMaterialConstants;
	vclosure* currentMat;
	vclosure* setMaterialConstant;
};
struct _iron__object__Uniforms {
	hl_type *$type;
};
#endif

