// Generated by HLC 4.2.5 (HL v4)
#ifndef INC_armory__data__Config
#define INC_armory__data__Config
typedef struct _armory__data__$Config *armory__data__$Config;
typedef struct _armory__data__Config *armory__data__Config;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _armory__data__$Config {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	vvirtual* raw;
};
struct _armory__data__Config {
	hl_type *$type;
};
#endif

