// Generated by HLC 4.2.5 (HL v4)
#ifndef INC_bullet___Bt__DefaultCollisionConfiguration_Impl_
#define INC_bullet___Bt__DefaultCollisionConfiguration_Impl_
typedef struct _bullet___Bt__$DefaultCollisionConfiguration_Impl_ *bullet___Bt__$DefaultCollisionConfiguration_Impl_;
typedef struct _bullet___Bt__DefaultCollisionConfiguration_Impl_ *bullet___Bt__DefaultCollisionConfiguration_Impl_;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _bullet___Bt__$DefaultCollisionConfiguration_Impl_ {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _bullet___Bt__DefaultCollisionConfiguration_Impl_ {
	hl_type *$type;
};
#endif

