// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <kha/arrays/_Uint32Array/Uint32Array_Impl_.h>
vbyte* kha_arrays__ByteBuffer_ByteBuffer_Impl__create(int);
extern hl_type t$kha_arrays_ByteArrayPrivate;
void kha_arrays_ByteArrayPrivate_new(kha__arrays__ByteArrayPrivate,int,int);

kha__arrays__ByteArrayPrivate kha_arrays__Uint32Array_Uint32Array_Impl___new(int r0) {
	kha__arrays__ByteArrayPrivate r5;
	vbyte *r4;
	int r1, r2;
	r2 = 4;
	r1 = r0 * r2;
	r4 = kha_arrays__ByteBuffer_ByteBuffer_Impl__create(r1);
	r5 = (kha__arrays__ByteArrayPrivate)hl_alloc_obj(&t$kha_arrays_ByteArrayPrivate);
	r2 = 0;
	kha_arrays_ByteArrayPrivate_new(r5,r2,r1);
	r5->self = r4;
	return r5;
}

