// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <armory/logicnode/AddObjectToGroupNode.h>
void armory_logicnode_LogicNode_new(armory__logicnode__LogicNode,armory__logicnode__LogicTree);
#include <armory/logicnode/LogicNodeLink.h>
#include <iron/object/Object.h>
#include <iron/Scene.h>
extern hl_type t$String;
extern hl_type t$_dyn;
extern hl_type t$iron_object_Object;
extern iron__$Scene g$_iron_Scene;
hl__types__ArrayObj iron_Scene_getGroup(iron__Scene,String);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
void armory_logicnode_LogicNode_runOutput(armory__logicnode__LogicNode,int);

void armory_logicnode_AddObjectToGroupNode_new(armory__logicnode__AddObjectToGroupNode r0,armory__logicnode__LogicTree r1) {
	armory_logicnode_LogicNode_new(((armory__logicnode__LogicNode)r0),r1);
	return;
}

void armory_logicnode_AddObjectToGroupNode_run(armory__logicnode__AddObjectToGroupNode r0,int r1) {
	String r11;
	armory__logicnode__LogicNodeLink r5, r10;
	hl__types__ArrayObj r2;
	iron__$Scene r14;
	iron__Scene r13;
	armory__logicnode__LogicNode r9;
	iron__object__Object r12;
	vdynamic *r6;
	varray *r7;
	int r3, r4;
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r3 = 1;
	r4 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$aef4795_2_7;
	r5 = NULL;
	goto label$aef4795_2_10;
	label$aef4795_2_7:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r3];
	r5 = (armory__logicnode__LogicNodeLink)r6;
	label$aef4795_2_10:
	if( r5 == NULL ) hl_null_access();
	r9 = r5->fromNode;
	if( r9 == NULL ) hl_null_access();
	r3 = r5->fromIndex;
	r6 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r9->$type->vobj_proto[1])(r9,r3);
	r11 = (String)hl_dyn_castp(&r6,&t$_dyn,&t$String);
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r3 = 2;
	r4 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$aef4795_2_23;
	r10 = NULL;
	goto label$aef4795_2_26;
	label$aef4795_2_23:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r3];
	r10 = (armory__logicnode__LogicNodeLink)r6;
	label$aef4795_2_26:
	if( r10 == NULL ) hl_null_access();
	r9 = r10->fromNode;
	if( r9 == NULL ) hl_null_access();
	r3 = r10->fromIndex;
	r6 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r9->$type->vobj_proto[1])(r9,r3);
	r12 = (iron__object__Object)hl_dyn_castp(&r6,&t$_dyn,&t$iron_object_Object);
	r14 = (iron__$Scene)g$_iron_Scene;
	r13 = r14->active;
	if( r13 == NULL ) hl_null_access();
	r2 = iron_Scene_getGroup(r13,r11);
	if( r2 == NULL ) hl_null_access();
	r3 = hl_types_ArrayObj_push(r2,((vdynamic*)r12));
	r3 = 0;
	armory_logicnode_LogicNode_runOutput(((armory__logicnode__LogicNode)r0),r3);
	return;
}

