// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <armory/logicnode/ArrayLoopNode.h>
void armory_logicnode_LogicNode_new(armory__logicnode__LogicNode,armory__logicnode__LogicTree);
#include <armory/logicnode/LogicNodeLink.h>
#include <hl/types/ArrayDyn.h>
extern hl_type t$hl_types_ArrayDyn;
extern hl_type t$_dyn;
int hl_types_ArrayDyn_get_length(hl__types__ArrayDyn);
void armory_logicnode_LogicNode_runOutput(armory__logicnode__LogicNode,int);
extern hl_type t$_i32;

void armory_logicnode_ArrayLoopNode_new(armory__logicnode__ArrayLoopNode r0,armory__logicnode__LogicTree r1) {
	armory_logicnode_LogicNode_new(((armory__logicnode__LogicNode)r0),r1);
	return;
}

void armory_logicnode_ArrayLoopNode_run(armory__logicnode__ArrayLoopNode r0,int r1) {
	armory__logicnode__LogicTree r13;
	armory__logicnode__LogicNodeLink r5;
	hl__types__ArrayObj r2;
	bool r12;
	armory__logicnode__LogicNode r9;
	hl__types__ArrayDyn r10;
	vdynamic *r6;
	varray *r7;
	int r3, r4, r11;
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r3 = 1;
	r4 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$e9ea9a7_2_7;
	r5 = NULL;
	goto label$e9ea9a7_2_10;
	label$e9ea9a7_2_7:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r3];
	r5 = (armory__logicnode__LogicNodeLink)r6;
	label$e9ea9a7_2_10:
	if( r5 == NULL ) hl_null_access();
	r9 = r5->fromNode;
	if( r9 == NULL ) hl_null_access();
	r3 = r5->fromIndex;
	r6 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r9->$type->vobj_proto[1])(r9,r3);
	r10 = (hl__types__ArrayDyn)hl_dyn_castp(&r6,&t$_dyn,&t$hl_types_ArrayDyn);
	if( r10 ) goto label$e9ea9a7_2_18;
	return;
	label$e9ea9a7_2_18:
	r3 = -1;
	r0->index = r3;
	r3 = 0;
	label$e9ea9a7_2_21:
	if( r10 == NULL ) hl_null_access();
	r11 = hl_types_ArrayDyn_get_length(r10);
	if( r3 >= r11 ) goto label$e9ea9a7_2_52;
	r6 = ((vdynamic* (*)(hl__types__ArrayDyn,int))r10->$type->vobj_proto[0])(r10,r3);
	++r3;
	r0->value = r6;
	r4 = r0->index;
	++r4;
	r0->index = r4;
	r4 = 0;
	armory_logicnode_LogicNode_runOutput(((armory__logicnode__LogicNode)r0),r4);
	r13 = r0->tree;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->loopBreak;
	if( !r12 ) goto label$e9ea9a7_2_42;
	r13 = r0->tree;
	if( r13 == NULL ) hl_null_access();
	r12 = false;
	r13->loopBreak = r12;
	goto label$e9ea9a7_2_52;
	label$e9ea9a7_2_42:
	r13 = r0->tree;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->loopContinue;
	if( !r12 ) goto label$e9ea9a7_2_51;
	r13 = r0->tree;
	if( r13 == NULL ) hl_null_access();
	r12 = false;
	r13->loopContinue = r12;
	goto label$e9ea9a7_2_21;
	label$e9ea9a7_2_51:
	goto label$e9ea9a7_2_21;
	label$e9ea9a7_2_52:
	r3 = 3;
	armory_logicnode_LogicNode_runOutput(((armory__logicnode__LogicNode)r0),r3);
	return;
}

vdynamic* armory_logicnode_ArrayLoopNode_get(armory__logicnode__ArrayLoopNode r0,int r1) {
	vdynamic *r4;
	int r2, r3;
	r3 = 1;
	if( r1 != r3 ) goto label$e9ea9a7_3_4;
	r4 = r0->value;
	return r4;
	label$e9ea9a7_3_4:
	r2 = r0->index;
	r4 = hl_alloc_dynamic(&t$_i32);
	r4->v.i = r2;
	return r4;
}

