// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <armory/logicnode/ColorNode.h>
#include <armory/logicnode/LogicNodeLink.h>
extern hl_type t$iron_math_Vec4;
void iron_math_Vec4_new(iron__math__Vec4,float*,float*,float*,float*);
void armory_logicnode_LogicNode_new(armory__logicnode__LogicNode,armory__logicnode__LogicTree);

vdynamic* armory_logicnode_ColorNode_get(armory__logicnode__ColorNode r0,int r1) {
	armory__logicnode__LogicNodeLink r5;
	hl__types__ArrayObj r3;
	iron__math__Vec4 r9;
	armory__logicnode__LogicNode r8;
	vdynamic *r6;
	varray *r7;
	int r2, r4;
	r3 = r0->inputs;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->length;
	r4 = 0;
	if( r4 >= r2 ) goto label$f6107ca_1_21;
	r3 = r0->inputs;
	if( r3 == NULL ) hl_null_access();
	r2 = 0;
	r4 = r3->length;
	if( ((unsigned)r2) < ((unsigned)r4) ) goto label$f6107ca_1_12;
	r5 = NULL;
	goto label$f6107ca_1_15;
	label$f6107ca_1_12:
	r7 = r3->array;
	r6 = ((vdynamic**)(r7 + 1))[r2];
	r5 = (armory__logicnode__LogicNodeLink)r6;
	label$f6107ca_1_15:
	if( r5 == NULL ) hl_null_access();
	r8 = r5->fromNode;
	if( r8 == NULL ) hl_null_access();
	r2 = r5->fromIndex;
	r6 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r8->$type->vobj_proto[1])(r8,r2);
	return r6;
	label$f6107ca_1_21:
	r9 = r0->value;
	return ((vdynamic*)r9);
}

void armory_logicnode_ColorNode_new(armory__logicnode__ColorNode r0,armory__logicnode__LogicTree r1,double* r2,double* r3,double* r4,double* r5) {
	iron__math__Vec4 r10;
	float r16;
	double r6, r7, r8, r9;
	float *r11, *r12, *r13, *r14;
	if( r2 ) goto label$f6107ca_2_3;
	r6 = 0.8000000000000000444;
	goto label$f6107ca_2_4;
	label$f6107ca_2_3:
	r6 = *r2;
	label$f6107ca_2_4:
	if( r3 ) goto label$f6107ca_2_7;
	r7 = 0.8000000000000000444;
	goto label$f6107ca_2_8;
	label$f6107ca_2_7:
	r7 = *r3;
	label$f6107ca_2_8:
	if( r4 ) goto label$f6107ca_2_11;
	r8 = 0.8000000000000000444;
	goto label$f6107ca_2_12;
	label$f6107ca_2_11:
	r8 = *r4;
	label$f6107ca_2_12:
	if( r5 ) goto label$f6107ca_2_15;
	r9 = 1.;
	goto label$f6107ca_2_16;
	label$f6107ca_2_15:
	r9 = *r5;
	label$f6107ca_2_16:
	r10 = (iron__math__Vec4)hl_alloc_obj(&t$iron_math_Vec4);
	r11 = NULL;
	r12 = NULL;
	r13 = NULL;
	r14 = NULL;
	iron_math_Vec4_new(r10,r11,r12,r13,r14);
	r0->value = r10;
	armory_logicnode_LogicNode_new(((armory__logicnode__LogicNode)r0),r1);
	r10 = r0->value;
	if( r10 == NULL ) hl_null_access();
	r16 = (float)r6;
	r10->x = r16;
	r16 = (float)r7;
	r10->y = r16;
	r16 = (float)r8;
	r10->z = r16;
	r16 = (float)r9;
	r10->w = r16;
	return;
}

