// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <armory/logicnode/DisplayInfoNode.h>
void armory_logicnode_LogicNode_new(armory__logicnode__LogicNode,armory__logicnode__LogicTree);
#include <kha/Display.h>
hl__types__ArrayObj kha_Display_get_all(void);
int kha_Display_get_width(kha__Display);
extern hl_type t$_i32;
int kha_Display_get_height(kha__Display);

void armory_logicnode_DisplayInfoNode_new(armory__logicnode__DisplayInfoNode r0,armory__logicnode__LogicTree r1) {
	armory_logicnode_LogicNode_new(((armory__logicnode__LogicNode)r0),r1);
	return;
}

vdynamic* armory_logicnode_DisplayInfoNode_get(armory__logicnode__DisplayInfoNode r0,int r1) {
	hl__types__ArrayObj r4;
	kha__Display r5;
	vdynamic *r6;
	varray *r7;
	int r2, r3;
	r3 = 0;
	if( r1 != r3 ) goto label$1eb0c4f_2_16;
	r4 = kha_Display_get_all();
	if( r4 == NULL ) hl_null_access();
	r2 = 0;
	r3 = r4->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$1eb0c4f_2_9;
	r5 = NULL;
	goto label$1eb0c4f_2_12;
	label$1eb0c4f_2_9:
	r7 = r4->array;
	r6 = ((vdynamic**)(r7 + 1))[r2];
	r5 = (kha__Display)r6;
	label$1eb0c4f_2_12:
	if( r5 == NULL ) hl_null_access();
	r2 = kha_Display_get_width(r5);
	r6 = hl_alloc_dynamic(&t$_i32);
	r6->v.i = r2;
	return r6;
	label$1eb0c4f_2_16:
	r4 = kha_Display_get_all();
	if( r4 == NULL ) hl_null_access();
	r2 = 0;
	r3 = r4->length;
	if( ((unsigned)r2) < ((unsigned)r3) ) goto label$1eb0c4f_2_23;
	r5 = NULL;
	goto label$1eb0c4f_2_26;
	label$1eb0c4f_2_23:
	r7 = r4->array;
	r6 = ((vdynamic**)(r7 + 1))[r2];
	r5 = (kha__Display)r6;
	label$1eb0c4f_2_26:
	if( r5 == NULL ) hl_null_access();
	r2 = kha_Display_get_height(r5);
	r6 = hl_alloc_dynamic(&t$_i32);
	r6->v.i = r2;
	return r6;
}

