// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <armory/logicnode/GetMouseMovementNode.h>
void armory_logicnode_LogicNode_new(armory__logicnode__LogicNode,armory__logicnode__LogicTree);
#include <iron/system/Mouse.h>
#include <armory/logicnode/LogicNodeLink.h>
iron__system__Mouse iron_system_Input_getMouse(void);
extern hl_type t$_dyn;
extern hl_type t$_i32;
extern hl_type t$_f64;
extern hl_type t$_f32;

void armory_logicnode_GetMouseMovementNode_new(armory__logicnode__GetMouseMovementNode r0,armory__logicnode__LogicTree r1) {
	armory_logicnode_LogicNode_new(((armory__logicnode__LogicNode)r0),r1);
	return;
}

vdynamic* armory_logicnode_GetMouseMovementNode_get(armory__logicnode__GetMouseMovementNode r0,int r1) {
	armory__logicnode__LogicNodeLink r6, r10, r12;
	hl__types__ArrayObj r3;
	iron__system__Mouse r2;
	armory__logicnode__LogicNode r9;
	float r11, r13, r14, r16;
	double r15, r17;
	vdynamic *r7;
	varray *r8;
	int r4, r5;
	r2 = iron_system_Input_getMouse();
	r3 = r0->inputs;
	if( r3 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r3->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$43af056_2_8;
	r6 = NULL;
	goto label$43af056_2_11;
	label$43af056_2_8:
	r8 = r3->array;
	r7 = ((vdynamic**)(r8 + 1))[r4];
	r6 = (armory__logicnode__LogicNodeLink)r7;
	label$43af056_2_11:
	if( r6 == NULL ) hl_null_access();
	r9 = r6->fromNode;
	if( r9 == NULL ) hl_null_access();
	r4 = r6->fromIndex;
	r7 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r9->$type->vobj_proto[1])(r9,r4);
	r11 = (float)hl_dyn_castf(&r7,&t$_dyn);
	r3 = r0->inputs;
	if( r3 == NULL ) hl_null_access();
	r4 = 1;
	r5 = r3->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$43af056_2_24;
	r10 = NULL;
	goto label$43af056_2_27;
	label$43af056_2_24:
	r8 = r3->array;
	r7 = ((vdynamic**)(r8 + 1))[r4];
	r10 = (armory__logicnode__LogicNodeLink)r7;
	label$43af056_2_27:
	if( r10 == NULL ) hl_null_access();
	r9 = r10->fromNode;
	if( r9 == NULL ) hl_null_access();
	r4 = r10->fromIndex;
	r7 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r9->$type->vobj_proto[1])(r9,r4);
	r13 = (float)hl_dyn_castf(&r7,&t$_dyn);
	r3 = r0->inputs;
	if( r3 == NULL ) hl_null_access();
	r4 = 2;
	r5 = r3->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$43af056_2_40;
	r12 = NULL;
	goto label$43af056_2_43;
	label$43af056_2_40:
	r8 = r3->array;
	r7 = ((vdynamic**)(r8 + 1))[r4];
	r12 = (armory__logicnode__LogicNodeLink)r7;
	label$43af056_2_43:
	if( r12 == NULL ) hl_null_access();
	r9 = r12->fromNode;
	if( r9 == NULL ) hl_null_access();
	r4 = r12->fromIndex;
	r7 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r9->$type->vobj_proto[1])(r9,r4);
	r14 = (float)hl_dyn_castf(&r7,&t$_dyn);
	switch(r1) {
		default:
			r4 = 0;
			r7 = hl_alloc_dynamic(&t$_i32);
			r7->v.i = r4;
			return r7;
		case 0:
			if( r2 == NULL ) hl_null_access();
			r15 = r2->movementX;
			r7 = hl_alloc_dynamic(&t$_f64);
			r7->v.d = r15;
			return r7;
		case 1:
			if( r2 == NULL ) hl_null_access();
			r15 = r2->movementY;
			r7 = hl_alloc_dynamic(&t$_f64);
			r7->v.d = r15;
			return r7;
		case 2:
			if( r2 == NULL ) hl_null_access();
			r15 = r2->movementX;
			r17 = (double)r11;
			r15 = r15 * r17;
			r7 = hl_alloc_dynamic(&t$_f64);
			r7->v.d = r15;
			return r7;
		case 3:
			if( r2 == NULL ) hl_null_access();
			r15 = r2->movementY;
			r17 = (double)r13;
			r15 = r15 * r17;
			r7 = hl_alloc_dynamic(&t$_f64);
			r7->v.d = r15;
			return r7;
		case 4:
			if( r2 == NULL ) hl_null_access();
			r4 = r2->wheelDelta;
			r7 = hl_alloc_dynamic(&t$_i32);
			r7->v.i = r4;
			return r7;
		case 5:
			if( r2 == NULL ) hl_null_access();
			r4 = r2->wheelDelta;
			r16 = (float)r4;
			r16 = r16 * r14;
			r7 = hl_alloc_dynamic(&t$_f32);
			r7->v.f = r16;
			return r7;
	}
}

