// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <armory/logicnode/GetObjectNode.h>
void armory_logicnode_LogicNode_new(armory__logicnode__LogicNode,armory__logicnode__LogicTree);
#include <armory/logicnode/LogicNodeLink.h>
#include <iron/object/Object.h>
#include <iron/Scene.h>
extern hl_type t$String;
extern hl_type t$_dyn;
extern iron__$Scene g$_iron_Scene;
iron__object__Object iron_Scene_getChild(iron__Scene,String);

void armory_logicnode_GetObjectNode_new(armory__logicnode__GetObjectNode r0,armory__logicnode__LogicTree r1) {
	armory_logicnode_LogicNode_new(((armory__logicnode__LogicNode)r0),r1);
	return;
}

vdynamic* armory_logicnode_GetObjectNode_get(armory__logicnode__GetObjectNode r0,int r1) {
	String r9;
	armory__logicnode__LogicNodeLink r5;
	hl__types__ArrayObj r2;
	iron__$Scene r12;
	iron__Scene r11;
	armory__logicnode__LogicNode r8;
	iron__object__Object r10;
	vdynamic *r6;
	varray *r7;
	int r3, r4;
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r3 = 0;
	r4 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$b1d939b_2_7;
	r5 = NULL;
	goto label$b1d939b_2_10;
	label$b1d939b_2_7:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r3];
	r5 = (armory__logicnode__LogicNodeLink)r6;
	label$b1d939b_2_10:
	if( r5 == NULL ) hl_null_access();
	r8 = r5->fromNode;
	if( r8 == NULL ) hl_null_access();
	r3 = r5->fromIndex;
	r6 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r8->$type->vobj_proto[1])(r8,r3);
	r9 = (String)hl_dyn_castp(&r6,&t$_dyn,&t$String);
	r12 = (iron__$Scene)g$_iron_Scene;
	r11 = r12->active;
	if( r11 == NULL ) hl_null_access();
	r10 = iron_Scene_getChild(r11,r9);
	return ((vdynamic*)r10);
}

