// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <armory/logicnode/MathNode.h>
void armory_logicnode_LogicNode_new(armory__logicnode__LogicNode,armory__logicnode__LogicTree);
extern hl_type t$_i32;
#include <hl/natives.h>
#include <armory/logicnode/LogicNodeLink.h>
extern hl_type t$_dyn;
double Math_max(double,double);
double Math_min(double,double);
extern hl_type t$nul_i32;
extern hl_type t$_f64;

void armory_logicnode_MathNode_new(armory__logicnode__MathNode r0,armory__logicnode__LogicTree r1) {
	armory_logicnode_LogicNode_new(((armory__logicnode__LogicNode)r0),r1);
	return;
}

double armory_logicnode_MathNode_round(double r0,vdynamic* r1) {
	double r3, r5, r6;
	vdynamic *r4;
	int r2;
	if( r1 ) goto label$9d82f56_2_3;
	r2 = 2;
	r1 = hl_alloc_dynamic(&t$_i32);
	r1->v.i = r2;
	label$9d82f56_2_3:
	r2 = r1 ? r1->v.i : 0;
	r3 = (double)r2;
	r3 = hl_math_abs(r3);
	r2 = hl_math_round(r3);
	r4 = hl_alloc_dynamic(&t$_i32);
	r4->v.i = r2;
	r5 = 10.;
	r2 = r4 ? r4->v.i : 0;
	r6 = (double)r2;
	r5 = hl_math_pow(r5,r6);
	r3 = r0 * r5;
	r2 = hl_math_round(r3);
	r3 = (double)r2;
	r5 = 10.;
	r2 = r4 ? r4->v.i : 0;
	r6 = (double)r2;
	r5 = hl_math_pow(r5,r6);
	r3 = r3 / r5;
	return r3;
}

double armory_logicnode_MathNode_fract(armory__logicnode__MathNode r0,double r1) {
	double r2, r4;
	int r3;
	r3 = hl_math_floor(r1);
	r4 = (double)r3;
	r2 = r1 - r4;
	return r2;
}

double armory_logicnode_MathNode_pingpong(armory__logicnode__MathNode r0,double r1,double r2) {
	double r3, r4, r5;
	r4 = 0.;
	if( r2 != r4 ) goto label$9d82f56_4_4;
	r3 = 0.;
	return r3;
	label$9d82f56_4_4:
	r3 = r1 - r2;
	r5 = 2.;
	r4 = r2 * r5;
	r3 = r3 / r4;
	r3 = armory_logicnode_MathNode_fract(r0,r3);
	r3 = r3 * r2;
	r4 = 2.;
	r3 = r3 * r4;
	r3 = r3 - r2;
	r3 = hl_math_abs(r3);
	return r3;
}

vdynamic* armory_logicnode_MathNode_get(armory__logicnode__MathNode r0,int r1) {
	String r3;
	armory__logicnode__LogicNodeLink r9, r14;
	hl__types__ArrayObj r8;
	bool r21;
	armory__logicnode__LogicNode r13;
	double r2, r12, r16, r18;
	vdynamic *r10, *r17, *r19, *r20;
	varray *r11;
	vbyte *r6, *r7;
	int r4, r5, r15;
	r2 = 0.;
	r3 = r0->property0;
	if( !r3 ) goto label$9d82f56_5_11;
	r4 = r3->length;
	r5 = 3;
	if( r4 != r5 ) goto label$9d82f56_5_11;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Abs");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_237;
	label$9d82f56_5_11:
	if( !r3 ) goto label$9d82f56_5_20;
	r4 = r3->length;
	r5 = 3;
	if( r4 != r5 ) goto label$9d82f56_5_20;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Add");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_256;
	label$9d82f56_5_20:
	if( !r3 ) goto label$9d82f56_5_29;
	r4 = r3->length;
	r5 = 9;
	if( r4 != r5 ) goto label$9d82f56_5_29;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Arccosine");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_280;
	label$9d82f56_5_29:
	if( !r3 ) goto label$9d82f56_5_38;
	r4 = r3->length;
	r5 = 7;
	if( r4 != r5 ) goto label$9d82f56_5_38;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Arcsine");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_299;
	label$9d82f56_5_38:
	if( !r3 ) goto label$9d82f56_5_47;
	r4 = r3->length;
	r5 = 7;
	if( r4 != r5 ) goto label$9d82f56_5_47;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Arctan2");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_318;
	label$9d82f56_5_47:
	if( !r3 ) goto label$9d82f56_5_56;
	r4 = r3->length;
	r5 = 10;
	if( r4 != r5 ) goto label$9d82f56_5_56;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Arctangent");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_353;
	label$9d82f56_5_56:
	if( !r3 ) goto label$9d82f56_5_65;
	r4 = r3->length;
	r5 = 4;
	if( r4 != r5 ) goto label$9d82f56_5_65;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Ceil");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_372;
	label$9d82f56_5_65:
	if( !r3 ) goto label$9d82f56_5_74;
	r4 = r3->length;
	r5 = 6;
	if( r4 != r5 ) goto label$9d82f56_5_74;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Cosine");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_392;
	label$9d82f56_5_74:
	if( !r3 ) goto label$9d82f56_5_83;
	r4 = r3->length;
	r5 = 6;
	if( r4 != r5 ) goto label$9d82f56_5_83;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Divide");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_411;
	label$9d82f56_5_83:
	if( !r3 ) goto label$9d82f56_5_92;
	r4 = r3->length;
	r5 = 3;
	if( r4 != r5 ) goto label$9d82f56_5_92;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Exp");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_454;
	label$9d82f56_5_92:
	if( !r3 ) goto label$9d82f56_5_101;
	r4 = r3->length;
	r5 = 5;
	if( r4 != r5 ) goto label$9d82f56_5_101;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Floor");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_473;
	label$9d82f56_5_101:
	if( !r3 ) goto label$9d82f56_5_110;
	r4 = r3->length;
	r5 = 5;
	if( r4 != r5 ) goto label$9d82f56_5_110;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Fract");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_493;
	label$9d82f56_5_110:
	if( !r3 ) goto label$9d82f56_5_119;
	r4 = r3->length;
	r5 = 12;
	if( r4 != r5 ) goto label$9d82f56_5_119;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Greater Than");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_514;
	label$9d82f56_5_119:
	if( !r3 ) goto label$9d82f56_5_128;
	r4 = r3->length;
	r5 = 9;
	if( r4 != r5 ) goto label$9d82f56_5_128;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Less Than");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_550;
	label$9d82f56_5_128:
	if( !r3 ) goto label$9d82f56_5_137;
	r4 = r3->length;
	r5 = 9;
	if( r4 != r5 ) goto label$9d82f56_5_137;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Logarithm");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_586;
	label$9d82f56_5_137:
	if( !r3 ) goto label$9d82f56_5_146;
	r4 = r3->length;
	r5 = 3;
	if( r4 != r5 ) goto label$9d82f56_5_146;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Max");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_605;
	label$9d82f56_5_146:
	if( !r3 ) goto label$9d82f56_5_155;
	r4 = r3->length;
	r5 = 3;
	if( r4 != r5 ) goto label$9d82f56_5_155;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Min");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_640;
	label$9d82f56_5_155:
	if( !r3 ) goto label$9d82f56_5_164;
	r4 = r3->length;
	r5 = 6;
	if( r4 != r5 ) goto label$9d82f56_5_164;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Modulo");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_675;
	label$9d82f56_5_164:
	if( !r3 ) goto label$9d82f56_5_173;
	r4 = r3->length;
	r5 = 8;
	if( r4 != r5 ) goto label$9d82f56_5_173;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Multiply");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_711;
	label$9d82f56_5_173:
	if( !r3 ) goto label$9d82f56_5_182;
	r4 = r3->length;
	r5 = 9;
	if( r4 != r5 ) goto label$9d82f56_5_182;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Ping-Pong");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_754;
	label$9d82f56_5_182:
	if( !r3 ) goto label$9d82f56_5_191;
	r4 = r3->length;
	r5 = 5;
	if( r4 != r5 ) goto label$9d82f56_5_191;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Power");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_789;
	label$9d82f56_5_191:
	if( !r3 ) goto label$9d82f56_5_200;
	r4 = r3->length;
	r5 = 5;
	if( r4 != r5 ) goto label$9d82f56_5_200;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Round");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_824;
	label$9d82f56_5_200:
	if( !r3 ) goto label$9d82f56_5_209;
	r4 = r3->length;
	r5 = 4;
	if( r4 != r5 ) goto label$9d82f56_5_209;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Sine");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_859;
	label$9d82f56_5_209:
	if( !r3 ) goto label$9d82f56_5_218;
	r4 = r3->length;
	r5 = 11;
	if( r4 != r5 ) goto label$9d82f56_5_218;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Square Root");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_878;
	label$9d82f56_5_218:
	if( !r3 ) goto label$9d82f56_5_227;
	r4 = r3->length;
	r5 = 8;
	if( r4 != r5 ) goto label$9d82f56_5_227;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Subtract");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_897;
	label$9d82f56_5_227:
	if( !r3 ) goto label$9d82f56_5_236;
	r4 = r3->length;
	r5 = 7;
	if( r4 != r5 ) goto label$9d82f56_5_236;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("Tangent");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$9d82f56_5_940;
	label$9d82f56_5_236:
	goto label$9d82f56_5_958;
	label$9d82f56_5_237:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_244;
	r9 = NULL;
	goto label$9d82f56_5_247;
	label$9d82f56_5_244:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_247:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r12 = (double)hl_dyn_castd(&r10,&t$_dyn);
	r12 = hl_math_abs(r12);
	r2 = r12;
	goto label$9d82f56_5_958;
	label$9d82f56_5_256:
	r4 = 0;
	r8 = r0->inputs;
	label$9d82f56_5_258:
	if( r8 == NULL ) hl_null_access();
	r15 = r8->length;
	if( r4 >= r15 ) goto label$9d82f56_5_279;
	r15 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r15) ) goto label$9d82f56_5_266;
	r9 = NULL;
	goto label$9d82f56_5_269;
	label$9d82f56_5_266:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_269:
	++r4;
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r5 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r5);
	r16 = (double)hl_dyn_castd(&r10,&t$_dyn);
	r12 = r2 + r16;
	r2 = r12;
	goto label$9d82f56_5_258;
	label$9d82f56_5_279:
	goto label$9d82f56_5_958;
	label$9d82f56_5_280:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_287;
	r9 = NULL;
	goto label$9d82f56_5_290;
	label$9d82f56_5_287:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_290:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r12 = (double)hl_dyn_castd(&r10,&t$_dyn);
	r12 = hl_math_acos(r12);
	r2 = r12;
	goto label$9d82f56_5_958;
	label$9d82f56_5_299:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_306;
	r9 = NULL;
	goto label$9d82f56_5_309;
	label$9d82f56_5_306:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_309:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r12 = (double)hl_dyn_castd(&r10,&t$_dyn);
	r12 = hl_math_asin(r12);
	r2 = r12;
	goto label$9d82f56_5_958;
	label$9d82f56_5_318:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_325;
	r9 = NULL;
	goto label$9d82f56_5_328;
	label$9d82f56_5_325:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_328:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 1;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_340;
	r14 = NULL;
	goto label$9d82f56_5_343;
	label$9d82f56_5_340:
	r11 = r8->array;
	r17 = ((vdynamic**)(r11 + 1))[r4];
	r14 = (armory__logicnode__LogicNodeLink)r17;
	label$9d82f56_5_343:
	r12 = (double)hl_dyn_castd(&r10,&t$_dyn);
	if( r14 == NULL ) hl_null_access();
	r13 = r14->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r14->fromIndex;
	r17 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r16 = (double)hl_dyn_castd(&r17,&t$_dyn);
	r12 = hl_math_atan2(r12,r16);
	r2 = r12;
	goto label$9d82f56_5_958;
	label$9d82f56_5_353:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_360;
	r9 = NULL;
	goto label$9d82f56_5_363;
	label$9d82f56_5_360:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_363:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r12 = (double)hl_dyn_castd(&r10,&t$_dyn);
	r12 = hl_math_atan(r12);
	r2 = r12;
	goto label$9d82f56_5_958;
	label$9d82f56_5_372:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_379;
	r9 = NULL;
	goto label$9d82f56_5_382;
	label$9d82f56_5_379:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_382:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r12 = (double)hl_dyn_castd(&r10,&t$_dyn);
	r4 = hl_math_ceil(r12);
	r12 = (double)r4;
	r2 = r12;
	goto label$9d82f56_5_958;
	label$9d82f56_5_392:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_399;
	r9 = NULL;
	goto label$9d82f56_5_402;
	label$9d82f56_5_399:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_402:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r12 = (double)hl_dyn_castd(&r10,&t$_dyn);
	r12 = hl_math_cos(r12);
	r2 = r12;
	goto label$9d82f56_5_958;
	label$9d82f56_5_411:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_418;
	r9 = NULL;
	goto label$9d82f56_5_421;
	label$9d82f56_5_418:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_421:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r12 = (double)hl_dyn_castd(&r10,&t$_dyn);
	r2 = r12;
	r4 = 1;
	label$9d82f56_5_429:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r15 = r8->length;
	if( r4 >= r15 ) goto label$9d82f56_5_453;
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r15 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r15) ) goto label$9d82f56_5_440;
	r14 = NULL;
	goto label$9d82f56_5_443;
	label$9d82f56_5_440:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r14 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_443:
	if( r14 == NULL ) hl_null_access();
	r13 = r14->fromNode;
	if( r13 == NULL ) hl_null_access();
	r5 = r14->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r5);
	r16 = (double)hl_dyn_castd(&r10,&t$_dyn);
	r12 = r2 / r16;
	r2 = r12;
	++r4;
	goto label$9d82f56_5_429;
	label$9d82f56_5_453:
	goto label$9d82f56_5_958;
	label$9d82f56_5_454:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_461;
	r9 = NULL;
	goto label$9d82f56_5_464;
	label$9d82f56_5_461:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_464:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r12 = (double)hl_dyn_castd(&r10,&t$_dyn);
	r12 = hl_math_exp(r12);
	r2 = r12;
	goto label$9d82f56_5_958;
	label$9d82f56_5_473:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_480;
	r9 = NULL;
	goto label$9d82f56_5_483;
	label$9d82f56_5_480:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_483:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r12 = (double)hl_dyn_castd(&r10,&t$_dyn);
	r4 = hl_math_floor(r12);
	r12 = (double)r4;
	r2 = r12;
	goto label$9d82f56_5_958;
	label$9d82f56_5_493:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_500;
	r9 = NULL;
	goto label$9d82f56_5_503;
	label$9d82f56_5_500:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_503:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r12 = (double)hl_dyn_castd(&r10,&t$_dyn);
	r4 = (int)r12;
	r18 = (double)r4;
	r16 = r12 - r18;
	r2 = r16;
	goto label$9d82f56_5_958;
	label$9d82f56_5_514:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_521;
	r9 = NULL;
	goto label$9d82f56_5_524;
	label$9d82f56_5_521:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_524:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 1;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_536;
	r14 = NULL;
	goto label$9d82f56_5_539;
	label$9d82f56_5_536:
	r11 = r8->array;
	r17 = ((vdynamic**)(r11 + 1))[r4];
	r14 = (armory__logicnode__LogicNodeLink)r17;
	label$9d82f56_5_539:
	if( r14 == NULL ) hl_null_access();
	r13 = r14->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r14->fromIndex;
	r19 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	{ int i = hl_dyn_compare((vdynamic*)r19,(vdynamic*)r10); if( i >= 0 && i != hl_invalid_comparison ) goto label$9d82f56_5_547; };
	r12 = 1.;
	goto label$9d82f56_5_548;
	label$9d82f56_5_547:
	r12 = 0.;
	label$9d82f56_5_548:
	r2 = r12;
	goto label$9d82f56_5_958;
	label$9d82f56_5_550:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_557;
	r9 = NULL;
	goto label$9d82f56_5_560;
	label$9d82f56_5_557:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_560:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 1;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_572;
	r14 = NULL;
	goto label$9d82f56_5_575;
	label$9d82f56_5_572:
	r11 = r8->array;
	r17 = ((vdynamic**)(r11 + 1))[r4];
	r14 = (armory__logicnode__LogicNodeLink)r17;
	label$9d82f56_5_575:
	if( r14 == NULL ) hl_null_access();
	r13 = r14->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r14->fromIndex;
	r19 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	{ int i = hl_dyn_compare((vdynamic*)r10,(vdynamic*)r19); if( i >= 0 && i != hl_invalid_comparison ) goto label$9d82f56_5_583; };
	r12 = 1.;
	goto label$9d82f56_5_584;
	label$9d82f56_5_583:
	r12 = 0.;
	label$9d82f56_5_584:
	r2 = r12;
	goto label$9d82f56_5_958;
	label$9d82f56_5_586:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_593;
	r9 = NULL;
	goto label$9d82f56_5_596;
	label$9d82f56_5_593:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_596:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r12 = (double)hl_dyn_castd(&r10,&t$_dyn);
	r12 = hl_math_log(r12);
	r2 = r12;
	goto label$9d82f56_5_958;
	label$9d82f56_5_605:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_612;
	r9 = NULL;
	goto label$9d82f56_5_615;
	label$9d82f56_5_612:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_615:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 1;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_627;
	r14 = NULL;
	goto label$9d82f56_5_630;
	label$9d82f56_5_627:
	r11 = r8->array;
	r17 = ((vdynamic**)(r11 + 1))[r4];
	r14 = (armory__logicnode__LogicNodeLink)r17;
	label$9d82f56_5_630:
	r12 = (double)hl_dyn_castd(&r10,&t$_dyn);
	if( r14 == NULL ) hl_null_access();
	r13 = r14->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r14->fromIndex;
	r17 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r16 = (double)hl_dyn_castd(&r17,&t$_dyn);
	r12 = Math_max(r12,r16);
	r2 = r12;
	goto label$9d82f56_5_958;
	label$9d82f56_5_640:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_647;
	r9 = NULL;
	goto label$9d82f56_5_650;
	label$9d82f56_5_647:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_650:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 1;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_662;
	r14 = NULL;
	goto label$9d82f56_5_665;
	label$9d82f56_5_662:
	r11 = r8->array;
	r17 = ((vdynamic**)(r11 + 1))[r4];
	r14 = (armory__logicnode__LogicNodeLink)r17;
	label$9d82f56_5_665:
	r12 = (double)hl_dyn_castd(&r10,&t$_dyn);
	if( r14 == NULL ) hl_null_access();
	r13 = r14->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r14->fromIndex;
	r17 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r16 = (double)hl_dyn_castd(&r17,&t$_dyn);
	r12 = Math_min(r12,r16);
	r2 = r12;
	goto label$9d82f56_5_958;
	label$9d82f56_5_675:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_682;
	r9 = NULL;
	goto label$9d82f56_5_685;
	label$9d82f56_5_682:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_685:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 1;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_697;
	r14 = NULL;
	goto label$9d82f56_5_700;
	label$9d82f56_5_697:
	r11 = r8->array;
	r17 = ((vdynamic**)(r11 + 1))[r4];
	r14 = (armory__logicnode__LogicNodeLink)r17;
	label$9d82f56_5_700:
	r4 = (int)hl_dyn_casti(&r10,&t$_dyn,&t$_i32);
	if( r14 == NULL ) hl_null_access();
	r13 = r14->fromNode;
	if( r13 == NULL ) hl_null_access();
	r5 = r14->fromIndex;
	r17 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r5);
	r5 = (int)hl_dyn_casti(&r17,&t$_dyn,&t$_i32);
	r4 = r5 == 0 ? 0 : r4 % r5;
	r12 = (double)r4;
	r2 = r12;
	goto label$9d82f56_5_958;
	label$9d82f56_5_711:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_718;
	r9 = NULL;
	goto label$9d82f56_5_721;
	label$9d82f56_5_718:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_721:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r12 = (double)hl_dyn_castd(&r10,&t$_dyn);
	r2 = r12;
	r4 = 1;
	label$9d82f56_5_729:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r15 = r8->length;
	if( r4 >= r15 ) goto label$9d82f56_5_753;
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r15 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r15) ) goto label$9d82f56_5_740;
	r14 = NULL;
	goto label$9d82f56_5_743;
	label$9d82f56_5_740:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r14 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_743:
	if( r14 == NULL ) hl_null_access();
	r13 = r14->fromNode;
	if( r13 == NULL ) hl_null_access();
	r5 = r14->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r5);
	r16 = (double)hl_dyn_castd(&r10,&t$_dyn);
	r12 = r2 * r16;
	r2 = r12;
	++r4;
	goto label$9d82f56_5_729;
	label$9d82f56_5_753:
	goto label$9d82f56_5_958;
	label$9d82f56_5_754:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_761;
	r9 = NULL;
	goto label$9d82f56_5_764;
	label$9d82f56_5_761:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_764:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 1;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_776;
	r14 = NULL;
	goto label$9d82f56_5_779;
	label$9d82f56_5_776:
	r11 = r8->array;
	r17 = ((vdynamic**)(r11 + 1))[r4];
	r14 = (armory__logicnode__LogicNodeLink)r17;
	label$9d82f56_5_779:
	r12 = (double)hl_dyn_castd(&r10,&t$_dyn);
	if( r14 == NULL ) hl_null_access();
	r13 = r14->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r14->fromIndex;
	r17 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r16 = (double)hl_dyn_castd(&r17,&t$_dyn);
	r12 = armory_logicnode_MathNode_pingpong(r0,r12,r16);
	r2 = r12;
	goto label$9d82f56_5_958;
	label$9d82f56_5_789:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_796;
	r9 = NULL;
	goto label$9d82f56_5_799;
	label$9d82f56_5_796:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_799:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 1;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_811;
	r14 = NULL;
	goto label$9d82f56_5_814;
	label$9d82f56_5_811:
	r11 = r8->array;
	r17 = ((vdynamic**)(r11 + 1))[r4];
	r14 = (armory__logicnode__LogicNodeLink)r17;
	label$9d82f56_5_814:
	r12 = (double)hl_dyn_castd(&r10,&t$_dyn);
	if( r14 == NULL ) hl_null_access();
	r13 = r14->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r14->fromIndex;
	r17 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r16 = (double)hl_dyn_castd(&r17,&t$_dyn);
	r12 = hl_math_pow(r12,r16);
	r2 = r12;
	goto label$9d82f56_5_958;
	label$9d82f56_5_824:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_831;
	r9 = NULL;
	goto label$9d82f56_5_834;
	label$9d82f56_5_831:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_834:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 1;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_846;
	r14 = NULL;
	goto label$9d82f56_5_849;
	label$9d82f56_5_846:
	r11 = r8->array;
	r17 = ((vdynamic**)(r11 + 1))[r4];
	r14 = (armory__logicnode__LogicNodeLink)r17;
	label$9d82f56_5_849:
	r12 = (double)hl_dyn_castd(&r10,&t$_dyn);
	if( r14 == NULL ) hl_null_access();
	r13 = r14->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r14->fromIndex;
	r17 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r20 = (vdynamic*)hl_dyn_castp(&r17,&t$_dyn,&t$nul_i32);
	r12 = armory_logicnode_MathNode_round(r12,r20);
	r2 = r12;
	goto label$9d82f56_5_958;
	label$9d82f56_5_859:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_866;
	r9 = NULL;
	goto label$9d82f56_5_869;
	label$9d82f56_5_866:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_869:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r12 = (double)hl_dyn_castd(&r10,&t$_dyn);
	r12 = hl_math_sin(r12);
	r2 = r12;
	goto label$9d82f56_5_958;
	label$9d82f56_5_878:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_885;
	r9 = NULL;
	goto label$9d82f56_5_888;
	label$9d82f56_5_885:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_888:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r12 = (double)hl_dyn_castd(&r10,&t$_dyn);
	r12 = hl_math_sqrt(r12);
	r2 = r12;
	goto label$9d82f56_5_958;
	label$9d82f56_5_897:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_904;
	r9 = NULL;
	goto label$9d82f56_5_907;
	label$9d82f56_5_904:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_907:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r12 = (double)hl_dyn_castd(&r10,&t$_dyn);
	r2 = r12;
	r4 = 1;
	label$9d82f56_5_915:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r15 = r8->length;
	if( r4 >= r15 ) goto label$9d82f56_5_939;
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r15 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r15) ) goto label$9d82f56_5_926;
	r14 = NULL;
	goto label$9d82f56_5_929;
	label$9d82f56_5_926:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r14 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_929:
	if( r14 == NULL ) hl_null_access();
	r13 = r14->fromNode;
	if( r13 == NULL ) hl_null_access();
	r5 = r14->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r5);
	r16 = (double)hl_dyn_castd(&r10,&t$_dyn);
	r12 = r2 - r16;
	r2 = r12;
	++r4;
	goto label$9d82f56_5_915;
	label$9d82f56_5_939:
	goto label$9d82f56_5_958;
	label$9d82f56_5_940:
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$9d82f56_5_947;
	r9 = NULL;
	goto label$9d82f56_5_950;
	label$9d82f56_5_947:
	r11 = r8->array;
	r10 = ((vdynamic**)(r11 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r10;
	label$9d82f56_5_950:
	if( r9 == NULL ) hl_null_access();
	r13 = r9->fromNode;
	if( r13 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r10 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r13->$type->vobj_proto[1])(r13,r4);
	r12 = (double)hl_dyn_castd(&r10,&t$_dyn);
	r12 = hl_math_tan(r12);
	r2 = r12;
	label$9d82f56_5_958:
	r21 = r0->property1;
	if( !r21 ) goto label$9d82f56_5_969;
	r16 = 0.;
	if( !(r2 < r16) ) goto label$9d82f56_5_965;
	r12 = 0.;
	r2 = r12;
	goto label$9d82f56_5_969;
	label$9d82f56_5_965:
	r16 = 1.;
	if( !(r16 < r2) ) goto label$9d82f56_5_969;
	r12 = 1.;
	r2 = r12;
	label$9d82f56_5_969:
	r10 = hl_alloc_dynamic(&t$_f64);
	r10->v.d = r2;
	return r10;
}

