// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <armory/logicnode/MergedKeyboardNode.h>
void armory_logicnode_LogicNode_new(armory__logicnode__LogicNode,armory__logicnode__LogicTree);
void armory_logicnode_MergedKeyboardNode_update(armory__logicnode__MergedKeyboardNode);
extern hl_type t$fun_e271a2f;
#include <iron/Trait.h>
void iron_Trait_notifyOnUpdate(iron__Trait,vclosure*);
#include <iron/system/Keyboard.h>
iron__system__Keyboard iron_system_Input_getKeyboard(void);
#include <hl/natives.h>
bool iron_system_Keyboard_down(iron__system__Keyboard,String);
bool iron_system_Keyboard_released(iron__system__Keyboard,String);
bool iron_system_Keyboard_started(iron__system__Keyboard,String);
void armory_logicnode_LogicNode_runOutput(armory__logicnode__LogicNode,int);

void armory_logicnode_MergedKeyboardNode_new(armory__logicnode__MergedKeyboardNode r0,armory__logicnode__LogicTree r1) {
	vclosure *r3;
	armory_logicnode_LogicNode_new(((armory__logicnode__LogicNode)r0),r1);
	if( r1 == NULL ) hl_null_access();
	r3 = hl_alloc_closure_ptr(&t$fun_e271a2f,armory_logicnode_MergedKeyboardNode_update,r0);
	iron_Trait_notifyOnUpdate(((iron__Trait)r1),r3);
	return;
}

void armory_logicnode_MergedKeyboardNode_update(armory__logicnode__MergedKeyboardNode r0) {
	String r4;
	bool r3, r9;
	iron__system__Keyboard r1;
	vbyte *r7, *r8;
	int r5, r6;
	r1 = iron_system_Input_getKeyboard();
	r3 = false;
	r4 = r0->property0;
	if( !r4 ) goto label$603b4bc_2_12;
	r5 = r4->length;
	r6 = 4;
	if( r5 != r6 ) goto label$603b4bc_2_12;
	r7 = r4->bytes;
	r8 = (vbyte*)USTR("down");
	r5 = hl_string_compare(r7,r8,r5);
	r6 = 0;
	if( r5 == r6 ) goto label$603b4bc_2_31;
	label$603b4bc_2_12:
	if( !r4 ) goto label$603b4bc_2_21;
	r5 = r4->length;
	r6 = 8;
	if( r5 != r6 ) goto label$603b4bc_2_21;
	r7 = r4->bytes;
	r8 = (vbyte*)USTR("released");
	r5 = hl_string_compare(r7,r8,r5);
	r6 = 0;
	if( r5 == r6 ) goto label$603b4bc_2_36;
	label$603b4bc_2_21:
	if( !r4 ) goto label$603b4bc_2_30;
	r5 = r4->length;
	r6 = 7;
	if( r5 != r6 ) goto label$603b4bc_2_30;
	r7 = r4->bytes;
	r8 = (vbyte*)USTR("started");
	r5 = hl_string_compare(r7,r8,r5);
	r6 = 0;
	if( r5 == r6 ) goto label$603b4bc_2_41;
	label$603b4bc_2_30:
	goto label$603b4bc_2_45;
	label$603b4bc_2_31:
	if( r1 == NULL ) hl_null_access();
	r4 = r0->property1;
	r9 = iron_system_Keyboard_down(r1,r4);
	r3 = r9;
	goto label$603b4bc_2_45;
	label$603b4bc_2_36:
	if( r1 == NULL ) hl_null_access();
	r4 = r0->property1;
	r9 = iron_system_Keyboard_released(r1,r4);
	r3 = r9;
	goto label$603b4bc_2_45;
	label$603b4bc_2_41:
	if( r1 == NULL ) hl_null_access();
	r4 = r0->property1;
	r9 = iron_system_Keyboard_started(r1,r4);
	r3 = r9;
	label$603b4bc_2_45:
	if( !r3 ) goto label$603b4bc_2_48;
	r5 = 0;
	armory_logicnode_LogicNode_runOutput(((armory__logicnode__LogicNode)r0),r5);
	label$603b4bc_2_48:
	return;
}

vdynamic* armory_logicnode_MergedKeyboardNode_get(armory__logicnode__MergedKeyboardNode r0,int r1) {
	String r3;
	bool r8;
	iron__system__Keyboard r2;
	vdynamic *r9;
	vbyte *r6, *r7;
	int r4, r5;
	r2 = iron_system_Input_getKeyboard();
	r3 = r0->property0;
	if( !r3 ) goto label$603b4bc_3_11;
	r4 = r3->length;
	r5 = 4;
	if( r4 != r5 ) goto label$603b4bc_3_11;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("down");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$603b4bc_3_30;
	label$603b4bc_3_11:
	if( !r3 ) goto label$603b4bc_3_20;
	r4 = r3->length;
	r5 = 8;
	if( r4 != r5 ) goto label$603b4bc_3_20;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("released");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$603b4bc_3_35;
	label$603b4bc_3_20:
	if( !r3 ) goto label$603b4bc_3_29;
	r4 = r3->length;
	r5 = 7;
	if( r4 != r5 ) goto label$603b4bc_3_29;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("started");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$603b4bc_3_40;
	label$603b4bc_3_29:
	goto label$603b4bc_3_45;
	label$603b4bc_3_30:
	if( r2 == NULL ) hl_null_access();
	r3 = r0->property1;
	r8 = iron_system_Keyboard_down(r2,r3);
	r9 = hl_alloc_dynbool(r8);
	return r9;
	label$603b4bc_3_35:
	if( r2 == NULL ) hl_null_access();
	r3 = r0->property1;
	r8 = iron_system_Keyboard_released(r2,r3);
	r9 = hl_alloc_dynbool(r8);
	return r9;
	label$603b4bc_3_40:
	if( r2 == NULL ) hl_null_access();
	r3 = r0->property1;
	r8 = iron_system_Keyboard_started(r2,r3);
	r9 = hl_alloc_dynbool(r8);
	return r9;
	label$603b4bc_3_45:
	r8 = false;
	r9 = hl_alloc_dynbool(r8);
	return r9;
}

