// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <armory/logicnode/NotNode.h>
void armory_logicnode_LogicNode_new(armory__logicnode__LogicNode,armory__logicnode__LogicTree);
#include <armory/logicnode/LogicNodeLink.h>
extern hl_type t$_bool;
extern hl_type t$_dyn;

void armory_logicnode_NotNode_new(armory__logicnode__NotNode r0,armory__logicnode__LogicTree r1) {
	armory_logicnode_LogicNode_new(((armory__logicnode__LogicNode)r0),r1);
	return;
}

vdynamic* armory_logicnode_NotNode_get(armory__logicnode__NotNode r0,int r1) {
	armory__logicnode__LogicNodeLink r5;
	hl__types__ArrayObj r2;
	bool r9, r10;
	armory__logicnode__LogicNode r8;
	vdynamic *r6;
	varray *r7;
	int r3, r4;
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r3 = 0;
	r4 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$53a4efa_2_7;
	r5 = NULL;
	goto label$53a4efa_2_10;
	label$53a4efa_2_7:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r3];
	r5 = (armory__logicnode__LogicNodeLink)r6;
	label$53a4efa_2_10:
	if( r5 == NULL ) hl_null_access();
	r8 = r5->fromNode;
	if( r8 == NULL ) hl_null_access();
	r3 = r5->fromIndex;
	r6 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r8->$type->vobj_proto[1])(r8,r3);
	r9 = (bool)hl_dyn_casti(&r6,&t$_dyn,&t$_bool);
	r10 = !r9;
	r6 = hl_alloc_dynbool(r10);
	return r6;
}

