// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <armory/logicnode/OnTimerNode.h>
#include <armory/logicnode/LogicNodeLink.h>
extern hl_type t$_dyn;
extern hl_type t$_bool;
double iron_system_Time_get_delta(void);
extern hl_type t$fun_fa8ca24;
#include <iron/Trait.h>
void iron_Trait_removeUpdate(iron__Trait,vclosure*);
void armory_logicnode_LogicNode_runOutput(armory__logicnode__LogicNode,int);
void armory_logicnode_LogicNode_new(armory__logicnode__LogicNode,armory__logicnode__LogicTree);
void iron_Trait_notifyOnUpdate(iron__Trait,vclosure*);

void armory_logicnode_OnTimerNode_update(armory__logicnode__OnTimerNode r0) {
	armory__logicnode__LogicTree r13;
	armory__logicnode__LogicNodeLink r7, r11;
	hl__types__ArrayObj r4;
	bool r12;
	armory__logicnode__LogicNode r10;
	vclosure *r14;
	double r2, r3;
	vdynamic *r8;
	varray *r9;
	int r5, r6;
	r2 = r0->duration;
	r3 = 0.;
	if( !(r3 >= r2) ) goto label$c4ad850_1_37;
	r4 = r0->inputs;
	if( r4 == NULL ) hl_null_access();
	r5 = 0;
	r6 = r4->length;
	if( ((unsigned)r5) < ((unsigned)r6) ) goto label$c4ad850_1_10;
	r7 = NULL;
	goto label$c4ad850_1_13;
	label$c4ad850_1_10:
	r9 = r4->array;
	r8 = ((vdynamic**)(r9 + 1))[r5];
	r7 = (armory__logicnode__LogicNodeLink)r8;
	label$c4ad850_1_13:
	if( r7 == NULL ) hl_null_access();
	r10 = r7->fromNode;
	if( r10 == NULL ) hl_null_access();
	r5 = r7->fromIndex;
	r8 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r10->$type->vobj_proto[1])(r10,r5);
	r2 = (double)hl_dyn_castd(&r8,&t$_dyn);
	r0->duration = r2;
	r4 = r0->inputs;
	if( r4 == NULL ) hl_null_access();
	r5 = 1;
	r6 = r4->length;
	if( ((unsigned)r5) < ((unsigned)r6) ) goto label$c4ad850_1_27;
	r11 = NULL;
	goto label$c4ad850_1_30;
	label$c4ad850_1_27:
	r9 = r4->array;
	r8 = ((vdynamic**)(r9 + 1))[r5];
	r11 = (armory__logicnode__LogicNodeLink)r8;
	label$c4ad850_1_30:
	if( r11 == NULL ) hl_null_access();
	r10 = r11->fromNode;
	if( r10 == NULL ) hl_null_access();
	r5 = r11->fromIndex;
	r8 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r10->$type->vobj_proto[1])(r10,r5);
	r12 = (bool)hl_dyn_casti(&r8,&t$_dyn,&t$_bool);
	r0->repeat = r12;
	label$c4ad850_1_37:
	r2 = r0->duration;
	r3 = iron_system_Time_get_delta();
	r2 = r2 - r3;
	r0->duration = r2;
	r2 = r0->duration;
	r3 = 0.;
	if( !(r3 >= r2) ) goto label$c4ad850_1_52;
	r12 = r0->repeat;
	if( r12 ) goto label$c4ad850_1_50;
	r13 = r0->tree;
	if( r13 == NULL ) hl_null_access();
	r14 = hl_alloc_closure_ptr(&t$fun_fa8ca24,armory_logicnode_OnTimerNode_update,r0);
	iron_Trait_removeUpdate(((iron__Trait)r13),r14);
	label$c4ad850_1_50:
	r5 = 0;
	armory_logicnode_LogicNode_runOutput(((armory__logicnode__LogicNode)r0),r5);
	label$c4ad850_1_52:
	return;
}

void armory_logicnode_OnTimerNode_new(armory__logicnode__OnTimerNode r0,armory__logicnode__LogicTree r1) {
	bool r2;
	vclosure *r5;
	double r3;
	r2 = false;
	r0->repeat = r2;
	r3 = 0.;
	r0->duration = r3;
	armory_logicnode_LogicNode_new(((armory__logicnode__LogicNode)r0),r1);
	if( r1 == NULL ) hl_null_access();
	r5 = hl_alloc_closure_ptr(&t$fun_fa8ca24,armory_logicnode_OnTimerNode_update,r0);
	iron_Trait_notifyOnUpdate(((iron__Trait)r1),r5);
	return;
}

