// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <armory/logicnode/OnUpdateNode.h>
void armory_logicnode_LogicNode_new(armory__logicnode__LogicNode,armory__logicnode__LogicTree);
void armory_logicnode_OnUpdateNode_init(armory__logicnode__OnUpdateNode);
extern hl_type t$fun_e66dc03;
#include <iron/Trait.h>
void iron_Trait_notifyOnInit(iron__Trait,vclosure*);
#include <armory/trait/physics/bullet/PhysicsWorld.h>
#include <hl/natives.h>
void armory_logicnode_OnUpdateNode_update(armory__logicnode__OnUpdateNode);
void iron_Trait_notifyOnUpdate(iron__Trait,vclosure*);
void iron_Trait_notifyOnLateUpdate(iron__Trait,vclosure*);
extern armory__trait__physics__bullet__$PhysicsWorld g$e9bc575;
void armory_trait_physics_bullet_PhysicsWorld_notifyOnPreUpdate(armory__trait__physics__bullet__PhysicsWorld,vclosure*);
void armory_logicnode_LogicNode_runOutput(armory__logicnode__LogicNode,int);

void armory_logicnode_OnUpdateNode_new(armory__logicnode__OnUpdateNode r0,armory__logicnode__LogicTree r1) {
	vclosure *r3;
	armory_logicnode_LogicNode_new(((armory__logicnode__LogicNode)r0),r1);
	if( r1 == NULL ) hl_null_access();
	r3 = hl_alloc_closure_ptr(&t$fun_e66dc03,armory_logicnode_OnUpdateNode_init,r0);
	iron_Trait_notifyOnInit(((iron__Trait)r1),r3);
	return;
}

void armory_logicnode_OnUpdateNode_init(armory__logicnode__OnUpdateNode r0) {
	armory__trait__physics__bullet__PhysicsWorld r9;
	String r2;
	armory__trait__physics__bullet__$PhysicsWorld r10;
	armory__logicnode__LogicTree r7;
	vclosure *r8;
	vbyte *r5, *r6;
	int r3, r4;
	r2 = r0->property0;
	if( !r2 ) goto label$aca277c_2_10;
	r3 = r2->length;
	r4 = 11;
	if( r3 != r4 ) goto label$aca277c_2_10;
	r5 = r2->bytes;
	r6 = (vbyte*)USTR("Late Update");
	r3 = hl_string_compare(r5,r6,r3);
	r4 = 0;
	if( r3 == r4 ) goto label$aca277c_2_24;
	label$aca277c_2_10:
	if( !r2 ) goto label$aca277c_2_19;
	r3 = r2->length;
	r4 = 18;
	if( r3 != r4 ) goto label$aca277c_2_19;
	r5 = r2->bytes;
	r6 = (vbyte*)USTR("Physics Pre-Update");
	r3 = hl_string_compare(r5,r6,r3);
	r4 = 0;
	if( r3 == r4 ) goto label$aca277c_2_29;
	label$aca277c_2_19:
	r7 = r0->tree;
	if( r7 == NULL ) hl_null_access();
	r8 = hl_alloc_closure_ptr(&t$fun_e66dc03,armory_logicnode_OnUpdateNode_update,r0);
	iron_Trait_notifyOnUpdate(((iron__Trait)r7),r8);
	goto label$aca277c_2_34;
	label$aca277c_2_24:
	r7 = r0->tree;
	if( r7 == NULL ) hl_null_access();
	r8 = hl_alloc_closure_ptr(&t$fun_e66dc03,armory_logicnode_OnUpdateNode_update,r0);
	iron_Trait_notifyOnLateUpdate(((iron__Trait)r7),r8);
	goto label$aca277c_2_34;
	label$aca277c_2_29:
	r10 = (armory__trait__physics__bullet__$PhysicsWorld)g$e9bc575;
	r9 = r10->active;
	if( r9 == NULL ) hl_null_access();
	r8 = hl_alloc_closure_ptr(&t$fun_e66dc03,armory_logicnode_OnUpdateNode_update,r0);
	armory_trait_physics_bullet_PhysicsWorld_notifyOnPreUpdate(r9,r8);
	label$aca277c_2_34:
	return;
}

void armory_logicnode_OnUpdateNode_update(armory__logicnode__OnUpdateNode r0) {
	int r2;
	r2 = 0;
	armory_logicnode_LogicNode_runOutput(((armory__logicnode__LogicNode)r0),r2);
	return;
}

