// Generated by HLC 4.2.5 (HL v4)
#ifndef INC_armory__logicnode__OnUpdateNode
#define INC_armory__logicnode__OnUpdateNode
typedef struct _armory__logicnode__$OnUpdateNode *armory__logicnode__$OnUpdateNode;
typedef struct _armory__logicnode__OnUpdateNode *armory__logicnode__OnUpdateNode;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <armory/logicnode/LogicNode.h>
#include <armory/logicnode/LogicTree.h>
#include <hl/types/ArrayObj.h>


struct _armory__logicnode__$OnUpdateNode {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _armory__logicnode__OnUpdateNode {
	hl_type *$type;
	armory__logicnode__LogicTree tree;
	hl__types__ArrayObj inputs;
	hl__types__ArrayObj outputs;
	String property0;
};
#endif

