// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <armory/logicnode/PrintNode.h>
void armory_logicnode_LogicNode_new(armory__logicnode__LogicNode,armory__logicnode__LogicTree);
#include <armory/logicnode/LogicNodeLink.h>
#include <hl/types/ArrayDyn.h>
#include <haxe/Log.h>
extern haxe__$Log g$_haxe_Log;
extern hl_type t$vrt_329ffa8;
extern String s$dbe2055;
extern hl_type t$String;
extern hl_type t$_i32;
extern String s$armory_logicnode_PrintNode;
extern String s$run;
extern hl_type t$vrt_eaa6a3b;
void armory_logicnode_LogicNode_runOutput(armory__logicnode__LogicNode,int);

void armory_logicnode_PrintNode_new(armory__logicnode__PrintNode r0,armory__logicnode__LogicTree r1) {
	armory_logicnode_LogicNode_new(((armory__logicnode__LogicNode)r0),r1);
	return;
}

void armory_logicnode_PrintNode_run(armory__logicnode__PrintNode r0,int r1) {
	String r13;
	vvirtual *r12, *r14;
	armory__logicnode__LogicNodeLink r5;
	hl__types__ArrayObj r2;
	haxe__$Log r11;
	armory__logicnode__LogicNode r9;
	vclosure *r10;
	vdynamic *r6;
	varray *r7;
	int r3, r4;
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r3 = 1;
	r4 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$d5df399_2_7;
	r5 = NULL;
	goto label$d5df399_2_10;
	label$d5df399_2_7:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r3];
	r5 = (armory__logicnode__LogicNodeLink)r6;
	label$d5df399_2_10:
	if( r5 == NULL ) hl_null_access();
	r9 = r5->fromNode;
	if( r9 == NULL ) hl_null_access();
	r3 = r5->fromIndex;
	r6 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r9->$type->vobj_proto[1])(r9,r3);
	r11 = (haxe__$Log)g$_haxe_Log;
	r10 = r11->trace;
	if( r10 == NULL ) hl_null_access();
	r12 = hl_alloc_virtual(&t$vrt_329ffa8);
	r13 = (String)s$dbe2055;
	if( hl_vfields(r12)[1] ) *(String*)(hl_vfields(r12)[1]) = (String)r13; else hl_dyn_setp(r12->value,37969014/*fileName*/,&t$String,r13);
	r3 = 15;
	if( hl_vfields(r12)[2] ) *(int*)(hl_vfields(r12)[2]) = (int)r3; else hl_dyn_seti(r12->value,371360620/*lineNumber*/,&t$_i32,r3);
	r13 = (String)s$armory_logicnode_PrintNode;
	if( hl_vfields(r12)[0] ) *(String*)(hl_vfields(r12)[0]) = (String)r13; else hl_dyn_setp(r12->value,-63073762/*className*/,&t$String,r13);
	r13 = (String)s$run;
	if( hl_vfields(r12)[3] ) *(String*)(hl_vfields(r12)[3]) = (String)r13; else hl_dyn_setp(r12->value,302979532/*methodName*/,&t$String,r13);
	r14 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r12);
	r10->hasValue ? ((void (*)(vdynamic*,vdynamic*,vvirtual*))r10->fun)((vdynamic*)r10->value,r6,r14) : ((void (*)(vdynamic*,vvirtual*))r10->fun)(r6,r14);
	r3 = 0;
	armory_logicnode_LogicNode_runOutput(((armory__logicnode__LogicNode)r0),r3);
	return;
}

