// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <armory/logicnode/RandomIntegerNode.h>
void armory_logicnode_LogicNode_new(armory__logicnode__LogicNode,armory__logicnode__LogicTree);
#include <armory/logicnode/LogicNodeLink.h>
extern hl_type t$_i32;
extern hl_type t$_dyn;
int Std_random(int);

void armory_logicnode_RandomIntegerNode_new(armory__logicnode__RandomIntegerNode r0,armory__logicnode__LogicTree r1) {
	armory_logicnode_LogicNode_new(((armory__logicnode__LogicNode)r0),r1);
	return;
}

vdynamic* armory_logicnode_RandomIntegerNode_get(armory__logicnode__RandomIntegerNode r0,int r1) {
	armory__logicnode__LogicNodeLink r5, r9;
	hl__types__ArrayObj r2;
	armory__logicnode__LogicNode r8;
	vdynamic *r6;
	varray *r7;
	int r3, r4, r10, r11;
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r3 = 0;
	r4 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$70bf235_2_7;
	r5 = NULL;
	goto label$70bf235_2_10;
	label$70bf235_2_7:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r3];
	r5 = (armory__logicnode__LogicNodeLink)r6;
	label$70bf235_2_10:
	if( r5 == NULL ) hl_null_access();
	r8 = r5->fromNode;
	if( r8 == NULL ) hl_null_access();
	r3 = r5->fromIndex;
	r6 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r8->$type->vobj_proto[1])(r8,r3);
	r3 = (int)hl_dyn_casti(&r6,&t$_dyn,&t$_i32);
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r4 = 1;
	r10 = r2->length;
	if( ((unsigned)r4) < ((unsigned)r10) ) goto label$70bf235_2_23;
	r9 = NULL;
	goto label$70bf235_2_26;
	label$70bf235_2_23:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r4];
	r9 = (armory__logicnode__LogicNodeLink)r6;
	label$70bf235_2_26:
	if( r9 == NULL ) hl_null_access();
	r8 = r9->fromNode;
	if( r8 == NULL ) hl_null_access();
	r4 = r9->fromIndex;
	r6 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r8->$type->vobj_proto[1])(r8,r4);
	r4 = (int)hl_dyn_casti(&r6,&t$_dyn,&t$_i32);
	r11 = r4 - r3;
	r11 = Std_random(r11);
	r10 = r3 + r11;
	r6 = hl_alloc_dynamic(&t$_i32);
	r6->v.i = r10;
	return r6;
}

