// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <armory/logicnode/RandomFloatNode.h>
void armory_logicnode_LogicNode_new(armory__logicnode__LogicNode,armory__logicnode__LogicTree);
#include <armory/logicnode/LogicNodeLink.h>
extern hl_type t$_dyn;
double Math_random(void);
extern hl_type t$_f64;

void armory_logicnode_RandomFloatNode_new(armory__logicnode__RandomFloatNode r0,armory__logicnode__LogicTree r1) {
	armory_logicnode_LogicNode_new(((armory__logicnode__LogicNode)r0),r1);
	return;
}

vdynamic* armory_logicnode_RandomFloatNode_get(armory__logicnode__RandomFloatNode r0,int r1) {
	armory__logicnode__LogicNodeLink r5, r9;
	hl__types__ArrayObj r2;
	armory__logicnode__LogicNode r8;
	double r10, r11, r12, r13, r14;
	vdynamic *r6;
	varray *r7;
	int r3, r4;
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r3 = 0;
	r4 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$e10ab85_2_7;
	r5 = NULL;
	goto label$e10ab85_2_10;
	label$e10ab85_2_7:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r3];
	r5 = (armory__logicnode__LogicNodeLink)r6;
	label$e10ab85_2_10:
	if( r5 == NULL ) hl_null_access();
	r8 = r5->fromNode;
	if( r8 == NULL ) hl_null_access();
	r3 = r5->fromIndex;
	r6 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r8->$type->vobj_proto[1])(r8,r3);
	r10 = (double)hl_dyn_castd(&r6,&t$_dyn);
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r3 = 1;
	r4 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$e10ab85_2_23;
	r9 = NULL;
	goto label$e10ab85_2_26;
	label$e10ab85_2_23:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r3];
	r9 = (armory__logicnode__LogicNodeLink)r6;
	label$e10ab85_2_26:
	if( r9 == NULL ) hl_null_access();
	r8 = r9->fromNode;
	if( r8 == NULL ) hl_null_access();
	r3 = r9->fromIndex;
	r6 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r8->$type->vobj_proto[1])(r8,r3);
	r11 = (double)hl_dyn_castd(&r6,&t$_dyn);
	r13 = Math_random();
	r14 = r11 - r10;
	r13 = r13 * r14;
	r12 = r10 + r13;
	r6 = hl_alloc_dynamic(&t$_f64);
	r6->v.d = r12;
	return r6;
}

