// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <armory/logicnode/VectorMathNode.h>
#include <armory/logicnode/LogicNodeLink.h>
extern hl_type t$iron_math_Vec4;
extern hl_type t$_dyn;
#include <hl/natives.h>
void iron_math_Vec4_new(iron__math__Vec4,float*,float*,float*,float*);
extern hl_type t$_f32;
extern hl_type t$_f64;
void armory_logicnode_LogicNode_new(armory__logicnode__LogicNode,armory__logicnode__LogicTree);

vdynamic* armory_logicnode_VectorMathNode_get(armory__logicnode__VectorMathNode r0,int r1) {
	String r16;
	armory__logicnode__LogicNodeLink r5, r10;
	hl__types__ArrayObj r2;
	bool r33;
	iron__math__Vec4 r11, r12, r13, r15;
	armory__logicnode__LogicNode r9;
	float r14, r24, r26, r27, r28, r29, r30, r31;
	double r25, r32;
	vdynamic *r6;
	float *r19, *r20, *r21, *r22;
	vbyte *r17, *r18;
	varray *r7;
	int r3, r4, r23;
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r3 = 0;
	r4 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$8c14d50_1_7;
	r5 = NULL;
	goto label$8c14d50_1_10;
	label$8c14d50_1_7:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r3];
	r5 = (armory__logicnode__LogicNodeLink)r6;
	label$8c14d50_1_10:
	if( r5 == NULL ) hl_null_access();
	r9 = r5->fromNode;
	if( r9 == NULL ) hl_null_access();
	r3 = r5->fromIndex;
	r6 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r9->$type->vobj_proto[1])(r9,r3);
	r11 = (iron__math__Vec4)hl_dyn_castp(&r6,&t$_dyn,&t$iron_math_Vec4);
	if( r11 ) goto label$8c14d50_1_19;
	r6 = NULL;
	return r6;
	label$8c14d50_1_19:
	r12 = r0->res_v;
	if( r12 == NULL ) hl_null_access();
	if( r11 == NULL ) hl_null_access();
	r14 = r11->x;
	r12->x = r14;
	r14 = r11->y;
	r12->y = r14;
	r14 = r11->z;
	r12->z = r14;
	r14 = r11->w;
	r12->w = r14;
	r16 = r0->property0;
	if( !r16 ) goto label$8c14d50_1_40;
	r3 = r16->length;
	r4 = 3;
	if( r3 != r4 ) goto label$8c14d50_1_40;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("Add");
	r3 = hl_string_compare(r17,r18,r3);
	r4 = 0;
	if( r3 == r4 ) goto label$8c14d50_1_131;
	label$8c14d50_1_40:
	if( !r16 ) goto label$8c14d50_1_49;
	r3 = r16->length;
	r4 = 7;
	if( r3 != r4 ) goto label$8c14d50_1_49;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("Average");
	r3 = hl_string_compare(r17,r18,r3);
	r4 = 0;
	if( r3 == r4 ) goto label$8c14d50_1_180;
	label$8c14d50_1_49:
	if( !r16 ) goto label$8c14d50_1_58;
	r3 = r16->length;
	r4 = 13;
	if( r3 != r4 ) goto label$8c14d50_1_58;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("Cross Product");
	r3 = hl_string_compare(r17,r18,r3);
	r4 = 0;
	if( r3 == r4 ) goto label$8c14d50_1_246;
	label$8c14d50_1_58:
	if( !r16 ) goto label$8c14d50_1_67;
	r3 = r16->length;
	r4 = 8;
	if( r3 != r4 ) goto label$8c14d50_1_67;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("Distance");
	r3 = hl_string_compare(r17,r18,r3);
	r4 = 0;
	if( r3 == r4 ) goto label$8c14d50_1_301;
	label$8c14d50_1_67:
	if( !r16 ) goto label$8c14d50_1_76;
	r3 = r16->length;
	r4 = 11;
	if( r3 != r4 ) goto label$8c14d50_1_76;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("Dot Product");
	r3 = hl_string_compare(r17,r18,r3);
	r4 = 0;
	if( r3 == r4 ) goto label$8c14d50_1_352;
	label$8c14d50_1_76:
	if( !r16 ) goto label$8c14d50_1_85;
	r3 = r16->length;
	r4 = 6;
	if( r3 != r4 ) goto label$8c14d50_1_85;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("Length");
	r3 = hl_string_compare(r17,r18,r3);
	r4 = 0;
	if( r3 == r4 ) goto label$8c14d50_1_416;
	label$8c14d50_1_85:
	if( !r16 ) goto label$8c14d50_1_94;
	r3 = r16->length;
	r4 = 8;
	if( r3 != r4 ) goto label$8c14d50_1_94;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("Multiply");
	r3 = hl_string_compare(r17,r18,r3);
	r4 = 0;
	if( r3 == r4 ) goto label$8c14d50_1_435;
	label$8c14d50_1_94:
	if( !r16 ) goto label$8c14d50_1_103;
	r3 = r16->length;
	r4 = 14;
	if( r3 != r4 ) goto label$8c14d50_1_103;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("MultiplyFloats");
	r3 = hl_string_compare(r17,r18,r3);
	r4 = 0;
	if( r3 == r4 ) goto label$8c14d50_1_488;
	label$8c14d50_1_103:
	if( !r16 ) goto label$8c14d50_1_112;
	r3 = r16->length;
	r4 = 9;
	if( r3 != r4 ) goto label$8c14d50_1_112;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("Normalize");
	r3 = hl_string_compare(r17,r18,r3);
	r4 = 0;
	if( r3 == r4 ) goto label$8c14d50_1_527;
	label$8c14d50_1_112:
	if( !r16 ) goto label$8c14d50_1_121;
	r3 = r16->length;
	r4 = 7;
	if( r3 != r4 ) goto label$8c14d50_1_121;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("Reflect");
	r3 = hl_string_compare(r17,r18,r3);
	r4 = 0;
	if( r3 == r4 ) goto label$8c14d50_1_562;
	label$8c14d50_1_121:
	if( !r16 ) goto label$8c14d50_1_130;
	r3 = r16->length;
	r4 = 8;
	if( r3 != r4 ) goto label$8c14d50_1_130;
	r17 = r16->bytes;
	r18 = (vbyte*)USTR("Subtract");
	r3 = hl_string_compare(r17,r18,r3);
	r4 = 0;
	if( r3 == r4 ) goto label$8c14d50_1_614;
	label$8c14d50_1_130:
	goto label$8c14d50_1_662;
	label$8c14d50_1_131:
	r12 = (iron__math__Vec4)hl_alloc_obj(&t$iron_math_Vec4);
	r19 = NULL;
	r20 = NULL;
	r21 = NULL;
	r22 = NULL;
	iron_math_Vec4_new(r12,r19,r20,r21,r22);
	r3 = 1;
	label$8c14d50_1_138:
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r23 = r2->length;
	if( r3 >= r23 ) goto label$8c14d50_1_179;
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r23 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r23) ) goto label$8c14d50_1_149;
	r10 = NULL;
	goto label$8c14d50_1_152;
	label$8c14d50_1_149:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r3];
	r10 = (armory__logicnode__LogicNodeLink)r6;
	label$8c14d50_1_152:
	if( r10 == NULL ) hl_null_access();
	r9 = r10->fromNode;
	if( r9 == NULL ) hl_null_access();
	r4 = r10->fromIndex;
	r6 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r9->$type->vobj_proto[1])(r9,r4);
	r13 = (iron__math__Vec4)hl_dyn_castp(&r6,&t$_dyn,&t$iron_math_Vec4);
	r12 = r13;
	if( r13 ) goto label$8c14d50_1_162;
	r6 = NULL;
	return r6;
	label$8c14d50_1_162:
	r13 = r0->res_v;
	if( r13 == NULL ) hl_null_access();
	r14 = r13->x;
	if( r12 == NULL ) hl_null_access();
	r24 = r12->x;
	r14 = r14 + r24;
	r13->x = r14;
	r14 = r13->y;
	r24 = r12->y;
	r14 = r14 + r24;
	r13->y = r14;
	r14 = r13->z;
	r24 = r12->z;
	r14 = r14 + r24;
	r13->z = r14;
	++r3;
	goto label$8c14d50_1_138;
	label$8c14d50_1_179:
	goto label$8c14d50_1_662;
	label$8c14d50_1_180:
	r12 = (iron__math__Vec4)hl_alloc_obj(&t$iron_math_Vec4);
	r19 = NULL;
	r20 = NULL;
	r21 = NULL;
	r22 = NULL;
	iron_math_Vec4_new(r12,r19,r20,r21,r22);
	r3 = 1;
	label$8c14d50_1_187:
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r23 = r2->length;
	if( r3 >= r23 ) goto label$8c14d50_1_245;
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r23 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r23) ) goto label$8c14d50_1_198;
	r10 = NULL;
	goto label$8c14d50_1_201;
	label$8c14d50_1_198:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r3];
	r10 = (armory__logicnode__LogicNodeLink)r6;
	label$8c14d50_1_201:
	if( r10 == NULL ) hl_null_access();
	r9 = r10->fromNode;
	if( r9 == NULL ) hl_null_access();
	r4 = r10->fromIndex;
	r6 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r9->$type->vobj_proto[1])(r9,r4);
	r13 = (iron__math__Vec4)hl_dyn_castp(&r6,&t$_dyn,&t$iron_math_Vec4);
	r12 = r13;
	if( r13 ) goto label$8c14d50_1_211;
	r6 = NULL;
	return r6;
	label$8c14d50_1_211:
	r13 = r0->res_v;
	if( r13 == NULL ) hl_null_access();
	r14 = r13->x;
	if( r12 == NULL ) hl_null_access();
	r24 = r12->x;
	r14 = r14 + r24;
	r13->x = r14;
	r14 = r13->y;
	r24 = r12->y;
	r14 = r14 + r24;
	r13->y = r14;
	r14 = r13->z;
	r24 = r12->z;
	r14 = r14 + r24;
	r13->z = r14;
	r13 = r0->res_v;
	if( r13 == NULL ) hl_null_access();
	r14 = r13->x;
	r25 = 0.5;
	r24 = (float)r25;
	r14 = r14 * r24;
	r13->x = r14;
	r14 = r13->y;
	r25 = 0.5;
	r24 = (float)r25;
	r14 = r14 * r24;
	r13->y = r14;
	r14 = r13->z;
	r25 = 0.5;
	r24 = (float)r25;
	r14 = r14 * r24;
	r13->z = r14;
	++r3;
	goto label$8c14d50_1_187;
	label$8c14d50_1_245:
	goto label$8c14d50_1_662;
	label$8c14d50_1_246:
	r12 = (iron__math__Vec4)hl_alloc_obj(&t$iron_math_Vec4);
	r19 = NULL;
	r20 = NULL;
	r21 = NULL;
	r22 = NULL;
	iron_math_Vec4_new(r12,r19,r20,r21,r22);
	r3 = 1;
	label$8c14d50_1_253:
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r23 = r2->length;
	if( r3 >= r23 ) goto label$8c14d50_1_300;
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r23 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r23) ) goto label$8c14d50_1_264;
	r10 = NULL;
	goto label$8c14d50_1_267;
	label$8c14d50_1_264:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r3];
	r10 = (armory__logicnode__LogicNodeLink)r6;
	label$8c14d50_1_267:
	if( r10 == NULL ) hl_null_access();
	r9 = r10->fromNode;
	if( r9 == NULL ) hl_null_access();
	r4 = r10->fromIndex;
	r6 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r9->$type->vobj_proto[1])(r9,r4);
	r13 = (iron__math__Vec4)hl_dyn_castp(&r6,&t$_dyn,&t$iron_math_Vec4);
	r12 = r13;
	if( r13 ) goto label$8c14d50_1_277;
	r6 = NULL;
	return r6;
	label$8c14d50_1_277:
	r13 = r0->res_v;
	if( r13 == NULL ) hl_null_access();
	r14 = r13->x;
	r24 = r13->y;
	r26 = r13->z;
	if( r12 == NULL ) hl_null_access();
	r27 = r12->x;
	r28 = r12->y;
	r29 = r12->z;
	r30 = r24 * r29;
	r31 = r26 * r28;
	r30 = r30 - r31;
	r13->x = r30;
	r30 = r26 * r27;
	r31 = r14 * r29;
	r30 = r30 - r31;
	r13->y = r30;
	r30 = r14 * r28;
	r31 = r24 * r27;
	r30 = r30 - r31;
	r13->z = r30;
	++r3;
	goto label$8c14d50_1_253;
	label$8c14d50_1_300:
	goto label$8c14d50_1_662;
	label$8c14d50_1_301:
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r3 = 1;
	r4 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$8c14d50_1_308;
	r10 = NULL;
	goto label$8c14d50_1_311;
	label$8c14d50_1_308:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r3];
	r10 = (armory__logicnode__LogicNodeLink)r6;
	label$8c14d50_1_311:
	if( r10 == NULL ) hl_null_access();
	r9 = r10->fromNode;
	if( r9 == NULL ) hl_null_access();
	r3 = r10->fromIndex;
	r6 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r9->$type->vobj_proto[1])(r9,r3);
	r12 = (iron__math__Vec4)hl_dyn_castp(&r6,&t$_dyn,&t$iron_math_Vec4);
	if( r12 ) goto label$8c14d50_1_320;
	r6 = NULL;
	return r6;
	label$8c14d50_1_320:
	r13 = r0->res_v;
	if( r12 == NULL ) hl_null_access();
	r14 = r12->x;
	if( r13 == NULL ) hl_null_access();
	r24 = r13->x;
	r14 = r14 - r24;
	r24 = r12->x;
	r26 = r13->x;
	r24 = r24 - r26;
	r14 = r14 * r24;
	r24 = r12->y;
	r26 = r13->y;
	r24 = r24 - r26;
	r26 = r12->y;
	r27 = r13->y;
	r26 = r26 - r27;
	r24 = r24 * r26;
	r14 = r14 + r24;
	r24 = r12->z;
	r26 = r13->z;
	r24 = r24 - r26;
	r26 = r12->z;
	r27 = r13->z;
	r26 = r26 - r27;
	r24 = r24 * r26;
	r14 = r14 + r24;
	r25 = (double)r14;
	r25 = hl_math_sqrt(r25);
	r14 = (float)r25;
	r25 = (double)r14;
	r0->res_f = r25;
	goto label$8c14d50_1_662;
	label$8c14d50_1_352:
	r12 = (iron__math__Vec4)hl_alloc_obj(&t$iron_math_Vec4);
	r19 = NULL;
	r20 = NULL;
	r21 = NULL;
	r22 = NULL;
	iron_math_Vec4_new(r12,r19,r20,r21,r22);
	r3 = 1;
	label$8c14d50_1_359:
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r23 = r2->length;
	if( r3 >= r23 ) goto label$8c14d50_1_415;
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r23 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r23) ) goto label$8c14d50_1_370;
	r10 = NULL;
	goto label$8c14d50_1_373;
	label$8c14d50_1_370:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r3];
	r10 = (armory__logicnode__LogicNodeLink)r6;
	label$8c14d50_1_373:
	if( r10 == NULL ) hl_null_access();
	r9 = r10->fromNode;
	if( r9 == NULL ) hl_null_access();
	r4 = r10->fromIndex;
	r6 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r9->$type->vobj_proto[1])(r9,r4);
	r13 = (iron__math__Vec4)hl_dyn_castp(&r6,&t$_dyn,&t$iron_math_Vec4);
	r12 = r13;
	if( r13 ) goto label$8c14d50_1_383;
	r6 = NULL;
	return r6;
	label$8c14d50_1_383:
	r13 = r0->res_v;
	if( r13 == NULL ) hl_null_access();
	r14 = r13->x;
	if( r12 == NULL ) hl_null_access();
	r24 = r12->x;
	r14 = r14 * r24;
	r24 = r13->y;
	r26 = r12->y;
	r24 = r24 * r26;
	r14 = r14 + r24;
	r24 = r13->z;
	r26 = r12->z;
	r24 = r24 * r26;
	r14 = r14 + r24;
	r25 = (double)r14;
	r0->res_f = r25;
	r15 = r0->res_v;
	if( r15 == NULL ) hl_null_access();
	r25 = r0->res_f;
	r14 = (float)r25;
	r15->x = r14;
	r25 = r0->res_f;
	r14 = (float)r25;
	r15->y = r14;
	r25 = r0->res_f;
	r14 = (float)r25;
	r15->z = r14;
	r25 = 1.;
	r14 = (float)r25;
	r15->w = r14;
	++r3;
	goto label$8c14d50_1_359;
	label$8c14d50_1_415:
	goto label$8c14d50_1_662;
	label$8c14d50_1_416:
	r12 = r0->res_v;
	if( r12 == NULL ) hl_null_access();
	r14 = r12->x;
	r24 = r12->x;
	r14 = r14 * r24;
	r24 = r12->y;
	r26 = r12->y;
	r24 = r24 * r26;
	r14 = r14 + r24;
	r24 = r12->z;
	r26 = r12->z;
	r24 = r24 * r26;
	r14 = r14 + r24;
	r25 = (double)r14;
	r25 = hl_math_sqrt(r25);
	r14 = (float)r25;
	r25 = (double)r14;
	r0->res_f = r25;
	goto label$8c14d50_1_662;
	label$8c14d50_1_435:
	r12 = (iron__math__Vec4)hl_alloc_obj(&t$iron_math_Vec4);
	r19 = NULL;
	r20 = NULL;
	r21 = NULL;
	r22 = NULL;
	iron_math_Vec4_new(r12,r19,r20,r21,r22);
	r3 = 1;
	label$8c14d50_1_442:
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r23 = r2->length;
	if( r3 >= r23 ) goto label$8c14d50_1_487;
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r23 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r23) ) goto label$8c14d50_1_453;
	r10 = NULL;
	goto label$8c14d50_1_456;
	label$8c14d50_1_453:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r3];
	r10 = (armory__logicnode__LogicNodeLink)r6;
	label$8c14d50_1_456:
	if( r10 == NULL ) hl_null_access();
	r9 = r10->fromNode;
	if( r9 == NULL ) hl_null_access();
	r4 = r10->fromIndex;
	r6 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r9->$type->vobj_proto[1])(r9,r4);
	r13 = (iron__math__Vec4)hl_dyn_castp(&r6,&t$_dyn,&t$iron_math_Vec4);
	r12 = r13;
	if( r13 ) goto label$8c14d50_1_466;
	r6 = NULL;
	return r6;
	label$8c14d50_1_466:
	r13 = r0->res_v;
	if( r13 == NULL ) hl_null_access();
	r14 = r13->x;
	if( r12 == NULL ) hl_null_access();
	r24 = r12->x;
	r14 = r14 * r24;
	r13->x = r14;
	r13 = r0->res_v;
	if( r13 == NULL ) hl_null_access();
	r14 = r13->y;
	r24 = r12->y;
	r14 = r14 * r24;
	r13->y = r14;
	r13 = r0->res_v;
	if( r13 == NULL ) hl_null_access();
	r14 = r13->z;
	r24 = r12->z;
	r14 = r14 * r24;
	r13->z = r14;
	++r3;
	goto label$8c14d50_1_442;
	label$8c14d50_1_487:
	goto label$8c14d50_1_662;
	label$8c14d50_1_488:
	r25 = 1.;
	r3 = 1;
	label$8c14d50_1_490:
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r23 = r2->length;
	if( r3 >= r23 ) goto label$8c14d50_1_526;
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r23 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r23) ) goto label$8c14d50_1_501;
	r10 = NULL;
	goto label$8c14d50_1_504;
	label$8c14d50_1_501:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r3];
	r10 = (armory__logicnode__LogicNodeLink)r6;
	label$8c14d50_1_504:
	if( r10 == NULL ) hl_null_access();
	r9 = r10->fromNode;
	if( r9 == NULL ) hl_null_access();
	r4 = r10->fromIndex;
	r6 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r9->$type->vobj_proto[1])(r9,r4);
	r32 = (double)hl_dyn_castd(&r6,&t$_dyn);
	r12 = r0->res_v;
	if( r12 == NULL ) hl_null_access();
	r14 = r12->x;
	r24 = (float)r32;
	r14 = r14 * r24;
	r12->x = r14;
	r14 = r12->y;
	r24 = (float)r32;
	r14 = r14 * r24;
	r12->y = r14;
	r14 = r12->z;
	r24 = (float)r32;
	r14 = r14 * r24;
	r12->z = r14;
	++r3;
	goto label$8c14d50_1_490;
	label$8c14d50_1_526:
	goto label$8c14d50_1_662;
	label$8c14d50_1_527:
	r12 = r0->res_v;
	if( r12 == NULL ) hl_null_access();
	r14 = r12->x;
	r24 = r12->x;
	r14 = r14 * r24;
	r24 = r12->y;
	r26 = r12->y;
	r24 = r24 * r26;
	r14 = r14 + r24;
	r24 = r12->z;
	r26 = r12->z;
	r24 = r24 * r26;
	r14 = r14 + r24;
	r25 = (double)r14;
	r25 = hl_math_sqrt(r25);
	r14 = (float)r25;
	r25 = (double)r14;
	r32 = 0.;
	if( !(r32 < r25) ) goto label$8c14d50_1_561;
	r25 = 1.;
	r32 = (double)r14;
	r25 = r25 / r32;
	r24 = r12->x;
	r26 = (float)r25;
	r24 = r24 * r26;
	r12->x = r24;
	r24 = r12->y;
	r26 = (float)r25;
	r24 = r24 * r26;
	r12->y = r24;
	r24 = r12->z;
	r26 = (float)r25;
	r24 = r24 * r26;
	r12->z = r24;
	label$8c14d50_1_561:
	goto label$8c14d50_1_662;
	label$8c14d50_1_562:
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r3 = 1;
	r4 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$8c14d50_1_569;
	r10 = NULL;
	goto label$8c14d50_1_572;
	label$8c14d50_1_569:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r3];
	r10 = (armory__logicnode__LogicNodeLink)r6;
	label$8c14d50_1_572:
	if( r10 == NULL ) hl_null_access();
	r9 = r10->fromNode;
	if( r9 == NULL ) hl_null_access();
	r3 = r10->fromIndex;
	r6 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r9->$type->vobj_proto[1])(r9,r3);
	r12 = (iron__math__Vec4)hl_dyn_castp(&r6,&t$_dyn,&t$iron_math_Vec4);
	if( r12 ) goto label$8c14d50_1_581;
	r6 = NULL;
	return r6;
	label$8c14d50_1_581:
	r13 = r0->res_v;
	r3 = 2;
	r14 = (float)r3;
	if( r13 == NULL ) hl_null_access();
	r24 = r13->x;
	if( r12 == NULL ) hl_null_access();
	r26 = r12->x;
	r24 = r24 * r26;
	r26 = r13->y;
	r27 = r12->y;
	r26 = r26 * r27;
	r24 = r24 + r26;
	r26 = r13->z;
	r27 = r12->z;
	r26 = r26 * r27;
	r24 = r24 + r26;
	r14 = r14 * r24;
	r24 = r13->x;
	r27 = r12->x;
	r26 = r14 * r27;
	r24 = r24 - r26;
	r13->x = r24;
	r24 = r13->y;
	r27 = r12->y;
	r26 = r14 * r27;
	r24 = r24 - r26;
	r13->y = r24;
	r24 = r13->z;
	r27 = r12->z;
	r26 = r14 * r27;
	r24 = r24 - r26;
	r13->z = r24;
	goto label$8c14d50_1_662;
	label$8c14d50_1_614:
	r12 = (iron__math__Vec4)hl_alloc_obj(&t$iron_math_Vec4);
	r19 = NULL;
	r20 = NULL;
	r21 = NULL;
	r22 = NULL;
	iron_math_Vec4_new(r12,r19,r20,r21,r22);
	r3 = 1;
	label$8c14d50_1_621:
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r23 = r2->length;
	if( r3 >= r23 ) goto label$8c14d50_1_662;
	r2 = r0->inputs;
	if( r2 == NULL ) hl_null_access();
	r23 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r23) ) goto label$8c14d50_1_632;
	r10 = NULL;
	goto label$8c14d50_1_635;
	label$8c14d50_1_632:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r3];
	r10 = (armory__logicnode__LogicNodeLink)r6;
	label$8c14d50_1_635:
	if( r10 == NULL ) hl_null_access();
	r9 = r10->fromNode;
	if( r9 == NULL ) hl_null_access();
	r4 = r10->fromIndex;
	r6 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r9->$type->vobj_proto[1])(r9,r4);
	r13 = (iron__math__Vec4)hl_dyn_castp(&r6,&t$_dyn,&t$iron_math_Vec4);
	r12 = r13;
	if( r13 ) goto label$8c14d50_1_645;
	r6 = NULL;
	return r6;
	label$8c14d50_1_645:
	r13 = r0->res_v;
	if( r13 == NULL ) hl_null_access();
	r14 = r13->x;
	if( r12 == NULL ) hl_null_access();
	r24 = r12->x;
	r14 = r14 - r24;
	r13->x = r14;
	r14 = r13->y;
	r24 = r12->y;
	r14 = r14 - r24;
	r13->y = r14;
	r14 = r13->z;
	r24 = r12->z;
	r14 = r14 - r24;
	r13->z = r14;
	++r3;
	goto label$8c14d50_1_621;
	label$8c14d50_1_662:
	switch(r1) {
		default:
			goto label$8c14d50_1_701;
		case 0:
			r12 = r0->res_v;
			return ((vdynamic*)r12);
		case 1:
			r33 = r0->property1;
			if( !r33 ) goto label$8c14d50_1_673;
			r12 = r0->res_v;
			if( r12 == NULL ) hl_null_access();
			r14 = r12->x;
			r6 = hl_alloc_dynamic(&t$_f32);
			r6->v.f = r14;
			return r6;
			label$8c14d50_1_673:
			r25 = r0->res_f;
			r6 = hl_alloc_dynamic(&t$_f64);
			r6->v.d = r25;
			return r6;
		case 2:
			r33 = r0->property1;
			if( !r33 ) goto label$8c14d50_1_683;
			r12 = r0->res_v;
			if( r12 == NULL ) hl_null_access();
			r14 = r12->y;
			r6 = hl_alloc_dynamic(&t$_f32);
			r6->v.f = r14;
			return r6;
			label$8c14d50_1_683:
			r25 = r0->res_f;
			r6 = hl_alloc_dynamic(&t$_f64);
			r6->v.d = r25;
			return r6;
		case 3:
			r33 = r0->property1;
			if( !r33 ) goto label$8c14d50_1_693;
			r12 = r0->res_v;
			if( r12 == NULL ) hl_null_access();
			r14 = r12->z;
			r6 = hl_alloc_dynamic(&t$_f32);
			r6->v.f = r14;
			return r6;
			label$8c14d50_1_693:
			r25 = r0->res_f;
			r6 = hl_alloc_dynamic(&t$_f64);
			r6->v.d = r25;
			return r6;
		case 4:
			r33 = r0->property1;
			if( !r33 ) goto label$8c14d50_1_701;
			r25 = r0->res_f;
			r6 = hl_alloc_dynamic(&t$_f64);
			r6->v.d = r25;
			return r6;
	}
	label$8c14d50_1_701:
	r6 = NULL;
	return r6;
}

void armory_logicnode_VectorMathNode_new(armory__logicnode__VectorMathNode r0,armory__logicnode__LogicTree r1) {
	iron__math__Vec4 r3;
	double r2;
	float *r4, *r5, *r6, *r7;
	r2 = 0.;
	r0->res_f = r2;
	r3 = (iron__math__Vec4)hl_alloc_obj(&t$iron_math_Vec4);
	r4 = NULL;
	r5 = NULL;
	r6 = NULL;
	r7 = NULL;
	iron_math_Vec4_new(r3,r4,r5,r6,r7);
	r0->res_v = r3;
	armory_logicnode_LogicNode_new(((armory__logicnode__LogicNode)r0),r1);
	return;
}

