// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <armory/logicnode/VectorNode.h>
#include <armory/logicnode/LogicNodeLink.h>
extern hl_type t$iron_math_Vec4;
void iron_math_Vec4_new(iron__math__Vec4,float*,float*,float*,float*);
extern hl_type t$_dyn;
#include <armory/logicnode/FloatNode.h>
void armory_logicnode_LogicNode_new(armory__logicnode__LogicNode,armory__logicnode__LogicTree);
extern hl_type t$armory_logicnode_FloatNode;
void armory_logicnode_FloatNode_new(armory__logicnode__FloatNode,armory__logicnode__LogicTree,double*);
armory__logicnode__LogicNodeLink armory_logicnode_LogicNode_addLink(armory__logicnode__LogicNode,armory__logicnode__LogicNode,int,int);

vdynamic* armory_logicnode_VectorNode_get(armory__logicnode__VectorNode r0,int r1) {
	armory__logicnode__LogicNodeLink r11, r15, r18;
	hl__types__ArrayObj r8;
	iron__math__Vec4 r2;
	armory__logicnode__LogicNode r14;
	float r17;
	vdynamic *r12, *r16, *r19;
	varray *r13;
	int r9, r10;
	float *r3, *r4, *r5, *r6;
	r2 = (iron__math__Vec4)hl_alloc_obj(&t$iron_math_Vec4);
	r3 = NULL;
	r4 = NULL;
	r5 = NULL;
	r6 = NULL;
	iron_math_Vec4_new(r2,r3,r4,r5,r6);
	r0->value = r2;
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r9 = 0;
	r10 = r8->length;
	if( ((unsigned)r9) < ((unsigned)r10) ) goto label$a7aadf4_1_14;
	r11 = NULL;
	goto label$a7aadf4_1_17;
	label$a7aadf4_1_14:
	r13 = r8->array;
	r12 = ((vdynamic**)(r13 + 1))[r9];
	r11 = (armory__logicnode__LogicNodeLink)r12;
	label$a7aadf4_1_17:
	if( r11 == NULL ) hl_null_access();
	r14 = r11->fromNode;
	if( r14 == NULL ) hl_null_access();
	r9 = r11->fromIndex;
	r12 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r14->$type->vobj_proto[1])(r14,r9);
	r2 = r0->value;
	if( r2 == NULL ) hl_null_access();
	r17 = (float)hl_dyn_castf(&r12,&t$_dyn);
	r2->x = r17;
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r9 = 1;
	r10 = r8->length;
	if( ((unsigned)r9) < ((unsigned)r10) ) goto label$a7aadf4_1_33;
	r15 = NULL;
	goto label$a7aadf4_1_36;
	label$a7aadf4_1_33:
	r13 = r8->array;
	r16 = ((vdynamic**)(r13 + 1))[r9];
	r15 = (armory__logicnode__LogicNodeLink)r16;
	label$a7aadf4_1_36:
	if( r15 == NULL ) hl_null_access();
	r14 = r15->fromNode;
	if( r14 == NULL ) hl_null_access();
	r9 = r15->fromIndex;
	r16 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r14->$type->vobj_proto[1])(r14,r9);
	r2 = r0->value;
	if( r2 == NULL ) hl_null_access();
	r17 = (float)hl_dyn_castf(&r16,&t$_dyn);
	r2->y = r17;
	r8 = r0->inputs;
	if( r8 == NULL ) hl_null_access();
	r9 = 2;
	r10 = r8->length;
	if( ((unsigned)r9) < ((unsigned)r10) ) goto label$a7aadf4_1_52;
	r18 = NULL;
	goto label$a7aadf4_1_55;
	label$a7aadf4_1_52:
	r13 = r8->array;
	r19 = ((vdynamic**)(r13 + 1))[r9];
	r18 = (armory__logicnode__LogicNodeLink)r19;
	label$a7aadf4_1_55:
	if( r18 == NULL ) hl_null_access();
	r14 = r18->fromNode;
	if( r14 == NULL ) hl_null_access();
	r9 = r18->fromIndex;
	r19 = ((vdynamic* (*)(armory__logicnode__LogicNode,int))r14->$type->vobj_proto[1])(r14,r9);
	r2 = r0->value;
	if( r2 == NULL ) hl_null_access();
	r17 = (float)hl_dyn_castf(&r19,&t$_dyn);
	r2->z = r17;
	r2 = r0->value;
	return ((vdynamic*)r2);
}

void armory_logicnode_VectorNode_new(armory__logicnode__VectorNode r0,armory__logicnode__LogicTree r1,vdynamic* r2,vdynamic* r3,vdynamic* r4) {
	armory__logicnode__LogicNodeLink r11;
	iron__math__Vec4 r5;
	double r14, r17, r18;
	armory__logicnode__FloatNode r12;
	double *r13;
	int r15, r16;
	float *r6, *r7, *r8, *r9;
	r5 = (iron__math__Vec4)hl_alloc_obj(&t$iron_math_Vec4);
	r6 = NULL;
	r7 = NULL;
	r8 = NULL;
	r9 = NULL;
	iron_math_Vec4_new(r5,r6,r7,r8,r9);
	r0->value = r5;
	armory_logicnode_LogicNode_new(((armory__logicnode__LogicNode)r0),r1);
	if( !r2 ) goto label$a7aadf4_2_39;
	r12 = (armory__logicnode__FloatNode)hl_alloc_obj(&t$armory_logicnode_FloatNode);
	if( r2 ) goto label$a7aadf4_2_13;
	r13 = NULL;
	goto label$a7aadf4_2_15;
	label$a7aadf4_2_13:
	r14 = r2 ? r2->v.d : 0;
	r13 = &r14;
	label$a7aadf4_2_15:
	armory_logicnode_FloatNode_new(r12,r1,r13);
	r15 = 0;
	r16 = 0;
	r11 = armory_logicnode_LogicNode_addLink(((armory__logicnode__LogicNode)r12),((armory__logicnode__LogicNode)r0),r15,r16);
	r12 = (armory__logicnode__FloatNode)hl_alloc_obj(&t$armory_logicnode_FloatNode);
	if( r3 ) goto label$a7aadf4_2_23;
	r13 = NULL;
	goto label$a7aadf4_2_25;
	label$a7aadf4_2_23:
	r17 = r3 ? r3->v.d : 0;
	r13 = &r17;
	label$a7aadf4_2_25:
	armory_logicnode_FloatNode_new(r12,r1,r13);
	r15 = 0;
	r16 = 1;
	r11 = armory_logicnode_LogicNode_addLink(((armory__logicnode__LogicNode)r12),((armory__logicnode__LogicNode)r0),r15,r16);
	r12 = (armory__logicnode__FloatNode)hl_alloc_obj(&t$armory_logicnode_FloatNode);
	if( r4 ) goto label$a7aadf4_2_33;
	r13 = NULL;
	goto label$a7aadf4_2_35;
	label$a7aadf4_2_33:
	r18 = r4 ? r4->v.d : 0;
	r13 = &r18;
	label$a7aadf4_2_35:
	armory_logicnode_FloatNode_new(r12,r1,r13);
	r15 = 0;
	r16 = 2;
	r11 = armory_logicnode_LogicNode_addLink(((armory__logicnode__LogicNode)r12),((armory__logicnode__LogicNode)r0),r15,r16);
	label$a7aadf4_2_39:
	return;
}

