// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <kha/math/FastMatrix4.h>

void kha_math_FastMatrix4_new(kha__math__FastMatrix4 r0,float r1,float r2,float r3,float r4,float r5,float r6,float r7,float r8,float r9,float r10,float r11,float r12,float r13,float r14,float r15,float r16) {
	r0->_00 = r1;
	r0->_10 = r2;
	r0->_20 = r3;
	r0->_30 = r4;
	r0->_01 = r5;
	r0->_11 = r6;
	r0->_21 = r7;
	r0->_31 = r8;
	r0->_02 = r9;
	r0->_12 = r10;
	r0->_22 = r11;
	r0->_32 = r12;
	r0->_03 = r13;
	r0->_13 = r14;
	r0->_23 = r15;
	r0->_33 = r16;
	return;
}

