// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/RenderPath.h>
extern iron__$RenderPath g$_iron_RenderPath;
#include <iron/App.h>
#include <iron/object/CameraObject.h>
#include <iron/Scene.h>
#include <iron/data/TLightData.h>
#include <iron/data/LightData.h>
extern iron__$App g$_iron_App;
void iron_RenderPath_resize(iron__RenderPath);
double kha_Scheduler_time(void);
extern iron__$Scene g$_iron_Scene;
vvirtual* kha_Image_get_g4(kha__Image);
vvirtual* kha_graphics4_CubeMap_get_g4(kha__graphics4__CubeMap);
void iron_object_LightObject_buildMatrix(iron__object__LightObject,iron__object__CameraObject);
extern String s$sun;
int String___compare(String,vdynamic*);
extern String s$;
int kha_graphics4_CubeMap_get_width(kha__graphics4__CubeMap);
int kha_graphics4_CubeMap_get_height(kha__graphics4__CubeMap);
extern hl_type t$fun_4c7a70a;
extern hl_type t$fun_dc4017d;
extern hl_type t$fun_58e3acc;
void iron_RenderPath_setFrameScissor(iron__RenderPath);
void iron_RenderPath_setCurrentViewport(iron__RenderPath,int,int);
void iron_RenderPath_setCurrentScissor(iron__RenderPath,int,int);
vdynamic* haxe_ds_StringMap_get(haxe__ds__StringMap,String);
extern hl_type t$vrt_7ced7cf;
#include <hl/natives.h>
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
int kha_Image_get_width(kha__Image);
int kha_Image_get_height(kha__Image);
int kha_Image_get_depth(kha__Image);
extern hl_type t$fun_5ac3579;
#include <iron/data/WorldData.h>
#include <iron/data/TWorldData.h>
#include <iron/data/TCameraData.h>
#include <iron/data/CameraData.h>
extern hl_type t$_i32;
int kha__Color_Color_Impl__fromFloats(float,float,float,float*);
extern hl_type t$fun_5967954;
#include <iron/object/MeshObject.h>
extern hl_type t$fun_01f8d35;
int wrapt$fun_2237bde(vclosure*,vdynamic*,vdynamic*);
extern hl_type t$fun_2237bde;
void hl_types_ArrayObj_sort(hl__types__ArrayObj,vclosure*);
#include <iron/data/MaterialData.h>
#include <iron/object/LightObject.h>
extern String s$shadowmap;
void iron_object_LightObject_setCubeFace(iron__object__LightObject,int,iron__object__CameraObject);
extern iron__object__$LightObject g$_iron_object_LightObject;
void iron_object_LightObject_setCascade(iron__object__LightObject,iron__object__CameraObject,int);
void iron_RenderPath_submitDraw(iron__RenderPath,String);
#include <iron/math/Mat4.h>
#include <iron/object/Transform.h>
extern iron__object__$MeshObject g$_iron_object_MeshObject;
void iron_object_MeshObject_render(iron__object__MeshObject,vvirtual*,String,hl__types__ArrayObj);
#include <iron/data/ConstData.h>
#include <iron/CachedShaderContext.h>
#include <iron/data/ShaderContext.h>
#include <iron/object/Object.h>
extern iron__data__$ConstData g$_iron_data_ConstData;
void iron_data_ConstData_createSkydomeData(void);
extern hl_type t$fun_c80ec77;
void iron_object_Uniforms_setContextConstants(vvirtual*,iron__data__ShaderContext,hl__types__ArrayObj);
void iron_object_Uniforms_setObjectConstants(vvirtual*,iron__data__ShaderContext,iron__object__Object);
extern hl_type t$fun_a561c62;
extern hl_type t$fun_46c6b6e;
extern hl_type t$fun_8305be0;
extern hl_type t$String;
void iron_data_ConstData_createScreenAlignedData(void);
#include <iron/data/ShaderData.h>
iron__data__ShaderContext iron_data_ShaderData_getContext(iron__data__ShaderData,String);
#include <iron/data/TShaderOverride.h>
extern hl_type t$iron_CachedShaderContext;
void iron_CachedShaderContext_new(iron__CachedShaderContext);
void hl_types_ArrayObj___expand(hl__types__ArrayObj,int);
void haxe_ds_StringMap_set(haxe__ds__StringMap,String,vdynamic*);
extern String s$6666cd7;
hl__types__ArrayObj String_split(String,String);
extern hl_type t$ctx_93b0219;
extern hl_type t$fun_dbb682c;
void iron_data_Data_getShader(String,String,vclosure*,iron__data__TShaderOverride);
#include <iron/data/Data.h>
bool haxe_ds_StringMap_remove(haxe__ds__StringMap,String);
extern iron__data__$Data g$_iron_data_Data;
#include <iron/RenderTargetRaw.h>
int kha_System_windowWidth(int*);
int kha_System_windowHeight(int*);
vvirtual* haxe_ds_StringMap_iterator(haxe__ds__StringMap);
extern hl_type t$vrt_06f6bad;
extern hl_type t$fun_bf7849e;
extern hl_type t$fun_c699427;
void kha_Image_setDepthStencilFrom(kha__Image,kha__Image);
void kha_Image_unload(kha__Image);
extern hl_type t$fun_ccaddd2;
void iron_App_notifyOnInit(vclosure*);
kha__Image iron_RenderPath_createImage(iron__RenderPath,iron__RenderTargetRaw,int);
iron__RenderTarget iron_RenderPath_createTarget(iron__RenderPath,iron__RenderTargetRaw);
extern hl_type t$vrt_ee58142;
extern hl_type t$iron_RenderTarget;
void iron_RenderTarget_new(iron__RenderTarget,iron__RenderTargetRaw);
kha__graphics4__CubeMap iron_RenderPath_createCubeMap(iron__RenderPath,iron__RenderTargetRaw,int);
kha__Image kha_Image_create3D(int,int,int,vdynamic*,vdynamic*,bool*);
void kha_Image_generateMipmaps(kha__Image,int);
kha__Image kha_Image_create(int,int,vdynamic*,vdynamic*,bool*);
kha__Image kha_Image_createRenderTarget(int,int,vdynamic*,int*,int*);
kha__graphics4__CubeMap kha_graphics4_CubeMap_createRenderTarget(int,vdynamic*,vdynamic*);
extern hl_type t$haxe_ds_StringMap;
void haxe_ds_StringMap_new(haxe__ds__StringMap);

bool iron_RenderPath_get_ready(iron__RenderPath r0) {
	bool r1;
	int r2, r3;
	r2 = r0->loading;
	r3 = 0;
	if( r2 == r3 ) goto label$80733c3_1_5;
	r1 = false;
	goto label$80733c3_1_6;
	label$80733c3_1_5:
	r1 = true;
	label$80733c3_1_6:
	return r1;
}

void iron_RenderPath_setActive(iron__RenderPath r0) {
	iron__$RenderPath r1;
	r1 = (iron__$RenderPath)g$_iron_RenderPath;
	r1->active = r0;
	return;
}

void iron_RenderPath_renderFrame(iron__RenderPath r0,vvirtual* r1) {
	String r22, r25;
	kha__graphics4__CubeMap r16;
	kha__Image r15;
	iron__data__TLightData r23;
	hl__types__ArrayObj r18;
	vvirtual *r17;
	iron__$App r6;
	iron__$Scene r13;
	iron__Scene r12;
	bool r3;
	iron__data__LightData r24;
	iron__object__LightObject r20;
	iron__object__CameraObject r11, r14;
	double r9, r10;
	vclosure *r5, *r26;
	vdynamic *r8;
	varray *r21;
	int r4, r7, r19;
	r3 = iron_RenderPath_get_ready(r0);
	if( !r3 ) goto label$80733c3_3_16;
	r3 = r0->paused;
	if( r3 ) goto label$80733c3_3_16;
	r6 = (iron__$App)g$_iron_App;
	r5 = r6->w;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->hasValue ? ((int (*)(vdynamic*))r5->fun)((vdynamic*)r5->value) : ((int (*)(void))r5->fun)();
	r7 = 0;
	if( r4 == r7 ) goto label$80733c3_3_16;
	r6 = (iron__$App)g$_iron_App;
	r5 = r6->h;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->hasValue ? ((int (*)(vdynamic*))r5->fun)((vdynamic*)r5->value) : ((int (*)(void))r5->fun)();
	r7 = 0;
	if( r4 != r7 ) goto label$80733c3_3_17;
	label$80733c3_3_16:
	return;
	label$80733c3_3_17:
	r4 = r0->lastW;
	r7 = 0;
	if( r7 >= r4 ) goto label$80733c3_3_33;
	r4 = r0->lastW;
	r6 = (iron__$App)g$_iron_App;
	r5 = r6->w;
	if( r5 == NULL ) hl_null_access();
	r7 = r5->hasValue ? ((int (*)(vdynamic*))r5->fun)((vdynamic*)r5->value) : ((int (*)(void))r5->fun)();
	if( r4 != r7 ) goto label$80733c3_3_32;
	r4 = r0->lastH;
	r6 = (iron__$App)g$_iron_App;
	r5 = r6->h;
	if( r5 == NULL ) hl_null_access();
	r7 = r5->hasValue ? ((int (*)(vdynamic*))r5->fun)((vdynamic*)r5->value) : ((int (*)(void))r5->fun)();
	if( r4 == r7 ) goto label$80733c3_3_33;
	label$80733c3_3_32:
	iron_RenderPath_resize(r0);
	label$80733c3_3_33:
	r6 = (iron__$App)g$_iron_App;
	r5 = r6->w;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->hasValue ? ((int (*)(vdynamic*))r5->fun)((vdynamic*)r5->value) : ((int (*)(void))r5->fun)();
	r0->lastW = r4;
	r6 = (iron__$App)g$_iron_App;
	r5 = r6->h;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->hasValue ? ((int (*)(vdynamic*))r5->fun)((vdynamic*)r5->value) : ((int (*)(void))r5->fun)();
	r0->lastH = r4;
	r9 = kha_Scheduler_time();
	r10 = r0->lastFrameTime;
	r9 = r9 - r10;
	r0->frameTime = r9;
	r9 = kha_Scheduler_time();
	r0->lastFrameTime = r9;
	r13 = (iron__$Scene)g$_iron_Scene;
	r12 = r13->active;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->camera;
	if( !r11 ) goto label$80733c3_3_59;
	if( r11 == NULL ) hl_null_access();
	r15 = r11->renderTarget;
	if( !r15 ) goto label$80733c3_3_59;
	r3 = true;
	goto label$80733c3_3_60;
	label$80733c3_3_59:
	r3 = false;
	label$80733c3_3_60:
	r0->isProbePlanar = r3;
	if( !r11 ) goto label$80733c3_3_67;
	if( r11 == NULL ) hl_null_access();
	r16 = r11->renderTargetCube;
	if( !r16 ) goto label$80733c3_3_67;
	r3 = true;
	goto label$80733c3_3_68;
	label$80733c3_3_67:
	r3 = false;
	label$80733c3_3_68:
	r0->isProbeCube = r3;
	r3 = r0->isProbePlanar;
	if( r3 ) goto label$80733c3_3_75;
	r3 = r0->isProbeCube;
	if( r3 ) goto label$80733c3_3_75;
	r3 = false;
	goto label$80733c3_3_76;
	label$80733c3_3_75:
	r3 = true;
	label$80733c3_3_76:
	r0->isProbe = r3;
	r3 = r0->isProbePlanar;
	if( !r3 ) goto label$80733c3_3_85;
	if( r11 == NULL ) hl_null_access();
	r15 = r11->renderTarget;
	if( r15 == NULL ) hl_null_access();
	r17 = kha_Image_get_g4(r15);
	r0->frameG = r17;
	goto label$80733c3_3_94;
	label$80733c3_3_85:
	r3 = r0->isProbeCube;
	if( !r3 ) goto label$80733c3_3_93;
	if( r11 == NULL ) hl_null_access();
	r16 = r11->renderTargetCube;
	if( r16 == NULL ) hl_null_access();
	r17 = kha_graphics4_CubeMap_get_g4(r16);
	r0->frameG = r17;
	goto label$80733c3_3_94;
	label$80733c3_3_93:
	r0->frameG = r1;
	label$80733c3_3_94:
	r6 = (iron__$App)g$_iron_App;
	r5 = r6->w;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->hasValue ? ((int (*)(vdynamic*))r5->fun)((vdynamic*)r5->value) : ((int (*)(void))r5->fun)();
	r0->currentW = r4;
	r6 = (iron__$App)g$_iron_App;
	r5 = r6->h;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->hasValue ? ((int (*)(vdynamic*))r5->fun)((vdynamic*)r5->value) : ((int (*)(void))r5->fun)();
	r0->currentH = r4;
	r4 = 1;
	r0->currentD = r4;
	r4 = -1;
	r0->currentFace = r4;
	r3 = false;
	r0->meshesSorted = r3;
	r4 = 0;
	r13 = (iron__$Scene)g$_iron_Scene;
	r12 = r13->active;
	if( r12 == NULL ) hl_null_access();
	r18 = r12->lights;
	label$80733c3_3_115:
	if( r18 == NULL ) hl_null_access();
	r19 = r18->length;
	if( r4 >= r19 ) goto label$80733c3_3_146;
	r19 = r18->length;
	if( ((unsigned)r4) < ((unsigned)r19) ) goto label$80733c3_3_123;
	r20 = NULL;
	goto label$80733c3_3_126;
	label$80733c3_3_123:
	r21 = r18->array;
	r8 = ((vdynamic**)(r21 + 1))[r4];
	r20 = (iron__object__LightObject)r8;
	label$80733c3_3_126:
	++r4;
	if( r20 == NULL ) hl_null_access();
	r3 = r20->visible;
	if( !r3 ) goto label$80733c3_3_135;
	r13 = (iron__$Scene)g$_iron_Scene;
	r12 = r13->active;
	if( r12 == NULL ) hl_null_access();
	r14 = r12->camera;
	iron_object_LightObject_buildMatrix(r20,r14);
	label$80733c3_3_135:
	r24 = r20->data;
	if( r24 == NULL ) hl_null_access();
	r23 = r24->raw;
	if( r23 == NULL ) hl_null_access();
	r22 = r23->type;
	r25 = (String)s$sun;
	if( r22 != r25 && (!r22 || !r25 || String___compare(r22,(vdynamic*)r25) != 0) ) goto label$80733c3_3_144;
	r0->sun = r20;
	goto label$80733c3_3_145;
	label$80733c3_3_144:
	r0->point = r20;
	label$80733c3_3_145:
	goto label$80733c3_3_115;
	label$80733c3_3_146:
	r13 = (iron__$Scene)g$_iron_Scene;
	r12 = r13->active;
	if( r12 == NULL ) hl_null_access();
	r18 = r12->lights;
	if( r18 == NULL ) hl_null_access();
	r4 = 0;
	r7 = r18->length;
	if( ((unsigned)r4) < ((unsigned)r7) ) goto label$80733c3_3_156;
	r20 = NULL;
	goto label$80733c3_3_159;
	label$80733c3_3_156:
	r21 = r18->array;
	r8 = ((vdynamic**)(r21 + 1))[r4];
	r20 = (iron__object__LightObject)r8;
	label$80733c3_3_159:
	r0->light = r20;
	r26 = r0->commands;
	if( r26 == NULL ) hl_null_access();
	r26->hasValue ? ((void (*)(vdynamic*))r26->fun)((vdynamic*)r26->value) : ((void (*)(void))r26->fun)();
	r3 = r0->isProbe;
	if( r3 ) goto label$80733c3_3_168;
	r4 = r0->frame;
	++r4;
	r0->frame = r4;
	label$80733c3_3_168:
	return;
}

void iron_RenderPath_setTarget(iron__RenderPath r0,String r1,hl__types__ArrayObj r2,double* r3) {
	kha__graphics4__CubeMap r11;
	String r6, r7;
	kha__Image r28;
	haxe__ds__StringMap r24;
	hl__types__ArrayObj r16, r18;
	vvirtual *r15, *r17;
	hl_type *r27;
	iron__$App r22;
	iron__$Scene r14;
	iron__Scene r13;
	bool r10;
	iron__RenderTarget r9, r25;
	vclosure *r21;
	iron__object__CameraObject r12;
	double r4, r29, r30;
	vdynamic *r23;
	varray *r26;
	int r8, r19, r20;
	if( r3 ) goto label$80733c3_4_3;
	r4 = 1.;
	goto label$80733c3_4_4;
	label$80733c3_4_3:
	r4 = *r3;
	label$80733c3_4_4:
	r7 = (String)s$;
	if( r1 != r7 && (!r1 || !r7 || String___compare(r1,(vdynamic*)r7) != 0) ) goto label$80733c3_4_128;
	r8 = 1;
	r0->currentD = r8;
	r9 = NULL;
	r0->currentTarget = r9;
	r8 = -1;
	r0->currentFace = r8;
	r10 = r0->isProbeCube;
	if( !r10 ) goto label$80733c3_4_66;
	r14 = (iron__$Scene)g$_iron_Scene;
	r13 = r14->active;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->camera;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->renderTargetCube;
	if( r11 == NULL ) hl_null_access();
	r8 = kha_graphics4_CubeMap_get_width(r11);
	r0->currentW = r8;
	r14 = (iron__$Scene)g$_iron_Scene;
	r13 = r14->active;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->camera;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->renderTargetCube;
	if( r11 == NULL ) hl_null_access();
	r8 = kha_graphics4_CubeMap_get_height(r11);
	r0->currentH = r8;
	r15 = r0->frameG;
	r16 = NULL;
	r14 = (iron__$Scene)g$_iron_Scene;
	r13 = r14->active;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->camera;
	if( r12 == NULL ) hl_null_access();
	r8 = r12->currentFace;
	r17 = r0->currentG;
	if( !r17 ) goto label$80733c3_4_56;
	r10 = r0->scissorSet;
	if( !r10 ) goto label$80733c3_4_49;
	r17 = r0->currentG;
	if( r17 == NULL ) hl_null_access();
	if( hl_vfields(r17)[27] ) ((void (*)(vdynamic*))hl_vfields(r17)[27])(r17->value); else {
		hl_dyn_call_obj(r17->value,&t$fun_4c7a70a,40268564/*disableScissor*/,NULL,NULL);
	}
	r10 = false;
	r0->scissorSet = r10;
	label$80733c3_4_49:
	r17 = r0->currentG;
	if( r17 == NULL ) hl_null_access();
	if( hl_vfields(r17)[24] ) ((void (*)(vdynamic*))hl_vfields(r17)[24])(r17->value); else {
		hl_dyn_call_obj(r17->value,&t$fun_4c7a70a,5047259/*end*/,NULL,NULL);
	}
	r17 = NULL;
	r0->currentG = r17;
	r18 = NULL;
	r0->bindParams = r18;
	label$80733c3_4_56:
	r0->currentG = r15;
	r0->additionalTargets = r16;
	r20 = 0;
	if( r8 < r20 ) goto label$80733c3_4_63;
	if( r15 == NULL ) hl_null_access();
	if( hl_vfields(r15)[29] ) ((void (*)(vdynamic*,int))hl_vfields(r15)[29])(r15->value,r8); else {
		void *args[] = {&r8};
		hl_dyn_call_obj(r15->value,&t$fun_dc4017d,-326135337/*beginFace*/,args,NULL);
	}
	goto label$80733c3_4_65;
	label$80733c3_4_63:
	if( r15 == NULL ) hl_null_access();
	if( hl_vfields(r15)[30] ) ((void (*)(vdynamic*,hl__types__ArrayObj))hl_vfields(r15)[30])(r15->value,r16); else {
		void *args[] = {r16};
		hl_dyn_call_obj(r15->value,&t$fun_58e3acc,-262805217/*begin*/,args,NULL);
	}
	label$80733c3_4_65:
	goto label$80733c3_4_127;
	label$80733c3_4_66:
	r22 = (iron__$App)g$_iron_App;
	r21 = r22->w;
	if( r21 == NULL ) hl_null_access();
	r8 = r21->hasValue ? ((int (*)(vdynamic*))r21->fun)((vdynamic*)r21->value) : ((int (*)(void))r21->fun)();
	r0->currentW = r8;
	r22 = (iron__$App)g$_iron_App;
	r21 = r22->h;
	if( r21 == NULL ) hl_null_access();
	r8 = r21->hasValue ? ((int (*)(vdynamic*))r21->fun)((vdynamic*)r21->value) : ((int (*)(void))r21->fun)();
	r0->currentH = r8;
	r10 = r0->frameScissor;
	if( !r10 ) goto label$80733c3_4_79;
	iron_RenderPath_setFrameScissor(r0);
	label$80733c3_4_79:
	r15 = r0->frameG;
	r16 = NULL;
	r8 = -1;
	r17 = r0->currentG;
	if( !r17 ) goto label$80733c3_4_98;
	r10 = r0->scissorSet;
	if( !r10 ) goto label$80733c3_4_91;
	r17 = r0->currentG;
	if( r17 == NULL ) hl_null_access();
	if( hl_vfields(r17)[27] ) ((void (*)(vdynamic*))hl_vfields(r17)[27])(r17->value); else {
		hl_dyn_call_obj(r17->value,&t$fun_4c7a70a,40268564/*disableScissor*/,NULL,NULL);
	}
	r10 = false;
	r0->scissorSet = r10;
	label$80733c3_4_91:
	r17 = r0->currentG;
	if( r17 == NULL ) hl_null_access();
	if( hl_vfields(r17)[24] ) ((void (*)(vdynamic*))hl_vfields(r17)[24])(r17->value); else {
		hl_dyn_call_obj(r17->value,&t$fun_4c7a70a,5047259/*end*/,NULL,NULL);
	}
	r17 = NULL;
	r0->currentG = r17;
	r18 = NULL;
	r0->bindParams = r18;
	label$80733c3_4_98:
	r0->currentG = r15;
	r0->additionalTargets = r16;
	r20 = 0;
	if( r8 < r20 ) goto label$80733c3_4_105;
	if( r15 == NULL ) hl_null_access();
	if( hl_vfields(r15)[29] ) ((void (*)(vdynamic*,int))hl_vfields(r15)[29])(r15->value,r8); else {
		void *args[] = {&r8};
		hl_dyn_call_obj(r15->value,&t$fun_dc4017d,-326135337/*beginFace*/,args,NULL);
	}
	goto label$80733c3_4_107;
	label$80733c3_4_105:
	if( r15 == NULL ) hl_null_access();
	if( hl_vfields(r15)[30] ) ((void (*)(vdynamic*,hl__types__ArrayObj))hl_vfields(r15)[30])(r15->value,r16); else {
		void *args[] = {r16};
		hl_dyn_call_obj(r15->value,&t$fun_58e3acc,-262805217/*begin*/,args,NULL);
	}
	label$80733c3_4_107:
	r10 = r0->isProbe;
	if( r10 ) goto label$80733c3_4_127;
	r22 = (iron__$App)g$_iron_App;
	r21 = r22->w;
	if( r21 == NULL ) hl_null_access();
	r8 = r21->hasValue ? ((int (*)(vdynamic*))r21->fun)((vdynamic*)r21->value) : ((int (*)(void))r21->fun)();
	r22 = (iron__$App)g$_iron_App;
	r21 = r22->h;
	if( r21 == NULL ) hl_null_access();
	r19 = r21->hasValue ? ((int (*)(vdynamic*))r21->fun)((vdynamic*)r21->value) : ((int (*)(void))r21->fun)();
	iron_RenderPath_setCurrentViewport(r0,r8,r19);
	r22 = (iron__$App)g$_iron_App;
	r21 = r22->w;
	if( r21 == NULL ) hl_null_access();
	r8 = r21->hasValue ? ((int (*)(vdynamic*))r21->fun)((vdynamic*)r21->value) : ((int (*)(void))r21->fun)();
	r22 = (iron__$App)g$_iron_App;
	r21 = r22->h;
	if( r21 == NULL ) hl_null_access();
	r19 = r21->hasValue ? ((int (*)(vdynamic*))r21->fun)((vdynamic*)r21->value) : ((int (*)(void))r21->fun)();
	iron_RenderPath_setCurrentScissor(r0,r8,r19);
	label$80733c3_4_127:
	goto label$80733c3_4_224;
	label$80733c3_4_128:
	r24 = r0->renderTargets;
	if( r24 == NULL ) hl_null_access();
	r23 = haxe_ds_StringMap_get(r24,r1);
	r9 = (iron__RenderTarget)r23;
	r0->currentTarget = r9;
	r16 = NULL;
	if( !r2 ) goto label$80733c3_4_162;
	r27 = &t$vrt_7ced7cf;
	r8 = 0;
	r26 = hl_alloc_array(r27,r8);
	r18 = hl_types_ArrayObj_alloc(r26);
	r16 = r18;
	r8 = 0;
	label$80733c3_4_141:
	if( r2 == NULL ) hl_null_access();
	r20 = r2->length;
	if( r8 >= r20 ) goto label$80733c3_4_162;
	r20 = r2->length;
	if( ((unsigned)r8) < ((unsigned)r20) ) goto label$80733c3_4_149;
	r6 = NULL;
	goto label$80733c3_4_152;
	label$80733c3_4_149:
	r26 = r2->array;
	r23 = ((vdynamic**)(r26 + 1))[r8];
	r6 = (String)r23;
	label$80733c3_4_152:
	++r8;
	r24 = r0->renderTargets;
	if( r24 == NULL ) hl_null_access();
	r23 = haxe_ds_StringMap_get(r24,r6);
	r25 = (iron__RenderTarget)r23;
	if( r16 == NULL ) hl_null_access();
	if( r25 == NULL ) hl_null_access();
	r28 = r25->image;
	r19 = hl_types_ArrayObj_push(r16,((vdynamic*)r28));
	goto label$80733c3_4_141;
	label$80733c3_4_162:
	if( r9 == NULL ) hl_null_access();
	r10 = r9->isCubeMap;
	if( !r10 ) goto label$80733c3_4_169;
	r11 = r9->cubeMap;
	if( r11 == NULL ) hl_null_access();
	r15 = kha_graphics4_CubeMap_get_g4(r11);
	goto label$80733c3_4_172;
	label$80733c3_4_169:
	r28 = r9->image;
	if( r28 == NULL ) hl_null_access();
	r15 = kha_Image_get_g4(r28);
	label$80733c3_4_172:
	r10 = r9->isCubeMap;
	if( !r10 ) goto label$80733c3_4_178;
	r11 = r9->cubeMap;
	if( r11 == NULL ) hl_null_access();
	r8 = kha_graphics4_CubeMap_get_width(r11);
	goto label$80733c3_4_181;
	label$80733c3_4_178:
	r28 = r9->image;
	if( r28 == NULL ) hl_null_access();
	r8 = kha_Image_get_width(r28);
	label$80733c3_4_181:
	r0->currentW = r8;
	r10 = r9->isCubeMap;
	if( !r10 ) goto label$80733c3_4_188;
	r11 = r9->cubeMap;
	if( r11 == NULL ) hl_null_access();
	r8 = kha_graphics4_CubeMap_get_height(r11);
	goto label$80733c3_4_191;
	label$80733c3_4_188:
	r28 = r9->image;
	if( r28 == NULL ) hl_null_access();
	r8 = kha_Image_get_height(r28);
	label$80733c3_4_191:
	r0->currentH = r8;
	r10 = r9->is3D;
	if( !r10 ) goto label$80733c3_4_198;
	r28 = r9->image;
	if( r28 == NULL ) hl_null_access();
	r8 = kha_Image_get_depth(r28);
	r0->currentD = r8;
	label$80733c3_4_198:
	r8 = r0->currentFace;
	r17 = r0->currentG;
	if( !r17 ) goto label$80733c3_4_215;
	r10 = r0->scissorSet;
	if( !r10 ) goto label$80733c3_4_208;
	r17 = r0->currentG;
	if( r17 == NULL ) hl_null_access();
	if( hl_vfields(r17)[27] ) ((void (*)(vdynamic*))hl_vfields(r17)[27])(r17->value); else {
		hl_dyn_call_obj(r17->value,&t$fun_4c7a70a,40268564/*disableScissor*/,NULL,NULL);
	}
	r10 = false;
	r0->scissorSet = r10;
	label$80733c3_4_208:
	r17 = r0->currentG;
	if( r17 == NULL ) hl_null_access();
	if( hl_vfields(r17)[24] ) ((void (*)(vdynamic*))hl_vfields(r17)[24])(r17->value); else {
		hl_dyn_call_obj(r17->value,&t$fun_4c7a70a,5047259/*end*/,NULL,NULL);
	}
	r17 = NULL;
	r0->currentG = r17;
	r18 = NULL;
	r0->bindParams = r18;
	label$80733c3_4_215:
	r0->currentG = r15;
	r0->additionalTargets = r16;
	r20 = 0;
	if( r8 < r20 ) goto label$80733c3_4_222;
	if( r15 == NULL ) hl_null_access();
	if( hl_vfields(r15)[29] ) ((void (*)(vdynamic*,int))hl_vfields(r15)[29])(r15->value,r8); else {
		void *args[] = {&r8};
		hl_dyn_call_obj(r15->value,&t$fun_dc4017d,-326135337/*beginFace*/,args,NULL);
	}
	goto label$80733c3_4_224;
	label$80733c3_4_222:
	if( r15 == NULL ) hl_null_access();
	if( hl_vfields(r15)[30] ) ((void (*)(vdynamic*,hl__types__ArrayObj))hl_vfields(r15)[30])(r15->value,r16); else {
		void *args[] = {r16};
		hl_dyn_call_obj(r15->value,&t$fun_58e3acc,-262805217/*begin*/,args,NULL);
	}
	label$80733c3_4_224:
	r30 = 1.;
	if( r4 == r30 ) goto label$80733c3_4_245;
	r10 = true;
	r0->viewportScaled = r10;
	r8 = r0->currentW;
	r29 = (double)r8;
	r29 = r29 * r4;
	r8 = (int)r29;
	r19 = r0->currentH;
	r30 = (double)r19;
	r30 = r30 * r4;
	r19 = (int)r30;
	r15 = r0->currentG;
	if( r15 == NULL ) hl_null_access();
	r20 = 0;
	if( hl_vfields(r15)[0] ) ((void (*)(vdynamic*,int,int,int,int))hl_vfields(r15)[0])(r15->value,r20,r19,r8,r19); else {
		void *args[] = {&r20,&r19,&r8,&r19};
		hl_dyn_call_obj(r15->value,&t$fun_5ac3579,-56276265/*viewport*/,args,NULL);
	}
	r15 = r0->currentG;
	if( r15 == NULL ) hl_null_access();
	r20 = 0;
	if( hl_vfields(r15)[23] ) ((void (*)(vdynamic*,int,int,int,int))hl_vfields(r15)[23])(r15->value,r20,r19,r8,r19); else {
		void *args[] = {&r20,&r19,&r8,&r19};
		hl_dyn_call_obj(r15->value,&t$fun_5ac3579,82257948/*scissor*/,args,NULL);
	}
	goto label$80733c3_4_255;
	label$80733c3_4_245:
	r10 = r0->viewportScaled;
	if( !r10 ) goto label$80733c3_4_255;
	r10 = false;
	r0->viewportScaled = r10;
	r8 = r0->currentW;
	r19 = r0->currentH;
	iron_RenderPath_setCurrentViewport(r0,r8,r19);
	r8 = r0->currentW;
	r19 = r0->currentH;
	iron_RenderPath_setCurrentScissor(r0,r8,r19);
	label$80733c3_4_255:
	r16 = NULL;
	r0->bindParams = r16;
	return;
}

void iron_RenderPath_setCurrentViewport(iron__RenderPath r0,int r1,int r2) {
	vvirtual *r4;
	iron__$App r7;
	vclosure *r6;
	int r5, r8, r9, r10;
	r4 = r0->currentG;
	if( r4 == NULL ) hl_null_access();
	r7 = (iron__$App)g$_iron_App;
	r6 = r7->x;
	if( r6 == NULL ) hl_null_access();
	r5 = r6->hasValue ? ((int (*)(vdynamic*))r6->fun)((vdynamic*)r6->value) : ((int (*)(void))r6->fun)();
	r8 = r0->currentH;
	r7 = (iron__$App)g$_iron_App;
	r6 = r7->y;
	if( r6 == NULL ) hl_null_access();
	r10 = r6->hasValue ? ((int (*)(vdynamic*))r6->fun)((vdynamic*)r6->value) : ((int (*)(void))r6->fun)();
	r9 = r2 - r10;
	r8 = r8 - r9;
	if( hl_vfields(r4)[0] ) ((void (*)(vdynamic*,int,int,int,int))hl_vfields(r4)[0])(r4->value,r5,r8,r1,r2); else {
		void *args[] = {&r5,&r8,&r1,&r2};
		hl_dyn_call_obj(r4->value,&t$fun_5ac3579,-56276265/*viewport*/,args,NULL);
	}
	return;
}

void iron_RenderPath_setCurrentScissor(iron__RenderPath r0,int r1,int r2) {
	vvirtual *r4;
	iron__$App r7;
	bool r11;
	vclosure *r6;
	int r5, r8, r9, r10;
	r4 = r0->currentG;
	if( r4 == NULL ) hl_null_access();
	r7 = (iron__$App)g$_iron_App;
	r6 = r7->x;
	if( r6 == NULL ) hl_null_access();
	r5 = r6->hasValue ? ((int (*)(vdynamic*))r6->fun)((vdynamic*)r6->value) : ((int (*)(void))r6->fun)();
	r8 = r0->currentH;
	r7 = (iron__$App)g$_iron_App;
	r6 = r7->y;
	if( r6 == NULL ) hl_null_access();
	r10 = r6->hasValue ? ((int (*)(vdynamic*))r6->fun)((vdynamic*)r6->value) : ((int (*)(void))r6->fun)();
	r9 = r2 - r10;
	r8 = r8 - r9;
	if( hl_vfields(r4)[23] ) ((void (*)(vdynamic*,int,int,int,int))hl_vfields(r4)[23])(r4->value,r5,r8,r1,r2); else {
		void *args[] = {&r5,&r8,&r1,&r2};
		hl_dyn_call_obj(r4->value,&t$fun_5ac3579,82257948/*scissor*/,args,NULL);
	}
	r11 = true;
	r0->scissorSet = r11;
	return;
}

void iron_RenderPath_setFrameScissor(iron__RenderPath r0) {
	vvirtual *r2;
	int r3, r4, r5, r6;
	r2 = r0->frameG;
	if( r2 == NULL ) hl_null_access();
	r3 = r0->frameScissorX;
	r4 = r0->currentH;
	r5 = r0->frameScissorH;
	r6 = r0->frameScissorY;
	r5 = r5 - r6;
	r4 = r4 - r5;
	r5 = r0->frameScissorW;
	r6 = r0->frameScissorH;
	if( hl_vfields(r2)[23] ) ((void (*)(vdynamic*,int,int,int,int))hl_vfields(r2)[23])(r2->value,r3,r4,r5,r6); else {
		void *args[] = {&r3,&r4,&r5,&r6};
		hl_dyn_call_obj(r2->value,&t$fun_5ac3579,82257948/*scissor*/,args,NULL);
	}
	return;
}

void iron_RenderPath_clearTarget(iron__RenderPath r0,vdynamic* r1,vdynamic* r2) {
	vvirtual *r21;
	iron__$Scene r9;
	iron__Scene r8;
	iron__data__TCameraData r13;
	iron__data__CameraData r14;
	kha__arrays__ByteArrayPrivate r12;
	iron__data__TWorldData r10;
	float r15, r17, r19;
	iron__data__WorldData r7;
	iron__object__CameraObject r11;
	vdynamic *r4, *r6;
	float *r20;
	vbyte *r16;
	int r5, r18;
	r5 = -1;
	r6 = hl_alloc_dynamic(&t$_i32);
	r6->v.i = r5;
	if( r1 != r6 && (!r1 || !r6 || (r1->v.i != r6->v.i)) ) goto label$80733c3_8_53;
	r9 = (iron__$Scene)g$_iron_Scene;
	r8 = r9->active;
	if( r8 == NULL ) hl_null_access();
	r7 = r8->world;
	if( !r7 ) goto label$80733c3_8_19;
	r9 = (iron__$Scene)g$_iron_Scene;
	r8 = r9->active;
	if( r8 == NULL ) hl_null_access();
	r7 = r8->world;
	if( r7 == NULL ) hl_null_access();
	r10 = r7->raw;
	if( r10 == NULL ) hl_null_access();
	r5 = r10->background_color;
	r4 = hl_alloc_dynamic(&t$_i32);
	r4->v.i = r5;
	r1 = r4;
	goto label$80733c3_8_53;
	label$80733c3_8_19:
	r9 = (iron__$Scene)g$_iron_Scene;
	r8 = r9->active;
	if( r8 == NULL ) hl_null_access();
	r11 = r8->camera;
	if( !r11 ) goto label$80733c3_8_53;
	r9 = (iron__$Scene)g$_iron_Scene;
	r8 = r9->active;
	if( r8 == NULL ) hl_null_access();
	r11 = r8->camera;
	if( r11 == NULL ) hl_null_access();
	r14 = r11->data;
	if( r14 == NULL ) hl_null_access();
	r13 = r14->raw;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->clear_color;
	if( !r12 ) goto label$80733c3_8_53;
	if( r12 == NULL ) hl_null_access();
	r16 = r12->self;
	r5 = r12->byteArrayOffset;
	r15 = hl_kinc_bytearray_getfloat32(r16,r5);
	r16 = r12->self;
	r5 = r12->byteArrayOffset;
	r18 = 4;
	r5 = r5 + r18;
	r17 = hl_kinc_bytearray_getfloat32(r16,r5);
	r16 = r12->self;
	r5 = r12->byteArrayOffset;
	r18 = 8;
	r5 = r5 + r18;
	r19 = hl_kinc_bytearray_getfloat32(r16,r5);
	r20 = NULL;
	r5 = kha__Color_Color_Impl__fromFloats(r15,r17,r19,r20);
	r4 = hl_alloc_dynamic(&t$_i32);
	r4->v.i = r5;
	r1 = r4;
	label$80733c3_8_53:
	r21 = r0->currentG;
	if( r21 == NULL ) hl_null_access();
	r6 = NULL;
	if( hl_vfields(r21)[28] ) ((void (*)(vdynamic*,vdynamic*,vdynamic*,vdynamic*))hl_vfields(r21)[28])(r21->value,r1,r2,r6); else {
		void *args[] = {r1,r2,r6};
		hl_dyn_call_obj(r21->value,&t$fun_5967954,140210839/*clear*/,args,NULL);
	}
	return;
}

int iron_RenderPath_sortMeshesDistance__$1(iron__object__MeshObject r0,iron__object__MeshObject r1) {
	double r2, r3;
	int r4;
	if( r0 == NULL ) hl_null_access();
	r2 = r0->cameraDistance;
	if( r1 == NULL ) hl_null_access();
	r3 = r1->cameraDistance;
	if( !(r2 >= r3) ) goto label$80733c3_9_7;
	r4 = 1;
	return r4;
	label$80733c3_9_7:
	r4 = -1;
	return r4;
}

void iron_RenderPath_sortMeshesDistance(hl__types__ArrayObj r0) {
	vclosure *r2, *r3;
	static vclosure cl$0 = { &t$fun_01f8d35, iron_RenderPath_sortMeshesDistance__$1, 0 };
	if( r0 == NULL ) hl_null_access();
	r2 = &cl$0;
	if( r2 ) goto label$80733c3_10_5;
	r3 = NULL;
	goto label$80733c3_10_6;
	label$80733c3_10_5:
	r3 = hl_alloc_closure_ptr(&t$fun_2237bde,wrapt$fun_2237bde,r2);
	label$80733c3_10_6:
	hl_types_ArrayObj_sort(r0,r3);
	return;
}

int iron_RenderPath_sortMeshesShader__$1(iron__object__MeshObject r0,iron__object__MeshObject r1) {
	String r2, r9;
	hl__types__ArrayObj r3;
	iron__data__MaterialData r6;
	vdynamic *r7;
	varray *r8;
	int r4, r5;
	if( r0 == NULL ) hl_null_access();
	r3 = r0->materials;
	if( r3 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r3->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$80733c3_11_8;
	r6 = NULL;
	goto label$80733c3_11_11;
	label$80733c3_11_8:
	r8 = r3->array;
	r7 = ((vdynamic**)(r8 + 1))[r4];
	r6 = (iron__data__MaterialData)r7;
	label$80733c3_11_11:
	if( r6 == NULL ) hl_null_access();
	r2 = r6->name;
	if( r1 == NULL ) hl_null_access();
	r3 = r1->materials;
	if( r3 == NULL ) hl_null_access();
	r4 = 0;
	r5 = r3->length;
	if( ((unsigned)r4) < ((unsigned)r5) ) goto label$80733c3_11_21;
	r6 = NULL;
	goto label$80733c3_11_24;
	label$80733c3_11_21:
	r8 = r3->array;
	r7 = ((vdynamic**)(r8 + 1))[r4];
	r6 = (iron__data__MaterialData)r7;
	label$80733c3_11_24:
	if( r6 == NULL ) hl_null_access();
	r9 = r6->name;
	if( r2 && r9 && String___compare(r2,(vdynamic*)r9) < 0 ) goto label$80733c3_11_29;
	r4 = 1;
	return r4;
	label$80733c3_11_29:
	r4 = -1;
	return r4;
}

void iron_RenderPath_sortMeshesShader(hl__types__ArrayObj r0) {
	vclosure *r2, *r3;
	static vclosure cl$0 = { &t$fun_01f8d35, iron_RenderPath_sortMeshesShader__$1, 0 };
	if( r0 == NULL ) hl_null_access();
	r2 = &cl$0;
	if( r2 ) goto label$80733c3_12_5;
	r3 = NULL;
	goto label$80733c3_12_6;
	label$80733c3_12_5:
	r3 = hl_alloc_closure_ptr(&t$fun_2237bde,wrapt$fun_2237bde,r2);
	label$80733c3_12_6:
	hl_types_ArrayObj_sort(r0,r3);
	return;
}

void iron_RenderPath_drawMeshes(iron__RenderPath r0,String r1) {
	String r3, r4;
	hl__types__ArrayObj r25;
	vvirtual *r23;
	iron__data__TLightData r9;
	iron__$Scene r17;
	iron__Scene r16;
	bool r2, r6, r18;
	iron__data__LightData r10;
	iron__object__LightObject r7;
	float r11, r13;
	iron__object__CameraObject r15;
	vdynamic *r8;
	iron__object__$LightObject r20;
	int r12, r14, r19, r21, r22, r24;
	r4 = (String)s$shadowmap;
	if( r1 == r4 || (r1 && r4 && String___compare(r1,(vdynamic*)r4) == 0) ) goto label$80733c3_13_4;
	r2 = false;
	goto label$80733c3_13_5;
	label$80733c3_13_4:
	r2 = true;
	label$80733c3_13_5:
	if( !r2 ) goto label$80733c3_13_32;
	r7 = r0->light;
	if( !r7 ) goto label$80733c3_13_31;
	r7 = r0->light;
	if( r7 == NULL ) hl_null_access();
	r10 = r7->data;
	if( r10 == NULL ) hl_null_access();
	r9 = r10->raw;
	if( r9 == NULL ) hl_null_access();
	r8 = r9->cast_shadow;
	r6 = r8 ? r8->v.b : 0;
	if( !r6 ) goto label$80733c3_13_31;
	r7 = r0->light;
	if( r7 == NULL ) hl_null_access();
	r6 = r7->visible;
	if( !r6 ) goto label$80733c3_13_31;
	r7 = r0->light;
	if( r7 == NULL ) hl_null_access();
	r10 = r7->data;
	if( r10 == NULL ) hl_null_access();
	r9 = r10->raw;
	if( r9 == NULL ) hl_null_access();
	r11 = r9->strength;
	r12 = 0;
	r13 = (float)r12;
	if( r11 != r13 ) goto label$80733c3_13_32;
	label$80733c3_13_31:
	return;
	label$80733c3_13_32:
	r12 = r0->currentFace;
	r14 = 0;
	if( r12 < r14 ) goto label$80733c3_13_45;
	r7 = r0->light;
	if( !r7 ) goto label$80733c3_13_45;
	r7 = r0->light;
	if( r7 == NULL ) hl_null_access();
	r12 = r0->currentFace;
	r17 = (iron__$Scene)g$_iron_Scene;
	r16 = r17->active;
	if( r16 == NULL ) hl_null_access();
	r15 = r16->camera;
	iron_object_LightObject_setCubeFace(r7,r12,r15);
	label$80733c3_13_45:
	r6 = false;
	if( !r2 ) goto label$80733c3_13_80;
	r7 = r0->light;
	if( r7 == NULL ) hl_null_access();
	r10 = r7->data;
	if( r10 == NULL ) hl_null_access();
	r9 = r10->raw;
	if( r9 == NULL ) hl_null_access();
	r3 = r9->type;
	r4 = (String)s$sun;
	if( r3 != r4 && (!r3 || !r4 || String___compare(r3,(vdynamic*)r4) != 0) ) goto label$80733c3_13_80;
	r12 = r0->currentH;
	r14 = 0;
	r20 = (iron__object__$LightObject)g$_iron_object_LightObject;
	r19 = r20->cascadeCount;
	label$80733c3_13_60:
	if( r14 >= r19 ) goto label$80733c3_13_78;
	r21 = r14;
	++r14;
	r7 = r0->light;
	if( r7 == NULL ) hl_null_access();
	r17 = (iron__$Scene)g$_iron_Scene;
	r16 = r17->active;
	if( r16 == NULL ) hl_null_access();
	r15 = r16->camera;
	iron_object_LightObject_setCascade(r7,r15,r21);
	r23 = r0->currentG;
	if( r23 == NULL ) hl_null_access();
	r22 = r21 * r12;
	r24 = 0;
	if( hl_vfields(r23)[0] ) ((void (*)(vdynamic*,int,int,int,int))hl_vfields(r23)[0])(r23->value,r22,r24,r12,r12); else {
		void *args[] = {&r22,&r24,&r12,&r12};
		hl_dyn_call_obj(r23->value,&t$fun_5ac3579,-56276265/*viewport*/,args,NULL);
	}
	iron_RenderPath_submitDraw(r0,r1);
	goto label$80733c3_13_60;
	label$80733c3_13_78:
	r18 = true;
	r6 = r18;
	label$80733c3_13_80:
	if( r6 ) goto label$80733c3_13_82;
	iron_RenderPath_submitDraw(r0,r1);
	label$80733c3_13_82:
	r18 = r0->scissorSet;
	if( !r18 ) goto label$80733c3_13_89;
	r23 = r0->currentG;
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[27] ) ((void (*)(vdynamic*))hl_vfields(r23)[27])(r23->value); else {
		hl_dyn_call_obj(r23->value,&t$fun_4c7a70a,40268564/*disableScissor*/,NULL,NULL);
	}
	r18 = false;
	r0->scissorSet = r18;
	label$80733c3_13_89:
	r23 = r0->currentG;
	if( r23 == NULL ) hl_null_access();
	if( hl_vfields(r23)[24] ) ((void (*)(vdynamic*))hl_vfields(r23)[24])(r23->value); else {
		hl_dyn_call_obj(r23->value,&t$fun_4c7a70a,5047259/*end*/,NULL,NULL);
	}
	r23 = NULL;
	r0->currentG = r23;
	r25 = NULL;
	r0->bindParams = r25;
	return;
}

void iron_RenderPath_submitDraw(iron__RenderPath r0,String r1) {
	iron__object__$MeshObject r8;
	iron__object__MeshObject r20;
	kha__graphics4__PipelineState r7;
	vvirtual *r29;
	hl__types__ArrayObj r6, r19;
	kha__math__FastMatrix4 r11;
	bool r9;
	iron__$Scene r4;
	iron__Scene r3;
	iron__object__Transform r13;
	iron__math__Mat4 r12;
	float r10, r14, r15, r23, r24, r25, r26, r28;
	double r27;
	iron__object__CameraObject r2;
	vdynamic *r21;
	varray *r22;
	int r16, r17, r18;
	r4 = (iron__$Scene)g$_iron_Scene;
	r3 = r4->active;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->camera;
	r4 = (iron__$Scene)g$_iron_Scene;
	r3 = r4->active;
	if( r3 == NULL ) hl_null_access();
	r6 = r3->meshes;
	r7 = NULL;
	r8 = (iron__object__$MeshObject)g$_iron_object_MeshObject;
	r8->lastPipeline = r7;
	r9 = r0->meshesSorted;
	if( r9 ) goto label$80733c3_14_93;
	if( !r2 ) goto label$80733c3_14_93;
	if( r2 == NULL ) hl_null_access();
	r13 = r2->transform;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->world;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->self;
	if( r11 == NULL ) hl_null_access();
	r10 = r11->_30;
	r13 = r2->transform;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->world;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->self;
	if( r11 == NULL ) hl_null_access();
	r14 = r11->_31;
	r13 = r2->transform;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->world;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->self;
	if( r11 == NULL ) hl_null_access();
	r15 = r11->_32;
	r16 = 0;
	label$80733c3_14_37:
	if( r6 == NULL ) hl_null_access();
	r18 = r6->length;
	if( r16 >= r18 ) goto label$80733c3_14_85;
	r18 = r6->length;
	if( ((unsigned)r16) < ((unsigned)r18) ) goto label$80733c3_14_45;
	r20 = NULL;
	goto label$80733c3_14_48;
	label$80733c3_14_45:
	r22 = r6->array;
	r21 = ((vdynamic**)(r22 + 1))[r16];
	r20 = (iron__object__MeshObject)r21;
	label$80733c3_14_48:
	++r16;
	if( r20 == NULL ) hl_null_access();
	r13 = r20->transform;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->world;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->self;
	if( r11 == NULL ) hl_null_access();
	r24 = r11->_30;
	r23 = r10 - r24;
	r13 = r20->transform;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->world;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->self;
	if( r11 == NULL ) hl_null_access();
	r25 = r11->_31;
	r24 = r14 - r25;
	r13 = r20->transform;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->world;
	if( r12 == NULL ) hl_null_access();
	r11 = r12->self;
	if( r11 == NULL ) hl_null_access();
	r26 = r11->_32;
	r25 = r15 - r26;
	r26 = r23 * r23;
	r28 = r24 * r24;
	r26 = r26 + r28;
	r28 = r25 * r25;
	r26 = r26 + r28;
	r27 = (double)r26;
	r27 = hl_math_sqrt(r27);
	r26 = (float)r27;
	r27 = (double)r26;
	r20->cameraDistance = r27;
	goto label$80733c3_14_37;
	label$80733c3_14_85:
	r16 = r0->drawOrder;
	r17 = 1;
	if( r16 != r17 ) goto label$80733c3_14_90;
	iron_RenderPath_sortMeshesShader(r6);
	goto label$80733c3_14_91;
	label$80733c3_14_90:
	iron_RenderPath_sortMeshesDistance(r6);
	label$80733c3_14_91:
	r9 = true;
	r0->meshesSorted = r9;
	label$80733c3_14_93:
	r29 = r0->currentG;
	r19 = r0->bindParams;
	r16 = 0;
	label$80733c3_14_96:
	if( r6 == NULL ) hl_null_access();
	r18 = r6->length;
	if( r16 >= r18 ) goto label$80733c3_14_111;
	r18 = r6->length;
	if( ((unsigned)r16) < ((unsigned)r18) ) goto label$80733c3_14_104;
	r20 = NULL;
	goto label$80733c3_14_107;
	label$80733c3_14_104:
	r22 = r6->array;
	r21 = ((vdynamic**)(r22 + 1))[r16];
	r20 = (iron__object__MeshObject)r21;
	label$80733c3_14_107:
	++r16;
	if( r20 == NULL ) hl_null_access();
	iron_object_MeshObject_render(r20,r29,r1,r19);
	goto label$80733c3_14_96;
	label$80733c3_14_111:
	return;
}

void iron_RenderPath_drawSkydome(iron__RenderPath r0,String r1) {
	kha__graphics4__PipelineState r10;
	iron__data__$ConstData r4;
	hl__types__ArrayObj r11;
	vvirtual *r9;
	iron__data__ShaderContext r8;
	haxe__ds__StringMap r6;
	bool r16;
	kha__graphics4__VertexBuffer r3;
	kha__graphics4__IndexBuffer r13;
	iron__CachedShaderContext r7;
	int *r14, *r15;
	iron__object__Object r12;
	vdynamic *r5;
	r4 = (iron__data__$ConstData)g$_iron_data_ConstData;
	r3 = r4->skydomeVB;
	if( r3 ) goto label$80733c3_15_4;
	iron_data_ConstData_createSkydomeData();
	label$80733c3_15_4:
	r6 = r0->cachedShaderContexts;
	if( r6 == NULL ) hl_null_access();
	r5 = haxe_ds_StringMap_get(r6,r1);
	r7 = (iron__CachedShaderContext)r5;
	if( r7 == NULL ) hl_null_access();
	r8 = r7->context;
	if( r8 ) goto label$80733c3_15_12;
	return;
	label$80733c3_15_12:
	r9 = r0->currentG;
	if( r9 == NULL ) hl_null_access();
	r8 = r7->context;
	if( r8 == NULL ) hl_null_access();
	r10 = r8->pipeState;
	if( hl_vfields(r9)[8] ) ((void (*)(vdynamic*,kha__graphics4__PipelineState))hl_vfields(r9)[8])(r9->value,r10); else {
		void *args[] = {r10};
		hl_dyn_call_obj(r9->value,&t$fun_c80ec77,467961459/*setPipeline*/,args,NULL);
	}
	r9 = r0->currentG;
	r8 = r7->context;
	r11 = r0->bindParams;
	iron_object_Uniforms_setContextConstants(r9,r8,r11);
	r9 = r0->currentG;
	r8 = r7->context;
	r12 = NULL;
	iron_object_Uniforms_setObjectConstants(r9,r8,r12);
	r9 = r0->currentG;
	if( r9 == NULL ) hl_null_access();
	r4 = (iron__data__$ConstData)g$_iron_data_ConstData;
	r3 = r4->skydomeVB;
	if( hl_vfields(r9)[2] ) ((void (*)(vdynamic*,kha__graphics4__VertexBuffer))hl_vfields(r9)[2])(r9->value,r3); else {
		void *args[] = {r3};
		hl_dyn_call_obj(r9->value,&t$fun_a561c62,-278953801/*setVertexBuffer*/,args,NULL);
	}
	r9 = r0->currentG;
	if( r9 == NULL ) hl_null_access();
	r4 = (iron__data__$ConstData)g$_iron_data_ConstData;
	r13 = r4->skydomeIB;
	if( hl_vfields(r9)[12] ) ((void (*)(vdynamic*,kha__graphics4__IndexBuffer))hl_vfields(r9)[12])(r9->value,r13); else {
		void *args[] = {r13};
		hl_dyn_call_obj(r9->value,&t$fun_46c6b6e,-43737183/*setIndexBuffer*/,args,NULL);
	}
	r9 = r0->currentG;
	if( r9 == NULL ) hl_null_access();
	r14 = NULL;
	r15 = NULL;
	if( hl_vfields(r9)[26] ) ((void (*)(vdynamic*,int*,int*))hl_vfields(r9)[26])(r9->value,r14,r15); else {
		void *args[] = {r14,r15};
		hl_dyn_call_obj(r9->value,&t$fun_8305be0,-519327652/*drawIndexedVertices*/,args,NULL);
	}
	r16 = r0->scissorSet;
	if( !r16 ) goto label$80733c3_15_48;
	r9 = r0->currentG;
	if( r9 == NULL ) hl_null_access();
	if( hl_vfields(r9)[27] ) ((void (*)(vdynamic*))hl_vfields(r9)[27])(r9->value); else {
		hl_dyn_call_obj(r9->value,&t$fun_4c7a70a,40268564/*disableScissor*/,NULL,NULL);
	}
	r16 = false;
	r0->scissorSet = r16;
	label$80733c3_15_48:
	r9 = r0->currentG;
	if( r9 == NULL ) hl_null_access();
	if( hl_vfields(r9)[24] ) ((void (*)(vdynamic*))hl_vfields(r9)[24])(r9->value); else {
		hl_dyn_call_obj(r9->value,&t$fun_4c7a70a,5047259/*end*/,NULL,NULL);
	}
	r9 = NULL;
	r0->currentG = r9;
	r11 = NULL;
	r0->bindParams = r11;
	return;
}

void iron_RenderPath_bindTarget(iron__RenderPath r0,String r1,String r2) {
	hl__types__ArrayObj r4;
	hl_type *r7;
	varray *r6;
	int r5;
	r4 = r0->bindParams;
	if( !r4 ) goto label$80733c3_16_9;
	r4 = r0->bindParams;
	if( r4 == NULL ) hl_null_access();
	r5 = hl_types_ArrayObj_push(r4,((vdynamic*)r1));
	r4 = r0->bindParams;
	if( r4 == NULL ) hl_null_access();
	r5 = hl_types_ArrayObj_push(r4,((vdynamic*)r2));
	goto label$80733c3_16_18;
	label$80733c3_16_9:
	r7 = &t$String;
	r5 = 2;
	r6 = hl_alloc_array(r7,r5);
	r5 = 0;
	((String*)(r6 + 1))[r5] = r1;
	r5 = 1;
	((String*)(r6 + 1))[r5] = r2;
	r4 = hl_types_ArrayObj_alloc(r6);
	r0->bindParams = r4;
	label$80733c3_16_18:
	return;
}

void iron_RenderPath_drawShader(iron__RenderPath r0,String r1) {
	kha__graphics4__PipelineState r9;
	iron__data__$ConstData r7;
	hl__types__ArrayObj r11;
	iron__data__ShaderContext r10;
	vvirtual *r8;
	haxe__ds__StringMap r3;
	bool r16;
	kha__graphics4__VertexBuffer r6;
	kha__graphics4__IndexBuffer r13;
	iron__CachedShaderContext r4;
	int *r14, *r15;
	iron__object__Object r12;
	vdynamic *r2;
	r3 = r0->cachedShaderContexts;
	if( r3 == NULL ) hl_null_access();
	r2 = haxe_ds_StringMap_get(r3,r1);
	r4 = (iron__CachedShaderContext)r2;
	r7 = (iron__data__$ConstData)g$_iron_data_ConstData;
	r6 = r7->screenAlignedVB;
	if( r6 ) goto label$80733c3_17_8;
	iron_data_ConstData_createScreenAlignedData();
	label$80733c3_17_8:
	r8 = r0->currentG;
	if( r8 == NULL ) hl_null_access();
	if( r4 == NULL ) hl_null_access();
	r10 = r4->context;
	if( r10 == NULL ) hl_null_access();
	r9 = r10->pipeState;
	if( hl_vfields(r8)[8] ) ((void (*)(vdynamic*,kha__graphics4__PipelineState))hl_vfields(r8)[8])(r8->value,r9); else {
		void *args[] = {r9};
		hl_dyn_call_obj(r8->value,&t$fun_c80ec77,467961459/*setPipeline*/,args,NULL);
	}
	r8 = r0->currentG;
	r10 = r4->context;
	r11 = r0->bindParams;
	iron_object_Uniforms_setContextConstants(r8,r10,r11);
	r8 = r0->currentG;
	r10 = r4->context;
	r12 = NULL;
	iron_object_Uniforms_setObjectConstants(r8,r10,r12);
	r8 = r0->currentG;
	if( r8 == NULL ) hl_null_access();
	r7 = (iron__data__$ConstData)g$_iron_data_ConstData;
	r6 = r7->screenAlignedVB;
	if( hl_vfields(r8)[2] ) ((void (*)(vdynamic*,kha__graphics4__VertexBuffer))hl_vfields(r8)[2])(r8->value,r6); else {
		void *args[] = {r6};
		hl_dyn_call_obj(r8->value,&t$fun_a561c62,-278953801/*setVertexBuffer*/,args,NULL);
	}
	r8 = r0->currentG;
	if( r8 == NULL ) hl_null_access();
	r7 = (iron__data__$ConstData)g$_iron_data_ConstData;
	r13 = r7->screenAlignedIB;
	if( hl_vfields(r8)[12] ) ((void (*)(vdynamic*,kha__graphics4__IndexBuffer))hl_vfields(r8)[12])(r8->value,r13); else {
		void *args[] = {r13};
		hl_dyn_call_obj(r8->value,&t$fun_46c6b6e,-43737183/*setIndexBuffer*/,args,NULL);
	}
	r8 = r0->currentG;
	if( r8 == NULL ) hl_null_access();
	r14 = NULL;
	r15 = NULL;
	if( hl_vfields(r8)[26] ) ((void (*)(vdynamic*,int*,int*))hl_vfields(r8)[26])(r8->value,r14,r15); else {
		void *args[] = {r14,r15};
		hl_dyn_call_obj(r8->value,&t$fun_8305be0,-519327652/*drawIndexedVertices*/,args,NULL);
	}
	r16 = r0->scissorSet;
	if( !r16 ) goto label$80733c3_17_45;
	r8 = r0->currentG;
	if( r8 == NULL ) hl_null_access();
	if( hl_vfields(r8)[27] ) ((void (*)(vdynamic*))hl_vfields(r8)[27])(r8->value); else {
		hl_dyn_call_obj(r8->value,&t$fun_4c7a70a,40268564/*disableScissor*/,NULL,NULL);
	}
	r16 = false;
	r0->scissorSet = r16;
	label$80733c3_17_45:
	r8 = r0->currentG;
	if( r8 == NULL ) hl_null_access();
	if( hl_vfields(r8)[24] ) ((void (*)(vdynamic*))hl_vfields(r8)[24])(r8->value); else {
		hl_dyn_call_obj(r8->value,&t$fun_4c7a70a,5047259/*end*/,NULL,NULL);
	}
	r8 = NULL;
	r0->currentG = r8;
	r11 = NULL;
	r0->bindParams = r11;
	return;
}

void iron_RenderPath_loadShader__$1(venum* r0,iron__data__ShaderData r1) {
	String r9;
	iron__data__ShaderContext r8;
	hl__types__ArrayObj r2;
	iron__CachedShaderContext r5;
	vdynamic *r6;
	iron__RenderPath r10;
	varray *r7;
	int r3, r4;
	r2 = ((Enumt$ctx_93b0219*)r0)->p0;
	if( r2 == NULL ) hl_null_access();
	r3 = 0;
	r4 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$80733c3_18_7;
	r5 = NULL;
	goto label$80733c3_18_10;
	label$80733c3_18_7:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r3];
	r5 = (iron__CachedShaderContext)r6;
	label$80733c3_18_10:
	if( r5 == NULL ) hl_null_access();
	if( r1 == NULL ) hl_null_access();
	r2 = ((Enumt$ctx_93b0219*)r0)->p1;
	if( r2 == NULL ) hl_null_access();
	r3 = 2;
	r4 = r2->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$80733c3_18_19;
	r9 = NULL;
	goto label$80733c3_18_22;
	label$80733c3_18_19:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r3];
	r9 = (String)r6;
	label$80733c3_18_22:
	r8 = iron_data_ShaderData_getContext(r1,r9);
	r5->context = r8;
	r10 = ((Enumt$ctx_93b0219*)r0)->p2;
	if( r10 == NULL ) hl_null_access();
	r3 = r10->loading;
	--r3;
	r10->loading = r3;
	return;
}

void iron_RenderPath_loadShader(iron__RenderPath r0,String r1) {
	String r10, r13;
	haxe__ds__StringMap r9;
	hl__types__ArrayObj r5, r12;
	venum *r15;
	hl_type *r7;
	vclosure *r14;
	iron__CachedShaderContext r11;
	vdynamic *r8;
	iron__data__TShaderOverride r16;
	varray *r6;
	int r3, r4;
	r3 = r0->loading;
	++r3;
	r0->loading = r3;
	r7 = &t$iron_CachedShaderContext;
	r3 = 1;
	r6 = hl_alloc_array(r7,r3);
	r9 = r0->cachedShaderContexts;
	if( r9 == NULL ) hl_null_access();
	r8 = haxe_ds_StringMap_get(r9,r1);
	r11 = (iron__CachedShaderContext)r8;
	r3 = 0;
	((iron__CachedShaderContext*)(r6 + 1))[r3] = r11;
	r5 = hl_types_ArrayObj_alloc(r6);
	if( r5 == NULL ) hl_null_access();
	r3 = 0;
	r4 = r5->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$80733c3_19_19;
	r11 = NULL;
	goto label$80733c3_19_22;
	label$80733c3_19_19:
	r6 = r5->array;
	r8 = ((vdynamic**)(r6 + 1))[r3];
	r11 = (iron__CachedShaderContext)r8;
	label$80733c3_19_22:
	if( !r11 ) goto label$80733c3_19_27;
	r3 = r0->loading;
	--r3;
	r0->loading = r3;
	return;
	label$80733c3_19_27:
	r3 = 0;
	r11 = (iron__CachedShaderContext)hl_alloc_obj(&t$iron_CachedShaderContext);
	iron_CachedShaderContext_new(r11);
	r4 = r5->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$80733c3_19_33;
	hl_types_ArrayObj___expand(r5,r3);
	label$80733c3_19_33:
	r6 = r5->array;
	((iron__CachedShaderContext*)(r6 + 1))[r3] = r11;
	r9 = r0->cachedShaderContexts;
	if( r9 == NULL ) hl_null_access();
	r3 = 0;
	r4 = r5->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$80733c3_19_42;
	r11 = NULL;
	goto label$80733c3_19_45;
	label$80733c3_19_42:
	r6 = r5->array;
	r8 = ((vdynamic**)(r6 + 1))[r3];
	r11 = (iron__CachedShaderContext)r8;
	label$80733c3_19_45:
	haxe_ds_StringMap_set(r9,r1,((vdynamic*)r11));
	if( r1 == NULL ) hl_null_access();
	r13 = (String)s$6666cd7;
	r12 = String_split(r1,r13);
	if( r12 == NULL ) hl_null_access();
	r3 = 0;
	r4 = r12->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$80733c3_19_55;
	r10 = NULL;
	goto label$80733c3_19_58;
	label$80733c3_19_55:
	r6 = r12->array;
	r8 = ((vdynamic**)(r6 + 1))[r3];
	r10 = (String)r8;
	label$80733c3_19_58:
	r3 = 1;
	r4 = r12->length;
	if( ((unsigned)r3) < ((unsigned)r4) ) goto label$80733c3_19_63;
	r13 = NULL;
	goto label$80733c3_19_66;
	label$80733c3_19_63:
	r6 = r12->array;
	r8 = ((vdynamic**)(r6 + 1))[r3];
	r13 = (String)r8;
	label$80733c3_19_66:
	r15 = hl_alloc_enum(&t$ctx_93b0219,0);
	((Enumt$ctx_93b0219*)r15)->p0 = (hl__types__ArrayObj)r5;
	((Enumt$ctx_93b0219*)r15)->p1 = (hl__types__ArrayObj)r12;
	((Enumt$ctx_93b0219*)r15)->p2 = (iron__RenderPath)r0;
	r14 = hl_alloc_closure_ptr(&t$fun_dbb682c,iron_RenderPath_loadShader__$1,r15);
	r16 = NULL;
	iron_data_Data_getShader(r10,r13,r14,r16);
	return;
}

void iron_RenderPath_unloadShader(iron__RenderPath r0,String r1) {
	String r4, r6;
	hl__types__ArrayObj r5;
	haxe__ds__StringMap r3;
	bool r2;
	vdynamic *r11;
	varray *r12;
	int r9, r10;
	iron__data__$Data r8;
	r3 = r0->cachedShaderContexts;
	if( r3 == NULL ) hl_null_access();
	r2 = haxe_ds_StringMap_remove(r3,r1);
	if( r1 == NULL ) hl_null_access();
	r6 = (String)s$6666cd7;
	r5 = String_split(r1,r6);
	r8 = (iron__data__$Data)g$_iron_data_Data;
	r3 = r8->cachedShaders;
	if( r3 == NULL ) hl_null_access();
	if( r5 == NULL ) hl_null_access();
	r9 = 1;
	r10 = r5->length;
	if( ((unsigned)r9) < ((unsigned)r10) ) goto label$80733c3_20_15;
	r4 = NULL;
	goto label$80733c3_20_18;
	label$80733c3_20_15:
	r12 = r5->array;
	r11 = ((vdynamic**)(r12 + 1))[r9];
	r4 = (String)r11;
	label$80733c3_20_18:
	r2 = haxe_ds_StringMap_remove(r3,r4);
	return;
}

void iron_RenderPath_resize(iron__RenderPath r0) {
	String r14, r15;
	kha__Image r18, r19;
	haxe__ds__StringMap r7;
	vvirtual *r6, *r8, *r10;
	iron__RenderTargetRaw r13;
	bool r9;
	iron__RenderTarget r11, r12, r16, r17;
	vclosure *r20;
	vdynamic *r5;
	int *r3;
	int r2, r4;
	r3 = NULL;
	r2 = kha_System_windowWidth(r3);
	r4 = 0;
	if( r2 == r4 ) goto label$80733c3_21_8;
	r3 = NULL;
	r2 = kha_System_windowHeight(r3);
	r4 = 0;
	if( r2 != r4 ) goto label$80733c3_21_9;
	label$80733c3_21_8:
	return;
	label$80733c3_21_9:
	r7 = r0->renderTargets;
	if( r7 == NULL ) hl_null_access();
	r6 = haxe_ds_StringMap_iterator(r7);
	r8 = hl_to_virtual(&t$vrt_06f6bad,(vdynamic*)r6);
	label$80733c3_21_13:
	if( r8 == NULL ) hl_null_access();
	if( hl_vfields(r8)[0] ) r9 = ((bool (*)(vdynamic*))hl_vfields(r8)[0])(r8->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r8->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r9 = (bool)ret.v.i;
	}
	if( !r9 ) goto label$80733c3_21_73;
	if( hl_vfields(r8)[1] ) r11 = ((iron__RenderTarget (*)(vdynamic*))hl_vfields(r8)[1])(r8->value); else {
		r11 = (iron__RenderTarget)hl_dyn_call_obj(r8->value,&t$fun_c699427,151160317/*next*/,NULL,NULL);
	}
	if( !r11 ) goto label$80733c3_21_34;
	if( r11 == NULL ) hl_null_access();
	r13 = r11->raw;
	if( r13 == NULL ) hl_null_access();
	r2 = r13->width;
	r4 = 0;
	if( r4 < r2 ) goto label$80733c3_21_34;
	r14 = r11->depthStencilFrom;
	r15 = (String)s$;
	if( r14 == r15 || (r14 && r15 && String___compare(r14,(vdynamic*)r15) == 0) ) goto label$80733c3_21_34;
	r7 = r0->depthToRenderTarget;
	if( r7 == NULL ) hl_null_access();
	r14 = r11->depthStencilFrom;
	r5 = haxe_ds_StringMap_get(r7,r14);
	r16 = (iron__RenderTarget)r5;
	if( r11 != r16 ) goto label$80733c3_21_35;
	label$80733c3_21_34:
	goto label$80733c3_21_13;
	label$80733c3_21_35:
	r12 = NULL;
	r7 = r0->renderTargets;
	if( r7 == NULL ) hl_null_access();
	r6 = haxe_ds_StringMap_iterator(r7);
	r10 = hl_to_virtual(&t$vrt_06f6bad,(vdynamic*)r6);
	label$80733c3_21_40:
	if( r10 == NULL ) hl_null_access();
	if( hl_vfields(r10)[0] ) r9 = ((bool (*)(vdynamic*))hl_vfields(r10)[0])(r10->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r10->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r9 = (bool)ret.v.i;
	}
	if( !r9 ) goto label$80733c3_21_65;
	if( hl_vfields(r10)[1] ) r16 = ((iron__RenderTarget (*)(vdynamic*))hl_vfields(r10)[1])(r10->value); else {
		r16 = (iron__RenderTarget)hl_dyn_call_obj(r10->value,&t$fun_c699427,151160317/*next*/,NULL,NULL);
	}
	if( !r16 ) goto label$80733c3_21_63;
	if( r16 == NULL ) hl_null_access();
	r13 = r16->raw;
	if( r13 == NULL ) hl_null_access();
	r2 = r13->width;
	r4 = 0;
	if( r4 < r2 ) goto label$80733c3_21_63;
	r14 = r16->depthStencilFrom;
	r15 = (String)s$;
	if( r14 != r15 && (!r14 || !r15 || String___compare(r14,(vdynamic*)r15) != 0) ) goto label$80733c3_21_63;
	r7 = r0->depthToRenderTarget;
	if( r7 == NULL ) hl_null_access();
	r13 = r16->raw;
	if( r13 == NULL ) hl_null_access();
	r14 = r13->depth_buffer;
	r5 = haxe_ds_StringMap_get(r7,r14);
	r17 = (iron__RenderTarget)r5;
	if( !r17 ) goto label$80733c3_21_64;
	label$80733c3_21_63:
	goto label$80733c3_21_40;
	label$80733c3_21_64:
	r12 = r16;
	label$80733c3_21_65:
	if( !r12 ) goto label$80733c3_21_72;
	if( r11 == NULL ) hl_null_access();
	r18 = r11->image;
	if( r18 == NULL ) hl_null_access();
	if( r12 == NULL ) hl_null_access();
	r19 = r12->image;
	kha_Image_setDepthStencilFrom(r18,r19);
	label$80733c3_21_72:
	goto label$80733c3_21_13;
	label$80733c3_21_73:
	r7 = r0->renderTargets;
	if( r7 == NULL ) hl_null_access();
	r6 = haxe_ds_StringMap_iterator(r7);
	r8 = hl_to_virtual(&t$vrt_06f6bad,(vdynamic*)r6);
	label$80733c3_21_77:
	if( r8 == NULL ) hl_null_access();
	if( hl_vfields(r8)[0] ) r9 = ((bool (*)(vdynamic*))hl_vfields(r8)[0])(r8->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r8->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r9 = (bool)ret.v.i;
	}
	if( !r9 ) goto label$80733c3_21_98;
	if( hl_vfields(r8)[1] ) r11 = ((iron__RenderTarget (*)(vdynamic*))hl_vfields(r8)[1])(r8->value); else {
		r11 = (iron__RenderTarget)hl_dyn_call_obj(r8->value,&t$fun_c699427,151160317/*next*/,NULL,NULL);
	}
	if( !r11 ) goto label$80733c3_21_97;
	if( r11 == NULL ) hl_null_access();
	r13 = r11->raw;
	if( r13 == NULL ) hl_null_access();
	r2 = r13->width;
	r4 = 0;
	if( r2 != r4 ) goto label$80733c3_21_97;
	r18 = r11->image;
	if( r18 == NULL ) hl_null_access();
	r20 = hl_alloc_closure_ptr(&t$fun_ccaddd2,kha_Image_unload,r18);
	iron_App_notifyOnInit(r20);
	r13 = r11->raw;
	r2 = r11->depthStencil;
	r18 = iron_RenderPath_createImage(r0,r13,r2);
	r11->image = r18;
	label$80733c3_21_97:
	goto label$80733c3_21_77;
	label$80733c3_21_98:
	r7 = r0->renderTargets;
	if( r7 == NULL ) hl_null_access();
	r6 = haxe_ds_StringMap_iterator(r7);
	r8 = hl_to_virtual(&t$vrt_06f6bad,(vdynamic*)r6);
	label$80733c3_21_102:
	if( r8 == NULL ) hl_null_access();
	if( hl_vfields(r8)[0] ) r9 = ((bool (*)(vdynamic*))hl_vfields(r8)[0])(r8->value); else {
		vdynamic ret;
		hl_dyn_call_obj(r8->value,&t$fun_bf7849e,407283053/*hasNext*/,NULL,&ret);
		r9 = (bool)ret.v.i;
	}
	if( !r9 ) goto label$80733c3_21_123;
	if( hl_vfields(r8)[1] ) r11 = ((iron__RenderTarget (*)(vdynamic*))hl_vfields(r8)[1])(r8->value); else {
		r11 = (iron__RenderTarget)hl_dyn_call_obj(r8->value,&t$fun_c699427,151160317/*next*/,NULL,NULL);
	}
	if( !r11 ) goto label$80733c3_21_122;
	if( r11 == NULL ) hl_null_access();
	r14 = r11->depthStencilFrom;
	r15 = (String)s$;
	if( r14 == r15 || (r14 && r15 && String___compare(r14,(vdynamic*)r15) == 0) ) goto label$80733c3_21_122;
	r18 = r11->image;
	if( r18 == NULL ) hl_null_access();
	r7 = r0->depthToRenderTarget;
	if( r7 == NULL ) hl_null_access();
	r14 = r11->depthStencilFrom;
	r5 = haxe_ds_StringMap_get(r7,r14);
	r12 = (iron__RenderTarget)r5;
	if( r12 == NULL ) hl_null_access();
	r19 = r12->image;
	kha_Image_setDepthStencilFrom(r18,r19);
	label$80733c3_21_122:
	goto label$80733c3_21_102;
	label$80733c3_21_123:
	return;
}

iron__RenderTarget iron_RenderPath_createRenderTarget(iron__RenderPath r0,iron__RenderTargetRaw r1) {
	String r5;
	haxe__ds__StringMap r4;
	iron__RenderTarget r2;
	r2 = iron_RenderPath_createTarget(r0,r1);
	r4 = r0->renderTargets;
	if( r4 == NULL ) hl_null_access();
	if( r1 == NULL ) hl_null_access();
	r5 = r1->name;
	haxe_ds_StringMap_set(r4,r5,((vdynamic*)r2));
	return r2;
}

void iron_RenderPath_createDepthBuffer(iron__RenderPath r0,String r1,String r2) {
	vvirtual *r5;
	hl__types__ArrayObj r4;
	int r3;
	r4 = r0->depthBuffers;
	if( r4 == NULL ) hl_null_access();
	r5 = hl_alloc_virtual(&t$vrt_ee58142);
	if( hl_vfields(r5)[1] ) *(String*)(hl_vfields(r5)[1]) = (String)r1; else hl_dyn_setp(r5->value,150958933/*name*/,&t$String,r1);
	if( hl_vfields(r5)[0] ) *(String*)(hl_vfields(r5)[0]) = (String)r2; else hl_dyn_setp(r5->value,-40988873/*format*/,&t$String,r2);
	r3 = hl_types_ArrayObj_push(r4,((vdynamic*)r5));
	return;
}

iron__RenderTarget iron_RenderPath_createTarget(iron__RenderPath r0,iron__RenderTargetRaw r1) {
	kha__graphics4__CubeMap r24;
	String r4, r15, r16;
	kha__Image r20, r21;
	vvirtual *r13;
	hl__types__ArrayObj r10;
	haxe__ds__StringMap r8;
	bool r6;
	iron__RenderTarget r2, r5;
	vdynamic *r7, *r22, *r23;
	vbyte *r18, *r19;
	varray *r14;
	int r9, r11, r12, r17;
	r2 = (iron__RenderTarget)hl_alloc_obj(&t$iron_RenderTarget);
	iron_RenderTarget_new(r2,r1);
	if( r1 == NULL ) hl_null_access();
	r4 = r1->depth_buffer;
	if( !r4 ) goto label$80733c3_24_86;
	r6 = true;
	r2->hasDepth = r6;
	r8 = r0->depthToRenderTarget;
	if( r8 == NULL ) hl_null_access();
	r4 = r1->depth_buffer;
	r7 = haxe_ds_StringMap_get(r8,r4);
	r5 = (iron__RenderTarget)r7;
	if( r5 ) goto label$80733c3_24_73;
	r9 = 0;
	r10 = r0->depthBuffers;
	label$80733c3_24_15:
	if( r10 == NULL ) hl_null_access();
	r12 = r10->length;
	if( r9 >= r12 ) goto label$80733c3_24_72;
	r12 = r10->length;
	if( ((unsigned)r9) < ((unsigned)r12) ) goto label$80733c3_24_23;
	r13 = NULL;
	goto label$80733c3_24_26;
	label$80733c3_24_23:
	r14 = r10->array;
	r7 = ((vdynamic**)(r14 + 1))[r9];
	r13 = hl_to_virtual(&t$vrt_ee58142,(vdynamic*)r7);
	label$80733c3_24_26:
	++r9;
	if( r13 == NULL ) hl_null_access();
	r4 = hl_vfields(r13)[1] ? (*(String*)(hl_vfields(r13)[1])) : (String)hl_dyn_getp(r13->value,150958933/*name*/,&t$String);
	if( r1 == NULL ) hl_null_access();
	r15 = r1->depth_buffer;
	if( r4 != r15 && (!r4 || !r15 || String___compare(r4,(vdynamic*)r15) != 0) ) goto label$80733c3_24_71;
	r8 = r0->depthToRenderTarget;
	if( r8 == NULL ) hl_null_access();
	r4 = hl_vfields(r13)[1] ? (*(String*)(hl_vfields(r13)[1])) : (String)hl_dyn_getp(r13->value,150958933/*name*/,&t$String);
	haxe_ds_StringMap_set(r8,r4,((vdynamic*)r2));
	r4 = hl_vfields(r13)[0] ? (*(String*)(hl_vfields(r13)[0])) : (String)hl_dyn_getp(r13->value,-40988873/*format*/,&t$String);
	if( !r4 ) goto label$80733c3_24_40;
	r16 = (String)s$;
	if( r4 != r16 && (!r4 || !r16 || String___compare(r4,(vdynamic*)r16) != 0) ) goto label$80733c3_24_42;
	label$80733c3_24_40:
	r12 = 1;
	goto label$80733c3_24_65;
	label$80733c3_24_42:
	if( !r4 ) goto label$80733c3_24_51;
	r12 = r4->length;
	r17 = 7;
	if( r12 != r17 ) goto label$80733c3_24_51;
	r18 = r4->bytes;
	r19 = (vbyte*)USTR("DEPTH16");
	r12 = hl_string_compare(r18,r19,r12);
	r17 = 0;
	if( r12 == r17 ) goto label$80733c3_24_62;
	label$80733c3_24_51:
	if( !r4 ) goto label$80733c3_24_60;
	r12 = r4->length;
	r17 = 7;
	if( r12 != r17 ) goto label$80733c3_24_60;
	r18 = r4->bytes;
	r19 = (vbyte*)USTR("DEPTH24");
	r12 = hl_string_compare(r18,r19,r12);
	r17 = 0;
	if( r12 == r17 ) goto label$80733c3_24_64;
	label$80733c3_24_60:
	r12 = 1;
	goto label$80733c3_24_65;
	label$80733c3_24_62:
	r12 = 5;
	goto label$80733c3_24_65;
	label$80733c3_24_64:
	r12 = 1;
	label$80733c3_24_65:
	if( r2 == NULL ) hl_null_access();
	r2->depthStencil = r12;
	r12 = r2->depthStencil;
	r20 = iron_RenderPath_createImage(r0,r1,r12);
	r2->image = r20;
	goto label$80733c3_24_72;
	label$80733c3_24_71:
	goto label$80733c3_24_15;
	label$80733c3_24_72:
	goto label$80733c3_24_85;
	label$80733c3_24_73:
	r9 = 0;
	r2->depthStencil = r9;
	r4 = r1->depth_buffer;
	r2->depthStencilFrom = r4;
	r9 = r2->depthStencil;
	r20 = iron_RenderPath_createImage(r0,r1,r9);
	r2->image = r20;
	r20 = r2->image;
	if( r20 == NULL ) hl_null_access();
	if( r5 == NULL ) hl_null_access();
	r21 = r5->image;
	kha_Image_setDepthStencilFrom(r20,r21);
	label$80733c3_24_85:
	goto label$80733c3_24_112;
	label$80733c3_24_86:
	r6 = false;
	r2->hasDepth = r6;
	r22 = r1->depth;
	if( !r22 ) goto label$80733c3_24_96;
	r22 = r1->depth;
	r9 = r22 ? r22->v.i : 0;
	r11 = 1;
	if( r11 >= r9 ) goto label$80733c3_24_96;
	r6 = true;
	r2->is3D = r6;
	label$80733c3_24_96:
	r23 = r1->is_cubemap;
	r6 = r23 ? r23->v.b : 0;
	if( !r6 ) goto label$80733c3_24_107;
	r6 = true;
	r2->isCubeMap = r6;
	r9 = 0;
	r2->depthStencil = r9;
	r9 = r2->depthStencil;
	r24 = iron_RenderPath_createCubeMap(r0,r1,r9);
	r2->cubeMap = r24;
	goto label$80733c3_24_112;
	label$80733c3_24_107:
	r9 = 0;
	r2->depthStencil = r9;
	r9 = r2->depthStencil;
	r20 = iron_RenderPath_createImage(r0,r1,r9);
	r2->image = r20;
	label$80733c3_24_112:
	return r2;
}

kha__Image iron_RenderPath_createImage(iron__RenderPath r0,iron__RenderTargetRaw r1,int r2) {
	bool *r24;
	String r17;
	kha__Image r21;
	iron__$App r6;
	bool r26;
	double r12, r13, r14, r16;
	vclosure *r5;
	int *r27, *r28;
	vdynamic *r9, *r10, *r15, *r20, *r23, *r25;
	vbyte *r18, *r19;
	int r3, r4, r8, r11, r22;
	if( r1 == NULL ) hl_null_access();
	r3 = r1->width;
	r4 = 0;
	if( r3 != r4 ) goto label$80733c3_25_9;
	r6 = (iron__$App)g$_iron_App;
	r5 = r6->w;
	if( r5 == NULL ) hl_null_access();
	r3 = r5->hasValue ? ((int (*)(vdynamic*))r5->fun)((vdynamic*)r5->value) : ((int (*)(void))r5->fun)();
	goto label$80733c3_25_10;
	label$80733c3_25_9:
	r3 = r1->width;
	label$80733c3_25_10:
	r4 = r1->height;
	r8 = 0;
	if( r4 != r8 ) goto label$80733c3_25_18;
	r6 = (iron__$App)g$_iron_App;
	r5 = r6->h;
	if( r5 == NULL ) hl_null_access();
	r4 = r5->hasValue ? ((int (*)(vdynamic*))r5->fun)((vdynamic*)r5->value) : ((int (*)(void))r5->fun)();
	goto label$80733c3_25_19;
	label$80733c3_25_18:
	r4 = r1->height;
	label$80733c3_25_19:
	r9 = r1->depth;
	if( !r9 ) goto label$80733c3_25_23;
	r9 = r1->depth;
	goto label$80733c3_25_25;
	label$80733c3_25_23:
	r8 = 0;
	r9 = hl_alloc_dynamic(&t$_i32);
	r9->v.i = r8;
	label$80733c3_25_25:
	r10 = r1->displayp;
	if( !r10 ) goto label$80733c3_25_53;
	if( r4 >= r3 ) goto label$80733c3_25_41;
	r12 = (double)r3;
	r10 = r1->displayp;
	r8 = r10 ? r10->v.i : 0;
	r13 = (double)r8;
	r14 = (double)r4;
	r13 = r13 / r14;
	r12 = r12 * r13;
	r8 = (int)r12;
	r3 = r8;
	r10 = r1->displayp;
	r8 = r10 ? r10->v.i : 0;
	r4 = r8;
	goto label$80733c3_25_53;
	label$80733c3_25_41:
	r12 = (double)r4;
	r10 = r1->displayp;
	r8 = r10 ? r10->v.i : 0;
	r13 = (double)r8;
	r14 = (double)r3;
	r13 = r13 / r14;
	r12 = r12 * r13;
	r8 = (int)r12;
	r4 = r8;
	r10 = r1->displayp;
	r8 = r10 ? r10->v.i : 0;
	r3 = r8;
	label$80733c3_25_53:
	r15 = r1->scale;
	if( !r15 ) goto label$80733c3_25_75;
	r12 = (double)r3;
	r15 = r1->scale;
	r13 = r15 ? r15->v.d : 0;
	r12 = r12 * r13;
	r8 = (int)r12;
	r3 = r8;
	r13 = (double)r4;
	r15 = r1->scale;
	r14 = r15 ? r15->v.d : 0;
	r13 = r13 * r14;
	r8 = (int)r13;
	r4 = r8;
	r8 = r9 ? r9->v.i : 0;
	r14 = (double)r8;
	r15 = r1->scale;
	r16 = r15 ? r15->v.d : 0;
	r14 = r14 * r16;
	r8 = (int)r14;
	r10 = hl_alloc_dynamic(&t$_i32);
	r10->v.i = r8;
	r9 = r10;
	label$80733c3_25_75:
	r11 = 1;
	if( r3 >= r11 ) goto label$80733c3_25_79;
	r8 = 1;
	r3 = r8;
	label$80733c3_25_79:
	r11 = 1;
	if( r4 >= r11 ) goto label$80733c3_25_83;
	r8 = 1;
	r4 = r8;
	label$80733c3_25_83:
	r10 = r1->depth;
	if( !r10 ) goto label$80733c3_25_201;
	r10 = r1->depth;
	r8 = r10 ? r10->v.i : 0;
	r11 = 1;
	if( r11 >= r8 ) goto label$80733c3_25_201;
	r17 = r1->format;
	if( !r17 ) goto label$80733c3_25_187;
	r17 = r1->format;
	if( !r17 ) goto label$80733c3_25_101;
	r8 = r17->length;
	r11 = 7;
	if( r8 != r11 ) goto label$80733c3_25_101;
	r18 = r17->bytes;
	r19 = (vbyte*)USTR("DEPTH16");
	r8 = hl_string_compare(r18,r19,r8);
	r11 = 0;
	if( r8 == r11 ) goto label$80733c3_25_159;
	label$80733c3_25_101:
	if( !r17 ) goto label$80733c3_25_110;
	r8 = r17->length;
	r11 = 3;
	if( r8 != r11 ) goto label$80733c3_25_110;
	r18 = r17->bytes;
	r19 = (vbyte*)USTR("R16");
	r8 = hl_string_compare(r18,r19,r8);
	r11 = 0;
	if( r8 == r11 ) goto label$80733c3_25_163;
	label$80733c3_25_110:
	if( !r17 ) goto label$80733c3_25_119;
	r8 = r17->length;
	r11 = 3;
	if( r8 != r11 ) goto label$80733c3_25_119;
	r18 = r17->bytes;
	r19 = (vbyte*)USTR("R32");
	r8 = hl_string_compare(r18,r19,r8);
	r11 = 0;
	if( r8 == r11 ) goto label$80733c3_25_167;
	label$80733c3_25_119:
	if( !r17 ) goto label$80733c3_25_128;
	r8 = r17->length;
	r11 = 2;
	if( r8 != r11 ) goto label$80733c3_25_128;
	r18 = r17->bytes;
	r19 = (vbyte*)USTR("R8");
	r8 = hl_string_compare(r18,r19,r8);
	r11 = 0;
	if( r8 == r11 ) goto label$80733c3_25_171;
	label$80733c3_25_128:
	if( !r17 ) goto label$80733c3_25_137;
	r8 = r17->length;
	r11 = 7;
	if( r8 != r11 ) goto label$80733c3_25_137;
	r18 = r17->bytes;
	r19 = (vbyte*)USTR("RGBA128");
	r8 = hl_string_compare(r18,r19,r8);
	r11 = 0;
	if( r8 == r11 ) goto label$80733c3_25_175;
	label$80733c3_25_137:
	if( !r17 ) goto label$80733c3_25_146;
	r8 = r17->length;
	r11 = 6;
	if( r8 != r11 ) goto label$80733c3_25_146;
	r18 = r17->bytes;
	r19 = (vbyte*)USTR("RGBA32");
	r8 = hl_string_compare(r18,r19,r8);
	r11 = 0;
	if( r8 == r11 ) goto label$80733c3_25_179;
	label$80733c3_25_146:
	if( !r17 ) goto label$80733c3_25_155;
	r8 = r17->length;
	r11 = 6;
	if( r8 != r11 ) goto label$80733c3_25_155;
	r18 = r17->bytes;
	r19 = (vbyte*)USTR("RGBA64");
	r8 = hl_string_compare(r18,r19,r8);
	r11 = 0;
	if( r8 == r11 ) goto label$80733c3_25_183;
	label$80733c3_25_155:
	r8 = 0;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	r10 = r20;
	goto label$80733c3_25_186;
	label$80733c3_25_159:
	r8 = 3;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	r10 = r20;
	goto label$80733c3_25_186;
	label$80733c3_25_163:
	r8 = 6;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	r10 = r20;
	goto label$80733c3_25_186;
	label$80733c3_25_167:
	r8 = 5;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	r10 = r20;
	goto label$80733c3_25_186;
	label$80733c3_25_171:
	r8 = 1;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	r10 = r20;
	goto label$80733c3_25_186;
	label$80733c3_25_175:
	r8 = 2;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	r10 = r20;
	goto label$80733c3_25_186;
	label$80733c3_25_179:
	r8 = 0;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	r10 = r20;
	goto label$80733c3_25_186;
	label$80733c3_25_183:
	r8 = 4;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	r10 = r20;
	label$80733c3_25_186:
	goto label$80733c3_25_190;
	label$80733c3_25_187:
	r8 = 0;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	r10 = r20;
	label$80733c3_25_190:
	r22 = r9 ? r9->v.i : 0;
	r23 = NULL;
	r24 = NULL;
	r21 = kha_Image_create3D(r3,r4,r22,r10,r23,r24);
	r25 = r1->mipmaps;
	r26 = r25 ? r25->v.b : 0;
	if( !r26 ) goto label$80733c3_25_200;
	if( r21 == NULL ) hl_null_access();
	r8 = 1000;
	kha_Image_generateMipmaps(r21,r8);
	label$80733c3_25_200:
	return r21;
	label$80733c3_25_201:
	r25 = r1->is_image;
	if( !r25 ) goto label$80733c3_25_302;
	r25 = r1->is_image;
	r26 = r25 ? r25->v.b : 0;
	if( !r26 ) goto label$80733c3_25_302;
	r17 = r1->format;
	if( !r17 ) goto label$80733c3_25_296;
	r17 = r1->format;
	if( !r17 ) goto label$80733c3_25_218;
	r8 = r17->length;
	r11 = 7;
	if( r8 != r11 ) goto label$80733c3_25_218;
	r18 = r17->bytes;
	r19 = (vbyte*)USTR("DEPTH16");
	r8 = hl_string_compare(r18,r19,r8);
	r11 = 0;
	if( r8 == r11 ) goto label$80733c3_25_275;
	label$80733c3_25_218:
	if( !r17 ) goto label$80733c3_25_227;
	r8 = r17->length;
	r11 = 3;
	if( r8 != r11 ) goto label$80733c3_25_227;
	r18 = r17->bytes;
	r19 = (vbyte*)USTR("R16");
	r8 = hl_string_compare(r18,r19,r8);
	r11 = 0;
	if( r8 == r11 ) goto label$80733c3_25_278;
	label$80733c3_25_227:
	if( !r17 ) goto label$80733c3_25_236;
	r8 = r17->length;
	r11 = 3;
	if( r8 != r11 ) goto label$80733c3_25_236;
	r18 = r17->bytes;
	r19 = (vbyte*)USTR("R32");
	r8 = hl_string_compare(r18,r19,r8);
	r11 = 0;
	if( r8 == r11 ) goto label$80733c3_25_281;
	label$80733c3_25_236:
	if( !r17 ) goto label$80733c3_25_245;
	r8 = r17->length;
	r11 = 2;
	if( r8 != r11 ) goto label$80733c3_25_245;
	r18 = r17->bytes;
	r19 = (vbyte*)USTR("R8");
	r8 = hl_string_compare(r18,r19,r8);
	r11 = 0;
	if( r8 == r11 ) goto label$80733c3_25_284;
	label$80733c3_25_245:
	if( !r17 ) goto label$80733c3_25_254;
	r8 = r17->length;
	r11 = 7;
	if( r8 != r11 ) goto label$80733c3_25_254;
	r18 = r17->bytes;
	r19 = (vbyte*)USTR("RGBA128");
	r8 = hl_string_compare(r18,r19,r8);
	r11 = 0;
	if( r8 == r11 ) goto label$80733c3_25_287;
	label$80733c3_25_254:
	if( !r17 ) goto label$80733c3_25_263;
	r8 = r17->length;
	r11 = 6;
	if( r8 != r11 ) goto label$80733c3_25_263;
	r18 = r17->bytes;
	r19 = (vbyte*)USTR("RGBA32");
	r8 = hl_string_compare(r18,r19,r8);
	r11 = 0;
	if( r8 == r11 ) goto label$80733c3_25_290;
	label$80733c3_25_263:
	if( !r17 ) goto label$80733c3_25_272;
	r8 = r17->length;
	r11 = 6;
	if( r8 != r11 ) goto label$80733c3_25_272;
	r18 = r17->bytes;
	r19 = (vbyte*)USTR("RGBA64");
	r8 = hl_string_compare(r18,r19,r8);
	r11 = 0;
	if( r8 == r11 ) goto label$80733c3_25_293;
	label$80733c3_25_272:
	r8 = 0;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	goto label$80733c3_25_295;
	label$80733c3_25_275:
	r8 = 3;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	goto label$80733c3_25_295;
	label$80733c3_25_278:
	r8 = 6;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	goto label$80733c3_25_295;
	label$80733c3_25_281:
	r8 = 5;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	goto label$80733c3_25_295;
	label$80733c3_25_284:
	r8 = 1;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	goto label$80733c3_25_295;
	label$80733c3_25_287:
	r8 = 2;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	goto label$80733c3_25_295;
	label$80733c3_25_290:
	r8 = 0;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	goto label$80733c3_25_295;
	label$80733c3_25_293:
	r8 = 4;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	label$80733c3_25_295:
	goto label$80733c3_25_298;
	label$80733c3_25_296:
	r8 = 0;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	label$80733c3_25_298:
	r23 = NULL;
	r24 = NULL;
	r21 = kha_Image_create(r3,r4,r20,r23,r24);
	return r21;
	label$80733c3_25_302:
	r17 = r1->format;
	if( !r17 ) goto label$80733c3_25_392;
	r17 = r1->format;
	if( !r17 ) goto label$80733c3_25_314;
	r8 = r17->length;
	r11 = 7;
	if( r8 != r11 ) goto label$80733c3_25_314;
	r18 = r17->bytes;
	r19 = (vbyte*)USTR("DEPTH16");
	r8 = hl_string_compare(r18,r19,r8);
	r11 = 0;
	if( r8 == r11 ) goto label$80733c3_25_371;
	label$80733c3_25_314:
	if( !r17 ) goto label$80733c3_25_323;
	r8 = r17->length;
	r11 = 3;
	if( r8 != r11 ) goto label$80733c3_25_323;
	r18 = r17->bytes;
	r19 = (vbyte*)USTR("R16");
	r8 = hl_string_compare(r18,r19,r8);
	r11 = 0;
	if( r8 == r11 ) goto label$80733c3_25_374;
	label$80733c3_25_323:
	if( !r17 ) goto label$80733c3_25_332;
	r8 = r17->length;
	r11 = 3;
	if( r8 != r11 ) goto label$80733c3_25_332;
	r18 = r17->bytes;
	r19 = (vbyte*)USTR("R32");
	r8 = hl_string_compare(r18,r19,r8);
	r11 = 0;
	if( r8 == r11 ) goto label$80733c3_25_377;
	label$80733c3_25_332:
	if( !r17 ) goto label$80733c3_25_341;
	r8 = r17->length;
	r11 = 2;
	if( r8 != r11 ) goto label$80733c3_25_341;
	r18 = r17->bytes;
	r19 = (vbyte*)USTR("R8");
	r8 = hl_string_compare(r18,r19,r8);
	r11 = 0;
	if( r8 == r11 ) goto label$80733c3_25_380;
	label$80733c3_25_341:
	if( !r17 ) goto label$80733c3_25_350;
	r8 = r17->length;
	r11 = 7;
	if( r8 != r11 ) goto label$80733c3_25_350;
	r18 = r17->bytes;
	r19 = (vbyte*)USTR("RGBA128");
	r8 = hl_string_compare(r18,r19,r8);
	r11 = 0;
	if( r8 == r11 ) goto label$80733c3_25_383;
	label$80733c3_25_350:
	if( !r17 ) goto label$80733c3_25_359;
	r8 = r17->length;
	r11 = 6;
	if( r8 != r11 ) goto label$80733c3_25_359;
	r18 = r17->bytes;
	r19 = (vbyte*)USTR("RGBA32");
	r8 = hl_string_compare(r18,r19,r8);
	r11 = 0;
	if( r8 == r11 ) goto label$80733c3_25_386;
	label$80733c3_25_359:
	if( !r17 ) goto label$80733c3_25_368;
	r8 = r17->length;
	r11 = 6;
	if( r8 != r11 ) goto label$80733c3_25_368;
	r18 = r17->bytes;
	r19 = (vbyte*)USTR("RGBA64");
	r8 = hl_string_compare(r18,r19,r8);
	r11 = 0;
	if( r8 == r11 ) goto label$80733c3_25_389;
	label$80733c3_25_368:
	r8 = 0;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	goto label$80733c3_25_391;
	label$80733c3_25_371:
	r8 = 3;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	goto label$80733c3_25_391;
	label$80733c3_25_374:
	r8 = 6;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	goto label$80733c3_25_391;
	label$80733c3_25_377:
	r8 = 5;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	goto label$80733c3_25_391;
	label$80733c3_25_380:
	r8 = 1;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	goto label$80733c3_25_391;
	label$80733c3_25_383:
	r8 = 2;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	goto label$80733c3_25_391;
	label$80733c3_25_386:
	r8 = 0;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	goto label$80733c3_25_391;
	label$80733c3_25_389:
	r8 = 4;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	label$80733c3_25_391:
	goto label$80733c3_25_394;
	label$80733c3_25_392:
	r8 = 0;
	r20 = hl_alloc_dynamic(&t$_i32);
	r20->v.i = r8;
	label$80733c3_25_394:
	r22 = r2;
	r27 = &r22;
	r28 = NULL;
	r21 = kha_Image_createRenderTarget(r3,r4,r20,r27,r28);
	return r21;
}

kha__graphics4__CubeMap iron_RenderPath_createCubeMap(iron__RenderPath r0,iron__RenderTargetRaw r1,int r2) {
	kha__graphics4__CubeMap r9;
	String r3;
	vdynamic *r8, *r10;
	vbyte *r6, *r7;
	int r4, r5;
	if( r1 == NULL ) hl_null_access();
	r3 = r1->format;
	if( !r3 ) goto label$80733c3_26_91;
	r3 = r1->format;
	if( !r3 ) goto label$80733c3_26_13;
	r4 = r3->length;
	r5 = 7;
	if( r4 != r5 ) goto label$80733c3_26_13;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("DEPTH16");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$80733c3_26_70;
	label$80733c3_26_13:
	if( !r3 ) goto label$80733c3_26_22;
	r4 = r3->length;
	r5 = 3;
	if( r4 != r5 ) goto label$80733c3_26_22;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("R16");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$80733c3_26_73;
	label$80733c3_26_22:
	if( !r3 ) goto label$80733c3_26_31;
	r4 = r3->length;
	r5 = 3;
	if( r4 != r5 ) goto label$80733c3_26_31;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("R32");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$80733c3_26_76;
	label$80733c3_26_31:
	if( !r3 ) goto label$80733c3_26_40;
	r4 = r3->length;
	r5 = 2;
	if( r4 != r5 ) goto label$80733c3_26_40;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("R8");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$80733c3_26_79;
	label$80733c3_26_40:
	if( !r3 ) goto label$80733c3_26_49;
	r4 = r3->length;
	r5 = 7;
	if( r4 != r5 ) goto label$80733c3_26_49;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("RGBA128");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$80733c3_26_82;
	label$80733c3_26_49:
	if( !r3 ) goto label$80733c3_26_58;
	r4 = r3->length;
	r5 = 6;
	if( r4 != r5 ) goto label$80733c3_26_58;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("RGBA32");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$80733c3_26_85;
	label$80733c3_26_58:
	if( !r3 ) goto label$80733c3_26_67;
	r4 = r3->length;
	r5 = 6;
	if( r4 != r5 ) goto label$80733c3_26_67;
	r6 = r3->bytes;
	r7 = (vbyte*)USTR("RGBA64");
	r4 = hl_string_compare(r6,r7,r4);
	r5 = 0;
	if( r4 == r5 ) goto label$80733c3_26_88;
	label$80733c3_26_67:
	r4 = 0;
	r8 = hl_alloc_dynamic(&t$_i32);
	r8->v.i = r4;
	goto label$80733c3_26_90;
	label$80733c3_26_70:
	r4 = 3;
	r8 = hl_alloc_dynamic(&t$_i32);
	r8->v.i = r4;
	goto label$80733c3_26_90;
	label$80733c3_26_73:
	r4 = 6;
	r8 = hl_alloc_dynamic(&t$_i32);
	r8->v.i = r4;
	goto label$80733c3_26_90;
	label$80733c3_26_76:
	r4 = 5;
	r8 = hl_alloc_dynamic(&t$_i32);
	r8->v.i = r4;
	goto label$80733c3_26_90;
	label$80733c3_26_79:
	r4 = 1;
	r8 = hl_alloc_dynamic(&t$_i32);
	r8->v.i = r4;
	goto label$80733c3_26_90;
	label$80733c3_26_82:
	r4 = 2;
	r8 = hl_alloc_dynamic(&t$_i32);
	r8->v.i = r4;
	goto label$80733c3_26_90;
	label$80733c3_26_85:
	r4 = 0;
	r8 = hl_alloc_dynamic(&t$_i32);
	r8->v.i = r4;
	goto label$80733c3_26_90;
	label$80733c3_26_88:
	r4 = 4;
	r8 = hl_alloc_dynamic(&t$_i32);
	r8->v.i = r4;
	label$80733c3_26_90:
	goto label$80733c3_26_93;
	label$80733c3_26_91:
	r4 = 0;
	r8 = hl_alloc_dynamic(&t$_i32);
	r8->v.i = r4;
	label$80733c3_26_93:
	r4 = r1->width;
	r10 = hl_alloc_dynamic(&t$_i32);
	r10->v.i = r2;
	r9 = kha_graphics4_CubeMap_createRenderTarget(r4,r8,r10);
	return r9;
}

void iron_RenderPath_new(iron__RenderPath r0) {
	vvirtual *r10;
	haxe__ds__StringMap r5;
	hl__types__ArrayObj r1;
	hl_type *r3;
	bool r8;
	iron__RenderTarget r12;
	iron__object__LightObject r11;
	vclosure *r9;
	double r7;
	int r4;
	varray *r2;
	r3 = &t$vrt_ee58142;
	r4 = 0;
	r2 = hl_alloc_array(r3,r4);
	r1 = hl_types_ArrayObj_alloc(r2);
	r0->depthBuffers = r1;
	r5 = (haxe__ds__StringMap)hl_alloc_obj(&t$haxe_ds_StringMap);
	haxe_ds_StringMap_new(r5);
	r0->cachedShaderContexts = r5;
	r4 = 0;
	r0->loading = r4;
	r7 = 0.;
	r0->lastFrameTime = r7;
	r8 = false;
	r0->viewportScaled = r8;
	r8 = false;
	r0->scissorSet = r8;
	r4 = 0;
	r0->lastH = r4;
	r4 = 0;
	r0->lastW = r4;
	r5 = (haxe__ds__StringMap)hl_alloc_obj(&t$haxe_ds_StringMap);
	haxe_ds_StringMap_new(r5);
	r0->depthToRenderTarget = r5;
	r5 = (haxe__ds__StringMap)hl_alloc_obj(&t$haxe_ds_StringMap);
	haxe_ds_StringMap_new(r5);
	r0->renderTargets = r5;
	r9 = NULL;
	r0->setupDepthTexture = r9;
	r9 = NULL;
	r0->commands = r9;
	r8 = false;
	r0->paused = r8;
	r4 = 0;
	r0->drawOrder = r4;
	r10 = NULL;
	r0->currentG = r10;
	r8 = false;
	r0->isProbe = r8;
	r8 = false;
	r0->isProbeCube = r8;
	r8 = false;
	r0->isProbePlanar = r8;
	r11 = NULL;
	r0->point = r11;
	r11 = NULL;
	r0->sun = r11;
	r11 = NULL;
	r0->light = r11;
	r12 = NULL;
	r0->currentTarget = r12;
	r4 = 0;
	r0->frame = r4;
	r7 = 0.;
	r0->frameTime = r7;
	r4 = 0;
	r0->frameScissorH = r4;
	r4 = 0;
	r0->frameScissorW = r4;
	r4 = 0;
	r0->frameScissorY = r4;
	r4 = 0;
	r0->frameScissorX = r4;
	r8 = false;
	r0->frameScissor = r8;
	return;
}

