// Generated by HLC 4.2.5 (HL v4)
#ifndef INC_armory__trait__physics__bullet__ContactPair
#define INC_armory__trait__physics__bullet__ContactPair
typedef struct _armory__trait__physics__bullet__$ContactPair *armory__trait__physics__bullet__$ContactPair;
typedef struct _armory__trait__physics__bullet__ContactPair *armory__trait__physics__bullet__ContactPair;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <iron/math/Vec4.h>


struct _armory__trait__physics__bullet__$ContactPair {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _armory__trait__physics__bullet__ContactPair {
	hl_type *$type;
	int a;
	int b;
	iron__math__Vec4 posA;
	iron__math__Vec4 posB;
	iron__math__Vec4 normOnB;
	double impulse;
	double distance;
};
#endif

