// Generated by HLC 4.2.5 (HL v4)
#ifndef INC_armory__trait__physics__bullet__ConvexHit
#define INC_armory__trait__physics__bullet__ConvexHit
typedef struct _armory__trait__physics__bullet__$ConvexHit *armory__trait__physics__bullet__$ConvexHit;
typedef struct _armory__trait__physics__bullet__ConvexHit *armory__trait__physics__bullet__ConvexHit;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <iron/math/Vec4.h>


struct _armory__trait__physics__bullet__$ConvexHit {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _armory__trait__physics__bullet__ConvexHit {
	hl_type *$type;
	iron__math__Vec4 pos;
	iron__math__Vec4 normal;
	double hitFraction;
};
#endif

