// Generated by HLC 4.2.5 (HL v4)
#ifndef INC_armory__trait__physics__bullet__DebugDrawHelper
#define INC_armory__trait__physics__bullet__DebugDrawHelper
typedef struct _armory__trait__physics__bullet__$DebugDrawHelper *armory__trait__physics__bullet__$DebugDrawHelper;
typedef struct _armory__trait__physics__bullet__DebugDrawHelper *armory__trait__physics__bullet__DebugDrawHelper;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <armory/trait/physics/bullet/PhysicsWorld.h>
#include <hl/types/ArrayObj.h>
#include <kha/Kravur.h>


struct _armory__trait__physics__bullet__$DebugDrawHelper {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _armory__trait__physics__bullet__DebugDrawHelper {
	hl_type *$type;
	armory__trait__physics__bullet__PhysicsWorld physicsWorld;
	hl__types__ArrayObj lines;
	hl__types__ArrayObj texts;
	kha__Kravur font;
};
#endif

