// Generated by HLC 4.2.5 (HL v4)
#ifndef INC_armory__trait__physics__bullet__Hit
#define INC_armory__trait__physics__bullet__Hit
typedef struct _armory__trait__physics__bullet__$Hit *armory__trait__physics__bullet__$Hit;
typedef struct _armory__trait__physics__bullet__Hit *armory__trait__physics__bullet__Hit;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <armory/trait/physics/bullet/RigidBody.h>
#include <iron/math/Vec4.h>


struct _armory__trait__physics__bullet__$Hit {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _armory__trait__physics__bullet__Hit {
	hl_type *$type;
	armory__trait__physics__bullet__RigidBody rb;
	iron__math__Vec4 pos;
	iron__math__Vec4 normal;
};
#endif

