// Generated by HLC 4.2.5 (HL v4)
#ifndef INC_armory__trait__physics__bullet__TextData
#define INC_armory__trait__physics__bullet__TextData
typedef struct _armory__trait__physics__bullet__$TextData *armory__trait__physics__bullet__$TextData;
typedef struct _armory__trait__physics__bullet__TextData *armory__trait__physics__bullet__TextData;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _armory__trait__physics__bullet__$TextData {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _armory__trait__physics__bullet__TextData {
	hl_type *$type;
	float x;
	float y;
	int color;
	String text;
};
#endif

