// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <armory/renderpath/RenderPathCreator.h>
void armory_renderpath_RenderPathDeferred_commands(void);
extern armory__renderpath__$RenderPathCreator g$b7ec311;
extern hl_type t$fun_7b48b4f;
void armory_renderpath_RenderPathDeferred_setupDepthTexture(void);
extern hl_type t$iron_RenderPath;
void iron_RenderPath_new(iron__RenderPath);
void armory_renderpath_Inc_init(iron__RenderPath);
void armory_renderpath_RenderPathDeferred_init(iron__RenderPath);

void armory_renderpath_RenderPathCreator_get__$1() {
	armory__renderpath__$RenderPathCreator r2;
	vclosure *r1;
	armory_renderpath_RenderPathDeferred_commands();
	r2 = (armory__renderpath__$RenderPathCreator)g$b7ec311;
	r1 = r2->commands;
	if( r1 == NULL ) hl_null_access();
	r1->hasValue ? ((void (*)(vdynamic*))r1->fun)((vdynamic*)r1->value) : ((void (*)(void))r1->fun)();
	return;
}

iron__RenderPath armory_renderpath_RenderPathCreator_get() {
	armory__renderpath__$RenderPathCreator r2;
	vclosure *r3;
	iron__RenderPath r0;
	static vclosure cl$0 = { &t$fun_7b48b4f, armory_renderpath_RenderPathCreator_get__$1, 0 };
	static vclosure cl$1 = { &t$fun_7b48b4f, armory_renderpath_RenderPathDeferred_setupDepthTexture, 0 };
	r0 = (iron__RenderPath)hl_alloc_obj(&t$iron_RenderPath);
	iron_RenderPath_new(r0);
	r2 = (armory__renderpath__$RenderPathCreator)g$b7ec311;
	r2->path = r0;
	r2 = (armory__renderpath__$RenderPathCreator)g$b7ec311;
	r0 = r2->path;
	armory_renderpath_Inc_init(r0);
	r2 = (armory__renderpath__$RenderPathCreator)g$b7ec311;
	r0 = r2->path;
	armory_renderpath_RenderPathDeferred_init(r0);
	r2 = (armory__renderpath__$RenderPathCreator)g$b7ec311;
	r0 = r2->path;
	if( r0 == NULL ) hl_null_access();
	r3 = &cl$0;
	r0->commands = r3;
	r2 = (armory__renderpath__$RenderPathCreator)g$b7ec311;
	r0 = r2->path;
	if( r0 == NULL ) hl_null_access();
	r3 = &cl$1;
	r0->setupDepthTexture = r3;
	r2 = (armory__renderpath__$RenderPathCreator)g$b7ec311;
	r0 = r2->path;
	return r0;
}

