// Generated by HLC 4.2.5 (HL v4)
#ifndef INC_kha__audio2__ogg__vorbis__VorbisDecodeState
#define INC_kha__audio2__ogg__vorbis__VorbisDecodeState
typedef struct _kha__audio2__ogg__vorbis__$VorbisDecodeState *kha__audio2__ogg__vorbis__$VorbisDecodeState;
typedef struct _kha__audio2__ogg__vorbis__VorbisDecodeState *kha__audio2__ogg__vorbis__VorbisDecodeState;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <kha/audio2/ogg/vorbis/data/Page.h>
#include <kha/audio2/ogg/vorbis/data/ProbedPage.h>
#include <haxe/io/Input.h>
#include <hl/types/ArrayBytes_Int.h>
#include <kha/audio2/ogg/vorbis/data/ReaderError.h>


struct _kha__audio2__ogg__vorbis__$VorbisDecodeState {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _kha__audio2__ogg__vorbis__VorbisDecodeState {
	hl_type *$type;
	kha__audio2__ogg__vorbis__data__Page page;
	kha__audio2__ogg__vorbis__data__ProbedPage pFirst;
	kha__audio2__ogg__vorbis__data__ProbedPage pLast;
	int validBits;
	int inputPosition;
	haxe__io__Input input;
	int discardSamplesDeferred;
	hl__types__ArrayBytes_Int segments;
	int bytesInSeg;
	bool firstDecode;
	int nextSeg;
	int acc;
	bool lastSeg;
	int lastSegWhich;
	int endSegWithKnownLoc;
	int knownLocForPacket;
	kha__audio2__ogg__vorbis__data__ReaderError error;
	int currentLoc;
	int firstAudioPageOffset;
};
#endif

