// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <kha/audio2/ogg/vorbis/VorbisDecodeState.h>
#include <hl/natives.h>
hl__types__ArrayBytes_Int hl_types_ArrayBase_allocI32(vbyte*,int);
extern hl_type t$_i32;
extern hl_type t$_dyn;
void hl_types_ArrayBytes_Int___expand(hl__types__ArrayBytes_Int,int);
extern hl_type t$kha_audio2_ogg_vorbis_data_ProbedPage;
void kha_audio2_ogg_vorbis_data_ProbedPage_new(kha__audio2__ogg__vorbis__data__ProbedPage);
#include <haxe/Exception.h>
#include <kha/audio2/ogg/vorbis/data/ReaderError.h>
#include <kha/audio2/ogg/vorbis/data/ReaderErrorType.h>
#include <hl/types/ArrayDyn.h>
void kha_audio2_ogg_vorbis_data_Page_start(kha__audio2__ogg__vorbis__data__Page,kha__audio2__ogg__vorbis__VorbisDecodeState);
haxe__Exception haxe_Exception_caught(vdynamic*);
extern kha__audio2__ogg__vorbis__data__$ReaderError g$b9c07a3;
bool Std_isOfType(vdynamic*,vdynamic*);
extern hl_type t$kha_audio2_ogg_vorbis_data_ReaderError;
extern venum* g$47a4dc3;
extern hl_type t$vrt_329ffa8;
extern String s$2f4cf08;
extern hl_type t$String;
extern String s$0fb2b67;
extern String s$next;
extern hl_type t$vrt_eaa6a3b;
void kha_audio2_ogg_vorbis_data_ReaderError_new(kha__audio2__ogg__vorbis__data__ReaderError,venum*,String,vvirtual*);
vdynamic* haxe_Exception_thrown(vdynamic*);
extern venum* g$da6fdcc;
extern String s$startPacket;
#include <haxe/io/Eof.h>
extern haxe__io__$Eof g$_haxe_io_Eof;
extern String s$maybeStartPacket;
void kha_audio2_ogg_vorbis_data_Page_startWithoutCapturePattern(kha__audio2__ogg__vorbis__data__Page,kha__audio2__ogg__vorbis__VorbisDecodeState);
extern venum* g$21702d5;
extern String s$segmentCount;
extern String s$firstPageValidate;
extern String s$decodeState_head;
extern hl_type t$vrt_d41295c;
extern hl_type t$vrt_80c06ee;
#include <kha/audio2/ogg/vorbis/_VorbisDecodeState/FindPageResult.h>
venum* kha_audio2_ogg_vorbis_VorbisDecodeState_findPage(kha__audio2__ogg__vorbis__VorbisDecodeState,vclosure*,int);
extern venum* g$04ccacc;
extern String s$getSampleNumber;
int haxe_io_Input_readInt32(haxe__io__Input);
#include <kha/audio2/ogg/tools/Crc32.h>
extern venum* g$af6e6b5;
extern kha__audio2__ogg__tools__$Crc32 g$_kha_audio2_ogg_tools_Crc32;
extern hl_type t$kha_audio2_ogg_vorbis__VorbisDecodeState_FindPageResult;
#include <kha/audio2/ogg/vorbis/data/Codebook.h>
extern venum* g$d3e38e8;
extern String s$decodeScalarRaw;
extern hl_type t$kha_audio2_ogg_vorbis_data_Page;
void kha_audio2_ogg_vorbis_data_Page_new(kha__audio2__ogg__vorbis__data__Page);
void kha_audio2_ogg_tools_Crc32_init(void);

void kha_audio2_ogg_vorbis_VorbisDecodeState_setup(kha__audio2__ogg__vorbis__VorbisDecodeState r0,int r1,int r2) {
	kha__audio2__ogg__vorbis__data__ProbedPage r18;
	bool r17;
	hl__types__ArrayBytes_Int r8, r10, r14;
	vdynamic *r11, *r21;
	haxe__io__Input r5;
	vbyte *r9;
	int r3, r4, r7, r12, r13, r15, r16, r19, r20;
	r3 = r0->inputPosition;
	r4 = 1;
	r3 = r3 + r4;
	r0->inputPosition = r3;
	r5 = r0->input;
	if( r5 == NULL ) hl_null_access();
	r3 = ((int (*)(haxe__io__Input))r5->$type->vobj_proto[0])(r5);
	r4 = r0->inputPosition;
	r4 = r4 + r3;
	r0->inputPosition = r4;
	r4 = 0;
	r9 = hl_alloc_bytes(r4);
	r4 = 0;
	r4 = 0;
	r8 = hl_types_ArrayBase_allocI32(r9,r4);
	r7 = 0;
	if( r7 >= r3 ) goto label$8aebce3_1_29;
	if( r8 == NULL ) hl_null_access();
	r7 = 1;
	r4 = r3 - r7;
	r11 = NULL;
	r7 = (int)hl_dyn_casti(&r11,&t$_dyn,&t$_i32);
	r12 = r8->length;
	if( ((unsigned)r4) < ((unsigned)r12) ) goto label$8aebce3_1_25;
	hl_types_ArrayBytes_Int___expand(r8,r4);
	label$8aebce3_1_25:
	r9 = r8->bytes;
	r12 = 2;
	r12 = r4 << r12;
	*(int*)(r9 + r12) = r7;
	label$8aebce3_1_29:
	r10 = r8;
	r4 = 0;
	r7 = r3;
	label$8aebce3_1_32:
	if( r4 >= r7 ) goto label$8aebce3_1_48;
	r12 = r4;
	++r4;
	if( r10 == NULL ) hl_null_access();
	r5 = r0->input;
	if( r5 == NULL ) hl_null_access();
	r15 = ((int (*)(haxe__io__Input))r5->$type->vobj_proto[0])(r5);
	r16 = r10->length;
	if( ((unsigned)r12) < ((unsigned)r16) ) goto label$8aebce3_1_43;
	hl_types_ArrayBytes_Int___expand(r10,r12);
	label$8aebce3_1_43:
	r9 = r10->bytes;
	r16 = 2;
	r16 = r12 << r16;
	*(int*)(r9 + r16) = r15;
	goto label$8aebce3_1_32;
	label$8aebce3_1_48:
	r0->segments = r10;
	r4 = -2;
	r0->endSegWithKnownLoc = r4;
	r7 = -1;
	if( r1 != r7 ) goto label$8aebce3_1_55;
	r7 = -1;
	if( r2 == r7 ) goto label$8aebce3_1_79;
	label$8aebce3_1_55:
	r7 = 1;
	r4 = r3 - r7;
	label$8aebce3_1_57:
	r12 = 0;
	if( r4 < r12 ) goto label$8aebce3_1_79;
	r14 = r0->segments;
	if( r14 == NULL ) hl_null_access();
	r12 = r14->length;
	if( ((unsigned)r4) < ((unsigned)r12) ) goto label$8aebce3_1_66;
	r7 = 0;
	goto label$8aebce3_1_70;
	label$8aebce3_1_66:
	r9 = r14->bytes;
	r12 = 2;
	r12 = r4 << r12;
	r7 = *(int*)(r9 + r12);
	label$8aebce3_1_70:
	r12 = 255;
	if( r7 >= r12 ) goto label$8aebce3_1_73;
	goto label$8aebce3_1_79;
	label$8aebce3_1_73:
	r12 = 0;
	if( r4 < r12 ) goto label$8aebce3_1_77;
	r0->endSegWithKnownLoc = r4;
	r0->knownLocForPacket = r1;
	label$8aebce3_1_77:
	--r4;
	goto label$8aebce3_1_57;
	label$8aebce3_1_79:
	r17 = r0->firstDecode;
	if( !r17 ) goto label$8aebce3_1_120;
	r4 = 0;
	r7 = 0;
	r18 = (kha__audio2__ogg__vorbis__data__ProbedPage)hl_alloc_obj(&t$kha_audio2_ogg_vorbis_data_ProbedPage);
	kha_audio2_ogg_vorbis_data_ProbedPage_new(r18);
	r12 = 0;
	r13 = r3;
	label$8aebce3_1_87:
	if( r12 >= r13 ) goto label$8aebce3_1_104;
	r15 = r12;
	++r12;
	r14 = r0->segments;
	if( r14 == NULL ) hl_null_access();
	r20 = r14->length;
	if( ((unsigned)r15) < ((unsigned)r20) ) goto label$8aebce3_1_97;
	r19 = 0;
	goto label$8aebce3_1_101;
	label$8aebce3_1_97:
	r9 = r14->bytes;
	r20 = 2;
	r20 = r15 << r20;
	r19 = *(int*)(r9 + r20);
	label$8aebce3_1_101:
	r16 = r7 + r19;
	r7 = r16;
	goto label$8aebce3_1_87;
	label$8aebce3_1_104:
	r13 = 27;
	r13 = r13 + r3;
	r12 = r7 + r13;
	r7 = r12;
	if( r18 == NULL ) hl_null_access();
	r12 = r0->firstAudioPageOffset;
	r18->pageStart = r12;
	r12 = r18->pageStart;
	r12 = r12 + r7;
	r18->pageEnd = r12;
	r12 = 0;
	r21 = hl_alloc_dynamic(&t$_i32);
	r21->v.i = r12;
	r18->firstDecodedSample = r21;
	r21 = hl_alloc_dynamic(&t$_i32);
	r21->v.i = r1;
	r18->lastDecodedSample = r21;
	r0->pFirst = r18;
	label$8aebce3_1_120:
	r4 = 0;
	r0->nextSeg = r4;
	return;
}

int kha_audio2_ogg_vorbis_VorbisDecodeState_next(kha__audio2__ogg__vorbis__VorbisDecodeState r0) {
	String r13, r15;
	vvirtual *r14, *r16;
	venum *r12;
	bool r2;
	kha__audio2__ogg__vorbis__data__Page r7;
	hl__types__ArrayBytes_Int r6;
	kha__audio2__ogg__vorbis__data__$ReaderError r10;
	kha__audio2__ogg__vorbis__data__ReaderError r11;
	haxe__Exception r9;
	vdynamic *r4, *r8;
	vbyte *r17;
	int r3, r5, r18;
	hl_trap_ctx trap$0;
	r2 = r0->lastSeg;
	if( !r2 ) goto label$8aebce3_2_4;
	r3 = 0;
	return r3;
	label$8aebce3_2_4:
	r3 = r0->nextSeg;
	r5 = -1;
	if( r3 != r5 ) goto label$8aebce3_2_56;
	r6 = r0->segments;
	if( r6 == NULL ) hl_null_access();
	r3 = r6->length;
	r5 = 1;
	r3 = r3 - r5;
	r0->lastSegWhich = r3;
	hl_trap(trap$0,r4,label$8aebce3_2_19);
	r7 = r0->page;
	if( r7 == NULL ) hl_null_access();
	kha_audio2_ogg_vorbis_data_Page_start(r7,r0);
	hl_endtrap(trap$0);
	goto label$8aebce3_2_33;
	label$8aebce3_2_19:
	r8 = NULL;
	r9 = haxe_Exception_caught(r4);
	if( r9 == NULL ) hl_null_access();
	r8 = ((vdynamic* (*)(haxe__Exception))r9->$type->vobj_proto[0])(r9);
	r10 = (kha__audio2__ogg__vorbis__data__$ReaderError)g$b9c07a3;
	r2 = Std_isOfType(r8,((vdynamic*)r10));
	if( !r2 ) goto label$8aebce3_2_32;
	r11 = (kha__audio2__ogg__vorbis__data__ReaderError)hl_dyn_castp(&r8,&t$_dyn,&t$kha_audio2_ogg_vorbis_data_ReaderError);
	r2 = true;
	r0->lastSeg = r2;
	r0->error = r11;
	r3 = 0;
	return r3;
	label$8aebce3_2_32:
	hl_rethrow((vdynamic*)r4);
	label$8aebce3_2_33:
	r7 = r0->page;
	if( r7 == NULL ) hl_null_access();
	r3 = r7->flag;
	r5 = 1;
	r3 = r3 & r5;
	r5 = 0;
	if( r3 != r5 ) goto label$8aebce3_2_56;
	r11 = (kha__audio2__ogg__vorbis__data__ReaderError)hl_alloc_obj(&t$kha_audio2_ogg_vorbis_data_ReaderError);
	r12 = (venum*)g$47a4dc3;
	r13 = NULL;
	r14 = hl_alloc_virtual(&t$vrt_329ffa8);
	r15 = (String)s$2f4cf08;
	if( hl_vfields(r14)[1] ) *(String*)(hl_vfields(r14)[1]) = (String)r15; else hl_dyn_setp(r14->value,37969014/*fileName*/,&t$String,r15);
	r3 = 171;
	if( hl_vfields(r14)[2] ) *(int*)(hl_vfields(r14)[2]) = (int)r3; else hl_dyn_seti(r14->value,371360620/*lineNumber*/,&t$_i32,r3);
	r15 = (String)s$0fb2b67;
	if( hl_vfields(r14)[0] ) *(String*)(hl_vfields(r14)[0]) = (String)r15; else hl_dyn_setp(r14->value,-63073762/*className*/,&t$String,r15);
	r15 = (String)s$next;
	if( hl_vfields(r14)[3] ) *(String*)(hl_vfields(r14)[3]) = (String)r15; else hl_dyn_setp(r14->value,302979532/*methodName*/,&t$String,r15);
	r16 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r14);
	kha_audio2_ogg_vorbis_data_ReaderError_new(r11,r12,r13,r16);
	r8 = haxe_Exception_thrown(((vdynamic*)r11));
	hl_throw((vdynamic*)r8);
	label$8aebce3_2_56:
	r6 = r0->segments;
	if( r6 == NULL ) hl_null_access();
	r3 = r0->nextSeg;
	r5 = r3;
	++r3;
	r0->nextSeg = r3;
	r3 = r6->length;
	if( ((unsigned)r5) < ((unsigned)r3) ) goto label$8aebce3_2_66;
	r3 = 0;
	goto label$8aebce3_2_70;
	label$8aebce3_2_66:
	r17 = r6->bytes;
	r3 = 2;
	r3 = r5 << r3;
	r3 = *(int*)(r17 + r3);
	label$8aebce3_2_70:
	r18 = 255;
	if( r3 >= r18 ) goto label$8aebce3_2_78;
	r2 = true;
	r0->lastSeg = r2;
	r5 = r0->nextSeg;
	r18 = 1;
	r5 = r5 - r18;
	r0->lastSegWhich = r5;
	label$8aebce3_2_78:
	r5 = r0->nextSeg;
	r6 = r0->segments;
	if( r6 == NULL ) hl_null_access();
	r18 = r6->length;
	if( r5 < r18 ) goto label$8aebce3_2_85;
	r5 = -1;
	r0->nextSeg = r5;
	label$8aebce3_2_85:
	r0->bytesInSeg = r3;
	return r3;
}

void kha_audio2_ogg_vorbis_VorbisDecodeState_startPacket(kha__audio2__ogg__vorbis__VorbisDecodeState r0) {
	String r8, r10;
	vvirtual *r9, *r11;
	venum *r7;
	bool r12;
	kha__audio2__ogg__vorbis__data__Page r4;
	kha__audio2__ogg__vorbis__data__ReaderError r6;
	vdynamic *r5;
	int r1, r2;
	label$8aebce3_3_0:
	r1 = r0->nextSeg;
	r2 = -1;
	if( r1 != r2 ) goto label$8aebce3_3_31;
	r4 = r0->page;
	if( r4 == NULL ) hl_null_access();
	kha_audio2_ogg_vorbis_data_Page_start(r4,r0);
	r4 = r0->page;
	if( r4 == NULL ) hl_null_access();
	r1 = r4->flag;
	r2 = 1;
	r1 = r1 & r2;
	r2 = 0;
	if( r1 == r2 ) goto label$8aebce3_3_30;
	r6 = (kha__audio2__ogg__vorbis__data__ReaderError)hl_alloc_obj(&t$kha_audio2_ogg_vorbis_data_ReaderError);
	r7 = (venum*)g$da6fdcc;
	r8 = NULL;
	r9 = hl_alloc_virtual(&t$vrt_329ffa8);
	r10 = (String)s$2f4cf08;
	if( hl_vfields(r9)[1] ) *(String*)(hl_vfields(r9)[1]) = (String)r10; else hl_dyn_setp(r9->value,37969014/*fileName*/,&t$String,r10);
	r1 = 193;
	if( hl_vfields(r9)[2] ) *(int*)(hl_vfields(r9)[2]) = (int)r1; else hl_dyn_seti(r9->value,371360620/*lineNumber*/,&t$_i32,r1);
	r10 = (String)s$0fb2b67;
	if( hl_vfields(r9)[0] ) *(String*)(hl_vfields(r9)[0]) = (String)r10; else hl_dyn_setp(r9->value,-63073762/*className*/,&t$String,r10);
	r10 = (String)s$startPacket;
	if( hl_vfields(r9)[3] ) *(String*)(hl_vfields(r9)[3]) = (String)r10; else hl_dyn_setp(r9->value,302979532/*methodName*/,&t$String,r10);
	r11 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r9);
	kha_audio2_ogg_vorbis_data_ReaderError_new(r6,r7,r8,r11);
	r5 = haxe_Exception_thrown(((vdynamic*)r6));
	hl_throw((vdynamic*)r5);
	label$8aebce3_3_30:
	goto label$8aebce3_3_0;
	label$8aebce3_3_31:
	r12 = false;
	r0->lastSeg = r12;
	r1 = 0;
	r0->validBits = r1;
	r1 = 0;
	r0->bytesInSeg = r1;
	return;
}

bool kha_audio2_ogg_vorbis_VorbisDecodeState_maybeStartPacket(kha__audio2__ogg__vorbis__VorbisDecodeState r0) {
	String r17, r19;
	vvirtual *r18, *r20;
	venum *r16;
	bool r4, r8, r12, r13, r14;
	kha__audio2__ogg__vorbis__data__Page r21;
	kha__audio2__ogg__vorbis__data__ReaderError r15;
	haxe__io__$Eof r10;
	haxe__Exception r9;
	haxe__io__Input r6;
	vdynamic *r5, *r7;
	int r2, r3, r11;
	hl_trap_ctx trap$0;
	r2 = r0->nextSeg;
	r3 = -1;
	if( r2 != r3 ) goto label$8aebce3_4_95;
	r4 = false;
	hl_trap(trap$0,r5,label$8aebce3_4_14);
	r2 = r0->inputPosition;
	r3 = 1;
	r2 = r2 + r3;
	r0->inputPosition = r2;
	r6 = r0->input;
	if( r6 == NULL ) hl_null_access();
	r3 = ((int (*)(haxe__io__Input))r6->$type->vobj_proto[0])(r6);
	hl_endtrap(trap$0);
	goto label$8aebce3_4_26;
	label$8aebce3_4_14:
	r7 = NULL;
	r9 = haxe_Exception_caught(r5);
	if( r9 == NULL ) hl_null_access();
	r7 = ((vdynamic* (*)(haxe__Exception))r9->$type->vobj_proto[0])(r9);
	r10 = (haxe__io__$Eof)g$_haxe_io_Eof;
	r8 = Std_isOfType(r7,((vdynamic*)r10));
	if( !r8 ) goto label$8aebce3_4_25;
	r8 = true;
	r4 = r8;
	r3 = 0;
	goto label$8aebce3_4_26;
	label$8aebce3_4_25:
	hl_rethrow((vdynamic*)r5);
	label$8aebce3_4_26:
	if( !r4 ) goto label$8aebce3_4_29;
	r8 = false;
	return r8;
	label$8aebce3_4_29:
	r11 = 79;
	if( r3 != r11 ) goto label$8aebce3_4_44;
	r3 = r0->inputPosition;
	r11 = 1;
	r3 = r3 + r11;
	r0->inputPosition = r3;
	r6 = r0->input;
	if( r6 == NULL ) hl_null_access();
	r3 = ((int (*)(haxe__io__Input))r6->$type->vobj_proto[0])(r6);
	r11 = 103;
	if( r3 != r11 ) goto label$8aebce3_4_42;
	r12 = false;
	goto label$8aebce3_4_43;
	label$8aebce3_4_42:
	r12 = true;
	label$8aebce3_4_43:
	goto label$8aebce3_4_45;
	label$8aebce3_4_44:
	r12 = true;
	label$8aebce3_4_45:
	if( r12 ) goto label$8aebce3_4_59;
	r3 = r0->inputPosition;
	r11 = 1;
	r3 = r3 + r11;
	r0->inputPosition = r3;
	r6 = r0->input;
	if( r6 == NULL ) hl_null_access();
	r3 = ((int (*)(haxe__io__Input))r6->$type->vobj_proto[0])(r6);
	r11 = 103;
	if( r3 != r11 ) goto label$8aebce3_4_57;
	r13 = false;
	goto label$8aebce3_4_58;
	label$8aebce3_4_57:
	r13 = true;
	label$8aebce3_4_58:
	goto label$8aebce3_4_60;
	label$8aebce3_4_59:
	r13 = true;
	label$8aebce3_4_60:
	if( r13 ) goto label$8aebce3_4_74;
	r3 = r0->inputPosition;
	r11 = 1;
	r3 = r3 + r11;
	r0->inputPosition = r3;
	r6 = r0->input;
	if( r6 == NULL ) hl_null_access();
	r3 = ((int (*)(haxe__io__Input))r6->$type->vobj_proto[0])(r6);
	r11 = 83;
	if( r3 != r11 ) goto label$8aebce3_4_72;
	r14 = false;
	goto label$8aebce3_4_73;
	label$8aebce3_4_72:
	r14 = true;
	label$8aebce3_4_73:
	goto label$8aebce3_4_75;
	label$8aebce3_4_74:
	r14 = true;
	label$8aebce3_4_75:
	if( !r14 ) goto label$8aebce3_4_92;
	r15 = (kha__audio2__ogg__vorbis__data__ReaderError)hl_alloc_obj(&t$kha_audio2_ogg_vorbis_data_ReaderError);
	r16 = (venum*)g$da6fdcc;
	r17 = NULL;
	r18 = hl_alloc_virtual(&t$vrt_329ffa8);
	r19 = (String)s$2f4cf08;
	if( hl_vfields(r18)[1] ) *(String*)(hl_vfields(r18)[1]) = (String)r19; else hl_dyn_setp(r18->value,37969014/*fileName*/,&t$String,r19);
	r3 = 218;
	if( hl_vfields(r18)[2] ) *(int*)(hl_vfields(r18)[2]) = (int)r3; else hl_dyn_seti(r18->value,371360620/*lineNumber*/,&t$_i32,r3);
	r19 = (String)s$0fb2b67;
	if( hl_vfields(r18)[0] ) *(String*)(hl_vfields(r18)[0]) = (String)r19; else hl_dyn_setp(r18->value,-63073762/*className*/,&t$String,r19);
	r19 = (String)s$maybeStartPacket;
	if( hl_vfields(r18)[3] ) *(String*)(hl_vfields(r18)[3]) = (String)r19; else hl_dyn_setp(r18->value,302979532/*methodName*/,&t$String,r19);
	r20 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r18);
	kha_audio2_ogg_vorbis_data_ReaderError_new(r15,r16,r17,r20);
	r7 = haxe_Exception_thrown(((vdynamic*)r15));
	hl_throw((vdynamic*)r7);
	label$8aebce3_4_92:
	r21 = r0->page;
	if( r21 == NULL ) hl_null_access();
	kha_audio2_ogg_vorbis_data_Page_startWithoutCapturePattern(r21,r0);
	label$8aebce3_4_95:
	kha_audio2_ogg_vorbis_VorbisDecodeState_startPacket(r0);
	r4 = true;
	return r4;
}

int kha_audio2_ogg_vorbis_VorbisDecodeState_readBits(kha__audio2__ogg__vorbis__VorbisDecodeState r0,int r1) {
	bool r5;
	haxe__io__Input r6;
	int r2, r3, r4;
	r2 = r0->validBits;
	r3 = 0;
	if( r2 >= r3 ) goto label$8aebce3_5_5;
	r2 = 0;
	return r2;
	label$8aebce3_5_5:
	r2 = r0->validBits;
	if( r2 >= r1 ) goto label$8aebce3_5_78;
	r3 = 24;
	if( r3 >= r1 ) goto label$8aebce3_5_18;
	r2 = 24;
	r2 = kha_audio2_ogg_vorbis_VorbisDecodeState_readBits(r0,r2);
	r4 = 24;
	r3 = r1 - r4;
	r3 = kha_audio2_ogg_vorbis_VorbisDecodeState_readBits(r0,r3);
	r4 = 24;
	r3 = r3 << r4;
	r2 = r2 + r3;
	return r2;
	label$8aebce3_5_18:
	r2 = r0->validBits;
	r3 = 0;
	if( r2 != r3 ) goto label$8aebce3_5_23;
	r2 = 0;
	r0->acc = r2;
	label$8aebce3_5_23:
	r5 = true;
	if( !r5 ) goto label$8aebce3_5_60;
	r2 = r0->bytesInSeg;
	r3 = 0;
	if( r2 != r3 ) goto label$8aebce3_5_37;
	r5 = r0->lastSeg;
	if( r5 ) goto label$8aebce3_5_34;
	r2 = kha_audio2_ogg_vorbis_VorbisDecodeState_next(r0);
	r3 = 0;
	if( r2 != r3 ) goto label$8aebce3_5_37;
	label$8aebce3_5_34:
	r2 = -1;
	r0->validBits = r2;
	goto label$8aebce3_5_60;
	label$8aebce3_5_37:
	r2 = r0->bytesInSeg;
	--r2;
	r0->bytesInSeg = r2;
	r2 = r0->inputPosition;
	r3 = 1;
	r2 = r2 + r3;
	r0->inputPosition = r2;
	r2 = r0->acc;
	r6 = r0->input;
	if( r6 == NULL ) hl_null_access();
	r3 = ((int (*)(haxe__io__Input))r6->$type->vobj_proto[0])(r6);
	r4 = r0->validBits;
	r3 = r3 << r4;
	r2 = r2 + r3;
	r0->acc = r2;
	r2 = r0->validBits;
	r3 = 8;
	r2 = r2 + r3;
	r0->validBits = r2;
	r2 = r0->validBits;
	if( r2 < r1 ) goto label$8aebce3_5_59;
	goto label$8aebce3_5_60;
	label$8aebce3_5_59:
	goto label$8aebce3_5_23;
	label$8aebce3_5_60:
	r2 = r0->validBits;
	r3 = 0;
	if( r2 >= r3 ) goto label$8aebce3_5_65;
	r2 = 0;
	return r2;
	label$8aebce3_5_65:
	r2 = r0->acc;
	r3 = 1;
	r3 = r3 << r1;
	r4 = 1;
	r3 = r3 - r4;
	r2 = r2 & r3;
	r3 = r0->acc;
	r3 = ((unsigned)r3) >> r1;
	r0->acc = r3;
	r3 = r0->validBits;
	r3 = r3 - r1;
	r0->validBits = r3;
	return r2;
	label$8aebce3_5_78:
	r2 = r0->acc;
	r3 = 1;
	r3 = r3 << r1;
	r4 = 1;
	r3 = r3 - r4;
	r2 = r2 & r3;
	r3 = r0->acc;
	r3 = ((unsigned)r3) >> r1;
	r0->acc = r3;
	r3 = r0->validBits;
	r3 = r3 - r1;
	r0->validBits = r3;
	return r2;
}

void kha_audio2_ogg_vorbis_VorbisDecodeState_firstPageValidate(kha__audio2__ogg__vorbis__VorbisDecodeState r0) {
	String r8, r10;
	vvirtual *r9, *r11;
	venum *r7;
	hl__types__ArrayBytes_Int r3;
	kha__audio2__ogg__vorbis__data__ReaderError r6;
	vdynamic *r5;
	vbyte *r12;
	int r2, r4;
	r3 = r0->segments;
	if( r3 == NULL ) hl_null_access();
	r2 = r3->length;
	r4 = 1;
	if( r2 == r4 ) goto label$8aebce3_6_21;
	r6 = (kha__audio2__ogg__vorbis__data__ReaderError)hl_alloc_obj(&t$kha_audio2_ogg_vorbis_data_ReaderError);
	r7 = (venum*)g$21702d5;
	r8 = (String)s$segmentCount;
	r9 = hl_alloc_virtual(&t$vrt_329ffa8);
	r10 = (String)s$2f4cf08;
	if( hl_vfields(r9)[1] ) *(String*)(hl_vfields(r9)[1]) = (String)r10; else hl_dyn_setp(r9->value,37969014/*fileName*/,&t$String,r10);
	r2 = 308;
	if( hl_vfields(r9)[2] ) *(int*)(hl_vfields(r9)[2]) = (int)r2; else hl_dyn_seti(r9->value,371360620/*lineNumber*/,&t$_i32,r2);
	r10 = (String)s$0fb2b67;
	if( hl_vfields(r9)[0] ) *(String*)(hl_vfields(r9)[0]) = (String)r10; else hl_dyn_setp(r9->value,-63073762/*className*/,&t$String,r10);
	r10 = (String)s$firstPageValidate;
	if( hl_vfields(r9)[3] ) *(String*)(hl_vfields(r9)[3]) = (String)r10; else hl_dyn_setp(r9->value,302979532/*methodName*/,&t$String,r10);
	r11 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r9);
	kha_audio2_ogg_vorbis_data_ReaderError_new(r6,r7,r8,r11);
	r5 = haxe_Exception_thrown(((vdynamic*)r6));
	hl_throw((vdynamic*)r5);
	label$8aebce3_6_21:
	r3 = r0->segments;
	if( r3 == NULL ) hl_null_access();
	r2 = 0;
	r4 = r3->length;
	if( ((unsigned)r2) < ((unsigned)r4) ) goto label$8aebce3_6_28;
	r2 = 0;
	goto label$8aebce3_6_32;
	label$8aebce3_6_28:
	r12 = r3->bytes;
	r4 = 2;
	r4 = r2 << r4;
	r2 = *(int*)(r12 + r4);
	label$8aebce3_6_32:
	r4 = 30;
	if( r2 == r4 ) goto label$8aebce3_6_50;
	r6 = (kha__audio2__ogg__vorbis__data__ReaderError)hl_alloc_obj(&t$kha_audio2_ogg_vorbis_data_ReaderError);
	r7 = (venum*)g$21702d5;
	r8 = (String)s$decodeState_head;
	r9 = hl_alloc_virtual(&t$vrt_329ffa8);
	r10 = (String)s$2f4cf08;
	if( hl_vfields(r9)[1] ) *(String*)(hl_vfields(r9)[1]) = (String)r10; else hl_dyn_setp(r9->value,37969014/*fileName*/,&t$String,r10);
	r2 = 311;
	if( hl_vfields(r9)[2] ) *(int*)(hl_vfields(r9)[2]) = (int)r2; else hl_dyn_seti(r9->value,371360620/*lineNumber*/,&t$_i32,r2);
	r10 = (String)s$0fb2b67;
	if( hl_vfields(r9)[0] ) *(String*)(hl_vfields(r9)[0]) = (String)r10; else hl_dyn_setp(r9->value,-63073762/*className*/,&t$String,r10);
	r10 = (String)s$firstPageValidate;
	if( hl_vfields(r9)[3] ) *(String*)(hl_vfields(r9)[3]) = (String)r10; else hl_dyn_setp(r9->value,302979532/*methodName*/,&t$String,r10);
	r11 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r9);
	kha_audio2_ogg_vorbis_data_ReaderError_new(r6,r7,r8,r11);
	r5 = haxe_Exception_thrown(((vdynamic*)r6));
	hl_throw((vdynamic*)r5);
	label$8aebce3_6_50:
	return;
}

void kha_audio2_ogg_vorbis_VorbisDecodeState_startFirstDecode(kha__audio2__ogg__vorbis__VorbisDecodeState r0) {
	bool r2;
	int r1;
	r1 = r0->inputPosition;
	r0->firstAudioPageOffset = r1;
	r2 = true;
	r0->firstDecode = r2;
	return;
}

void kha_audio2_ogg_vorbis_VorbisDecodeState_prepHuffman(kha__audio2__ogg__vorbis__VorbisDecodeState r0) {
	bool r4;
	haxe__io__Input r5;
	int r2, r3, r6;
	r2 = r0->validBits;
	r3 = 24;
	if( r3 < r2 ) goto label$8aebce3_8_44;
	r2 = r0->validBits;
	r3 = 0;
	if( r2 != r3 ) goto label$8aebce3_8_8;
	r2 = 0;
	r0->acc = r2;
	label$8aebce3_8_8:
	r4 = true;
	if( !r4 ) goto label$8aebce3_8_44;
	r2 = r0->bytesInSeg;
	r3 = 0;
	if( r2 != r3 ) goto label$8aebce3_8_20;
	r4 = r0->lastSeg;
	if( r4 ) goto label$8aebce3_8_19;
	r2 = kha_audio2_ogg_vorbis_VorbisDecodeState_next(r0);
	r3 = 0;
	if( r2 != r3 ) goto label$8aebce3_8_20;
	label$8aebce3_8_19:
	return;
	label$8aebce3_8_20:
	r2 = r0->bytesInSeg;
	--r2;
	r0->bytesInSeg = r2;
	r2 = r0->inputPosition;
	r3 = 1;
	r2 = r2 + r3;
	r0->inputPosition = r2;
	r2 = r0->acc;
	r5 = r0->input;
	if( r5 == NULL ) hl_null_access();
	r3 = ((int (*)(haxe__io__Input))r5->$type->vobj_proto[0])(r5);
	r6 = r0->validBits;
	r3 = r3 << r6;
	r2 = r2 + r3;
	r0->acc = r2;
	r2 = r0->validBits;
	r3 = 8;
	r2 = r2 + r3;
	r0->validBits = r2;
	r2 = r0->validBits;
	r3 = 24;
	if( r3 >= r2 ) goto label$8aebce3_8_43;
	goto label$8aebce3_8_44;
	label$8aebce3_8_43:
	goto label$8aebce3_8_8;
	label$8aebce3_8_44:
	return;
}

vvirtual* kha_audio2_ogg_vorbis_VorbisDecodeState_finishDecodePacket(kha__audio2__ogg__vorbis__VorbisDecodeState r0,int r1,int r2,vvirtual* r3) {
	vvirtual *r5, *r14;
	bool r6, r9;
	kha__audio2__ogg__vorbis__data__Page r11;
	int r4, r7, r8, r10, r12, r13;
	if( r3 == NULL ) hl_null_access();
	r5 = hl_vfields(r3)[0] ? (*(vvirtual**)(hl_vfields(r3)[0])) : (vvirtual*)hl_dyn_getp(r3->value,128977169/*left*/,&t$vrt_d41295c);
	if( r5 == NULL ) hl_null_access();
	r4 = hl_vfields(r5)[1] ? (*(int*)(hl_vfields(r5)[1])) : (int)hl_dyn_geti(r5->value,-469011757/*start*/,&t$_i32);
	r6 = false;
	r8 = 1;
	r7 = r2 >> r8;
	r9 = r0->firstDecode;
	if( !r9 ) goto label$8aebce3_9_21;
	r8 = -r7;
	r0->currentLoc = r8;
	r5 = hl_vfields(r3)[2] ? (*(vvirtual**)(hl_vfields(r3)[2])) : (vvirtual*)hl_dyn_getp(r3->value,-379319332/*right*/,&t$vrt_d41295c);
	if( r5 == NULL ) hl_null_access();
	r10 = hl_vfields(r5)[0] ? (*(int*)(hl_vfields(r5)[0])) : (int)hl_dyn_geti(r5->value,5047259/*end*/,&t$_i32);
	r8 = r2 - r10;
	r0->discardSamplesDeferred = r8;
	r9 = true;
	r6 = r9;
	r9 = false;
	r0->firstDecode = r9;
	goto label$8aebce3_9_43;
	label$8aebce3_9_21:
	r8 = r0->discardSamplesDeferred;
	r10 = 0;
	if( r8 == r10 ) goto label$8aebce3_9_37;
	r5 = hl_vfields(r3)[0] ? (*(vvirtual**)(hl_vfields(r3)[0])) : (vvirtual*)hl_dyn_getp(r3->value,128977169/*left*/,&t$vrt_d41295c);
	if( r5 == NULL ) hl_null_access();
	r8 = hl_vfields(r5)[1] ? (*(int*)(hl_vfields(r5)[1])) : (int)hl_dyn_geti(r5->value,-469011757/*start*/,&t$_i32);
	r10 = r0->discardSamplesDeferred;
	r8 = r8 + r10;
	if( hl_vfields(r5)[1] ) *(int*)(hl_vfields(r5)[1]) = (int)r8; else hl_dyn_seti(r5->value,-469011757/*start*/,&t$_i32,r8);
	r5 = hl_vfields(r3)[0] ? (*(vvirtual**)(hl_vfields(r3)[0])) : (vvirtual*)hl_dyn_getp(r3->value,128977169/*left*/,&t$vrt_d41295c);
	if( r5 == NULL ) hl_null_access();
	r8 = hl_vfields(r5)[1] ? (*(int*)(hl_vfields(r5)[1])) : (int)hl_dyn_geti(r5->value,-469011757/*start*/,&t$_i32);
	r4 = r8;
	r8 = 0;
	r0->discardSamplesDeferred = r8;
	goto label$8aebce3_9_43;
	label$8aebce3_9_37:
	r10 = 0;
	if( r1 != r10 ) goto label$8aebce3_9_42;
	if( !r6 ) goto label$8aebce3_9_42;
	r9 = true;
	goto label$8aebce3_9_43;
	label$8aebce3_9_42:
	r9 = false;
	label$8aebce3_9_43:
	r8 = r0->lastSegWhich;
	r10 = r0->endSegWithKnownLoc;
	if( r8 != r10 ) goto label$8aebce3_9_97;
	if( !r6 ) goto label$8aebce3_9_88;
	r11 = r0->page;
	if( r11 == NULL ) hl_null_access();
	r8 = r11->flag;
	r10 = 4;
	r8 = r8 & r10;
	r10 = 0;
	if( r8 == r10 ) goto label$8aebce3_9_88;
	r8 = r0->knownLocForPacket;
	r5 = hl_vfields(r3)[2] ? (*(vvirtual**)(hl_vfields(r3)[2])) : (vvirtual*)hl_dyn_getp(r3->value,-379319332/*right*/,&t$vrt_d41295c);
	if( r5 == NULL ) hl_null_access();
	r12 = hl_vfields(r5)[0] ? (*(int*)(hl_vfields(r5)[0])) : (int)hl_dyn_geti(r5->value,5047259/*end*/,&t$_i32);
	r10 = r2 - r12;
	r8 = r8 - r10;
	r12 = r0->currentLoc;
	r5 = hl_vfields(r3)[2] ? (*(vvirtual**)(hl_vfields(r3)[2])) : (vvirtual*)hl_dyn_getp(r3->value,-379319332/*right*/,&t$vrt_d41295c);
	if( r5 == NULL ) hl_null_access();
	r13 = hl_vfields(r5)[0] ? (*(int*)(hl_vfields(r5)[0])) : (int)hl_dyn_geti(r5->value,5047259/*end*/,&t$_i32);
	r12 = r12 + r13;
	if( r8 >= r12 ) goto label$8aebce3_9_88;
	r12 = r0->currentLoc;
	if( r8 >= r12 ) goto label$8aebce3_9_70;
	r10 = 0;
	goto label$8aebce3_9_72;
	label$8aebce3_9_70:
	r12 = r0->currentLoc;
	r10 = r8 - r12;
	label$8aebce3_9_72:
	r5 = hl_vfields(r3)[0] ? (*(vvirtual**)(hl_vfields(r3)[0])) : (vvirtual*)hl_dyn_getp(r3->value,128977169/*left*/,&t$vrt_d41295c);
	if( r5 == NULL ) hl_null_access();
	r13 = hl_vfields(r5)[1] ? (*(int*)(hl_vfields(r5)[1])) : (int)hl_dyn_geti(r5->value,-469011757/*start*/,&t$_i32);
	r12 = r10 + r13;
	r10 = r12;
	r12 = r0->currentLoc;
	r12 = r12 + r10;
	r0->currentLoc = r12;
	r14 = hl_alloc_virtual(&t$vrt_80c06ee);
	if( hl_vfields(r14)[1] ) *(int*)(hl_vfields(r14)[1]) = (int)r10; else hl_dyn_seti(r14->value,5393365/*len*/,&t$_i32,r10);
	if( hl_vfields(r14)[0] ) *(int*)(hl_vfields(r14)[0]) = (int)r4; else hl_dyn_seti(r14->value,128977169/*left*/,&t$_i32,r4);
	r5 = hl_vfields(r3)[2] ? (*(vvirtual**)(hl_vfields(r3)[2])) : (vvirtual*)hl_dyn_getp(r3->value,-379319332/*right*/,&t$vrt_d41295c);
	if( r5 == NULL ) hl_null_access();
	r12 = hl_vfields(r5)[1] ? (*(int*)(hl_vfields(r5)[1])) : (int)hl_dyn_geti(r5->value,-469011757/*start*/,&t$_i32);
	if( hl_vfields(r14)[2] ) *(int*)(hl_vfields(r14)[2]) = (int)r12; else hl_dyn_seti(r14->value,-379319332/*right*/,&t$_i32,r12);
	return r14;
	label$8aebce3_9_88:
	r8 = r0->knownLocForPacket;
	r5 = hl_vfields(r3)[0] ? (*(vvirtual**)(hl_vfields(r3)[0])) : (vvirtual*)hl_dyn_getp(r3->value,128977169/*left*/,&t$vrt_d41295c);
	if( r5 == NULL ) hl_null_access();
	r12 = hl_vfields(r5)[1] ? (*(int*)(hl_vfields(r5)[1])) : (int)hl_dyn_geti(r5->value,-469011757/*start*/,&t$_i32);
	r10 = r7 - r12;
	r8 = r8 - r10;
	r0->currentLoc = r8;
	r9 = true;
	r6 = r9;
	label$8aebce3_9_97:
	if( !r6 ) goto label$8aebce3_9_108;
	r8 = r0->currentLoc;
	r5 = hl_vfields(r3)[2] ? (*(vvirtual**)(hl_vfields(r3)[2])) : (vvirtual*)hl_dyn_getp(r3->value,-379319332/*right*/,&t$vrt_d41295c);
	if( r5 == NULL ) hl_null_access();
	r10 = hl_vfields(r5)[1] ? (*(int*)(hl_vfields(r5)[1])) : (int)hl_dyn_geti(r5->value,-469011757/*start*/,&t$_i32);
	r5 = hl_vfields(r3)[0] ? (*(vvirtual**)(hl_vfields(r3)[0])) : (vvirtual*)hl_dyn_getp(r3->value,128977169/*left*/,&t$vrt_d41295c);
	if( r5 == NULL ) hl_null_access();
	r12 = hl_vfields(r5)[1] ? (*(int*)(hl_vfields(r5)[1])) : (int)hl_dyn_geti(r5->value,-469011757/*start*/,&t$_i32);
	r10 = r10 - r12;
	r8 = r8 + r10;
	r0->currentLoc = r8;
	label$8aebce3_9_108:
	r14 = hl_alloc_virtual(&t$vrt_80c06ee);
	r5 = hl_vfields(r3)[2] ? (*(vvirtual**)(hl_vfields(r3)[2])) : (vvirtual*)hl_dyn_getp(r3->value,-379319332/*right*/,&t$vrt_d41295c);
	if( r5 == NULL ) hl_null_access();
	r8 = hl_vfields(r5)[0] ? (*(int*)(hl_vfields(r5)[0])) : (int)hl_dyn_geti(r5->value,5047259/*end*/,&t$_i32);
	if( hl_vfields(r14)[1] ) *(int*)(hl_vfields(r14)[1]) = (int)r8; else hl_dyn_seti(r14->value,5393365/*len*/,&t$_i32,r8);
	if( hl_vfields(r14)[0] ) *(int*)(hl_vfields(r14)[0]) = (int)r4; else hl_dyn_seti(r14->value,128977169/*left*/,&t$_i32,r4);
	r5 = hl_vfields(r3)[2] ? (*(vvirtual**)(hl_vfields(r3)[2])) : (vvirtual*)hl_dyn_getp(r3->value,-379319332/*right*/,&t$vrt_d41295c);
	if( r5 == NULL ) hl_null_access();
	r8 = hl_vfields(r5)[1] ? (*(int*)(hl_vfields(r5)[1])) : (int)hl_dyn_geti(r5->value,-469011757/*start*/,&t$_i32);
	if( hl_vfields(r14)[2] ) *(int*)(hl_vfields(r14)[2]) = (int)r8; else hl_dyn_seti(r14->value,-379319332/*right*/,&t$_i32,r8);
	return r14;
}

int kha_audio2_ogg_vorbis_VorbisDecodeState_getSampleNumber(kha__audio2__ogg__vorbis__VorbisDecodeState r0,vclosure* r1,int r2) {
	String r15, r17;
	kha__audio2__ogg__vorbis__data__ProbedPage r28;
	vvirtual *r16, *r18;
	venum *r8, *r14;
	bool r7, r10;
	hl__types__ArrayBytes_Int r20, r22;
	kha__audio2__ogg__vorbis__data__ReaderError r13;
	haxe__io__Input r26;
	vdynamic *r12, *r29;
	vbyte *r21;
	int r3, r5, r6, r9, r11, r19, r23, r24, r25, r27;
	r3 = r0->inputPosition;
	r6 = 65536;
	if( ((unsigned)r2) < ((unsigned)r6) ) goto label$8aebce3_10_10;
	r6 = 65536;
	r5 = r2 - r6;
	r6 = r0->firstAudioPageOffset;
	if( ((unsigned)r5) < ((unsigned)r6) ) goto label$8aebce3_10_10;
	r6 = 65536;
	r5 = r2 - r6;
	goto label$8aebce3_10_11;
	label$8aebce3_10_10:
	r5 = r0->firstAudioPageOffset;
	label$8aebce3_10_11:
	if( r1 == NULL ) hl_null_access();
	r0->inputPosition = r5;
	r1->hasValue ? ((void (*)(vdynamic*,int))r1->fun)((vdynamic*)r1->value,r5) : ((void (*)(int))r1->fun)(r5);
	r6 = 0;
	r7 = false;
	r8 = kha_audio2_ogg_vorbis_VorbisDecodeState_findPage(r0,r1,r2);
	if( r8 == NULL ) hl_null_access();
	r9 = HL__ENUM_INDEX__(r8);
	switch(r9) {
		default:
			goto label$8aebce3_10_42;
		case 0:
			r9 = ((kha_audio2_ogg_vorbis__VorbisDecodeState_FindPageResult_Found*)r8)->p0;
			r10 = ((kha_audio2_ogg_vorbis__VorbisDecodeState_FindPageResult_Found*)r8)->p1;
			r6 = r9;
			r7 = r10;
			goto label$8aebce3_10_42;
		case 1:
			r13 = (kha__audio2__ogg__vorbis__data__ReaderError)hl_alloc_obj(&t$kha_audio2_ogg_vorbis_data_ReaderError);
			r14 = (venum*)g$04ccacc;
			r15 = NULL;
			r16 = hl_alloc_virtual(&t$vrt_329ffa8);
			r17 = (String)s$2f4cf08;
			if( hl_vfields(r16)[1] ) *(String*)(hl_vfields(r16)[1]) = (String)r17; else hl_dyn_setp(r16->value,37969014/*fileName*/,&t$String,r17);
			r9 = 519;
			if( hl_vfields(r16)[2] ) *(int*)(hl_vfields(r16)[2]) = (int)r9; else hl_dyn_seti(r16->value,371360620/*lineNumber*/,&t$_i32,r9);
			r17 = (String)s$0fb2b67;
			if( hl_vfields(r16)[0] ) *(String*)(hl_vfields(r16)[0]) = (String)r17; else hl_dyn_setp(r16->value,-63073762/*className*/,&t$String,r17);
			r17 = (String)s$getSampleNumber;
			if( hl_vfields(r16)[3] ) *(String*)(hl_vfields(r16)[3]) = (String)r17; else hl_dyn_setp(r16->value,302979532/*methodName*/,&t$String,r17);
			r18 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r16);
			kha_audio2_ogg_vorbis_data_ReaderError_new(r13,r14,r15,r18);
			r12 = haxe_Exception_thrown(((vdynamic*)r13));
			hl_throw((vdynamic*)r12);
	}
	label$8aebce3_10_42:
	r9 = r0->inputPosition;
	label$8aebce3_10_43:
	if( r7 ) goto label$8aebce3_10_65;
	if( r1 == NULL ) hl_null_access();
	r0->inputPosition = r6;
	r1->hasValue ? ((void (*)(vdynamic*,int))r1->fun)((vdynamic*)r1->value,r6) : ((void (*)(int))r1->fun)(r6);
	r8 = kha_audio2_ogg_vorbis_VorbisDecodeState_findPage(r0,r1,r2);
	if( r8 == NULL ) hl_null_access();
	r11 = HL__ENUM_INDEX__(r8);
	switch(r11) {
		default:
			goto label$8aebce3_10_59;
		case 0:
			r11 = ((kha_audio2_ogg_vorbis__VorbisDecodeState_FindPageResult_Found*)r8)->p0;
			r10 = ((kha_audio2_ogg_vorbis__VorbisDecodeState_FindPageResult_Found*)r8)->p1;
			r6 = r11;
			r7 = r10;
			goto label$8aebce3_10_59;
		case 1:
			goto label$8aebce3_10_65;
	}
	label$8aebce3_10_59:
	r19 = 1;
	r11 = r9 + r19;
	r5 = r11;
	r11 = r0->inputPosition;
	r9 = r11;
	goto label$8aebce3_10_43;
	label$8aebce3_10_65:
	if( r1 == NULL ) hl_null_access();
	r0->inputPosition = r9;
	r1->hasValue ? ((void (*)(vdynamic*,int))r1->fun)((vdynamic*)r1->value,r9) : ((void (*)(int))r1->fun)(r9);
	r11 = r0->inputPosition;
	r19 = 6;
	r11 = r11 + r19;
	r0->inputPosition = r11;
	r11 = 0;
	r21 = hl_alloc_bytes(r11);
	r11 = 0;
	r11 = 0;
	r20 = hl_types_ArrayBase_allocI32(r21,r11);
	if( r20 == NULL ) hl_null_access();
	r11 = 5;
	r12 = NULL;
	r19 = (int)hl_dyn_casti(&r12,&t$_dyn,&t$_i32);
	r23 = r20->length;
	if( ((unsigned)r11) < ((unsigned)r23) ) goto label$8aebce3_10_84;
	hl_types_ArrayBytes_Int___expand(r20,r11);
	label$8aebce3_10_84:
	r21 = r20->bytes;
	r23 = 2;
	r23 = r11 << r23;
	*(int*)(r21 + r23) = r19;
	r22 = r20;
	r11 = 0;
	r19 = 6;
	label$8aebce3_10_91:
	if( r11 >= r19 ) goto label$8aebce3_10_107;
	r23 = r11;
	++r11;
	if( r22 == NULL ) hl_null_access();
	r26 = r0->input;
	if( r26 == NULL ) hl_null_access();
	r25 = ((int (*)(haxe__io__Input))r26->$type->vobj_proto[0])(r26);
	r27 = r22->length;
	if( ((unsigned)r23) < ((unsigned)r27) ) goto label$8aebce3_10_102;
	hl_types_ArrayBytes_Int___expand(r22,r23);
	label$8aebce3_10_102:
	r21 = r22->bytes;
	r27 = 2;
	r27 = r23 << r27;
	*(int*)(r21 + r27) = r25;
	goto label$8aebce3_10_91;
	label$8aebce3_10_107:
	r11 = r0->inputPosition;
	r19 = 4;
	r11 = r11 + r19;
	r0->inputPosition = r11;
	r26 = r0->input;
	if( r26 == NULL ) hl_null_access();
	r11 = haxe_io_Input_readInt32(r26);
	r19 = r0->inputPosition;
	r23 = 4;
	r19 = r19 + r23;
	r0->inputPosition = r19;
	r26 = r0->input;
	if( r26 == NULL ) hl_null_access();
	r19 = haxe_io_Input_readInt32(r26);
	r24 = -1;
	if( r11 != r24 ) goto label$8aebce3_10_125;
	r24 = -1;
	if( r19 == r24 ) goto label$8aebce3_10_127;
	label$8aebce3_10_125:
	r24 = 0;
	if( r24 >= r19 ) goto label$8aebce3_10_143;
	label$8aebce3_10_127:
	r13 = (kha__audio2__ogg__vorbis__data__ReaderError)hl_alloc_obj(&t$kha_audio2_ogg_vorbis_data_ReaderError);
	r14 = (venum*)g$04ccacc;
	r15 = NULL;
	r16 = hl_alloc_virtual(&t$vrt_329ffa8);
	r17 = (String)s$2f4cf08;
	if( hl_vfields(r16)[1] ) *(String*)(hl_vfields(r16)[1]) = (String)r17; else hl_dyn_setp(r16->value,37969014/*fileName*/,&t$String,r17);
	r23 = 553;
	if( hl_vfields(r16)[2] ) *(int*)(hl_vfields(r16)[2]) = (int)r23; else hl_dyn_seti(r16->value,371360620/*lineNumber*/,&t$_i32,r23);
	r17 = (String)s$0fb2b67;
	if( hl_vfields(r16)[0] ) *(String*)(hl_vfields(r16)[0]) = (String)r17; else hl_dyn_setp(r16->value,-63073762/*className*/,&t$String,r17);
	r17 = (String)s$getSampleNumber;
	if( hl_vfields(r16)[3] ) *(String*)(hl_vfields(r16)[3]) = (String)r17; else hl_dyn_setp(r16->value,302979532/*methodName*/,&t$String,r17);
	r18 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r16);
	kha_audio2_ogg_vorbis_data_ReaderError_new(r13,r14,r15,r18);
	r12 = haxe_Exception_thrown(((vdynamic*)r13));
	hl_throw((vdynamic*)r12);
	label$8aebce3_10_143:
	r28 = (kha__audio2__ogg__vorbis__data__ProbedPage)hl_alloc_obj(&t$kha_audio2_ogg_vorbis_data_ProbedPage);
	kha_audio2_ogg_vorbis_data_ProbedPage_new(r28);
	r0->pLast = r28;
	r28 = r0->pLast;
	if( r28 == NULL ) hl_null_access();
	r28->pageStart = r9;
	r28 = r0->pLast;
	if( r28 == NULL ) hl_null_access();
	r28->pageEnd = r6;
	r28 = r0->pLast;
	if( r28 == NULL ) hl_null_access();
	r29 = hl_alloc_dynamic(&t$_i32);
	r29->v.i = r11;
	r28->lastDecodedSample = r29;
	r28 = r0->pLast;
	if( r28 == NULL ) hl_null_access();
	r29 = NULL;
	r28->firstDecodedSample = r29;
	r28 = r0->pLast;
	if( r28 == NULL ) hl_null_access();
	r28->afterPreviousPageStart = r5;
	if( r1 == NULL ) hl_null_access();
	r0->inputPosition = r3;
	r1->hasValue ? ((void (*)(vdynamic*,int))r1->fun)((vdynamic*)r1->value,r3) : ((void (*)(int))r1->fun)(r3);
	return r11;
}

venum* kha_audio2_ogg_vorbis_VorbisDecodeState_findPage(kha__audio2__ogg__vorbis__VorbisDecodeState r0,vclosure* r1,int r2) {
	kha__audio2__ogg__tools__$Crc32 r22;
	venum *r11;
	bool r5, r12, r13;
	hl__types__ArrayBytes_Int r14, r16, r18;
	haxe__io__$Eof r30;
	haxe__Exception r29;
	haxe__io__Input r8;
	vdynamic *r3, *r28;
	vbyte *r15;
	int r6, r7, r9, r10, r17, r19, r20, r21, r23, r24, r25, r26, r27;
	hl_trap_ctx trap$0;
	hl_trap_ctx trap$1;
	hl_trap(trap$0,r3,label$8aebce3_11_707);
	label$8aebce3_11_1:
	r5 = true;
	if( !r5 ) goto label$8aebce3_11_705;
	r6 = r0->inputPosition;
	r7 = 1;
	r6 = r6 + r7;
	r0->inputPosition = r6;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r6 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r9 = 79;
	if( r6 != r9 ) goto label$8aebce3_11_704;
	r7 = r0->inputPosition;
	r10 = 25;
	r9 = r7 - r10;
	if( r2 >= r9 ) goto label$8aebce3_11_20;
	r11 = (venum*)g$af6e6b5;
	hl_endtrap(trap$0);
	return r11;
	label$8aebce3_11_20:
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r9 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r10 = 103;
	if( r9 != r10 ) goto label$8aebce3_11_42;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r9 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r10 = 103;
	if( r9 != r10 ) goto label$8aebce3_11_40;
	r12 = false;
	goto label$8aebce3_11_41;
	label$8aebce3_11_40:
	r12 = true;
	label$8aebce3_11_41:
	goto label$8aebce3_11_43;
	label$8aebce3_11_42:
	r12 = true;
	label$8aebce3_11_43:
	if( r12 ) goto label$8aebce3_11_57;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r9 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r10 = 83;
	if( r9 != r10 ) goto label$8aebce3_11_55;
	r13 = false;
	goto label$8aebce3_11_56;
	label$8aebce3_11_55:
	r13 = true;
	label$8aebce3_11_56:
	goto label$8aebce3_11_58;
	label$8aebce3_11_57:
	r13 = true;
	label$8aebce3_11_58:
	if( !r13 ) goto label$8aebce3_11_60;
	goto label$8aebce3_11_1;
	label$8aebce3_11_60:
	r9 = 0;
	r15 = hl_alloc_bytes(r9);
	r9 = 0;
	r9 = 0;
	r14 = hl_types_ArrayBase_allocI32(r15,r9);
	if( r14 == NULL ) hl_null_access();
	r9 = 26;
	r3 = NULL;
	r10 = (int)hl_dyn_casti(&r3,&t$_dyn,&t$_i32);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_72;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_72:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r16 = r14;
	r9 = 0;
	r10 = 79;
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_82;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_82:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = 1;
	r10 = 103;
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_91;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_91:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = 2;
	r10 = 103;
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_100;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_100:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = 3;
	r10 = 83;
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_109;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_109:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 4;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_124;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_124:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 5;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_139;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_139:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 6;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_154;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_154:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 7;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_169;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_169:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 8;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_184;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_184:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 9;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_199;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_199:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 10;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_214;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_214:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 11;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_229;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_229:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 12;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_244;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_244:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 13;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_259;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_259:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 14;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_274;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_274:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 15;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_289;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_289:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 16;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_304;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_304:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 17;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_319;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_319:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 18;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_334;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_334:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 19;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_349;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_349:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 20;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_364;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_364:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 21;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_379;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_379:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 22;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_394;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_394:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 23;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_409;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_409:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 24;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_424;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_424:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 25;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_439;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_439:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = r0->inputPosition;
	r10 = 1;
	r9 = r9 + r10;
	r0->inputPosition = r9;
	r9 = 26;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r10 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r17 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r17) ) goto label$8aebce3_11_454;
	hl_types_ArrayBytes_Int___expand(r14,r9);
	label$8aebce3_11_454:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r9 << r17;
	*(int*)(r15 + r17) = r10;
	r9 = 4;
	r10 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r10) ) goto label$8aebce3_11_463;
	r9 = 0;
	goto label$8aebce3_11_467;
	label$8aebce3_11_463:
	r15 = r14->bytes;
	r10 = 2;
	r10 = r9 << r10;
	r9 = *(int*)(r15 + r10);
	label$8aebce3_11_467:
	r10 = 0;
	if( r9 == r10 ) goto label$8aebce3_11_473;
	if( r1 == NULL ) hl_null_access();
	r0->inputPosition = r7;
	r1->hasValue ? ((void (*)(vdynamic*,int))r1->fun)((vdynamic*)r1->value,r7) : ((void (*)(int))r1->fun)(r7);
	goto label$8aebce3_11_1;
	label$8aebce3_11_473:
	r9 = 22;
	r10 = r14->length;
	if( ((unsigned)r9) < ((unsigned)r10) ) goto label$8aebce3_11_478;
	r9 = 0;
	goto label$8aebce3_11_482;
	label$8aebce3_11_478:
	r15 = r14->bytes;
	r10 = 2;
	r10 = r9 << r10;
	r9 = *(int*)(r15 + r10);
	label$8aebce3_11_482:
	r10 = 23;
	r17 = r14->length;
	if( ((unsigned)r10) < ((unsigned)r17) ) goto label$8aebce3_11_487;
	r10 = 0;
	goto label$8aebce3_11_491;
	label$8aebce3_11_487:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r10 << r17;
	r10 = *(int*)(r15 + r17);
	label$8aebce3_11_491:
	r17 = 8;
	r10 = r10 << r17;
	r9 = r9 + r10;
	r10 = 24;
	r17 = r14->length;
	if( ((unsigned)r10) < ((unsigned)r17) ) goto label$8aebce3_11_499;
	r10 = 0;
	goto label$8aebce3_11_503;
	label$8aebce3_11_499:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r10 << r17;
	r10 = *(int*)(r15 + r17);
	label$8aebce3_11_503:
	r17 = 16;
	r10 = r10 << r17;
	r9 = r9 + r10;
	r10 = 25;
	r17 = r14->length;
	if( ((unsigned)r10) < ((unsigned)r17) ) goto label$8aebce3_11_511;
	r10 = 0;
	goto label$8aebce3_11_515;
	label$8aebce3_11_511:
	r15 = r14->bytes;
	r17 = 2;
	r17 = r10 << r17;
	r10 = *(int*)(r15 + r17);
	label$8aebce3_11_515:
	r17 = 24;
	r10 = r10 << r17;
	r9 = r9 + r10;
	r10 = 22;
	r17 = 0;
	r19 = r14->length;
	if( ((unsigned)r10) < ((unsigned)r19) ) goto label$8aebce3_11_523;
	hl_types_ArrayBytes_Int___expand(r14,r10);
	label$8aebce3_11_523:
	r15 = r14->bytes;
	r19 = 2;
	r19 = r10 << r19;
	*(int*)(r15 + r19) = r17;
	r10 = 23;
	r17 = 0;
	r19 = r14->length;
	if( ((unsigned)r10) < ((unsigned)r19) ) goto label$8aebce3_11_532;
	hl_types_ArrayBytes_Int___expand(r14,r10);
	label$8aebce3_11_532:
	r15 = r14->bytes;
	r19 = 2;
	r19 = r10 << r19;
	*(int*)(r15 + r19) = r17;
	r10 = 24;
	r17 = 0;
	r19 = r14->length;
	if( ((unsigned)r10) < ((unsigned)r19) ) goto label$8aebce3_11_541;
	hl_types_ArrayBytes_Int___expand(r14,r10);
	label$8aebce3_11_541:
	r15 = r14->bytes;
	r19 = 2;
	r19 = r10 << r19;
	*(int*)(r15 + r19) = r17;
	r10 = 25;
	r17 = 0;
	r19 = r14->length;
	if( ((unsigned)r10) < ((unsigned)r19) ) goto label$8aebce3_11_550;
	hl_types_ArrayBytes_Int___expand(r14,r10);
	label$8aebce3_11_550:
	r15 = r14->bytes;
	r19 = 2;
	r19 = r10 << r19;
	*(int*)(r15 + r19) = r17;
	r10 = 0;
	r17 = 0;
	label$8aebce3_11_556:
	r20 = 27;
	if( r17 >= r20 ) goto label$8aebce3_11_589;
	r19 = r17;
	++r17;
	r21 = 8;
	r20 = r10 << r21;
	r22 = (kha__audio2__ogg__tools__$Crc32)g$_kha_audio2_ogg_tools_Crc32;
	r18 = r22->table;
	if( r18 == NULL ) hl_null_access();
	if( r16 == NULL ) hl_null_access();
	r23 = r16->length;
	if( ((unsigned)r19) < ((unsigned)r23) ) goto label$8aebce3_11_571;
	r21 = 0;
	goto label$8aebce3_11_575;
	label$8aebce3_11_571:
	r15 = r16->bytes;
	r23 = 2;
	r23 = r19 << r23;
	r21 = *(int*)(r15 + r23);
	label$8aebce3_11_575:
	r24 = 24;
	r23 = ((unsigned)r10) >> r24;
	r21 = r21 ^ r23;
	r23 = r18->length;
	if( ((unsigned)r21) < ((unsigned)r23) ) goto label$8aebce3_11_582;
	r21 = 0;
	goto label$8aebce3_11_586;
	label$8aebce3_11_582:
	r15 = r18->bytes;
	r23 = 2;
	r23 = r21 << r23;
	r21 = *(int*)(r15 + r23);
	label$8aebce3_11_586:
	r20 = r20 ^ r21;
	r10 = r20;
	goto label$8aebce3_11_556;
	label$8aebce3_11_589:
	r17 = 0;
	hl_trap(trap$1,r3,label$8aebce3_11_666);
	r19 = 0;
	if( r16 == NULL ) hl_null_access();
	r20 = 26;
	r21 = r16->length;
	if( ((unsigned)r20) < ((unsigned)r21) ) goto label$8aebce3_11_598;
	r20 = 0;
	goto label$8aebce3_11_602;
	label$8aebce3_11_598:
	r15 = r16->bytes;
	r21 = 2;
	r21 = r20 << r21;
	r20 = *(int*)(r15 + r21);
	label$8aebce3_11_602:
	if( r19 >= r20 ) goto label$8aebce3_11_633;
	++r19;
	r23 = r0->inputPosition;
	r24 = 1;
	r23 = r23 + r24;
	r0->inputPosition = r23;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r23 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r25 = 8;
	r24 = r10 << r25;
	r22 = (kha__audio2__ogg__tools__$Crc32)g$_kha_audio2_ogg_tools_Crc32;
	r18 = r22->table;
	if( r18 == NULL ) hl_null_access();
	r27 = 24;
	r26 = ((unsigned)r10) >> r27;
	r25 = r23 ^ r26;
	r26 = r18->length;
	if( ((unsigned)r25) < ((unsigned)r26) ) goto label$8aebce3_11_624;
	r25 = 0;
	goto label$8aebce3_11_628;
	label$8aebce3_11_624:
	r15 = r18->bytes;
	r26 = 2;
	r26 = r25 << r26;
	r25 = *(int*)(r15 + r26);
	label$8aebce3_11_628:
	r24 = r24 ^ r25;
	r10 = r24;
	r24 = r17 + r23;
	r17 = r24;
	goto label$8aebce3_11_602;
	label$8aebce3_11_633:
	r19 = 0;
	r20 = r17;
	label$8aebce3_11_635:
	if( r19 >= r20 ) goto label$8aebce3_11_664;
	++r19;
	r23 = r0->inputPosition;
	r24 = 1;
	r23 = r23 + r24;
	r0->inputPosition = r23;
	r8 = r0->input;
	if( r8 == NULL ) hl_null_access();
	r23 = ((int (*)(haxe__io__Input))r8->$type->vobj_proto[0])(r8);
	r25 = 8;
	r24 = r10 << r25;
	r22 = (kha__audio2__ogg__tools__$Crc32)g$_kha_audio2_ogg_tools_Crc32;
	r18 = r22->table;
	if( r18 == NULL ) hl_null_access();
	r27 = 24;
	r26 = ((unsigned)r10) >> r27;
	r25 = r23 ^ r26;
	r26 = r18->length;
	if( ((unsigned)r25) < ((unsigned)r26) ) goto label$8aebce3_11_657;
	r25 = 0;
	goto label$8aebce3_11_661;
	label$8aebce3_11_657:
	r15 = r18->bytes;
	r26 = 2;
	r26 = r25 << r26;
	r25 = *(int*)(r15 + r26);
	label$8aebce3_11_661:
	r24 = r24 ^ r25;
	r10 = r24;
	goto label$8aebce3_11_635;
	label$8aebce3_11_664:
	hl_endtrap(trap$1);
	goto label$8aebce3_11_677;
	label$8aebce3_11_666:
	r28 = NULL;
	r29 = haxe_Exception_caught(r3);
	if( r29 == NULL ) hl_null_access();
	r28 = ((vdynamic* (*)(haxe__Exception))r29->$type->vobj_proto[0])(r29);
	r30 = (haxe__io__$Eof)g$_haxe_io_Eof;
	r13 = Std_isOfType(r28,((vdynamic*)r30));
	if( !r13 ) goto label$8aebce3_11_676;
	r11 = (venum*)g$af6e6b5;
	hl_endtrap(trap$0);
	return r11;
	label$8aebce3_11_676:
	hl_rethrow((vdynamic*)r3);
	label$8aebce3_11_677:
	if( r10 != r9 ) goto label$8aebce3_11_704;
	r19 = r0->inputPosition;
	if( r1 == NULL ) hl_null_access();
	r21 = 1;
	r20 = r7 - r21;
	r0->inputPosition = r20;
	r1->hasValue ? ((void (*)(vdynamic*,int))r1->fun)((vdynamic*)r1->value,r20) : ((void (*)(int))r1->fun)(r20);
	if( r16 == NULL ) hl_null_access();
	r21 = 5;
	r23 = r16->length;
	if( ((unsigned)r21) < ((unsigned)r23) ) goto label$8aebce3_11_690;
	r21 = 0;
	goto label$8aebce3_11_694;
	label$8aebce3_11_690:
	r15 = r16->bytes;
	r23 = 2;
	r23 = r21 << r23;
	r21 = *(int*)(r15 + r23);
	label$8aebce3_11_694:
	r23 = 4;
	r21 = r21 & r23;
	r23 = 0;
	if( r21 != r23 ) goto label$8aebce3_11_700;
	r13 = false;
	goto label$8aebce3_11_701;
	label$8aebce3_11_700:
	r13 = true;
	label$8aebce3_11_701:
	r11 = hl_alloc_enum(&t$kha_audio2_ogg_vorbis__VorbisDecodeState_FindPageResult,0);
	((kha_audio2_ogg_vorbis__VorbisDecodeState_FindPageResult_Found*)r11)->p0 = r19;
	((kha_audio2_ogg_vorbis__VorbisDecodeState_FindPageResult_Found*)r11)->p1 = r13;
	hl_endtrap(trap$0);
	return r11;
	label$8aebce3_11_704:
	goto label$8aebce3_11_1;
	label$8aebce3_11_705:
	hl_endtrap(trap$0);
	goto label$8aebce3_11_717;
	label$8aebce3_11_707:
	r28 = NULL;
	r29 = haxe_Exception_caught(r3);
	if( r29 == NULL ) hl_null_access();
	r28 = ((vdynamic* (*)(haxe__Exception))r29->$type->vobj_proto[0])(r29);
	r30 = (haxe__io__$Eof)g$_haxe_io_Eof;
	r5 = Std_isOfType(r28,((vdynamic*)r30));
	if( !r5 ) goto label$8aebce3_11_716;
	r11 = (venum*)g$af6e6b5;
	return r11;
	label$8aebce3_11_716:
	hl_rethrow((vdynamic*)r3);
	label$8aebce3_11_717:
	r11 = NULL;
	return r11;
}

int kha_audio2_ogg_vorbis_VorbisDecodeState_decodeScalarRaw(kha__audio2__ogg__vorbis__VorbisDecodeState r0,kha__audio2__ogg__vorbis__data__Codebook r1) {
	String r20, r22;
	vvirtual *r21, *r23;
	venum *r19;
	bool r6;
	hl__types__ArrayBytes_Int r3, r4, r5, r9, r10;
	kha__audio2__ogg__vorbis__data__ReaderError r18;
	vbyte *r16;
	int r7, r8, r11, r12, r13, r14, r15, r17;
	kha_audio2_ogg_vorbis_VorbisDecodeState_prepHuffman(r0);
	if( r1 == NULL ) hl_null_access();
	r3 = r1->codewordLengths;
	r4 = r1->codewords;
	r5 = r1->sortedCodewords;
	r7 = r1->entries;
	r8 = 8;
	if( r8 >= r7 ) goto label$8aebce3_12_14;
	r10 = NULL;
	if( r5 != r10 ) goto label$8aebce3_12_12;
	r6 = false;
	goto label$8aebce3_12_13;
	label$8aebce3_12_12:
	r6 = true;
	label$8aebce3_12_13:
	goto label$8aebce3_12_19;
	label$8aebce3_12_14:
	r10 = NULL;
	if( r4 != r10 ) goto label$8aebce3_12_18;
	r6 = false;
	goto label$8aebce3_12_19;
	label$8aebce3_12_18:
	r6 = true;
	label$8aebce3_12_19:
	if( !r6 ) goto label$8aebce3_12_130;
	r7 = r0->acc;
	r11 = -1431655766;
	r8 = r7 & r11;
	r11 = 1;
	r8 = ((unsigned)r8) >> r11;
	r12 = 1431655765;
	r11 = r7 & r12;
	r12 = 1;
	r11 = r11 << r12;
	r8 = r8 | r11;
	r7 = r8;
	r11 = -858993460;
	r8 = r8 & r11;
	r11 = 2;
	r8 = ((unsigned)r8) >> r11;
	r12 = 858993459;
	r11 = r7 & r12;
	r12 = 2;
	r11 = r11 << r12;
	r8 = r8 | r11;
	r7 = r8;
	r11 = -252645136;
	r8 = r8 & r11;
	r11 = 4;
	r8 = ((unsigned)r8) >> r11;
	r12 = 252645135;
	r11 = r7 & r12;
	r12 = 4;
	r11 = r11 << r12;
	r8 = r8 | r11;
	r7 = r8;
	r11 = -16711936;
	r8 = r8 & r11;
	r11 = 8;
	r8 = ((unsigned)r8) >> r11;
	r12 = 16711935;
	r11 = r7 & r12;
	r12 = 8;
	r11 = r11 << r12;
	r8 = r8 | r11;
	r7 = r8;
	r11 = 16;
	r8 = ((unsigned)r8) >> r11;
	r12 = 16;
	r11 = r7 << r12;
	r8 = r8 | r11;
	r11 = 0;
	r12 = r1->sortedEntries;
	label$8aebce3_12_68:
	r14 = 1;
	if( r14 >= r12 ) goto label$8aebce3_12_94;
	r15 = 1;
	r14 = r12 >> r15;
	r13 = r11 + r14;
	if( r5 == NULL ) hl_null_access();
	r15 = r5->length;
	if( ((unsigned)r13) < ((unsigned)r15) ) goto label$8aebce3_12_79;
	r14 = 0;
	goto label$8aebce3_12_83;
	label$8aebce3_12_79:
	r16 = r5->bytes;
	r15 = 2;
	r15 = r13 << r15;
	r14 = *(int*)(r16 + r15);
	label$8aebce3_12_83:
	if( ((unsigned)r8) < ((unsigned)r14) ) goto label$8aebce3_12_90;
	r11 = r13;
	r17 = 1;
	r15 = r12 >> r17;
	r14 = r12 - r15;
	r12 = r14;
	goto label$8aebce3_12_93;
	label$8aebce3_12_90:
	r15 = 1;
	r14 = r12 >> r15;
	r12 = r14;
	label$8aebce3_12_93:
	goto label$8aebce3_12_68;
	label$8aebce3_12_94:
	if( r1 == NULL ) hl_null_access();
	r6 = r1->sparse;
	if( r6 ) goto label$8aebce3_12_108;
	r9 = r1->sortedValues;
	if( r9 == NULL ) hl_null_access();
	r14 = r9->length;
	if( ((unsigned)r11) < ((unsigned)r14) ) goto label$8aebce3_12_103;
	r13 = 0;
	goto label$8aebce3_12_107;
	label$8aebce3_12_103:
	r16 = r9->bytes;
	r14 = 2;
	r14 = r11 << r14;
	r13 = *(int*)(r16 + r14);
	label$8aebce3_12_107:
	r11 = r13;
	label$8aebce3_12_108:
	if( r3 == NULL ) hl_null_access();
	r14 = r3->length;
	if( ((unsigned)r11) < ((unsigned)r14) ) goto label$8aebce3_12_113;
	r13 = 0;
	goto label$8aebce3_12_117;
	label$8aebce3_12_113:
	r16 = r3->bytes;
	r14 = 2;
	r14 = r11 << r14;
	r13 = *(int*)(r16 + r14);
	label$8aebce3_12_117:
	r14 = r0->validBits;
	if( r14 < r13 ) goto label$8aebce3_12_126;
	r14 = r0->acc;
	r14 = ((unsigned)r14) >> r13;
	r0->acc = r14;
	r14 = r0->validBits;
	r14 = r14 - r13;
	r0->validBits = r14;
	return r11;
	label$8aebce3_12_126:
	r14 = 0;
	r0->validBits = r14;
	r14 = -1;
	return r14;
	label$8aebce3_12_130:
	r7 = 0;
	r8 = r1->entries;
	label$8aebce3_12_132:
	if( r7 >= r8 ) goto label$8aebce3_12_178;
	r11 = r7;
	++r7;
	if( r3 == NULL ) hl_null_access();
	r13 = r3->length;
	if( ((unsigned)r11) < ((unsigned)r13) ) goto label$8aebce3_12_141;
	r12 = 0;
	goto label$8aebce3_12_145;
	label$8aebce3_12_141:
	r16 = r3->bytes;
	r13 = 2;
	r13 = r11 << r13;
	r12 = *(int*)(r16 + r13);
	label$8aebce3_12_145:
	r14 = 255;
	if( r12 != r14 ) goto label$8aebce3_12_148;
	goto label$8aebce3_12_132;
	label$8aebce3_12_148:
	if( r4 == NULL ) hl_null_access();
	r14 = r4->length;
	if( ((unsigned)r11) < ((unsigned)r14) ) goto label$8aebce3_12_153;
	r13 = 0;
	goto label$8aebce3_12_157;
	label$8aebce3_12_153:
	r16 = r4->bytes;
	r14 = 2;
	r14 = r11 << r14;
	r13 = *(int*)(r16 + r14);
	label$8aebce3_12_157:
	r14 = r0->acc;
	r15 = 1;
	r15 = r15 << r12;
	r17 = 1;
	r15 = r15 - r17;
	r14 = r14 & r15;
	if( r13 != r14 ) goto label$8aebce3_12_177;
	r13 = r0->validBits;
	if( r13 < r12 ) goto label$8aebce3_12_173;
	r13 = r0->acc;
	r13 = ((unsigned)r13) >> r12;
	r0->acc = r13;
	r13 = r0->validBits;
	r13 = r13 - r12;
	r0->validBits = r13;
	return r11;
	label$8aebce3_12_173:
	r13 = 0;
	r0->validBits = r13;
	r13 = -1;
	return r13;
	label$8aebce3_12_177:
	goto label$8aebce3_12_132;
	label$8aebce3_12_178:
	r18 = (kha__audio2__ogg__vorbis__data__ReaderError)hl_alloc_obj(&t$kha_audio2_ogg_vorbis_data_ReaderError);
	r19 = (venum*)g$d3e38e8;
	r20 = NULL;
	r21 = hl_alloc_virtual(&t$vrt_329ffa8);
	r22 = (String)s$2f4cf08;
	if( hl_vfields(r21)[1] ) *(String*)(hl_vfields(r21)[1]) = (String)r22; else hl_dyn_setp(r21->value,37969014/*fileName*/,&t$String,r22);
	r7 = 847;
	if( hl_vfields(r21)[2] ) *(int*)(hl_vfields(r21)[2]) = (int)r7; else hl_dyn_seti(r21->value,371360620/*lineNumber*/,&t$_i32,r7);
	r22 = (String)s$0fb2b67;
	if( hl_vfields(r21)[0] ) *(String*)(hl_vfields(r21)[0]) = (String)r22; else hl_dyn_setp(r21->value,-63073762/*className*/,&t$String,r22);
	r22 = (String)s$decodeScalarRaw;
	if( hl_vfields(r21)[3] ) *(String*)(hl_vfields(r21)[3]) = (String)r22; else hl_dyn_setp(r21->value,302979532/*methodName*/,&t$String,r22);
	r23 = hl_to_virtual(&t$vrt_eaa6a3b,(vdynamic*)r21);
	kha_audio2_ogg_vorbis_data_ReaderError_new(r18,r19,r20,r23);
	r0->error = r18;
	r7 = 0;
	r0->validBits = r7;
	r7 = -1;
	return r7;
}

void kha_audio2_ogg_vorbis_VorbisDecodeState_new(kha__audio2__ogg__vorbis__VorbisDecodeState r0,haxe__io__Input r1) {
	bool r3;
	kha__audio2__ogg__vorbis__data__Page r4;
	int r2;
	r2 = 0;
	r0->nextSeg = r2;
	r3 = false;
	r0->firstDecode = r3;
	r2 = 0;
	r0->bytesInSeg = r2;
	r2 = 0;
	r0->validBits = r2;
	r0->input = r1;
	r2 = 0;
	r0->inputPosition = r2;
	r4 = (kha__audio2__ogg__vorbis__data__Page)hl_alloc_obj(&t$kha_audio2_ogg_vorbis_data_Page);
	kha_audio2_ogg_vorbis_data_Page_new(r4);
	r0->page = r4;
	kha_audio2_ogg_tools_Crc32_init();
	return;
}

