// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <kha/_Assets/FontList.h>
#include <hl/types/ArrayBytes_Int.h>
#include <hl/types/ArrayObj.h>
extern hl_type t$vrt_a7c0bb9;
extern String s$font_default;
extern hl_type t$String;
#include <hl/natives.h>
hl__types__ArrayBytes_Int hl_types_ArrayBase_allocI32(vbyte*,int);
extern hl_type t$hl_types_ArrayBytes_Int;
extern String s$data_font_default_ttf;
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
extern hl_type t$hl_types_ArrayObj;
extern String s$font;

void kha__Assets_FontList_new(kha___Assets__FontList r0) {
	String r2;
	hl__types__ArrayObj r8;
	vvirtual *r1;
	hl_type *r10;
	kha__Kravur r11;
	hl__types__ArrayBytes_Int r3;
	varray *r9;
	int r5, r6, r7;
	vbyte *r4;
	r1 = hl_alloc_virtual(&t$vrt_a7c0bb9);
	r2 = (String)s$font_default;
	if( hl_vfields(r1)[2] ) *(String*)(hl_vfields(r1)[2]) = (String)r2; else hl_dyn_setp(r1->value,150958933/*name*/,&t$String,r2);
	r5 = 4;
	r4 = hl_alloc_bytes(r5);
	r5 = 0;
	r6 = 1;
	r7 = 2;
	r7 = r5 << r7;
	*(int*)(r4 + r7) = r6;
	++r5;
	r5 = 1;
	r3 = hl_types_ArrayBase_allocI32(r4,r5);
	if( hl_vfields(r1)[0] ) *(hl__types__ArrayBytes_Int*)(hl_vfields(r1)[0]) = (hl__types__ArrayBytes_Int)r3; else hl_dyn_setp(r1->value,78652372/*file_sizes*/,&t$hl_types_ArrayBytes_Int,r3);
	r10 = &t$String;
	r5 = 1;
	r9 = hl_alloc_array(r10,r5);
	r2 = (String)s$data_font_default_ttf;
	r5 = 0;
	((String*)(r9 + 1))[r5] = r2;
	r8 = hl_types_ArrayObj_alloc(r9);
	if( hl_vfields(r1)[1] ) *(hl__types__ArrayObj*)(hl_vfields(r1)[1]) = (hl__types__ArrayObj)r8; else hl_dyn_setp(r1->value,10018423/*files*/,&t$hl_types_ArrayObj,r8);
	r2 = (String)s$font;
	if( hl_vfields(r1)[3] ) *(String*)(hl_vfields(r1)[3]) = (String)r2; else hl_dyn_setp(r1->value,218690500/*type*/,&t$String,r2);
	r0->font_defaultDescription = ((vdynamic*)r1);
	r11 = NULL;
	r0->font_default = r11;
	return;
}

