package arm.node;

@:access(armory.logicnode.LogicNode)@:keep class Addplayer extends armory.logicnode.LogicTree {

	var functionNodes:Map<String, armory.logicnode.FunctionNode>;

	var functionOutputNodes:Map<String, armory.logicnode.FunctionOutputNode>;

	public function new() {
		super();
		this.functionNodes = new Map();
		this.functionOutputNodes = new Map();
		notifyOnAdd(add);
	}

	override public function add() {
		var _LoopBreak = new armory.logicnode.LoopBreakNode(this);
		_LoopBreak.preallocInputs(1);
		_LoopBreak.preallocOutputs(0);
		var _RemoveObject = new armory.logicnode.RemoveObjectNode(this);
		_RemoveObject.preallocInputs(4);
		_RemoveObject.preallocOutputs(1);
		var _SetObjectRotation = new armory.logicnode.SetRotationNode(this);
		_SetObjectRotation.property0 = "Euler Angles";
		_SetObjectRotation.preallocInputs(3);
		_SetObjectRotation.preallocOutputs(1);
		var _SetObjectLocation = new armory.logicnode.SetLocationNode(this);
		_SetObjectLocation.preallocInputs(4);
		_SetObjectLocation.preallocOutputs(1);
		var _AddObjecttoCollection_001 = new armory.logicnode.AddObjectToGroupNode(this);
		_AddObjecttoCollection_001.preallocInputs(3);
		_AddObjecttoCollection_001.preallocOutputs(1);
		var _IsTrue = new armory.logicnode.IsTrueNode(this);
		_IsTrue.preallocInputs(2);
		_IsTrue.preallocOutputs(1);
		var _ArrayLoop = new armory.logicnode.ArrayLoopNode(this);
		_ArrayLoop.preallocInputs(2);
		_ArrayLoop.preallocOutputs(4);
		var _SetCameraActive = new armory.logicnode.SetCameraNode(this);
		_SetCameraActive.preallocInputs(2);
		_SetCameraActive.preallocOutputs(1);
		var _SpawnScene = new armory.logicnode.SpawnSceneNode(this);
		_SpawnScene.preallocInputs(3);
		_SpawnScene.preallocOutputs(2);
		var _OnInit = new armory.logicnode.OnInitNode(this);
		_OnInit.preallocInputs(0);
		_OnInit.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_OnInit, _SpawnScene, 0, 0);
		var _Scene = new armory.logicnode.SceneNode(this);
		_Scene.property0 = "player";
		_Scene.preallocInputs(0);
		_Scene.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_Scene, _SpawnScene, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.NullNode(this), _SpawnScene, 0, 2);
		armory.logicnode.LogicNode.addLink(_SpawnScene, _SetCameraActive, 0, 0);
		var _GetObjectChild = new armory.logicnode.GetChildNode(this);
		_GetObjectChild.property0 = "By Name";
		_GetObjectChild.preallocInputs(2);
		_GetObjectChild.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_SpawnScene, _GetObjectChild, 1, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "Camera"), _GetObjectChild, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectChild, _SetCameraActive, 0, 1);
		armory.logicnode.LogicNode.addLink(_SetCameraActive, _ArrayLoop, 0, 0);
		var _GetCollection = new armory.logicnode.GetGroupNode(this);
		_GetCollection.preallocInputs(1);
		_GetCollection.preallocOutputs(1);
		var _ConcatenateString = new armory.logicnode.ConcatenateStringNode(this);
		_ConcatenateString.preallocInputs(2);
		_ConcatenateString.preallocOutputs(1);
		var _GetSceneActive = new armory.logicnode.ActiveSceneNode(this);
		_GetSceneActive.preallocInputs(0);
		_GetSceneActive.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_GetSceneActive, _ConcatenateString, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "_load_zone"), _ConcatenateString, 0, 1);
		armory.logicnode.LogicNode.addLink(_ConcatenateString, _GetCollection, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetCollection, _ArrayLoop, 0, 1);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, new armory.logicnode.IntegerNode(this, 0), 2, 0);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, new armory.logicnode.NullNode(this), 3, 0);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, _IsTrue, 0, 0);
		var _StringContains = new armory.logicnode.ContainsStringNode(this);
		_StringContains.property0 = "Contains";
		_StringContains.preallocInputs(2);
		_StringContains.preallocOutputs(1);
		var _GetObjectName = new armory.logicnode.GetNameNode(this);
		_GetObjectName.preallocInputs(1);
		_GetObjectName.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, _GetObjectName, 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectName, _StringContains, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "spawn"), _StringContains, 0, 1);
		armory.logicnode.LogicNode.addLink(_StringContains, _IsTrue, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsTrue, _AddObjecttoCollection_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "active"), _AddObjecttoCollection_001, 0, 1);
		var _GetObjectParent_002 = new armory.logicnode.GetParentNode(this);
		_GetObjectParent_002.preallocInputs(1);
		_GetObjectParent_002.preallocOutputs(1);
		var _GetObjectParent_003 = new armory.logicnode.GetParentNode(this);
		_GetObjectParent_003.preallocInputs(1);
		_GetObjectParent_003.preallocOutputs(1);
		var _GetCameraActive = new armory.logicnode.ActiveCameraNode(this);
		_GetCameraActive.preallocInputs(0);
		_GetCameraActive.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_GetCameraActive, _GetObjectParent_003, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectParent_003, _GetObjectParent_002, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectParent_002, _AddObjecttoCollection_001, 0, 2);
		armory.logicnode.LogicNode.addLink(_AddObjecttoCollection_001, _SetObjectLocation, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectParent_002, _SetObjectLocation, 0, 1);
		var _GetObjectLocation = new armory.logicnode.GetLocationNode(this);
		_GetObjectLocation.preallocInputs(2);
		_GetObjectLocation.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, _GetObjectLocation, 1, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _GetObjectLocation, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectLocation, _SetObjectLocation, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _SetObjectLocation, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectLocation, _SetObjectRotation, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectParent_002, _SetObjectRotation, 0, 1);
		var _GetObjectRotation = new armory.logicnode.GetRotationNode(this);
		_GetObjectRotation.property0 = "Local";
		_GetObjectRotation.preallocInputs(1);
		_GetObjectRotation.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, _GetObjectRotation, 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectRotation, _SetObjectRotation, 0, 2);
		armory.logicnode.LogicNode.addLink(_SetObjectRotation, _RemoveObject, 0, 0);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, _RemoveObject, 1, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _RemoveObject, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _RemoveObject, 0, 3);
		armory.logicnode.LogicNode.addLink(_RemoveObject, _LoopBreak, 0, 0);
		var _LoopBreak_001 = new armory.logicnode.LoopBreakNode(this);
		_LoopBreak_001.preallocInputs(1);
		_LoopBreak_001.preallocOutputs(0);
		var _RemoveObject_001 = new armory.logicnode.RemoveObjectNode(this);
		_RemoveObject_001.preallocInputs(4);
		_RemoveObject_001.preallocOutputs(1);
		var _SetObjectRotation_001 = new armory.logicnode.SetRotationNode(this);
		_SetObjectRotation_001.property0 = "Euler Angles";
		_SetObjectRotation_001.preallocInputs(3);
		_SetObjectRotation_001.preallocOutputs(1);
		var _SetObjectLocation_001 = new armory.logicnode.SetLocationNode(this);
		_SetObjectLocation_001.preallocInputs(4);
		_SetObjectLocation_001.preallocOutputs(1);
		var _AddObjecttoCollection = new armory.logicnode.AddObjectToGroupNode(this);
		_AddObjecttoCollection.preallocInputs(3);
		_AddObjecttoCollection.preallocOutputs(1);
		var _Print_001 = new armory.logicnode.PrintNode(this);
		_Print_001.preallocInputs(2);
		_Print_001.preallocOutputs(1);
		var _IsTrue_001 = new armory.logicnode.IsTrueNode(this);
		_IsTrue_001.preallocInputs(2);
		_IsTrue_001.preallocOutputs(1);
		var _ArrayLoop_001 = new armory.logicnode.ArrayLoopNode(this);
		_ArrayLoop_001.preallocInputs(2);
		_ArrayLoop_001.preallocOutputs(4);
		var _SpawnObjectByName = new armory.logicnode.SpawnObjectByNameNode(this);
		_SpawnObjectByName.property0 = "player";
		_SpawnObjectByName.preallocInputs(4);
		_SpawnObjectByName.preallocOutputs(2);
		var _Print = new armory.logicnode.PrintNode(this);
		_Print.preallocInputs(2);
		_Print.preallocOutputs(1);
		var _Loop = new armory.logicnode.LoopNode(this);
		_Loop.preallocInputs(3);
		_Loop.preallocOutputs(3);
		var _OnInit_001 = new armory.logicnode.OnInitNode(this);
		_OnInit_001.preallocInputs(0);
		_OnInit_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_OnInit_001, _Loop, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 0), _Loop, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 3), _Loop, 0, 2);
		armory.logicnode.LogicNode.addLink(_Loop, new armory.logicnode.NullNode(this), 2, 0);
		armory.logicnode.LogicNode.addLink(_Loop, _Print, 0, 0);
		armory.logicnode.LogicNode.addLink(_Loop, _Print, 1, 1);
		armory.logicnode.LogicNode.addLink(_Print, _SpawnObjectByName, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "ai"), _SpawnObjectByName, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.NullNode(this), _SpawnObjectByName, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _SpawnObjectByName, 0, 3);
		armory.logicnode.LogicNode.addLink(_SpawnObjectByName, _ArrayLoop_001, 0, 0);
		var _GetCollection_001 = new armory.logicnode.GetGroupNode(this);
		_GetCollection_001.preallocInputs(1);
		_GetCollection_001.preallocOutputs(1);
		var _ConcatenateString_001 = new armory.logicnode.ConcatenateStringNode(this);
		_ConcatenateString_001.preallocInputs(2);
		_ConcatenateString_001.preallocOutputs(1);
		var _GetSceneActive_001 = new armory.logicnode.ActiveSceneNode(this);
		_GetSceneActive_001.preallocInputs(0);
		_GetSceneActive_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_GetSceneActive_001, _ConcatenateString_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "_load_zone"), _ConcatenateString_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_ConcatenateString_001, _GetCollection_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetCollection_001, _ArrayLoop_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_ArrayLoop_001, new armory.logicnode.IntegerNode(this, 0), 2, 0);
		armory.logicnode.LogicNode.addLink(_ArrayLoop_001, new armory.logicnode.NullNode(this), 3, 0);
		armory.logicnode.LogicNode.addLink(_ArrayLoop_001, _IsTrue_001, 0, 0);
		var _StringContains_001 = new armory.logicnode.ContainsStringNode(this);
		_StringContains_001.property0 = "Contains";
		_StringContains_001.preallocInputs(2);
		_StringContains_001.preallocOutputs(1);
		var _GetObjectName_001 = new armory.logicnode.GetNameNode(this);
		_GetObjectName_001.preallocInputs(1);
		_GetObjectName_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_ArrayLoop_001, _GetObjectName_001, 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectName_001, _StringContains_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "spawn"), _StringContains_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_StringContains_001, _IsTrue_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsTrue_001, _Print_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectName_001, _Print_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_Print_001, _AddObjecttoCollection, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "active"), _AddObjecttoCollection, 0, 1);
		armory.logicnode.LogicNode.addLink(_SpawnObjectByName, _AddObjecttoCollection, 1, 2);
		armory.logicnode.LogicNode.addLink(_AddObjecttoCollection, _SetObjectLocation_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_SpawnObjectByName, _SetObjectLocation_001, 1, 1);
		var _GetObjectLocation_001 = new armory.logicnode.GetLocationNode(this);
		_GetObjectLocation_001.preallocInputs(2);
		_GetObjectLocation_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_ArrayLoop_001, _GetObjectLocation_001, 1, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _GetObjectLocation_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectLocation_001, _SetObjectLocation_001, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _SetObjectLocation_001, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectLocation_001, _SetObjectRotation_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_SpawnObjectByName, _SetObjectRotation_001, 1, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.RotationNode(this, 0.0,0.0,0.0,1.0), _SetObjectRotation_001, 0, 2);
		armory.logicnode.LogicNode.addLink(_SetObjectRotation_001, _RemoveObject_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_ArrayLoop_001, _RemoveObject_001, 1, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _RemoveObject_001, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _RemoveObject_001, 0, 3);
		armory.logicnode.LogicNode.addLink(_RemoveObject_001, _LoopBreak_001, 0, 0);
		var _ReadStorage = new armory.logicnode.ReadStorageNode(this);
		_ReadStorage.preallocInputs(2);
		_ReadStorage.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "AIs"), _ReadStorage, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, ""), _ReadStorage, 0, 1);
		armory.logicnode.LogicNode.addLink(_ReadStorage, new armory.logicnode.NullNode(this), 0, 0);
	}
}