package arm.node;

@:access(armory.logicnode.LogicNode)@:keep class AI extends armory.logicnode.LogicTree {

	var functionNodes:Map<String, armory.logicnode.FunctionNode>;

	var functionOutputNodes:Map<String, armory.logicnode.FunctionOutputNode>;

	public function new() {
		super();
		this.functionNodes = new Map();
		this.functionOutputNodes = new Map();
		notifyOnAdd(add);
	}

	override public function add() {
		var _SetCursorState = new armory.logicnode.SetCursorStateNode(this);
		_SetCursorState.property0 = "hide locked";
		_SetCursorState.preallocInputs(2);
		_SetCursorState.preallocOutputs(1);
		var _IsFalse = new armory.logicnode.IsFalseNode(this);
		_IsFalse.preallocInputs(2);
		_IsFalse.preallocOutputs(1);
		var _Mouse = new armory.logicnode.MergedMouseNode(this);
		_Mouse.property0 = "moved";
		_Mouse.property1 = "left";
		_Mouse.preallocInputs(0);
		_Mouse.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_Mouse, new armory.logicnode.BooleanNode(this, false), 1, 0);
		armory.logicnode.LogicNode.addLink(_Mouse, _IsFalse, 0, 0);
		var _GetObjectProperty_001 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_001.preallocInputs(2);
		_GetObjectProperty_001.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "menu"), _GetObjectProperty_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_001, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_001, _IsFalse, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsFalse, _SetCursorState, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _SetCursorState, 0, 1);
		armory.logicnode.LogicNode.addLink(_SetCursorState, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty.preallocInputs(4);
		_SetObjectProperty.preallocOutputs(1);
		var _Keyboard = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard.property0 = "started";
		_Keyboard.property1 = "escape";
		_Keyboard.preallocInputs(0);
		_Keyboard.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_Keyboard, new armory.logicnode.BooleanNode(this, false), 1, 0);
		armory.logicnode.LogicNode.addLink(_Keyboard, _SetObjectProperty, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "menu"), _SetObjectProperty, 0, 2);
		var _InvertBoolean = new armory.logicnode.NotNode(this);
		_InvertBoolean.preallocInputs(1);
		_InvertBoolean.preallocOutputs(1);
		var _GetObjectProperty = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty.preallocInputs(2);
		_GetObjectProperty.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "menu"), _GetObjectProperty, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty, _InvertBoolean, 0, 0);
		armory.logicnode.LogicNode.addLink(_InvertBoolean, _SetObjectProperty, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty, new armory.logicnode.NullNode(this), 0, 0);
		var _SetCursorState_001 = new armory.logicnode.SetCursorStateNode(this);
		_SetCursorState_001.property0 = "hide locked";
		_SetCursorState_001.preallocInputs(2);
		_SetCursorState_001.preallocOutputs(1);
		var _IsTrue = new armory.logicnode.IsTrueNode(this);
		_IsTrue.preallocInputs(2);
		_IsTrue.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_Mouse, _IsTrue, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_001, _IsTrue, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsTrue, _SetCursorState_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _SetCursorState_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_SetCursorState_001, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_002 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_002.preallocInputs(4);
		_SetObjectProperty_002.preallocOutputs(1);
		var _IsTrue_001 = new armory.logicnode.IsTrueNode(this);
		_IsTrue_001.preallocInputs(2);
		_IsTrue_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_Keyboard, _IsTrue_001, 0, 0);
		var _GetObjectProperty_002 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_002.preallocInputs(2);
		_GetObjectProperty_002.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_002, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "menu"), _GetObjectProperty_002, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_002, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_002, _IsTrue_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsTrue_001, _SetObjectProperty_002, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_002, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "look_speed"), _SetObjectProperty_002, 0, 2);
		var _Float_001 = new armory.logicnode.FloatNode(this);
		_Float_001.preallocInputs(1);
		_Float_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Float_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_Float_001, _SetObjectProperty_002, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_002, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_001 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_001.preallocInputs(4);
		_SetObjectProperty_001.preallocOutputs(1);
		var _IsFalse_001 = new armory.logicnode.IsFalseNode(this);
		_IsFalse_001.preallocInputs(2);
		_IsFalse_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_Keyboard, _IsFalse_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_002, _IsFalse_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsFalse_001, _SetObjectProperty_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_001, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "look_speed"), _SetObjectProperty_001, 0, 2);
		var _Float = new armory.logicnode.FloatNode(this);
		_Float.preallocInputs(1);
		_Float.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.004999999888241291), _Float, 0, 0);
		armory.logicnode.LogicNode.addLink(_Float, _SetObjectProperty_001, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_001, new armory.logicnode.NullNode(this), 0, 0);
		var _Print_001 = new armory.logicnode.PrintNode(this);
		_Print_001.preallocInputs(2);
		_Print_001.preallocOutputs(1);
		var _WriteStorage_001 = new armory.logicnode.WriteStorageNode(this);
		_WriteStorage_001.preallocInputs(3);
		_WriteStorage_001.preallocOutputs(1);
		var _WriteStorage = new armory.logicnode.WriteStorageNode(this);
		_WriteStorage.preallocInputs(3);
		_WriteStorage.preallocOutputs(1);
		var _SetSceneActive = new armory.logicnode.SetSceneNode(this);
		_SetSceneActive.preallocInputs(2);
		_SetSceneActive.preallocOutputs(2);
		var _RemoveSceneActive = new armory.logicnode.RemoveActiveSceneNode(this);
		_RemoveSceneActive.preallocInputs(1);
		_RemoveSceneActive.preallocOutputs(1);
		var _IsTrue_004 = new armory.logicnode.IsTrueNode(this);
		_IsTrue_004.preallocInputs(2);
		_IsTrue_004.preallocOutputs(1);
		var _ArrayLoop = new armory.logicnode.ArrayLoopNode(this);
		_ArrayLoop.preallocInputs(2);
		_ArrayLoop.preallocOutputs(4);
		var _OnContactArray = new armory.logicnode.OnContactArrayNode(this);
		_OnContactArray.property0 = "begin";
		_OnContactArray.preallocInputs(2);
		_OnContactArray.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _OnContactArray, 0, 0);
		var _GetCollection = new armory.logicnode.GetGroupNode(this);
		_GetCollection.preallocInputs(1);
		_GetCollection.preallocOutputs(1);
		var _ConcatenateString = new armory.logicnode.ConcatenateStringNode(this);
		_ConcatenateString.preallocInputs(2);
		_ConcatenateString.preallocOutputs(1);
		var _GetSceneActive = new armory.logicnode.ActiveSceneNode(this);
		_GetSceneActive.preallocInputs(0);
		_GetSceneActive.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_GetSceneActive, _ConcatenateString, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "_load_zone"), _ConcatenateString, 0, 1);
		armory.logicnode.LogicNode.addLink(_ConcatenateString, _GetCollection, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetCollection, _OnContactArray, 0, 1);
		armory.logicnode.LogicNode.addLink(_OnContactArray, _ArrayLoop, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetCollection, _ArrayLoop, 0, 1);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, new armory.logicnode.IntegerNode(this, 0), 2, 0);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, new armory.logicnode.NullNode(this), 3, 0);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, _IsTrue_004, 0, 0);
		var _HasContact = new armory.logicnode.HasContactNode(this);
		_HasContact.preallocInputs(2);
		_HasContact.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _HasContact, 0, 0);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, _HasContact, 1, 1);
		armory.logicnode.LogicNode.addLink(_HasContact, _IsTrue_004, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsTrue_004, _RemoveSceneActive, 0, 0);
		armory.logicnode.LogicNode.addLink(_RemoveSceneActive, _SetSceneActive, 0, 0);
		var _GetObjectProperty_012 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_012.preallocInputs(2);
		_GetObjectProperty_012.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, _GetObjectProperty_012, 1, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "zone"), _GetObjectProperty_012, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_012, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_012, _SetSceneActive, 0, 1);
		armory.logicnode.LogicNode.addLink(_SetSceneActive, new armory.logicnode.ObjectNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_SetSceneActive, _WriteStorage, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "spawn"), _WriteStorage, 0, 1);
		var _GetObjectLocation = new armory.logicnode.GetLocationNode(this);
		_GetObjectLocation.preallocInputs(2);
		_GetObjectLocation.preallocOutputs(1);
		var _GetObjectChild_002 = new armory.logicnode.GetChildNode(this);
		_GetObjectChild_002.property0 = "Starts With";
		_GetObjectChild_002.preallocInputs(2);
		_GetObjectChild_002.preallocOutputs(1);
		var _GetObjectbyName = new armory.logicnode.GetObjectNode(this);
		_GetObjectbyName.preallocInputs(1);
		_GetObjectbyName.preallocOutputs(1);
		var _ConcatenateString_002 = new armory.logicnode.ConcatenateStringNode(this);
		_ConcatenateString_002.preallocInputs(3);
		_ConcatenateString_002.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_012, _ConcatenateString_002, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "_"), _ConcatenateString_002, 0, 1);
		var _ArrayGet = new armory.logicnode.ArrayGetNode(this);
		_ArrayGet.preallocInputs(2);
		_ArrayGet.preallocOutputs(1);
		var _SplitString = new armory.logicnode.SplitStringNode(this);
		_SplitString.preallocInputs(2);
		_SplitString.preallocOutputs(1);
		var _String = new armory.logicnode.StringNode(this);
		_String.preallocInputs(1);
		_String.preallocOutputs(1);
		var _GetObjectName = new armory.logicnode.GetNameNode(this);
		_GetObjectName.preallocInputs(1);
		_GetObjectName.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, _GetObjectName, 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectName, _String, 0, 0);
		armory.logicnode.LogicNode.addLink(_String, _SplitString, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "_"), _SplitString, 0, 1);
		armory.logicnode.LogicNode.addLink(_SplitString, _ArrayGet, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 1), _ArrayGet, 0, 1);
		armory.logicnode.LogicNode.addLink(_ArrayGet, _ConcatenateString_002, 0, 2);
		armory.logicnode.LogicNode.addLink(_ConcatenateString_002, _GetObjectbyName, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectbyName, _GetObjectChild_002, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "spawn"), _GetObjectChild_002, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectChild_002, _GetObjectLocation, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _GetObjectLocation, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectLocation, _WriteStorage, 0, 2);
		armory.logicnode.LogicNode.addLink(_WriteStorage, _WriteStorage_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "spawn_rot"), _WriteStorage_001, 0, 1);
		var _GetObjectRotation = new armory.logicnode.GetRotationNode(this);
		_GetObjectRotation.property0 = "Local";
		_GetObjectRotation.preallocInputs(1);
		_GetObjectRotation.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_GetObjectChild_002, _GetObjectRotation, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectRotation, _WriteStorage_001, 0, 2);
		armory.logicnode.LogicNode.addLink(_WriteStorage_001, _Print_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectRotation, _Print_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_Print_001, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_007 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_007.preallocInputs(4);
		_SetObjectProperty_007.preallocOutputs(1);
		var _SetRBVelocity = new armory.logicnode.SetVelocityNode(this);
		_SetRBVelocity.preallocInputs(6);
		_SetRBVelocity.preallocOutputs(1);
		var _IsTrue_003 = new armory.logicnode.IsTrueNode(this);
		_IsTrue_003.preallocInputs(2);
		_IsTrue_003.preallocOutputs(1);
		var _OnContactArray_001 = new armory.logicnode.OnContactArrayNode(this);
		_OnContactArray_001.property0 = "begin";
		_OnContactArray_001.preallocInputs(2);
		_OnContactArray_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _OnContactArray_001, 0, 0);
		var _GetCollection_003 = new armory.logicnode.GetGroupNode(this);
		_GetCollection_003.preallocInputs(1);
		_GetCollection_003.preallocOutputs(1);
		var _ConcatenateString_003 = new armory.logicnode.ConcatenateStringNode(this);
		_ConcatenateString_003.preallocInputs(2);
		_ConcatenateString_003.preallocOutputs(1);
		var _GetSceneActive_002 = new armory.logicnode.ActiveSceneNode(this);
		_GetSceneActive_002.preallocInputs(0);
		_GetSceneActive_002.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_GetSceneActive_002, _ConcatenateString_003, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "_GROUND"), _ConcatenateString_003, 0, 1);
		armory.logicnode.LogicNode.addLink(_ConcatenateString_003, _GetCollection_003, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetCollection_003, _OnContactArray_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_OnContactArray_001, _IsTrue_003, 0, 0);
		var _GetObjectProperty_024 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_024.preallocInputs(2);
		_GetObjectProperty_024.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_024, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "want_to_tether"), _GetObjectProperty_024, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_024, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_024, _IsTrue_003, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsTrue_003, _SetRBVelocity, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetRBVelocity, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.VectorNode(this, 0.0,0.0,0.0), _SetRBVelocity, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.VectorNode(this, 1.0,1.0,1.0), _SetRBVelocity, 0, 3);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.VectorNode(this, 0.0,0.0,0.0), _SetRBVelocity, 0, 4);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.VectorNode(this, 1.0,1.0,1.0), _SetRBVelocity, 0, 5);
		armory.logicnode.LogicNode.addLink(_SetRBVelocity, _SetObjectProperty_007, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_007, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "tethered"), _SetObjectProperty_007, 0, 2);
		var _Boolean = new armory.logicnode.BooleanNode(this);
		_Boolean.preallocInputs(1);
		_Boolean.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _Boolean, 0, 0);
		armory.logicnode.LogicNode.addLink(_Boolean, _SetObjectProperty_007, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_007, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_009 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_009.preallocInputs(4);
		_SetObjectProperty_009.preallocOutputs(1);
		var _ApplyImpulse_002 = new armory.logicnode.ApplyImpulseNode(this);
		_ApplyImpulse_002.preallocInputs(4);
		_ApplyImpulse_002.preallocOutputs(1);
		var _Gate_001 = new armory.logicnode.GateNode(this);
		_Gate_001.property0 = "Greater Equal";
		_Gate_001.property1 = 9.999999747378752e-05;
		_Gate_001.preallocInputs(3);
		_Gate_001.preallocOutputs(2);
		var _SetObjectProperty_008 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_008.preallocInputs(4);
		_SetObjectProperty_008.preallocOutputs(1);
		var _IsTrue_005 = new armory.logicnode.IsTrueNode(this);
		_IsTrue_005.preallocInputs(2);
		_IsTrue_005.preallocOutputs(1);
		var _OnUpdate_003 = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate_003.property0 = "Update";
		_OnUpdate_003.preallocInputs(0);
		_OnUpdate_003.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_OnUpdate_003, _IsTrue_005, 0, 0);
		var _GetObjectProperty_025 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_025.preallocInputs(2);
		_GetObjectProperty_025.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_025, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "want_to_tether"), _GetObjectProperty_025, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_025, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_025, _IsTrue_005, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsTrue_005, _SetObjectProperty_008, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_008, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "launch_power"), _SetObjectProperty_008, 0, 2);
		var _Math_011 = new armory.logicnode.MathNode(this);
		_Math_011.property0 = "Add";
		_Math_011.property1 = false;
		_Math_011.preallocInputs(2);
		_Math_011.preallocOutputs(1);
		var _GetObjectProperty_014 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_014.preallocInputs(2);
		_GetObjectProperty_014.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_014, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "launch_power"), _GetObjectProperty_014, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_014, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_014, _Math_011, 0, 0);
		var _Math_013 = new armory.logicnode.MathNode(this);
		_Math_013.property0 = "Multiply";
		_Math_013.property1 = false;
		_Math_013.preallocInputs(2);
		_Math_013.preallocOutputs(1);
		var _GetApplicationTime_005 = new armory.logicnode.TimeNode(this);
		_GetApplicationTime_005.preallocInputs(0);
		_GetApplicationTime_005.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_GetApplicationTime_005, new armory.logicnode.FloatNode(this, 0.0), 0, 0);
		armory.logicnode.LogicNode.addLink(_GetApplicationTime_005, _Math_013, 1, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 10.0), _Math_013, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_013, _Math_011, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_011, _SetObjectProperty_008, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_008, _Gate_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_Math_011, _Gate_001, 0, 1);
		var _Float_003 = new armory.logicnode.FloatNode(this);
		_Float_003.preallocInputs(1);
		_Float_003.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 50.0), _Float_003, 0, 0);
		armory.logicnode.LogicNode.addLink(_Float_003, _Gate_001, 0, 2);
		armory.logicnode.LogicNode.addLink(_Gate_001, new armory.logicnode.NullNode(this), 1, 0);
		armory.logicnode.LogicNode.addLink(_Gate_001, _ApplyImpulse_002, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _ApplyImpulse_002, 0, 1);
		var _Vector_008 = new armory.logicnode.VectorNode(this);
		_Vector_008.preallocInputs(3);
		_Vector_008.preallocOutputs(1);
		var _Math_012 = new armory.logicnode.MathNode(this);
		_Math_012.property0 = "Multiply";
		_Math_012.property1 = false;
		_Math_012.preallocInputs(2);
		_Math_012.preallocOutputs(1);
		var _GetObjectProperty_015 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_015.preallocInputs(2);
		_GetObjectProperty_015.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_015, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "launch_power"), _GetObjectProperty_015, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_015, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_015, _Math_012, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, -1.0), _Math_012, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_012, _Vector_008, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_008, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_008, 0, 2);
		armory.logicnode.LogicNode.addLink(_Vector_008, _ApplyImpulse_002, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _ApplyImpulse_002, 0, 3);
		armory.logicnode.LogicNode.addLink(_ApplyImpulse_002, _SetObjectProperty_009, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_009, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "launch_power"), _SetObjectProperty_009, 0, 2);
		var _Float_002 = new armory.logicnode.FloatNode(this);
		_Float_002.preallocInputs(1);
		_Float_002.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Float_002, 0, 0);
		armory.logicnode.LogicNode.addLink(_Float_002, _SetObjectProperty_009, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_009, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_010 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_010.preallocInputs(4);
		_SetObjectProperty_010.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_ApplyImpulse_002, _SetObjectProperty_010, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_010, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "tethered"), _SetObjectProperty_010, 0, 2);
		var _Boolean_001 = new armory.logicnode.BooleanNode(this);
		_Boolean_001.preallocInputs(1);
		_Boolean_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _Boolean_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_Boolean_001, _SetObjectProperty_010, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_010, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_012 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_012.preallocInputs(4);
		_SetObjectProperty_012.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_ApplyImpulse_002, _SetObjectProperty_012, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_012, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "launch_started"), _SetObjectProperty_012, 0, 2);
		armory.logicnode.LogicNode.addLink(_Boolean_001, _SetObjectProperty_012, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_012, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_003 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_003.preallocInputs(4);
		_SetObjectProperty_003.preallocOutputs(1);
		var _OnTimer = new armory.logicnode.OnTimerNode(this);
		_OnTimer.preallocInputs(2);
		_OnTimer.preallocOutputs(1);
		var _RandomInteger_001 = new armory.logicnode.RandomIntegerNode(this);
		_RandomInteger_001.preallocInputs(2);
		_RandomInteger_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 5), _RandomInteger_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 20), _RandomInteger_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_RandomInteger_001, _OnTimer, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _OnTimer, 0, 1);
		armory.logicnode.LogicNode.addLink(_OnTimer, _SetObjectProperty_003, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_003, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "want_to_tether"), _SetObjectProperty_003, 0, 2);
		var _Boolean_002 = new armory.logicnode.BooleanNode(this);
		_Boolean_002.preallocInputs(1);
		_Boolean_002.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _Boolean_002, 0, 0);
		armory.logicnode.LogicNode.addLink(_Boolean_002, _SetObjectProperty_003, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_003, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_013 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_013.preallocInputs(4);
		_SetObjectProperty_013.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_ApplyImpulse_002, _SetObjectProperty_013, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_013, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "grab"), _SetObjectProperty_013, 0, 2);
		armory.logicnode.LogicNode.addLink(_Boolean_001, _SetObjectProperty_013, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_013, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_017 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_017.preallocInputs(4);
		_SetObjectProperty_017.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_ApplyImpulse_002, _SetObjectProperty_017, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_017, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "want_to_tether"), _SetObjectProperty_017, 0, 2);
		armory.logicnode.LogicNode.addLink(_Boolean_001, _SetObjectProperty_017, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_017, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectRotation_001 = new armory.logicnode.SetRotationNode(this);
		_SetObjectRotation_001.property0 = "Euler Angles";
		_SetObjectRotation_001.preallocInputs(3);
		_SetObjectRotation_001.preallocOutputs(1);
		var _OnUpdate = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate.property0 = "Update";
		_OnUpdate.preallocInputs(0);
		_OnUpdate.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_OnUpdate, _SetObjectRotation_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectRotation_001, 0, 1);
		var _LookAt = new armory.logicnode.LookAtNode(this);
		_LookAt.property0 = "-X";
		_LookAt.preallocInputs(2);
		_LookAt.preallocOutputs(1);
		var _GetObjectLocation_001 = new armory.logicnode.GetLocationNode(this);
		_GetObjectLocation_001.preallocInputs(2);
		_GetObjectLocation_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectLocation_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _GetObjectLocation_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectLocation_001, _LookAt, 0, 0);
		var _GetObjectLocation_003 = new armory.logicnode.GetLocationNode(this);
		_GetObjectLocation_003.preallocInputs(2);
		_GetObjectLocation_003.preallocOutputs(1);
		var _GetCameraActive = new armory.logicnode.ActiveCameraNode(this);
		_GetCameraActive.preallocInputs(0);
		_GetCameraActive.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_GetCameraActive, _GetObjectLocation_003, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _GetObjectLocation_003, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectLocation_003, _LookAt, 0, 1);
		armory.logicnode.LogicNode.addLink(_LookAt, _SetObjectRotation_001, 0, 2);
		armory.logicnode.LogicNode.addLink(_SetObjectRotation_001, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_014 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_014.preallocInputs(4);
		_SetObjectProperty_014.preallocOutputs(1);
		var _OnUpdate_001 = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate_001.property0 = "Update";
		_OnUpdate_001.preallocInputs(0);
		_OnUpdate_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_OnUpdate_001, _SetObjectProperty_014, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_014, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "game_tick"), _SetObjectProperty_014, 0, 2);
		var _Math_014 = new armory.logicnode.MathNode(this);
		_Math_014.property0 = "Add";
		_Math_014.property1 = false;
		_Math_014.preallocInputs(2);
		_Math_014.preallocOutputs(1);
		var _GetObjectProperty_018 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_018.preallocInputs(2);
		_GetObjectProperty_018.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_018, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "game_tick"), _GetObjectProperty_018, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_018, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_018, _Math_014, 0, 0);
		var _GetApplicationTime_006 = new armory.logicnode.TimeNode(this);
		_GetApplicationTime_006.preallocInputs(0);
		_GetApplicationTime_006.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_GetApplicationTime_006, new armory.logicnode.FloatNode(this, 0.0), 0, 0);
		armory.logicnode.LogicNode.addLink(_GetApplicationTime_006, _Math_014, 1, 1);
		armory.logicnode.LogicNode.addLink(_Math_014, _SetObjectProperty_014, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_014, new armory.logicnode.NullNode(this), 0, 0);
		var _RandomInteger = new armory.logicnode.RandomIntegerNode(this);
		_RandomInteger.preallocInputs(2);
		_RandomInteger.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 10), _RandomInteger, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 30), _RandomInteger, 0, 1);
		armory.logicnode.LogicNode.addLink(_RandomInteger, new armory.logicnode.IntegerNode(this, 0), 0, 0);
		var _PlaySpeaker = new armory.logicnode.PlaySoundNode(this);
		_PlaySpeaker.preallocInputs(2);
		_PlaySpeaker.preallocOutputs(1);
		var _ApplyImpulse_003 = new armory.logicnode.ApplyImpulseNode(this);
		_ApplyImpulse_003.preallocInputs(4);
		_ApplyImpulse_003.preallocOutputs(1);
		var _SetObjectLocation_001 = new armory.logicnode.SetLocationNode(this);
		_SetObjectLocation_001.preallocInputs(4);
		_SetObjectLocation_001.preallocOutputs(1);
		var _SetObjectRotation = new armory.logicnode.SetRotationNode(this);
		_SetObjectRotation.property0 = "Euler Angles";
		_SetObjectRotation.preallocInputs(3);
		_SetObjectRotation.preallocOutputs(1);
		var _SpawnObjectByName = new armory.logicnode.SpawnObjectByNameNode(this);
		_SpawnObjectByName.property0 = "player";
		_SpawnObjectByName.preallocInputs(4);
		_SpawnObjectByName.preallocOutputs(2);
		var _SetObjectProperty_015 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_015.preallocInputs(4);
		_SetObjectProperty_015.preallocOutputs(1);
		var _SetObjectProperty_018 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_018.preallocInputs(4);
		_SetObjectProperty_018.preallocOutputs(1);
		var _Gate_006 = new armory.logicnode.GateNode(this);
		_Gate_006.property0 = "Greater Equal";
		_Gate_006.property1 = 9.999999747378752e-05;
		_Gate_006.preallocInputs(3);
		_Gate_006.preallocOutputs(2);
		var _Gate = new armory.logicnode.GateNode(this);
		_Gate.property0 = "Greater Equal";
		_Gate.property1 = 9.999999747378752e-05;
		_Gate.preallocInputs(3);
		_Gate.preallocOutputs(2);
		var _IsTrue_002 = new armory.logicnode.IsTrueNode(this);
		_IsTrue_002.preallocInputs(2);
		_IsTrue_002.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_OnUpdate_001, _IsTrue_002, 0, 0);
		var _GetObjectProperty_003 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_003.preallocInputs(2);
		_GetObjectProperty_003.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_003, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "want_to_fire"), _GetObjectProperty_003, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_003, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_003, _IsTrue_002, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsTrue_002, _Gate, 0, 0);
		var _Math_015 = new armory.logicnode.MathNode(this);
		_Math_015.property0 = "Subtract";
		_Math_015.property1 = false;
		_Math_015.preallocInputs(2);
		_Math_015.preallocOutputs(1);
		var _GetObjectProperty_020 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_020.preallocInputs(2);
		_GetObjectProperty_020.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_020, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "game_tick"), _GetObjectProperty_020, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_020, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_020, _Math_015, 0, 0);
		var _GetObjectProperty_019 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_019.preallocInputs(2);
		_GetObjectProperty_019.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_019, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "last_fire"), _GetObjectProperty_019, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_019, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_019, _Math_015, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_015, _Gate, 0, 1);
		var _GetObjectProperty_021 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_021.preallocInputs(2);
		_GetObjectProperty_021.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_021, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "fire_rate"), _GetObjectProperty_021, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_021, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_021, _Gate, 0, 2);
		armory.logicnode.LogicNode.addLink(_Gate, new armory.logicnode.NullNode(this), 1, 0);
		armory.logicnode.LogicNode.addLink(_Gate, _Gate_006, 0, 0);
		var _GetObjectProperty_035 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_035.preallocInputs(2);
		_GetObjectProperty_035.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_035, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "power"), _GetObjectProperty_035, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_035, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_035, _Gate_006, 0, 1);
		var _Float_004 = new armory.logicnode.FloatNode(this);
		_Float_004.preallocInputs(1);
		_Float_004.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 20.0), _Float_004, 0, 0);
		armory.logicnode.LogicNode.addLink(_Float_004, _Gate_006, 0, 2);
		armory.logicnode.LogicNode.addLink(_Gate_006, new armory.logicnode.NullNode(this), 1, 0);
		armory.logicnode.LogicNode.addLink(_Gate_006, _SetObjectProperty_018, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_018, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "power"), _SetObjectProperty_018, 0, 2);
		var _Math_024 = new armory.logicnode.MathNode(this);
		_Math_024.property0 = "Subtract";
		_Math_024.property1 = false;
		_Math_024.preallocInputs(2);
		_Math_024.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_035, _Math_024, 0, 0);
		armory.logicnode.LogicNode.addLink(_Float_004, _Math_024, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_024, _SetObjectProperty_018, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_018, _SetObjectProperty_015, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_015, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "last_fire"), _SetObjectProperty_015, 0, 2);
		var _GetObjectProperty_022 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_022.preallocInputs(2);
		_GetObjectProperty_022.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_022, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "game_tick"), _GetObjectProperty_022, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_022, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_022, _SetObjectProperty_015, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_015, _SpawnObjectByName, 0, 0);
		var _ConcatenateString_001 = new armory.logicnode.ConcatenateStringNode(this);
		_ConcatenateString_001.preallocInputs(2);
		_ConcatenateString_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "bullet_"), _ConcatenateString_001, 0, 0);
		var _GetObjectProperty_009 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_009.preallocInputs(2);
		_GetObjectProperty_009.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_009, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "gun_type"), _GetObjectProperty_009, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_009, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_009, _ConcatenateString_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_ConcatenateString_001, _SpawnObjectByName, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.NullNode(this), _SpawnObjectByName, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _SpawnObjectByName, 0, 3);
		armory.logicnode.LogicNode.addLink(_SpawnObjectByName, _SetObjectRotation, 0, 0);
		armory.logicnode.LogicNode.addLink(_SpawnObjectByName, _SetObjectRotation, 1, 1);
		var _GetObjectRotation_001 = new armory.logicnode.GetRotationNode(this);
		_GetObjectRotation_001.property0 = "Local";
		_GetObjectRotation_001.preallocInputs(1);
		_GetObjectRotation_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectRotation_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectRotation_001, _SetObjectRotation, 0, 2);
		armory.logicnode.LogicNode.addLink(_SetObjectRotation, _SetObjectLocation_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_SpawnObjectByName, _SetObjectLocation_001, 1, 1);
		var _GetObjectLocation_002 = new armory.logicnode.GetLocationNode(this);
		_GetObjectLocation_002.preallocInputs(2);
		_GetObjectLocation_002.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectLocation_002, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _GetObjectLocation_002, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectLocation_002, _SetObjectLocation_001, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _SetObjectLocation_001, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectLocation_001, _ApplyImpulse_003, 0, 0);
		armory.logicnode.LogicNode.addLink(_SpawnObjectByName, _ApplyImpulse_003, 1, 1);
		var _VectorMath = new armory.logicnode.VectorMathNode(this);
		_VectorMath.property0 = "Add";
		_VectorMath.property1 = false;
		_VectorMath.preallocInputs(2);
		_VectorMath.preallocOutputs(1);
		var _Vector_009 = new armory.logicnode.VectorNode(this);
		_Vector_009.preallocInputs(3);
		_Vector_009.preallocOutputs(1);
		var _Math_016 = new armory.logicnode.MathNode(this);
		_Math_016.property0 = "Multiply";
		_Math_016.property1 = false;
		_Math_016.preallocInputs(2);
		_Math_016.preallocOutputs(1);
		var _GetObjectProperty_023 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_023.preallocInputs(2);
		_GetObjectProperty_023.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_023, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "fire_speed"), _GetObjectProperty_023, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_023, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_023, _Math_016, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, -1.0), _Math_016, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_016, _Vector_009, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_009, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_009, 0, 2);
		armory.logicnode.LogicNode.addLink(_Vector_009, _VectorMath, 0, 0);
		var _Vector_011 = new armory.logicnode.VectorNode(this);
		_Vector_011.preallocInputs(3);
		_Vector_011.preallocOutputs(1);
		var _SeparateXYZ = new armory.logicnode.SeparateVectorNode(this);
		_SeparateXYZ.preallocInputs(1);
		_SeparateXYZ.preallocOutputs(3);
		var _GetRBVelocity = new armory.logicnode.GetVelocityNode(this);
		_GetRBVelocity.preallocInputs(3);
		_GetRBVelocity.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetRBVelocity, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _GetRBVelocity, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _GetRBVelocity, 0, 2);
		armory.logicnode.LogicNode.addLink(_GetRBVelocity, new armory.logicnode.VectorNode(this, 0.0,0.0,0.0), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetRBVelocity, _SeparateXYZ, 0, 0);
		armory.logicnode.LogicNode.addLink(_SeparateXYZ, new armory.logicnode.FloatNode(this, 0.0), 1, 0);
		armory.logicnode.LogicNode.addLink(_SeparateXYZ, new armory.logicnode.FloatNode(this, 0.0), 2, 0);
		armory.logicnode.LogicNode.addLink(_SeparateXYZ, _Vector_011, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_011, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_011, 0, 2);
		armory.logicnode.LogicNode.addLink(_Vector_011, _VectorMath, 0, 1);
		armory.logicnode.LogicNode.addLink(_VectorMath, _ApplyImpulse_003, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _ApplyImpulse_003, 0, 3);
		armory.logicnode.LogicNode.addLink(_ApplyImpulse_003, _PlaySpeaker, 0, 0);
		var _GetObjectChild = new armory.logicnode.GetChildNode(this);
		_GetObjectChild.property0 = "By Name";
		_GetObjectChild.preallocInputs(2);
		_GetObjectChild.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectChild, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "AISpeaker"), _GetObjectChild, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectChild, _PlaySpeaker, 0, 1);
		armory.logicnode.LogicNode.addLink(_PlaySpeaker, new armory.logicnode.NullNode(this), 0, 0);
		var _ApplyImpulse_004 = new armory.logicnode.ApplyImpulseNode(this);
		_ApplyImpulse_004.preallocInputs(4);
		_ApplyImpulse_004.preallocOutputs(1);
		var _IsFalse_007 = new armory.logicnode.IsFalseNode(this);
		_IsFalse_007.preallocInputs(2);
		_IsFalse_007.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_ApplyImpulse_003, _IsFalse_007, 0, 0);
		var _GetObjectProperty_029 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_029.preallocInputs(2);
		_GetObjectProperty_029.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_029, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "tethered"), _GetObjectProperty_029, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_029, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_029, _IsFalse_007, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsFalse_007, _ApplyImpulse_004, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _ApplyImpulse_004, 0, 1);
		var _Vector_010 = new armory.logicnode.VectorNode(this);
		_Vector_010.preallocInputs(3);
		_Vector_010.preallocOutputs(1);
		var _Math_017 = new armory.logicnode.MathNode(this);
		_Math_017.property0 = "Multiply";
		_Math_017.property1 = false;
		_Math_017.preallocInputs(2);
		_Math_017.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_023, _Math_017, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.10000000149011612), _Math_017, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_017, _Vector_010, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_010, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_010, 0, 2);
		armory.logicnode.LogicNode.addLink(_Vector_010, _ApplyImpulse_004, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _ApplyImpulse_004, 0, 3);
		armory.logicnode.LogicNode.addLink(_ApplyImpulse_004, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_004 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_004.preallocInputs(4);
		_SetObjectProperty_004.preallocOutputs(1);
		var _Gate_005 = new armory.logicnode.GateNode(this);
		_Gate_005.property0 = "Less";
		_Gate_005.property1 = 9.999999747378752e-05;
		_Gate_005.preallocInputs(3);
		_Gate_005.preallocOutputs(2);
		var _OnUpdate_004 = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate_004.property0 = "Update";
		_OnUpdate_004.preallocInputs(0);
		_OnUpdate_004.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_OnUpdate_004, _Gate_005, 0, 0);
		var _Math_022 = new armory.logicnode.MathNode(this);
		_Math_022.property0 = "Add";
		_Math_022.property1 = false;
		_Math_022.preallocInputs(2);
		_Math_022.preallocOutputs(1);
		var _GetObjectProperty_032 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_032.preallocInputs(2);
		_GetObjectProperty_032.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_032, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "power"), _GetObjectProperty_032, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_032, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_032, _Math_022, 0, 0);
		var _Math_021 = new armory.logicnode.MathNode(this);
		_Math_021.property0 = "Multiply";
		_Math_021.property1 = false;
		_Math_021.preallocInputs(2);
		_Math_021.preallocOutputs(1);
		var _GetObjectProperty_010 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_010.preallocInputs(2);
		_GetObjectProperty_010.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_010, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "power_regen"), _GetObjectProperty_010, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_010, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_010, _Math_021, 0, 0);
		var _GetApplicationTime_007 = new armory.logicnode.TimeNode(this);
		_GetApplicationTime_007.preallocInputs(0);
		_GetApplicationTime_007.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_GetApplicationTime_007, new armory.logicnode.FloatNode(this, 0.0), 0, 0);
		armory.logicnode.LogicNode.addLink(_GetApplicationTime_007, _Math_021, 1, 1);
		armory.logicnode.LogicNode.addLink(_Math_021, _Math_022, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_022, _Gate_005, 0, 1);
		var _GetObjectProperty_033 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_033.preallocInputs(2);
		_GetObjectProperty_033.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_033, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "max_power"), _GetObjectProperty_033, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_033, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_033, _Gate_005, 0, 2);
		armory.logicnode.LogicNode.addLink(_Gate_005, _SetObjectProperty_004, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_004, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "power"), _SetObjectProperty_004, 0, 2);
		armory.logicnode.LogicNode.addLink(_Math_022, _SetObjectProperty_004, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_004, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_005 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_005.preallocInputs(4);
		_SetObjectProperty_005.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_Gate_005, _SetObjectProperty_005, 1, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_005, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "power"), _SetObjectProperty_005, 0, 2);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_033, _SetObjectProperty_005, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_005, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_006 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_006.preallocInputs(4);
		_SetObjectProperty_006.preallocOutputs(1);
		var _Gate_002 = new armory.logicnode.GateNode(this);
		_Gate_002.property0 = "Less Equal";
		_Gate_002.property1 = 9.999999747378752e-05;
		_Gate_002.preallocInputs(3);
		_Gate_002.preallocOutputs(2);
		var _OnUpdate_002 = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate_002.property0 = "Update";
		_OnUpdate_002.preallocInputs(0);
		_OnUpdate_002.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_OnUpdate_002, _Gate_002, 0, 0);
		var _GetDistance = new armory.logicnode.GetDistanceNode(this);
		_GetDistance.preallocInputs(2);
		_GetDistance.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetDistance, 0, 0);
		var _GetObjectbyName_001 = new armory.logicnode.GetObjectNode(this);
		_GetObjectbyName_001.preallocInputs(1);
		_GetObjectbyName_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "player"), _GetObjectbyName_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectbyName_001, _GetDistance, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetDistance, _Gate_002, 0, 1);
		var _RandomFloat = new armory.logicnode.RandomFloatNode(this);
		_RandomFloat.preallocInputs(2);
		_RandomFloat.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 10.0), _RandomFloat, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 30.0), _RandomFloat, 0, 1);
		armory.logicnode.LogicNode.addLink(_RandomFloat, _Gate_002, 0, 2);
		armory.logicnode.LogicNode.addLink(_Gate_002, _SetObjectProperty_006, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_006, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "want_to_fire"), _SetObjectProperty_006, 0, 2);
		var _Boolean_004 = new armory.logicnode.BooleanNode(this);
		_Boolean_004.preallocInputs(1);
		_Boolean_004.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _Boolean_004, 0, 0);
		armory.logicnode.LogicNode.addLink(_Boolean_004, _SetObjectProperty_006, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_006, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_011 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_011.preallocInputs(4);
		_SetObjectProperty_011.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_Gate_002, _SetObjectProperty_011, 1, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_011, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "want_to_fire"), _SetObjectProperty_011, 0, 2);
		var _Boolean_005 = new armory.logicnode.BooleanNode(this);
		_Boolean_005.preallocInputs(1);
		_Boolean_005.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _Boolean_005, 0, 0);
		armory.logicnode.LogicNode.addLink(_Boolean_005, _SetObjectProperty_011, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_011, new armory.logicnode.NullNode(this), 0, 0);
		var _GetObjectProperty_004 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_004.preallocInputs(2);
		_GetObjectProperty_004.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_004, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "want_to_fire"), _GetObjectProperty_004, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_004, new armory.logicnode.NullNode(this), 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_004, new armory.logicnode.StringNode(this, ""), 1, 0);
	}
}