package arm.node;

@:access(armory.logicnode.LogicNode)@:keep class Player extends armory.logicnode.LogicTree {

	var functionNodes:Map<String, armory.logicnode.FunctionNode>;

	var functionOutputNodes:Map<String, armory.logicnode.FunctionOutputNode>;

	public function new() {
		super();
		this.functionNodes = new Map();
		this.functionOutputNodes = new Map();
		notifyOnAdd(add);
	}

	override public function add() {
		var _DrawString_002 = new armory.logicnode.DrawStringNode(this);
		_DrawString_002.preallocInputs(7);
		_DrawString_002.preallocOutputs(1);
		var _IsTrue_010 = new armory.logicnode.IsTrueNode(this);
		_IsTrue_010.preallocInputs(2);
		_IsTrue_010.preallocOutputs(1);
		var _IsFalse_005 = new armory.logicnode.IsFalseNode(this);
		_IsFalse_005.preallocInputs(2);
		_IsFalse_005.preallocOutputs(1);
		var _DrawString = new armory.logicnode.DrawStringNode(this);
		_DrawString.preallocInputs(7);
		_DrawString.preallocOutputs(1);
		var _OnRender2D = new armory.logicnode.OnRender2DNode(this);
		_OnRender2D.preallocInputs(0);
		_OnRender2D.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_OnRender2D, _DrawString, 0, 0);
		var _ConcatenateString_004 = new armory.logicnode.ConcatenateStringNode(this);
		_ConcatenateString_004.preallocInputs(2);
		_ConcatenateString_004.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "Life: "), _ConcatenateString_004, 0, 0);
		var _GetObjectProperty_024 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_024.preallocInputs(2);
		_GetObjectProperty_024.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_024, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "life"), _GetObjectProperty_024, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_024, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_024, _ConcatenateString_004, 0, 1);
		armory.logicnode.LogicNode.addLink(_ConcatenateString_004, _DrawString, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, ""), _DrawString, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 60), _DrawString, 0, 3);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ColorNode(this, 1.0,0.0,0.005675182212144136,1.0), _DrawString, 0, 4);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _DrawString, 0, 5);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _DrawString, 0, 6);
		armory.logicnode.LogicNode.addLink(_DrawString, _IsFalse_005, 0, 0);
		var _GetObjectProperty_027 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_027.preallocInputs(2);
		_GetObjectProperty_027.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_027, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "tethered"), _GetObjectProperty_027, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_027, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_027, _IsFalse_005, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsFalse_005, _IsTrue_010, 0, 0);
		var _GetObjectProperty_028 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_028.preallocInputs(2);
		_GetObjectProperty_028.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_028, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "grab"), _GetObjectProperty_028, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_028, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_028, _IsTrue_010, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsTrue_010, _DrawString_002, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "Grab wall"), _DrawString_002, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, ""), _DrawString_002, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 60), _DrawString_002, 0, 3);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ColorNode(this, 0.0,0.01081035565584898,1.0,1.0), _DrawString_002, 0, 4);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _DrawString_002, 0, 5);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 60.0), _DrawString_002, 0, 6);
		armory.logicnode.LogicNode.addLink(_DrawString_002, new armory.logicnode.NullNode(this), 0, 0);
		var _DrawString_003 = new armory.logicnode.DrawStringNode(this);
		_DrawString_003.preallocInputs(7);
		_DrawString_003.preallocOutputs(1);
		var _IsFalse_006 = new armory.logicnode.IsFalseNode(this);
		_IsFalse_006.preallocInputs(2);
		_IsFalse_006.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_IsFalse_005, _IsFalse_006, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_028, _IsFalse_006, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsFalse_006, _DrawString_003, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "Bounce of wall"), _DrawString_003, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, ""), _DrawString_003, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 60), _DrawString_003, 0, 3);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ColorNode(this, 0.47293904423713684,0.7088126540184021,0.0,1.0), _DrawString_003, 0, 4);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _DrawString_003, 0, 5);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 60.0), _DrawString_003, 0, 6);
		armory.logicnode.LogicNode.addLink(_DrawString_003, new armory.logicnode.NullNode(this), 0, 0);
		var _SendGlobalEvent = new armory.logicnode.SendGlobalEventNode(this);
		_SendGlobalEvent.preallocInputs(2);
		_SendGlobalEvent.preallocOutputs(1);
		var _Sleep = new armory.logicnode.SleepNode(this);
		_Sleep.preallocInputs(2);
		_Sleep.preallocOutputs(1);
		var _DrawString_004 = new armory.logicnode.DrawStringNode(this);
		_DrawString_004.preallocInputs(7);
		_DrawString_004.preallocOutputs(1);
		var _IsTrue_011 = new armory.logicnode.IsTrueNode(this);
		_IsTrue_011.preallocInputs(2);
		_IsTrue_011.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_OnRender2D, _IsTrue_011, 0, 0);
		var _GetObjectProperty_030 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_030.preallocInputs(2);
		_GetObjectProperty_030.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_030, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "WON"), _GetObjectProperty_030, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_030, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_030, _IsTrue_011, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsTrue_011, _DrawString_004, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "YOU WIN!"), _DrawString_004, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, ""), _DrawString_004, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 60), _DrawString_004, 0, 3);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ColorNode(this, 0.011072480119764805,0.4620864987373352,0.042283546179533005,1.0), _DrawString_004, 0, 4);
		var _Math_019 = new armory.logicnode.MathNode(this);
		_Math_019.property0 = "Divide";
		_Math_019.property1 = false;
		_Math_019.preallocInputs(2);
		_Math_019.preallocOutputs(1);
		var _GetDisplayResolution = new armory.logicnode.DisplayInfoNode(this);
		_GetDisplayResolution.preallocInputs(0);
		_GetDisplayResolution.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_GetDisplayResolution, _Math_019, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 2.0), _Math_019, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_019, _DrawString_004, 0, 5);
		var _Math_020 = new armory.logicnode.MathNode(this);
		_Math_020.property0 = "Divide";
		_Math_020.property1 = false;
		_Math_020.preallocInputs(2);
		_Math_020.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_GetDisplayResolution, _Math_020, 1, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 2.0), _Math_020, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_020, _DrawString_004, 0, 6);
		armory.logicnode.LogicNode.addLink(_DrawString_004, _Sleep, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 5.0), _Sleep, 0, 1);
		armory.logicnode.LogicNode.addLink(_Sleep, _SendGlobalEvent, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "load_menu"), _SendGlobalEvent, 0, 1);
		armory.logicnode.LogicNode.addLink(_SendGlobalEvent, new armory.logicnode.NullNode(this), 0, 0);
		var _DrawString_005 = new armory.logicnode.DrawStringNode(this);
		_DrawString_005.preallocInputs(7);
		_DrawString_005.preallocOutputs(1);
		var _Gate_003 = new armory.logicnode.GateNode(this);
		_Gate_003.property0 = "Less Equal";
		_Gate_003.property1 = 9.999999747378752e-05;
		_Gate_003.preallocInputs(3);
		_Gate_003.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_OnRender2D, _Gate_003, 0, 0);
		var _GetObjectProperty_031 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_031.preallocInputs(2);
		_GetObjectProperty_031.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_031, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "life"), _GetObjectProperty_031, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_031, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_031, _Gate_003, 0, 1);
		var _Integer_001 = new armory.logicnode.IntegerNode(this);
		_Integer_001.preallocInputs(1);
		_Integer_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 0), _Integer_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_Integer_001, _Gate_003, 0, 2);
		armory.logicnode.LogicNode.addLink(_Gate_003, new armory.logicnode.NullNode(this), 1, 0);
		armory.logicnode.LogicNode.addLink(_Gate_003, _DrawString_005, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "You are dead! Press R"), _DrawString_005, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, ""), _DrawString_005, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 60), _DrawString_005, 0, 3);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ColorNode(this, 0.4620864987373352,0.0022030281834304333,0.0,1.0), _DrawString_005, 0, 4);
		armory.logicnode.LogicNode.addLink(_Math_019, _DrawString_005, 0, 5);
		armory.logicnode.LogicNode.addLink(_Math_020, _DrawString_005, 0, 6);
		armory.logicnode.LogicNode.addLink(_DrawString_005, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty.preallocInputs(4);
		_SetObjectProperty.preallocOutputs(1);
		var _Keyboard = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard.property0 = "started";
		_Keyboard.property1 = "escape";
		_Keyboard.preallocInputs(0);
		_Keyboard.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_Keyboard, new armory.logicnode.BooleanNode(this, false), 1, 0);
		armory.logicnode.LogicNode.addLink(_Keyboard, _SetObjectProperty, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "menu"), _SetObjectProperty, 0, 2);
		var _InvertBoolean = new armory.logicnode.NotNode(this);
		_InvertBoolean.preallocInputs(1);
		_InvertBoolean.preallocOutputs(1);
		var _GetObjectProperty = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty.preallocInputs(2);
		_GetObjectProperty.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "menu"), _GetObjectProperty, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty, _InvertBoolean, 0, 0);
		armory.logicnode.LogicNode.addLink(_InvertBoolean, _SetObjectProperty, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty, new armory.logicnode.NullNode(this), 0, 0);
		var _SetCursorState_001 = new armory.logicnode.SetCursorStateNode(this);
		_SetCursorState_001.property0 = "hide locked";
		_SetCursorState_001.preallocInputs(2);
		_SetCursorState_001.preallocOutputs(1);
		var _IsTrue = new armory.logicnode.IsTrueNode(this);
		_IsTrue.preallocInputs(2);
		_IsTrue.preallocOutputs(1);
		var _Mouse = new armory.logicnode.MergedMouseNode(this);
		_Mouse.property0 = "moved";
		_Mouse.property1 = "left";
		_Mouse.preallocInputs(0);
		_Mouse.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_Mouse, new armory.logicnode.BooleanNode(this, false), 1, 0);
		armory.logicnode.LogicNode.addLink(_Mouse, _IsTrue, 0, 0);
		var _GetObjectProperty_001 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_001.preallocInputs(2);
		_GetObjectProperty_001.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "menu"), _GetObjectProperty_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_001, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_001, _IsTrue, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsTrue, _SetCursorState_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _SetCursorState_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_SetCursorState_001, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_002 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_002.preallocInputs(4);
		_SetObjectProperty_002.preallocOutputs(1);
		var _IsTrue_001 = new armory.logicnode.IsTrueNode(this);
		_IsTrue_001.preallocInputs(2);
		_IsTrue_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_Keyboard, _IsTrue_001, 0, 0);
		var _GetObjectProperty_002 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_002.preallocInputs(2);
		_GetObjectProperty_002.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_002, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "menu"), _GetObjectProperty_002, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_002, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_002, _IsTrue_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsTrue_001, _SetObjectProperty_002, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_002, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "look_speed"), _SetObjectProperty_002, 0, 2);
		var _Float_001 = new armory.logicnode.FloatNode(this);
		_Float_001.preallocInputs(1);
		_Float_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Float_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_Float_001, _SetObjectProperty_002, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_002, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_001 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_001.preallocInputs(4);
		_SetObjectProperty_001.preallocOutputs(1);
		var _IsFalse_001 = new armory.logicnode.IsFalseNode(this);
		_IsFalse_001.preallocInputs(2);
		_IsFalse_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_Keyboard, _IsFalse_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_002, _IsFalse_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsFalse_001, _SetObjectProperty_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_001, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "look_speed"), _SetObjectProperty_001, 0, 2);
		var _Float = new armory.logicnode.FloatNode(this);
		_Float.preallocInputs(1);
		_Float.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.004999999888241291), _Float, 0, 0);
		armory.logicnode.LogicNode.addLink(_Float, _SetObjectProperty_001, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_001, new armory.logicnode.NullNode(this), 0, 0);
		var _SetCursorState = new armory.logicnode.SetCursorStateNode(this);
		_SetCursorState.property0 = "hide locked";
		_SetCursorState.preallocInputs(2);
		_SetCursorState.preallocOutputs(1);
		var _IsFalse = new armory.logicnode.IsFalseNode(this);
		_IsFalse.preallocInputs(2);
		_IsFalse.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_Mouse, _IsFalse, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_001, _IsFalse, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsFalse, _SetCursorState, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _SetCursorState, 0, 1);
		armory.logicnode.LogicNode.addLink(_SetCursorState, new armory.logicnode.NullNode(this), 0, 0);
		var _Print_001 = new armory.logicnode.PrintNode(this);
		_Print_001.preallocInputs(2);
		_Print_001.preallocOutputs(1);
		var _WriteStorage_001 = new armory.logicnode.WriteStorageNode(this);
		_WriteStorage_001.preallocInputs(3);
		_WriteStorage_001.preallocOutputs(1);
		var _WriteStorage = new armory.logicnode.WriteStorageNode(this);
		_WriteStorage.preallocInputs(3);
		_WriteStorage.preallocOutputs(1);
		var _SetSceneActive = new armory.logicnode.SetSceneNode(this);
		_SetSceneActive.preallocInputs(2);
		_SetSceneActive.preallocOutputs(2);
		var _RemoveSceneActive = new armory.logicnode.RemoveActiveSceneNode(this);
		_RemoveSceneActive.preallocInputs(1);
		_RemoveSceneActive.preallocOutputs(1);
		var _IsTrue_004 = new armory.logicnode.IsTrueNode(this);
		_IsTrue_004.preallocInputs(2);
		_IsTrue_004.preallocOutputs(1);
		var _ArrayLoop = new armory.logicnode.ArrayLoopNode(this);
		_ArrayLoop.preallocInputs(2);
		_ArrayLoop.preallocOutputs(4);
		var _OnContactArray = new armory.logicnode.OnContactArrayNode(this);
		_OnContactArray.property0 = "begin";
		_OnContactArray.preallocInputs(2);
		_OnContactArray.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _OnContactArray, 0, 0);
		var _GetCollection = new armory.logicnode.GetGroupNode(this);
		_GetCollection.preallocInputs(1);
		_GetCollection.preallocOutputs(1);
		var _ConcatenateString = new armory.logicnode.ConcatenateStringNode(this);
		_ConcatenateString.preallocInputs(2);
		_ConcatenateString.preallocOutputs(1);
		var _GetSceneActive = new armory.logicnode.ActiveSceneNode(this);
		_GetSceneActive.preallocInputs(0);
		_GetSceneActive.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_GetSceneActive, _ConcatenateString, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "_load_zone"), _ConcatenateString, 0, 1);
		armory.logicnode.LogicNode.addLink(_ConcatenateString, _GetCollection, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetCollection, _OnContactArray, 0, 1);
		armory.logicnode.LogicNode.addLink(_OnContactArray, _ArrayLoop, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetCollection, _ArrayLoop, 0, 1);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, new armory.logicnode.IntegerNode(this, 0), 2, 0);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, new armory.logicnode.NullNode(this), 3, 0);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, _IsTrue_004, 0, 0);
		var _HasContact = new armory.logicnode.HasContactNode(this);
		_HasContact.preallocInputs(2);
		_HasContact.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _HasContact, 0, 0);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, _HasContact, 1, 1);
		armory.logicnode.LogicNode.addLink(_HasContact, _IsTrue_004, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsTrue_004, _RemoveSceneActive, 0, 0);
		armory.logicnode.LogicNode.addLink(_RemoveSceneActive, _SetSceneActive, 0, 0);
		var _GetObjectProperty_012 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_012.preallocInputs(2);
		_GetObjectProperty_012.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, _GetObjectProperty_012, 1, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "zone"), _GetObjectProperty_012, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_012, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_012, _SetSceneActive, 0, 1);
		armory.logicnode.LogicNode.addLink(_SetSceneActive, new armory.logicnode.ObjectNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_SetSceneActive, _WriteStorage, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "spawn"), _WriteStorage, 0, 1);
		var _GetObjectLocation = new armory.logicnode.GetLocationNode(this);
		_GetObjectLocation.preallocInputs(2);
		_GetObjectLocation.preallocOutputs(1);
		var _GetObjectChild_002 = new armory.logicnode.GetChildNode(this);
		_GetObjectChild_002.property0 = "Starts With";
		_GetObjectChild_002.preallocInputs(2);
		_GetObjectChild_002.preallocOutputs(1);
		var _GetObjectbyName = new armory.logicnode.GetObjectNode(this);
		_GetObjectbyName.preallocInputs(1);
		_GetObjectbyName.preallocOutputs(1);
		var _ConcatenateString_002 = new armory.logicnode.ConcatenateStringNode(this);
		_ConcatenateString_002.preallocInputs(3);
		_ConcatenateString_002.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_012, _ConcatenateString_002, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "_"), _ConcatenateString_002, 0, 1);
		var _ArrayGet = new armory.logicnode.ArrayGetNode(this);
		_ArrayGet.preallocInputs(2);
		_ArrayGet.preallocOutputs(1);
		var _SplitString = new armory.logicnode.SplitStringNode(this);
		_SplitString.preallocInputs(2);
		_SplitString.preallocOutputs(1);
		var _String = new armory.logicnode.StringNode(this);
		_String.preallocInputs(1);
		_String.preallocOutputs(1);
		var _GetObjectName = new armory.logicnode.GetNameNode(this);
		_GetObjectName.preallocInputs(1);
		_GetObjectName.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_ArrayLoop, _GetObjectName, 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectName, _String, 0, 0);
		armory.logicnode.LogicNode.addLink(_String, _SplitString, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "_"), _SplitString, 0, 1);
		armory.logicnode.LogicNode.addLink(_SplitString, _ArrayGet, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 1), _ArrayGet, 0, 1);
		armory.logicnode.LogicNode.addLink(_ArrayGet, _ConcatenateString_002, 0, 2);
		armory.logicnode.LogicNode.addLink(_ConcatenateString_002, _GetObjectbyName, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectbyName, _GetObjectChild_002, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "spawn"), _GetObjectChild_002, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectChild_002, _GetObjectLocation, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _GetObjectLocation, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectLocation, _WriteStorage, 0, 2);
		armory.logicnode.LogicNode.addLink(_WriteStorage, _WriteStorage_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "spawn_rot"), _WriteStorage_001, 0, 1);
		var _GetObjectRotation = new armory.logicnode.GetRotationNode(this);
		_GetObjectRotation.property0 = "Local";
		_GetObjectRotation.preallocInputs(1);
		_GetObjectRotation.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_GetObjectChild_002, _GetObjectRotation, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectRotation, _WriteStorage_001, 0, 2);
		armory.logicnode.LogicNode.addLink(_WriteStorage_001, _Print_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectRotation, _Print_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_Print_001, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_017 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_017.preallocInputs(4);
		_SetObjectProperty_017.preallocOutputs(1);
		var _Gate_002 = new armory.logicnode.GateNode(this);
		_Gate_002.property0 = "Greater Equal";
		_Gate_002.property1 = 9.999999747378752e-05;
		_Gate_002.preallocInputs(3);
		_Gate_002.preallocOutputs(2);
		var _Print = new armory.logicnode.PrintNode(this);
		_Print.preallocInputs(2);
		_Print.preallocOutputs(1);
		var _OnEvent = new armory.logicnode.OnEventNode(this);
		_OnEvent.property1 = "init";
		_OnEvent.preallocInputs(1);
		_OnEvent.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "AI_DOWN"), _OnEvent, 0, 0);
		armory.logicnode.LogicNode.addLink(_OnEvent, _Print, 0, 0);
		var _ArrayLength = new armory.logicnode.ArrayLengthNode(this);
		_ArrayLength.preallocInputs(1);
		_ArrayLength.preallocOutputs(1);
		var _GetCollection_002 = new armory.logicnode.GetGroupNode(this);
		_GetCollection_002.preallocInputs(1);
		_GetCollection_002.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "active"), _GetCollection_002, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetCollection_002, _ArrayLength, 0, 0);
		armory.logicnode.LogicNode.addLink(_ArrayLength, _Print, 0, 1);
		armory.logicnode.LogicNode.addLink(_Print, _Gate_002, 0, 0);
		var _Integer = new armory.logicnode.IntegerNode(this);
		_Integer.preallocInputs(1);
		_Integer.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 1), _Integer, 0, 0);
		armory.logicnode.LogicNode.addLink(_Integer, _Gate_002, 0, 1);
		armory.logicnode.LogicNode.addLink(_ArrayLength, _Gate_002, 0, 2);
		armory.logicnode.LogicNode.addLink(_Gate_002, new armory.logicnode.NullNode(this), 1, 0);
		armory.logicnode.LogicNode.addLink(_Gate_002, _SetObjectProperty_017, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_017, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "WON"), _SetObjectProperty_017, 0, 2);
		var _Boolean_004 = new armory.logicnode.BooleanNode(this);
		_Boolean_004.preallocInputs(1);
		_Boolean_004.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _Boolean_004, 0, 0);
		armory.logicnode.LogicNode.addLink(_Boolean_004, _SetObjectProperty_017, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_017, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_006 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_006.preallocInputs(4);
		_SetObjectProperty_006.preallocOutputs(1);
		var _IsFalse_003 = new armory.logicnode.IsFalseNode(this);
		_IsFalse_003.preallocInputs(2);
		_IsFalse_003.preallocOutputs(1);
		var _Keyboard_008 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_008.property0 = "released";
		_Keyboard_008.property1 = "space";
		_Keyboard_008.preallocInputs(0);
		_Keyboard_008.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_Keyboard_008, new armory.logicnode.BooleanNode(this, false), 1, 0);
		armory.logicnode.LogicNode.addLink(_Keyboard_008, _IsFalse_003, 0, 0);
		var _GetObjectProperty_013 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_013.preallocInputs(2);
		_GetObjectProperty_013.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_013, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "tethered"), _GetObjectProperty_013, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_013, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_013, _IsFalse_003, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsFalse_003, _SetObjectProperty_006, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_006, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "grab"), _SetObjectProperty_006, 0, 2);
		var _Keyboard_009 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_009.property0 = "down";
		_Keyboard_009.property1 = "space";
		_Keyboard_009.preallocInputs(0);
		_Keyboard_009.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_Keyboard_009, new armory.logicnode.NullNode(this), 0, 0);
		armory.logicnode.LogicNode.addLink(_Keyboard_009, _SetObjectProperty_006, 1, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_006, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_005 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_005.preallocInputs(4);
		_SetObjectProperty_005.preallocOutputs(1);
		var _IsFalse_002 = new armory.logicnode.IsFalseNode(this);
		_IsFalse_002.preallocInputs(2);
		_IsFalse_002.preallocOutputs(1);
		var _Keyboard_007 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_007.property0 = "started";
		_Keyboard_007.property1 = "space";
		_Keyboard_007.preallocInputs(0);
		_Keyboard_007.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_Keyboard_007, new armory.logicnode.BooleanNode(this, false), 1, 0);
		armory.logicnode.LogicNode.addLink(_Keyboard_007, _IsFalse_002, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_013, _IsFalse_002, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsFalse_002, _SetObjectProperty_005, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_005, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "grab"), _SetObjectProperty_005, 0, 2);
		armory.logicnode.LogicNode.addLink(_Keyboard_009, _SetObjectProperty_005, 1, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_005, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_007 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_007.preallocInputs(4);
		_SetObjectProperty_007.preallocOutputs(1);
		var _SetRBVelocity = new armory.logicnode.SetVelocityNode(this);
		_SetRBVelocity.preallocInputs(6);
		_SetRBVelocity.preallocOutputs(1);
		var _IsTrue_003 = new armory.logicnode.IsTrueNode(this);
		_IsTrue_003.preallocInputs(2);
		_IsTrue_003.preallocOutputs(1);
		var _OnContactArray_001 = new armory.logicnode.OnContactArrayNode(this);
		_OnContactArray_001.property0 = "begin";
		_OnContactArray_001.preallocInputs(2);
		_OnContactArray_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _OnContactArray_001, 0, 0);
		var _GetCollection_003 = new armory.logicnode.GetGroupNode(this);
		_GetCollection_003.preallocInputs(1);
		_GetCollection_003.preallocOutputs(1);
		var _ConcatenateString_003 = new armory.logicnode.ConcatenateStringNode(this);
		_ConcatenateString_003.preallocInputs(2);
		_ConcatenateString_003.preallocOutputs(1);
		var _GetSceneActive_002 = new armory.logicnode.ActiveSceneNode(this);
		_GetSceneActive_002.preallocInputs(0);
		_GetSceneActive_002.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_GetSceneActive_002, _ConcatenateString_003, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "_GROUND"), _ConcatenateString_003, 0, 1);
		armory.logicnode.LogicNode.addLink(_ConcatenateString_003, _GetCollection_003, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetCollection_003, _OnContactArray_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_OnContactArray_001, _IsTrue_003, 0, 0);
		var _GetObjectProperty_011 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_011.preallocInputs(2);
		_GetObjectProperty_011.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_011, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "grab"), _GetObjectProperty_011, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_011, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_011, _IsTrue_003, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsTrue_003, _SetRBVelocity, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetRBVelocity, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.VectorNode(this, 0.0,0.0,0.0), _SetRBVelocity, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.VectorNode(this, 1.0,1.0,1.0), _SetRBVelocity, 0, 3);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.VectorNode(this, 0.0,0.0,0.0), _SetRBVelocity, 0, 4);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.VectorNode(this, 1.0,1.0,1.0), _SetRBVelocity, 0, 5);
		armory.logicnode.LogicNode.addLink(_SetRBVelocity, _SetObjectProperty_007, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_007, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "tethered"), _SetObjectProperty_007, 0, 2);
		var _Boolean = new armory.logicnode.BooleanNode(this);
		_Boolean.preallocInputs(1);
		_Boolean.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _Boolean, 0, 0);
		armory.logicnode.LogicNode.addLink(_Boolean, _SetObjectProperty_007, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_007, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_012 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_012.preallocInputs(4);
		_SetObjectProperty_012.preallocOutputs(1);
		var _ApplyImpulse_002 = new armory.logicnode.ApplyImpulseNode(this);
		_ApplyImpulse_002.preallocInputs(4);
		_ApplyImpulse_002.preallocOutputs(1);
		var _IsTrue_007 = new armory.logicnode.IsTrueNode(this);
		_IsTrue_007.preallocInputs(2);
		_IsTrue_007.preallocOutputs(1);
		var _Keyboard_011 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_011.property0 = "released";
		_Keyboard_011.property1 = "space";
		_Keyboard_011.preallocInputs(0);
		_Keyboard_011.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_Keyboard_011, new armory.logicnode.BooleanNode(this, false), 1, 0);
		armory.logicnode.LogicNode.addLink(_Keyboard_011, _IsTrue_007, 0, 0);
		var _GetObjectProperty_017 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_017.preallocInputs(2);
		_GetObjectProperty_017.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_017, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "launch_started"), _GetObjectProperty_017, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_017, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_017, _IsTrue_007, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsTrue_007, _ApplyImpulse_002, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _ApplyImpulse_002, 0, 1);
		var _Vector_008 = new armory.logicnode.VectorNode(this);
		_Vector_008.preallocInputs(3);
		_Vector_008.preallocOutputs(1);
		var _Math_012 = new armory.logicnode.MathNode(this);
		_Math_012.property0 = "Multiply";
		_Math_012.property1 = false;
		_Math_012.preallocInputs(2);
		_Math_012.preallocOutputs(1);
		var _GetObjectProperty_015 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_015.preallocInputs(2);
		_GetObjectProperty_015.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_015, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "launch_power"), _GetObjectProperty_015, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_015, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_015, _Math_012, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, -1.0), _Math_012, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_012, _Vector_008, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_008, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_008, 0, 2);
		armory.logicnode.LogicNode.addLink(_Vector_008, _ApplyImpulse_002, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _ApplyImpulse_002, 0, 3);
		armory.logicnode.LogicNode.addLink(_ApplyImpulse_002, _SetObjectProperty_012, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_012, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "launch_started"), _SetObjectProperty_012, 0, 2);
		var _Boolean_001 = new armory.logicnode.BooleanNode(this);
		_Boolean_001.preallocInputs(1);
		_Boolean_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _Boolean_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_Boolean_001, _SetObjectProperty_012, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_012, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_011 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_011.preallocInputs(4);
		_SetObjectProperty_011.preallocOutputs(1);
		var _IsFalse_004 = new armory.logicnode.IsFalseNode(this);
		_IsFalse_004.preallocInputs(2);
		_IsFalse_004.preallocOutputs(1);
		var _IsTrue_008 = new armory.logicnode.IsTrueNode(this);
		_IsTrue_008.preallocInputs(2);
		_IsTrue_008.preallocOutputs(1);
		var _Keyboard_012 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_012.property0 = "started";
		_Keyboard_012.property1 = "space";
		_Keyboard_012.preallocInputs(0);
		_Keyboard_012.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_Keyboard_012, new armory.logicnode.BooleanNode(this, false), 1, 0);
		armory.logicnode.LogicNode.addLink(_Keyboard_012, _IsTrue_008, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_013, _IsTrue_008, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsTrue_008, _IsFalse_004, 0, 0);
		var _GetObjectProperty_016 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_016.preallocInputs(2);
		_GetObjectProperty_016.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_016, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "launch_started"), _GetObjectProperty_016, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_016, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_016, _IsFalse_004, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsFalse_004, _SetObjectProperty_011, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_011, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "launch_started"), _SetObjectProperty_011, 0, 2);
		var _Boolean_002 = new armory.logicnode.BooleanNode(this);
		_Boolean_002.preallocInputs(1);
		_Boolean_002.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _Boolean_002, 0, 0);
		armory.logicnode.LogicNode.addLink(_Boolean_002, _SetObjectProperty_011, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_011, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_013 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_013.preallocInputs(4);
		_SetObjectProperty_013.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_ApplyImpulse_002, _SetObjectProperty_013, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_013, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "grab"), _SetObjectProperty_013, 0, 2);
		armory.logicnode.LogicNode.addLink(_Boolean_001, _SetObjectProperty_013, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_013, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_009 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_009.preallocInputs(4);
		_SetObjectProperty_009.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_ApplyImpulse_002, _SetObjectProperty_009, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_009, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "launch_power"), _SetObjectProperty_009, 0, 2);
		var _Float_002 = new armory.logicnode.FloatNode(this);
		_Float_002.preallocInputs(1);
		_Float_002.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Float_002, 0, 0);
		armory.logicnode.LogicNode.addLink(_Float_002, _SetObjectProperty_009, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_009, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_010 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_010.preallocInputs(4);
		_SetObjectProperty_010.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_ApplyImpulse_002, _SetObjectProperty_010, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_010, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "tethered"), _SetObjectProperty_010, 0, 2);
		armory.logicnode.LogicNode.addLink(_Boolean_001, _SetObjectProperty_010, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_010, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_008 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_008.preallocInputs(4);
		_SetObjectProperty_008.preallocOutputs(1);
		var _Gate_001 = new armory.logicnode.GateNode(this);
		_Gate_001.property0 = "Less";
		_Gate_001.property1 = 9.999999747378752e-05;
		_Gate_001.preallocInputs(3);
		_Gate_001.preallocOutputs(2);
		var _IsTrue_005 = new armory.logicnode.IsTrueNode(this);
		_IsTrue_005.preallocInputs(2);
		_IsTrue_005.preallocOutputs(1);
		var _Keyboard_010 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_010.property0 = "down";
		_Keyboard_010.property1 = "space";
		_Keyboard_010.preallocInputs(0);
		_Keyboard_010.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_Keyboard_010, new armory.logicnode.BooleanNode(this, false), 1, 0);
		armory.logicnode.LogicNode.addLink(_Keyboard_010, _IsTrue_005, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_017, _IsTrue_005, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsTrue_005, _Gate_001, 0, 0);
		var _Math_011 = new armory.logicnode.MathNode(this);
		_Math_011.property0 = "Add";
		_Math_011.property1 = false;
		_Math_011.preallocInputs(2);
		_Math_011.preallocOutputs(1);
		var _GetObjectProperty_014 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_014.preallocInputs(2);
		_GetObjectProperty_014.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_014, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "launch_power"), _GetObjectProperty_014, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_014, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_014, _Math_011, 0, 0);
		var _Math_013 = new armory.logicnode.MathNode(this);
		_Math_013.property0 = "Multiply";
		_Math_013.property1 = false;
		_Math_013.preallocInputs(2);
		_Math_013.preallocOutputs(1);
		var _GetApplicationTime_005 = new armory.logicnode.TimeNode(this);
		_GetApplicationTime_005.preallocInputs(0);
		_GetApplicationTime_005.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_GetApplicationTime_005, new armory.logicnode.FloatNode(this, 0.0), 0, 0);
		armory.logicnode.LogicNode.addLink(_GetApplicationTime_005, _Math_013, 1, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 10.0), _Math_013, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_013, _Math_011, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_011, _Gate_001, 0, 1);
		var _GetObjectProperty_026 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_026.preallocInputs(2);
		_GetObjectProperty_026.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_026, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "launch_power_max"), _GetObjectProperty_026, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_026, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_026, _Gate_001, 0, 2);
		armory.logicnode.LogicNode.addLink(_Gate_001, new armory.logicnode.NullNode(this), 1, 0);
		armory.logicnode.LogicNode.addLink(_Gate_001, _SetObjectProperty_008, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_008, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "launch_power"), _SetObjectProperty_008, 0, 2);
		armory.logicnode.LogicNode.addLink(_Math_011, _SetObjectProperty_008, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_008, new armory.logicnode.NullNode(this), 0, 0);
		var _TranslateObject = new armory.logicnode.TranslateObjectNode(this);
		_TranslateObject.preallocInputs(4);
		_TranslateObject.preallocOutputs(1);
		var _Keyboard_001 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_001.property0 = "down";
		_Keyboard_001.property1 = "s";
		_Keyboard_001.preallocInputs(0);
		_Keyboard_001.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_Keyboard_001, new armory.logicnode.BooleanNode(this, false), 1, 0);
		armory.logicnode.LogicNode.addLink(_Keyboard_001, _TranslateObject, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _TranslateObject, 0, 1);
		var _Vector_002 = new armory.logicnode.VectorNode(this);
		_Vector_002.preallocInputs(3);
		_Vector_002.preallocOutputs(1);
		var _Math_002 = new armory.logicnode.MathNode(this);
		_Math_002.property0 = "Multiply";
		_Math_002.property1 = false;
		_Math_002.preallocInputs(2);
		_Math_002.preallocOutputs(1);
		var _GetObjectProperty_004 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_004.preallocInputs(2);
		_GetObjectProperty_004.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_004, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "current_speed"), _GetObjectProperty_004, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_004, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_004, _Math_002, 0, 0);
		var _GetApplicationTime_001 = new armory.logicnode.TimeNode(this);
		_GetApplicationTime_001.preallocInputs(0);
		_GetApplicationTime_001.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_GetApplicationTime_001, new armory.logicnode.FloatNode(this, 0.0), 0, 0);
		armory.logicnode.LogicNode.addLink(_GetApplicationTime_001, _Math_002, 1, 1);
		armory.logicnode.LogicNode.addLink(_Math_002, _Vector_002, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_002, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_002, 0, 2);
		armory.logicnode.LogicNode.addLink(_Vector_002, _TranslateObject, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _TranslateObject, 0, 3);
		armory.logicnode.LogicNode.addLink(_TranslateObject, new armory.logicnode.NullNode(this), 0, 0);
		var _TranslateObject_002 = new armory.logicnode.TranslateObjectNode(this);
		_TranslateObject_002.preallocInputs(4);
		_TranslateObject_002.preallocOutputs(1);
		var _Keyboard_004 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_004.property0 = "down";
		_Keyboard_004.property1 = "d";
		_Keyboard_004.preallocInputs(0);
		_Keyboard_004.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_Keyboard_004, new armory.logicnode.BooleanNode(this, false), 1, 0);
		armory.logicnode.LogicNode.addLink(_Keyboard_004, _TranslateObject_002, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _TranslateObject_002, 0, 1);
		var _Vector_004 = new armory.logicnode.VectorNode(this);
		_Vector_004.preallocInputs(3);
		_Vector_004.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_004, 0, 0);
		var _Math_005 = new armory.logicnode.MathNode(this);
		_Math_005.property0 = "Multiply";
		_Math_005.property1 = false;
		_Math_005.preallocInputs(2);
		_Math_005.preallocOutputs(1);
		var _GetObjectProperty_006 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_006.preallocInputs(2);
		_GetObjectProperty_006.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_006, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "current_speed"), _GetObjectProperty_006, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_006, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_006, _Math_005, 0, 0);
		var _GetApplicationTime_004 = new armory.logicnode.TimeNode(this);
		_GetApplicationTime_004.preallocInputs(0);
		_GetApplicationTime_004.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_GetApplicationTime_004, new armory.logicnode.FloatNode(this, 0.0), 0, 0);
		armory.logicnode.LogicNode.addLink(_GetApplicationTime_004, _Math_005, 1, 1);
		armory.logicnode.LogicNode.addLink(_Math_005, _Vector_004, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_004, 0, 2);
		armory.logicnode.LogicNode.addLink(_Vector_004, _TranslateObject_002, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _TranslateObject_002, 0, 3);
		armory.logicnode.LogicNode.addLink(_TranslateObject_002, new armory.logicnode.NullNode(this), 0, 0);
		var _TranslateObject_003 = new armory.logicnode.TranslateObjectNode(this);
		_TranslateObject_003.preallocInputs(4);
		_TranslateObject_003.preallocOutputs(1);
		var _Keyboard_003 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_003.property0 = "down";
		_Keyboard_003.property1 = "a";
		_Keyboard_003.preallocInputs(0);
		_Keyboard_003.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_Keyboard_003, new armory.logicnode.BooleanNode(this, false), 1, 0);
		armory.logicnode.LogicNode.addLink(_Keyboard_003, _TranslateObject_003, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _TranslateObject_003, 0, 1);
		var _Vector_005 = new armory.logicnode.VectorNode(this);
		_Vector_005.preallocInputs(3);
		_Vector_005.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, -0.05999999865889549), _Vector_005, 0, 0);
		var _Math_006 = new armory.logicnode.MathNode(this);
		_Math_006.property0 = "Multiply";
		_Math_006.property1 = false;
		_Math_006.preallocInputs(2);
		_Math_006.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, -1.0), _Math_006, 0, 0);
		var _Math_007 = new armory.logicnode.MathNode(this);
		_Math_007.property0 = "Multiply";
		_Math_007.property1 = false;
		_Math_007.preallocInputs(2);
		_Math_007.preallocOutputs(1);
		var _GetObjectProperty_007 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_007.preallocInputs(2);
		_GetObjectProperty_007.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_007, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "current_speed"), _GetObjectProperty_007, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_007, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_007, _Math_007, 0, 0);
		var _GetApplicationTime_003 = new armory.logicnode.TimeNode(this);
		_GetApplicationTime_003.preallocInputs(0);
		_GetApplicationTime_003.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_GetApplicationTime_003, new armory.logicnode.FloatNode(this, 0.0), 0, 0);
		armory.logicnode.LogicNode.addLink(_GetApplicationTime_003, _Math_007, 1, 1);
		armory.logicnode.LogicNode.addLink(_Math_007, _Math_006, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_006, _Vector_005, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_005, 0, 2);
		armory.logicnode.LogicNode.addLink(_Vector_005, _TranslateObject_003, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _TranslateObject_003, 0, 3);
		armory.logicnode.LogicNode.addLink(_TranslateObject_003, new armory.logicnode.NullNode(this), 0, 0);
		var _ApplyImpulse_001 = new armory.logicnode.ApplyImpulseNode(this);
		_ApplyImpulse_001.preallocInputs(4);
		_ApplyImpulse_001.preallocOutputs(1);
		var _Keyboard_002 = new armory.logicnode.MergedKeyboardNode(this);
		_Keyboard_002.property0 = "down";
		_Keyboard_002.property1 = "w";
		_Keyboard_002.preallocInputs(0);
		_Keyboard_002.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_Keyboard_002, new armory.logicnode.BooleanNode(this, false), 1, 0);
		armory.logicnode.LogicNode.addLink(_Keyboard_002, _ApplyImpulse_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _ApplyImpulse_001, 0, 1);
		var _Vector_003 = new armory.logicnode.VectorNode(this);
		_Vector_003.preallocInputs(3);
		_Vector_003.preallocOutputs(1);
		var _Math_004 = new armory.logicnode.MathNode(this);
		_Math_004.property0 = "Multiply";
		_Math_004.property1 = false;
		_Math_004.preallocInputs(2);
		_Math_004.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, -1.0), _Math_004, 0, 0);
		var _Math_003 = new armory.logicnode.MathNode(this);
		_Math_003.property0 = "Multiply";
		_Math_003.property1 = false;
		_Math_003.preallocInputs(2);
		_Math_003.preallocOutputs(1);
		var _GetObjectProperty_005 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_005.preallocInputs(2);
		_GetObjectProperty_005.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_005, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "current_speed"), _GetObjectProperty_005, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_005, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_005, _Math_003, 0, 0);
		var _GetApplicationTime_002 = new armory.logicnode.TimeNode(this);
		_GetApplicationTime_002.preallocInputs(0);
		_GetApplicationTime_002.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_GetApplicationTime_002, new armory.logicnode.FloatNode(this, 0.0), 0, 0);
		armory.logicnode.LogicNode.addLink(_GetApplicationTime_002, _Math_003, 1, 1);
		armory.logicnode.LogicNode.addLink(_Math_003, _Math_004, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_004, _Vector_003, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_003, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_003, 0, 2);
		armory.logicnode.LogicNode.addLink(_Vector_003, _ApplyImpulse_001, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _ApplyImpulse_001, 0, 3);
		armory.logicnode.LogicNode.addLink(_ApplyImpulse_001, new armory.logicnode.NullNode(this), 0, 0);
		var _Clamp = new armory.logicnode.ClampNode(this);
		_Clamp.preallocInputs(3);
		_Clamp.preallocOutputs(1);
		var _Math_008 = new armory.logicnode.MathNode(this);
		_Math_008.property0 = "Add";
		_Math_008.property1 = false;
		_Math_008.preallocInputs(2);
		_Math_008.preallocOutputs(1);
		var _SeparateXYZ = new armory.logicnode.SeparateVectorNode(this);
		_SeparateXYZ.preallocInputs(1);
		_SeparateXYZ.preallocOutputs(3);
		var _GetObjectLocation_001 = new armory.logicnode.GetLocationNode(this);
		_GetObjectLocation_001.preallocInputs(2);
		_GetObjectLocation_001.preallocOutputs(1);
		var _GetObjectChild_001 = new armory.logicnode.GetChildNode(this);
		_GetObjectChild_001.property0 = "By Name";
		_GetObjectChild_001.preallocInputs(2);
		_GetObjectChild_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectChild_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "Head"), _GetObjectChild_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectChild_001, _GetObjectLocation_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _GetObjectLocation_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectLocation_001, _SeparateXYZ, 0, 0);
		armory.logicnode.LogicNode.addLink(_SeparateXYZ, _Math_008, 2, 0);
		var _Math_010 = new armory.logicnode.MathNode(this);
		_Math_010.property0 = "Divide";
		_Math_010.property1 = false;
		_Math_010.preallocInputs(2);
		_Math_010.preallocOutputs(1);
		var _GetMouseMovement_001 = new armory.logicnode.GetMouseMovementNode(this);
		_GetMouseMovement_001.preallocInputs(3);
		_GetMouseMovement_001.preallocOutputs(6);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, -1.0), _GetMouseMovement_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, -1.0), _GetMouseMovement_001, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, -1.0), _GetMouseMovement_001, 0, 2);
		armory.logicnode.LogicNode.addLink(_GetMouseMovement_001, new armory.logicnode.FloatNode(this, 0.0), 0, 0);
		armory.logicnode.LogicNode.addLink(_GetMouseMovement_001, new armory.logicnode.FloatNode(this, 0.0), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetMouseMovement_001, new armory.logicnode.FloatNode(this, 0.0), 2, 0);
		armory.logicnode.LogicNode.addLink(_GetMouseMovement_001, new armory.logicnode.FloatNode(this, 0.0), 3, 0);
		armory.logicnode.LogicNode.addLink(_GetMouseMovement_001, new armory.logicnode.FloatNode(this, 0.0), 5, 0);
		armory.logicnode.LogicNode.addLink(_GetMouseMovement_001, _Math_010, 4, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 1.5), _Math_010, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_010, _Math_008, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_008, _Clamp, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 1.899999976158142), _Clamp, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 14.0), _Clamp, 0, 2);
		armory.logicnode.LogicNode.addLink(_Clamp, new armory.logicnode.FloatNode(this, 0.0), 0, 0);
		var _SetObjectLocation = new armory.logicnode.SetLocationNode(this);
		_SetObjectLocation.preallocInputs(4);
		_SetObjectLocation.preallocOutputs(1);
		var _IsTrue_006 = new armory.logicnode.IsTrueNode(this);
		_IsTrue_006.preallocInputs(2);
		_IsTrue_006.preallocOutputs(1);
		var _OnUpdate_002 = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate_002.property0 = "Update";
		_OnUpdate_002.preallocInputs(0);
		_OnUpdate_002.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_OnUpdate_002, _IsTrue_006, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetMouseMovement_001, _IsTrue_006, 4, 1);
		armory.logicnode.LogicNode.addLink(_IsTrue_006, _SetObjectLocation, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectChild_001, _SetObjectLocation, 0, 1);
		var _Vector_007 = new armory.logicnode.VectorNode(this);
		_Vector_007.preallocInputs(3);
		_Vector_007.preallocOutputs(1);
		var _Clamp_001 = new armory.logicnode.ClampNode(this);
		_Clamp_001.preallocInputs(3);
		_Clamp_001.preallocOutputs(1);
		var _Math_009 = new armory.logicnode.MathNode(this);
		_Math_009.property0 = "Add";
		_Math_009.property1 = false;
		_Math_009.preallocInputs(2);
		_Math_009.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_SeparateXYZ, _Math_009, 0, 0);
		armory.logicnode.LogicNode.addLink(_Math_010, _Math_009, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_009, _Clamp_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 1.2000000476837158), _Clamp_001, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 13.199999809265137), _Clamp_001, 0, 2);
		armory.logicnode.LogicNode.addLink(_Clamp_001, _Vector_007, 0, 0);
		armory.logicnode.LogicNode.addLink(_SeparateXYZ, _Vector_007, 1, 1);
		armory.logicnode.LogicNode.addLink(_SeparateXYZ, _Vector_007, 2, 2);
		armory.logicnode.LogicNode.addLink(_Vector_007, _SetObjectLocation, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _SetObjectLocation, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectLocation, new armory.logicnode.NullNode(this), 0, 0);
		var _RotateObject_001 = new armory.logicnode.RotateObjectNode(this);
		_RotateObject_001.property0 = "Local";
		_RotateObject_001.preallocInputs(3);
		_RotateObject_001.preallocOutputs(1);
		var _RotateObject = new armory.logicnode.RotateObjectNode(this);
		_RotateObject.property0 = "Local";
		_RotateObject.preallocInputs(3);
		_RotateObject.preallocOutputs(1);
		var _OnUpdate = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate.property0 = "Update";
		_OnUpdate.preallocInputs(0);
		_OnUpdate.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_OnUpdate, _RotateObject, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _RotateObject, 0, 1);
		var _Rotation = new armory.logicnode.RotationNode(this);
		_Rotation.property0 = "EulerAngles";
		_Rotation.property1 = "Rad";
		_Rotation.property2 = "XYZ";
		_Rotation.preallocInputs(2);
		_Rotation.preallocOutputs(1);
		var _Vector = new armory.logicnode.VectorNode(this);
		_Vector.preallocInputs(3);
		_Vector.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector, 0, 1);
		var _GetMouseMovement = new armory.logicnode.GetMouseMovementNode(this);
		_GetMouseMovement.preallocInputs(3);
		_GetMouseMovement.preallocOutputs(6);
		var _Math = new armory.logicnode.MathNode(this);
		_Math.property0 = "Multiply";
		_Math.property1 = false;
		_Math.preallocInputs(2);
		_Math.preallocOutputs(1);
		var _Math_001 = new armory.logicnode.MathNode(this);
		_Math_001.property0 = "Multiply";
		_Math_001.property1 = false;
		_Math_001.preallocInputs(2);
		_Math_001.preallocOutputs(1);
		var _GetObjectProperty_003 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_003.preallocInputs(2);
		_GetObjectProperty_003.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_003, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "look_speed"), _GetObjectProperty_003, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_003, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_003, _Math_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, -1.0), _Math_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_001, _Math, 0, 0);
		var _GetApplicationTime = new armory.logicnode.TimeNode(this);
		_GetApplicationTime.preallocInputs(0);
		_GetApplicationTime.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_GetApplicationTime, new armory.logicnode.FloatNode(this, 0.0), 0, 0);
		armory.logicnode.LogicNode.addLink(_GetApplicationTime, _Math, 1, 1);
		armory.logicnode.LogicNode.addLink(_Math, _GetMouseMovement, 0, 0);
		armory.logicnode.LogicNode.addLink(_Math, _GetMouseMovement, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, -1.0), _GetMouseMovement, 0, 2);
		armory.logicnode.LogicNode.addLink(_GetMouseMovement, new armory.logicnode.FloatNode(this, 0.0), 0, 0);
		armory.logicnode.LogicNode.addLink(_GetMouseMovement, new armory.logicnode.FloatNode(this, 0.0), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetMouseMovement, new armory.logicnode.IntegerNode(this, 0), 4, 0);
		armory.logicnode.LogicNode.addLink(_GetMouseMovement, new armory.logicnode.FloatNode(this, 0.0), 5, 0);
		armory.logicnode.LogicNode.addLink(_GetMouseMovement, _Vector, 2, 2);
		armory.logicnode.LogicNode.addLink(_Vector, _Rotation, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Rotation, 0, 1);
		armory.logicnode.LogicNode.addLink(_Rotation, _RotateObject, 0, 2);
		armory.logicnode.LogicNode.addLink(_RotateObject, _RotateObject_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _RotateObject_001, 0, 1);
		var _Rotation_001 = new armory.logicnode.RotationNode(this);
		_Rotation_001.property0 = "EulerAngles";
		_Rotation_001.property1 = "Rad";
		_Rotation_001.property2 = "XYZ";
		_Rotation_001.preallocInputs(2);
		_Rotation_001.preallocOutputs(1);
		var _Vector_001 = new armory.logicnode.VectorNode(this);
		_Vector_001.preallocInputs(3);
		_Vector_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetMouseMovement, _Vector_001, 3, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_001, 0, 2);
		armory.logicnode.LogicNode.addLink(_Vector_001, _Rotation_001, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Rotation_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_Rotation_001, _RotateObject_001, 0, 2);
		armory.logicnode.LogicNode.addLink(_RotateObject_001, new armory.logicnode.NullNode(this), 0, 0);
		var _DrawString_001 = new armory.logicnode.DrawStringNode(this);
		_DrawString_001.preallocInputs(7);
		_DrawString_001.preallocOutputs(1);
		var _IsTrue_009 = new armory.logicnode.IsTrueNode(this);
		_IsTrue_009.preallocInputs(2);
		_IsTrue_009.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_DrawString, _IsTrue_009, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_027, _IsTrue_009, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsTrue_009, _DrawString_001, 0, 0);
		var _ConcatenateString_005 = new armory.logicnode.ConcatenateStringNode(this);
		_ConcatenateString_005.preallocInputs(2);
		_ConcatenateString_005.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "Launch Power: "), _ConcatenateString_005, 0, 0);
		var _Math_018 = new armory.logicnode.MathNode(this);
		_Math_018.property0 = "Floor";
		_Math_018.property1 = false;
		_Math_018.preallocInputs(1);
		_Math_018.preallocOutputs(1);
		var _GetObjectProperty_025 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_025.preallocInputs(2);
		_GetObjectProperty_025.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_025, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "launch_power"), _GetObjectProperty_025, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_025, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_025, _Math_018, 0, 0);
		armory.logicnode.LogicNode.addLink(_Math_018, _ConcatenateString_005, 0, 1);
		armory.logicnode.LogicNode.addLink(_ConcatenateString_005, _DrawString_001, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, ""), _DrawString_001, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 60), _DrawString_001, 0, 3);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ColorNode(this, 1.0,1.0,1.0,1.0), _DrawString_001, 0, 4);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _DrawString_001, 0, 5);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 60.0), _DrawString_001, 0, 6);
		armory.logicnode.LogicNode.addLink(_DrawString_001, new armory.logicnode.NullNode(this), 0, 0);
		var _DrawString_006 = new armory.logicnode.DrawStringNode(this);
		_DrawString_006.preallocInputs(7);
		_DrawString_006.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_OnRender2D, _DrawString_006, 0, 0);
		var _ConcatenateString_006 = new armory.logicnode.ConcatenateStringNode(this);
		_ConcatenateString_006.preallocInputs(2);
		_ConcatenateString_006.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "Power: "), _ConcatenateString_006, 0, 0);
		var _Math_023 = new armory.logicnode.MathNode(this);
		_Math_023.property0 = "Floor";
		_Math_023.property1 = false;
		_Math_023.preallocInputs(1);
		_Math_023.preallocOutputs(1);
		var _GetObjectProperty_034 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_034.preallocInputs(2);
		_GetObjectProperty_034.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_034, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "power"), _GetObjectProperty_034, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_034, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_034, _Math_023, 0, 0);
		armory.logicnode.LogicNode.addLink(_Math_023, _ConcatenateString_006, 0, 1);
		armory.logicnode.LogicNode.addLink(_ConcatenateString_006, _DrawString_006, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, ""), _DrawString_006, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.IntegerNode(this, 60), _DrawString_006, 0, 3);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ColorNode(this, 1.0,1.0,1.0,1.0), _DrawString_006, 0, 4);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _DrawString_006, 0, 5);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 120.0), _DrawString_006, 0, 6);
		armory.logicnode.LogicNode.addLink(_DrawString_006, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_014 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_014.preallocInputs(4);
		_SetObjectProperty_014.preallocOutputs(1);
		var _OnUpdate_001 = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate_001.property0 = "Update";
		_OnUpdate_001.preallocInputs(0);
		_OnUpdate_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_OnUpdate_001, _SetObjectProperty_014, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_014, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "game_tick"), _SetObjectProperty_014, 0, 2);
		var _Math_014 = new armory.logicnode.MathNode(this);
		_Math_014.property0 = "Add";
		_Math_014.property1 = false;
		_Math_014.preallocInputs(2);
		_Math_014.preallocOutputs(1);
		var _GetObjectProperty_018 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_018.preallocInputs(2);
		_GetObjectProperty_018.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_018, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "game_tick"), _GetObjectProperty_018, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_018, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_018, _Math_014, 0, 0);
		var _GetApplicationTime_006 = new armory.logicnode.TimeNode(this);
		_GetApplicationTime_006.preallocInputs(0);
		_GetApplicationTime_006.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_GetApplicationTime_006, new armory.logicnode.FloatNode(this, 0.0), 0, 0);
		armory.logicnode.LogicNode.addLink(_GetApplicationTime_006, _Math_014, 1, 1);
		armory.logicnode.LogicNode.addLink(_Math_014, _SetObjectProperty_014, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_014, new armory.logicnode.NullNode(this), 0, 0);
		var _ApplyImpulse_004 = new armory.logicnode.ApplyImpulseNode(this);
		_ApplyImpulse_004.preallocInputs(4);
		_ApplyImpulse_004.preallocOutputs(1);
		var _IsFalse_007 = new armory.logicnode.IsFalseNode(this);
		_IsFalse_007.preallocInputs(2);
		_IsFalse_007.preallocOutputs(1);
		var _ApplyImpulse_003 = new armory.logicnode.ApplyImpulseNode(this);
		_ApplyImpulse_003.preallocInputs(4);
		_ApplyImpulse_003.preallocOutputs(1);
		var _SetObjectLocation_001 = new armory.logicnode.SetLocationNode(this);
		_SetObjectLocation_001.preallocInputs(4);
		_SetObjectLocation_001.preallocOutputs(1);
		var _SetObjectRotation = new armory.logicnode.SetRotationNode(this);
		_SetObjectRotation.property0 = "Euler Angles";
		_SetObjectRotation.preallocInputs(3);
		_SetObjectRotation.preallocOutputs(1);
		var _SpawnObjectByName = new armory.logicnode.SpawnObjectByNameNode(this);
		_SpawnObjectByName.property0 = "player";
		_SpawnObjectByName.preallocInputs(4);
		_SpawnObjectByName.preallocOutputs(2);
		var _SetObjectProperty_015 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_015.preallocInputs(4);
		_SetObjectProperty_015.preallocOutputs(1);
		var _SetObjectProperty_018 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_018.preallocInputs(4);
		_SetObjectProperty_018.preallocOutputs(1);
		var _Gate_006 = new armory.logicnode.GateNode(this);
		_Gate_006.property0 = "Greater Equal";
		_Gate_006.property1 = 9.999999747378752e-05;
		_Gate_006.preallocInputs(3);
		_Gate_006.preallocOutputs(2);
		var _Gate = new armory.logicnode.GateNode(this);
		_Gate.property0 = "Greater Equal";
		_Gate.property1 = 9.999999747378752e-05;
		_Gate.preallocInputs(3);
		_Gate.preallocOutputs(2);
		var _Gate_004 = new armory.logicnode.GateNode(this);
		_Gate_004.property0 = "Greater";
		_Gate_004.property1 = 9.999999747378752e-05;
		_Gate_004.preallocInputs(3);
		_Gate_004.preallocOutputs(2);
		var _Mouse_001 = new armory.logicnode.MergedMouseNode(this);
		_Mouse_001.property0 = "down";
		_Mouse_001.property1 = "left";
		_Mouse_001.preallocInputs(0);
		_Mouse_001.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_Mouse_001, new armory.logicnode.BooleanNode(this, false), 1, 0);
		armory.logicnode.LogicNode.addLink(_Mouse_001, _Gate_004, 0, 0);
		var _GetObjectProperty_008 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_008.preallocInputs(2);
		_GetObjectProperty_008.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_008, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "life"), _GetObjectProperty_008, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_008, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_008, _Gate_004, 0, 1);
		var _Float_003 = new armory.logicnode.FloatNode(this);
		_Float_003.preallocInputs(1);
		_Float_003.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Float_003, 0, 0);
		armory.logicnode.LogicNode.addLink(_Float_003, _Gate_004, 0, 2);
		armory.logicnode.LogicNode.addLink(_Gate_004, new armory.logicnode.NullNode(this), 1, 0);
		armory.logicnode.LogicNode.addLink(_Gate_004, _Gate, 0, 0);
		var _Math_015 = new armory.logicnode.MathNode(this);
		_Math_015.property0 = "Subtract";
		_Math_015.property1 = false;
		_Math_015.preallocInputs(2);
		_Math_015.preallocOutputs(1);
		var _GetObjectProperty_020 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_020.preallocInputs(2);
		_GetObjectProperty_020.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_020, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "game_tick"), _GetObjectProperty_020, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_020, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_020, _Math_015, 0, 0);
		var _GetObjectProperty_019 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_019.preallocInputs(2);
		_GetObjectProperty_019.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_019, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "last_fire"), _GetObjectProperty_019, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_019, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_019, _Math_015, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_015, _Gate, 0, 1);
		var _GetObjectProperty_021 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_021.preallocInputs(2);
		_GetObjectProperty_021.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_021, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "fire_rate"), _GetObjectProperty_021, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_021, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_021, _Gate, 0, 2);
		armory.logicnode.LogicNode.addLink(_Gate, new armory.logicnode.NullNode(this), 1, 0);
		armory.logicnode.LogicNode.addLink(_Gate, _Gate_006, 0, 0);
		var _GetObjectProperty_035 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_035.preallocInputs(2);
		_GetObjectProperty_035.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_035, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "power"), _GetObjectProperty_035, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_035, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_035, _Gate_006, 0, 1);
		var _Float_004 = new armory.logicnode.FloatNode(this);
		_Float_004.preallocInputs(1);
		_Float_004.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 20.0), _Float_004, 0, 0);
		armory.logicnode.LogicNode.addLink(_Float_004, _Gate_006, 0, 2);
		armory.logicnode.LogicNode.addLink(_Gate_006, new armory.logicnode.NullNode(this), 1, 0);
		armory.logicnode.LogicNode.addLink(_Gate_006, _SetObjectProperty_018, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_018, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "power"), _SetObjectProperty_018, 0, 2);
		var _Math_024 = new armory.logicnode.MathNode(this);
		_Math_024.property0 = "Subtract";
		_Math_024.property1 = false;
		_Math_024.preallocInputs(2);
		_Math_024.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_035, _Math_024, 0, 0);
		armory.logicnode.LogicNode.addLink(_Float_004, _Math_024, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_024, _SetObjectProperty_018, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_018, _SetObjectProperty_015, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_015, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "last_fire"), _SetObjectProperty_015, 0, 2);
		var _GetObjectProperty_022 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_022.preallocInputs(2);
		_GetObjectProperty_022.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_022, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "game_tick"), _GetObjectProperty_022, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_022, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_022, _SetObjectProperty_015, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_015, _SpawnObjectByName, 0, 0);
		var _ConcatenateString_001 = new armory.logicnode.ConcatenateStringNode(this);
		_ConcatenateString_001.preallocInputs(2);
		_ConcatenateString_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "bullet_"), _ConcatenateString_001, 0, 0);
		var _GetObjectProperty_009 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_009.preallocInputs(2);
		_GetObjectProperty_009.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_009, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "gun_type"), _GetObjectProperty_009, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_009, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_009, _ConcatenateString_001, 0, 1);
		armory.logicnode.LogicNode.addLink(_ConcatenateString_001, _SpawnObjectByName, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.NullNode(this), _SpawnObjectByName, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _SpawnObjectByName, 0, 3);
		armory.logicnode.LogicNode.addLink(_SpawnObjectByName, _SetObjectRotation, 0, 0);
		armory.logicnode.LogicNode.addLink(_SpawnObjectByName, _SetObjectRotation, 1, 1);
		var _GetObjectRotation_001 = new armory.logicnode.GetRotationNode(this);
		_GetObjectRotation_001.property0 = "Local";
		_GetObjectRotation_001.preallocInputs(1);
		_GetObjectRotation_001.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectRotation_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectRotation_001, _SetObjectRotation, 0, 2);
		armory.logicnode.LogicNode.addLink(_SetObjectRotation, _SetObjectLocation_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_SpawnObjectByName, _SetObjectLocation_001, 1, 1);
		var _GetObjectLocation_002 = new armory.logicnode.GetLocationNode(this);
		_GetObjectLocation_002.preallocInputs(2);
		_GetObjectLocation_002.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectLocation_002, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _GetObjectLocation_002, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectLocation_002, _SetObjectLocation_001, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _SetObjectLocation_001, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectLocation_001, _ApplyImpulse_003, 0, 0);
		armory.logicnode.LogicNode.addLink(_SpawnObjectByName, _ApplyImpulse_003, 1, 1);
		var _VectorMath = new armory.logicnode.VectorMathNode(this);
		_VectorMath.property0 = "Add";
		_VectorMath.property1 = false;
		_VectorMath.preallocInputs(2);
		_VectorMath.preallocOutputs(1);
		var _Vector_009 = new armory.logicnode.VectorNode(this);
		_Vector_009.preallocInputs(3);
		_Vector_009.preallocOutputs(1);
		var _Math_016 = new armory.logicnode.MathNode(this);
		_Math_016.property0 = "Multiply";
		_Math_016.property1 = false;
		_Math_016.preallocInputs(2);
		_Math_016.preallocOutputs(1);
		var _GetObjectProperty_023 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_023.preallocInputs(2);
		_GetObjectProperty_023.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_023, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "fire_speed"), _GetObjectProperty_023, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_023, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_023, _Math_016, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, -1.0), _Math_016, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_016, _Vector_009, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_009, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_009, 0, 2);
		armory.logicnode.LogicNode.addLink(_Vector_009, _VectorMath, 0, 0);
		var _Vector_011 = new armory.logicnode.VectorNode(this);
		_Vector_011.preallocInputs(3);
		_Vector_011.preallocOutputs(1);
		var _SeparateXYZ_001 = new armory.logicnode.SeparateVectorNode(this);
		_SeparateXYZ_001.preallocInputs(1);
		_SeparateXYZ_001.preallocOutputs(3);
		var _GetRBVelocity = new armory.logicnode.GetVelocityNode(this);
		_GetRBVelocity.preallocInputs(3);
		_GetRBVelocity.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetRBVelocity, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _GetRBVelocity, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, false), _GetRBVelocity, 0, 2);
		armory.logicnode.LogicNode.addLink(_GetRBVelocity, new armory.logicnode.VectorNode(this, 0.0,0.0,0.0), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetRBVelocity, _SeparateXYZ_001, 0, 0);
		armory.logicnode.LogicNode.addLink(_SeparateXYZ_001, new armory.logicnode.FloatNode(this, 0.0), 1, 0);
		armory.logicnode.LogicNode.addLink(_SeparateXYZ_001, new armory.logicnode.FloatNode(this, 0.0), 2, 0);
		armory.logicnode.LogicNode.addLink(_SeparateXYZ_001, _Vector_011, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_011, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_011, 0, 2);
		armory.logicnode.LogicNode.addLink(_Vector_011, _VectorMath, 0, 1);
		armory.logicnode.LogicNode.addLink(_VectorMath, _ApplyImpulse_003, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _ApplyImpulse_003, 0, 3);
		armory.logicnode.LogicNode.addLink(_ApplyImpulse_003, _IsFalse_007, 0, 0);
		var _GetObjectProperty_029 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_029.preallocInputs(2);
		_GetObjectProperty_029.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_029, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "tethered"), _GetObjectProperty_029, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_029, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_029, _IsFalse_007, 0, 1);
		armory.logicnode.LogicNode.addLink(_IsFalse_007, _ApplyImpulse_004, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _ApplyImpulse_004, 0, 1);
		var _Vector_010 = new armory.logicnode.VectorNode(this);
		_Vector_010.preallocInputs(3);
		_Vector_010.preallocOutputs(1);
		var _Math_017 = new armory.logicnode.MathNode(this);
		_Math_017.property0 = "Multiply";
		_Math_017.property1 = false;
		_Math_017.preallocInputs(2);
		_Math_017.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_023, _Math_017, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.10000000149011612), _Math_017, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_017, _Vector_010, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_010, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.FloatNode(this, 0.0), _Vector_010, 0, 2);
		armory.logicnode.LogicNode.addLink(_Vector_010, _ApplyImpulse_004, 0, 2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.BooleanNode(this, true), _ApplyImpulse_004, 0, 3);
		armory.logicnode.LogicNode.addLink(_ApplyImpulse_004, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_003 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_003.preallocInputs(4);
		_SetObjectProperty_003.preallocOutputs(1);
		var _Gate_005 = new armory.logicnode.GateNode(this);
		_Gate_005.property0 = "Less";
		_Gate_005.property1 = 9.999999747378752e-05;
		_Gate_005.preallocInputs(3);
		_Gate_005.preallocOutputs(2);
		var _OnUpdate_003 = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate_003.property0 = "Update";
		_OnUpdate_003.preallocInputs(0);
		_OnUpdate_003.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_OnUpdate_003, _Gate_005, 0, 0);
		var _Math_022 = new armory.logicnode.MathNode(this);
		_Math_022.property0 = "Add";
		_Math_022.property1 = false;
		_Math_022.preallocInputs(2);
		_Math_022.preallocOutputs(1);
		var _GetObjectProperty_032 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_032.preallocInputs(2);
		_GetObjectProperty_032.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_032, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "power"), _GetObjectProperty_032, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_032, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_032, _Math_022, 0, 0);
		var _Math_021 = new armory.logicnode.MathNode(this);
		_Math_021.property0 = "Multiply";
		_Math_021.property1 = false;
		_Math_021.preallocInputs(2);
		_Math_021.preallocOutputs(1);
		var _GetObjectProperty_010 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_010.preallocInputs(2);
		_GetObjectProperty_010.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_010, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "power_regen"), _GetObjectProperty_010, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_010, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_010, _Math_021, 0, 0);
		var _GetApplicationTime_007 = new armory.logicnode.TimeNode(this);
		_GetApplicationTime_007.preallocInputs(0);
		_GetApplicationTime_007.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(_GetApplicationTime_007, new armory.logicnode.FloatNode(this, 0.0), 0, 0);
		armory.logicnode.LogicNode.addLink(_GetApplicationTime_007, _Math_021, 1, 1);
		armory.logicnode.LogicNode.addLink(_Math_021, _Math_022, 0, 1);
		armory.logicnode.LogicNode.addLink(_Math_022, _Gate_005, 0, 1);
		var _GetObjectProperty_033 = new armory.logicnode.GetPropertyNode(this);
		_GetObjectProperty_033.preallocInputs(2);
		_GetObjectProperty_033.preallocOutputs(2);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _GetObjectProperty_033, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "max_power"), _GetObjectProperty_033, 0, 1);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_033, new armory.logicnode.StringNode(this, ""), 1, 0);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_033, _Gate_005, 0, 2);
		armory.logicnode.LogicNode.addLink(_Gate_005, _SetObjectProperty_003, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_003, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "power"), _SetObjectProperty_003, 0, 2);
		armory.logicnode.LogicNode.addLink(_Math_022, _SetObjectProperty_003, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_003, new armory.logicnode.NullNode(this), 0, 0);
		var _SetObjectProperty_004 = new armory.logicnode.SetPropertyNode(this);
		_SetObjectProperty_004.preallocInputs(4);
		_SetObjectProperty_004.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_Gate_005, _SetObjectProperty_004, 1, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, ""), _SetObjectProperty_004, 0, 1);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.StringNode(this, "power"), _SetObjectProperty_004, 0, 2);
		armory.logicnode.LogicNode.addLink(_GetObjectProperty_033, _SetObjectProperty_004, 0, 3);
		armory.logicnode.LogicNode.addLink(_SetObjectProperty_004, new armory.logicnode.NullNode(this), 0, 0);
		var _PlaySpeaker = new armory.logicnode.PlaySoundNode(this);
		_PlaySpeaker.preallocInputs(2);
		_PlaySpeaker.preallocOutputs(1);
		armory.logicnode.LogicNode.addLink(_ApplyImpulse_003, _PlaySpeaker, 0, 0);
		armory.logicnode.LogicNode.addLink(new armory.logicnode.ObjectNode(this, "Speaker"), _PlaySpeaker, 0, 1);
		armory.logicnode.LogicNode.addLink(_PlaySpeaker, new armory.logicnode.NullNode(this), 0, 0);
	}
}