#include "wayland-protocol.c.h"
#include "wayland-viewporter.c.h"
#include "xdg-shell.c.h"
#include "xdg-decoration.c.h"
#include "wayland-tablet.c.h"
#include "wayland-pointer-constraint.c.h"
#include "wayland-relative-pointer.c.h"
