// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <kha/graphics4/VertexStructure.h>
extern hl_type t$hl_types_ArrayObj;
void hl_types_ArrayObj_new(hl__types__ArrayObj);
#include <kha/graphics4/VertexElement.h>
extern hl_type t$kha_graphics4_VertexElement;
void kha_graphics4_VertexElement_new(kha__graphics4__VertexElement,String,int);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
int kha_graphics4_VertexStructure_dataByteSize(int);

void kha_graphics4_VertexStructure_new(kha__graphics4__VertexStructure r0) {
	hl__types__ArrayObj r1;
	bool r3;
	r1 = (hl__types__ArrayObj)hl_alloc_obj(&t$hl_types_ArrayObj);
	hl_types_ArrayObj_new(r1);
	r0->elements = r1;
	r3 = false;
	r0->instanced = r3;
	return;
}

void kha_graphics4_VertexStructure_add(kha__graphics4__VertexStructure r0,String r1,int r2) {
	hl__types__ArrayObj r4;
	kha__graphics4__VertexElement r5;
	int r3;
	r4 = r0->elements;
	if( r4 == NULL ) hl_null_access();
	r5 = (kha__graphics4__VertexElement)hl_alloc_obj(&t$kha_graphics4_VertexElement);
	kha_graphics4_VertexElement_new(r5,r1,r2);
	r3 = hl_types_ArrayObj_push(r4,((vdynamic*)r5));
	return;
}

int kha_graphics4_VertexStructure_size(kha__graphics4__VertexStructure r0) {
	hl__types__ArrayObj r2;
	int r1;
	r2 = r0->elements;
	if( r2 == NULL ) hl_null_access();
	r1 = r2->length;
	return r1;
}

int kha_graphics4_VertexStructure_byteSize(kha__graphics4__VertexStructure r0) {
	hl__types__ArrayObj r4;
	kha__graphics4__VertexElement r9;
	vdynamic *r10;
	varray *r11;
	int r1, r2, r3, r5, r6, r7, r8;
	r1 = 0;
	r2 = 0;
	r4 = r0->elements;
	if( r4 == NULL ) hl_null_access();
	r3 = r4->length;
	label$eb3330f_4_5:
	if( r2 >= r3 ) goto label$eb3330f_4_24;
	r5 = r2;
	++r2;
	r4 = r0->elements;
	if( r4 == NULL ) hl_null_access();
	r8 = r4->length;
	if( ((unsigned)r5) < ((unsigned)r8) ) goto label$eb3330f_4_15;
	r9 = NULL;
	goto label$eb3330f_4_18;
	label$eb3330f_4_15:
	r11 = r4->array;
	r10 = ((vdynamic**)(r11 + 1))[r5];
	r9 = (kha__graphics4__VertexElement)r10;
	label$eb3330f_4_18:
	if( r9 == NULL ) hl_null_access();
	r7 = r9->data;
	r7 = kha_graphics4_VertexStructure_dataByteSize(r7);
	r6 = r1 + r7;
	r1 = r6;
	goto label$eb3330f_4_5;
	label$eb3330f_4_24:
	return r1;
}

int kha_graphics4_VertexStructure_dataByteSize(int r0) {
	int r1;
	switch(r0) {
		default:
			goto label$eb3330f_5_32;
		case 0:
			r1 = 4;
			return r1;
		case 1:
			r1 = 8;
			return r1;
		case 2:
			r1 = 12;
			return r1;
		case 3:
			r1 = 16;
			return r1;
		case 4:
			r1 = 64;
			return r1;
		case 5:
		case 6:
		case 7:
		case 8:
			r1 = 1;
			return r1;
		case 9:
		case 10:
		case 11:
		case 12:
			r1 = 2;
			return r1;
		case 13:
		case 14:
		case 15:
		case 16:
			r1 = 4;
			return r1;
		case 17:
		case 18:
		case 19:
		case 20:
			r1 = 2;
			return r1;
		case 21:
		case 22:
		case 23:
		case 24:
			r1 = 4;
			return r1;
		case 25:
		case 26:
		case 27:
		case 28:
			r1 = 8;
			return r1;
		case 29:
		case 30:
			r1 = 4;
			return r1;
		case 31:
		case 32:
			r1 = 8;
			return r1;
		case 33:
		case 34:
			r1 = 12;
			return r1;
		case 35:
		case 36:
			r1 = 16;
			return r1;
	}
	label$eb3330f_5_32:
	r1 = 0;
	return r1;
}

kha__graphics4__VertexElement kha_graphics4_VertexStructure_get(kha__graphics4__VertexStructure r0,int r1) {
	hl__types__ArrayObj r2;
	kha__graphics4__VertexElement r4;
	vdynamic *r5;
	varray *r6;
	int r3;
	r2 = r0->elements;
	if( r2 == NULL ) hl_null_access();
	r3 = r2->length;
	if( ((unsigned)r1) < ((unsigned)r3) ) goto label$eb3330f_6_6;
	r4 = NULL;
	goto label$eb3330f_6_9;
	label$eb3330f_6_6:
	r6 = r2->array;
	r5 = ((vdynamic**)(r6 + 1))[r1];
	r4 = (kha__graphics4__VertexElement)r5;
	label$eb3330f_6_9:
	return r4;
}

