// Generated by HLC 4.2.5 (HL v4)
#ifndef INC_iron__data__ShaderContext
#define INC_iron__data__ShaderContext
typedef struct _iron__data__$ShaderContext *iron__data__$ShaderContext;
typedef struct _iron__data__ShaderContext *iron__data__ShaderContext;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <iron/data/TShaderContext.h>
#include <kha/graphics4/PipelineState.h>
#include <hl/types/ArrayObj.h>
#include <iron/data/TShaderOverride.h>
#include <kha/graphics4/VertexStructure.h>


struct _iron__data__$ShaderContext {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	vclosure* parseData;
};
struct _iron__data__ShaderContext {
	hl_type *$type;
	iron__data__TShaderContext raw;
	kha__graphics4__PipelineState pipeState;
	hl__types__ArrayObj constants;
	hl__types__ArrayObj textureUnits;
	iron__data__TShaderOverride overrideContext;
	kha__graphics4__VertexStructure structure;
	int instancingType;
};
#endif

