// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/data/TBindConstant.h>

void iron_data_TBindConstant_new(iron__data__TBindConstant r0,String r1,kha__arrays__ByteArrayPrivate r2,kha__arrays__ByteArrayPrivate r3,kha__arrays__ByteArrayPrivate r4,vdynamic* r5,vdynamic* r6,vdynamic* r7) {
	r0->name = r1;
	r0->vec4Value = r2;
	r0->vec3Value = r3;
	r0->vec2Value = r4;
	r0->floatValue = r5;
	r0->boolValue = r6;
	r0->intValue = r7;
	return;
}

