// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/data/TConstraint.h>

void iron_data_TConstraint_new(iron__data__TConstraint r0,String r1,String r2,String r3,String r4,vdynamic* r5,vdynamic* r6,vdynamic* r7,vdynamic* r8,vdynamic* r9,vdynamic* r10,vdynamic* r11,vdynamic* r12) {
	r0->name = r1;
	r0->type = r2;
	r0->bone = r3;
	r0->target = r4;
	r0->use_x = r5;
	r0->use_y = r6;
	r0->use_z = r7;
	r0->invert_x = r8;
	r0->invert_y = r9;
	r0->invert_z = r10;
	r0->use_offset = r11;
	r0->influence = r12;
	return;
}

