// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/data/TLightData.h>

void iron_data_TLightData_new(iron__data__TLightData r0,String r1,String r2,kha__arrays__ByteArrayPrivate r3,float r4,vdynamic* r5,vdynamic* r6,vdynamic* r7,vdynamic* r8,vdynamic* r9,vdynamic* r10,vdynamic* r11,vdynamic* r12,vdynamic* r13,vdynamic* r14,vdynamic* r15,vdynamic* r16) {
	r0->name = r1;
	r0->type = r2;
	r0->color = r3;
	r0->strength = r4;
	r0->cast_shadow = r5;
	r0->near_plane = r6;
	r0->far_plane = r7;
	r0->fov = r8;
	r0->shadows_bias = r9;
	r0->shadowmap_size = r10;
	r0->shadowmap_cube = r11;
	r0->spot_size = r12;
	r0->spot_blend = r13;
	r0->light_size = r14;
	r0->size = r15;
	r0->size_y = r16;
	return;
}

