// Generated by HLC 4.2.5 (HL v4)
#ifndef INC_iron__data__TLod
#define INC_iron__data__TLod
typedef struct _iron__data__$TLod *iron__data__$TLod;
typedef struct _iron__data__TLod *iron__data__TLod;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>


struct _iron__data__$TLod {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
};
struct _iron__data__TLod {
	hl_type *$type;
	String object_ref;
	float screen_size;
};
#endif

