// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/data/TMaterialContext.h>

void iron_data_TMaterialContext_new(iron__data__TMaterialContext r0,String r1,vdynamic* r2,hl__types__ArrayObj r3,hl__types__ArrayObj r4) {
	r0->name = r1;
	r0->depth_read = r2;
	r0->bind_constants = r3;
	r0->bind_textures = r4;
	return;
}

