// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/data/TProperty.h>

void iron_data_TProperty_new(iron__data__TProperty r0,String r1,vdynamic* r2) {
	r0->name = r1;
	r0->value = r2;
	return;
}

