// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/data/TSceneFormat.h>

void iron_data_TSceneFormat_new(iron__data__TSceneFormat r0,String r1,hl__types__ArrayObj r2,hl__types__ArrayObj r3,hl__types__ArrayObj r4,hl__types__ArrayObj r5,String r6,hl__types__ArrayObj r7,hl__types__ArrayObj r8,hl__types__ArrayObj r9,hl__types__ArrayObj r10,hl__types__ArrayObj r11,String r12,hl__types__ArrayObj r13,hl__types__ArrayObj r14,hl__types__ArrayObj r15,kha__arrays__ByteArrayPrivate r16,hl__types__ArrayObj r17,hl__types__ArrayObj r18,vdynamic* r19,kha__arrays__ByteArrayPrivate r20,hl__types__ArrayObj r21,String r22) {
	r0->name = r1;
	r0->mesh_datas = r2;
	r0->light_datas = r3;
	r0->probe_datas = r4;
	r0->camera_datas = r5;
	r0->camera_ref = r6;
	r0->material_datas = r7;
	r0->particle_datas = r8;
	r0->shader_datas = r9;
	r0->speaker_datas = r10;
	r0->world_datas = r11;
	r0->world_ref = r12;
	r0->tilesheet_datas = r13;
	r0->objects = r14;
	r0->groups = r15;
	r0->gravity = r16;
	r0->traits = r17;
	r0->embedded_datas = r18;
	r0->frame_time = r19;
	r0->irradiance = r20;
	r0->terrain_datas = r21;
	r0->terrain_ref = r22;
	return;
}

