// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/data/TShaderConstant.h>

void iron_data_TShaderConstant_new(iron__data__TShaderConstant r0,String r1,String r2,String r3,kha__arrays__ByteArrayPrivate r4,kha__arrays__ByteArrayPrivate r5,kha__arrays__ByteArrayPrivate r6,vdynamic* r7,vdynamic* r8,vdynamic* r9,vdynamic* r10) {
	r0->name = r1;
	r0->type = r2;
	r0->link = r3;
	r0->vec4Value = r4;
	r0->vec3Value = r5;
	r0->vec2Value = r6;
	r0->floatValue = r7;
	r0->boolValue = r8;
	r0->intValue = r9;
	r0->is_arm_parameter = r10;
	return;
}

