// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/data/TShaderData.h>

void iron_data_TShaderData_new(iron__data__TShaderData r0,String r1,hl__types__ArrayObj r2) {
	r0->name = r1;
	r0->contexts = r2;
	return;
}

