// Generated by HLC 4.2.5 (HL v4)
#ifndef INC_armory__trait__internal__LoadingScreen
#define INC_armory__trait__internal__LoadingScreen
typedef struct _armory__trait__internal__$LoadingScreen *armory__trait__internal__$LoadingScreen;
typedef struct _armory__trait__internal__LoadingScreen *armory__trait__internal__LoadingScreen;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <kha/graphics2/Graphics.h>


struct _armory__trait__internal__$LoadingScreen {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	vclosure* render;
};
struct _armory__trait__internal__LoadingScreen {
	hl_type *$type;
};
#endif

