// Generated by HLC 4.2.5 (HL v4)
#ifndef INC_armory__trait__WalkNavigation
#define INC_armory__trait__WalkNavigation
typedef struct _armory__trait__$WalkNavigation *armory__trait__$WalkNavigation;
typedef struct _armory__trait__WalkNavigation *armory__trait__WalkNavigation;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <iron/Trait.h>
#include <iron/object/Object.h>
#include <hl/types/ArrayObj.h>
#include <iron/math/Vec4.h>
#include <iron/object/CameraObject.h>
#include <iron/system/Keyboard.h>
#include <iron/system/Gamepad.h>
#include <iron/system/Mouse.h>


struct _armory__trait__$WalkNavigation {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	bool enabled;
	String keyUp;
	String keyDown;
	String keyLeft;
	String keyRight;
	String keyStrafeUp;
	String keyStrafeDown;
};
struct _armory__trait__WalkNavigation {
	hl_type *$type;
	iron__object__Object object;
	hl__types__ArrayObj _add;
	hl__types__ArrayObj _init;
	hl__types__ArrayObj _remove;
	hl__types__ArrayObj _update;
	hl__types__ArrayObj _lateUpdate;
	hl__types__ArrayObj _render;
	hl__types__ArrayObj _render2D;
	double speed;
	iron__math__Vec4 dir;
	iron__math__Vec4 xvec;
	iron__math__Vec4 yvec;
	double ease;
	iron__object__CameraObject camera;
	iron__system__Keyboard keyboard;
	iron__system__Gamepad gamepad;
	iron__system__Mouse mouse;
};
#endif

