// Generated by HLC 4.2.5 (HL v4)
#ifndef INC_armory__ui__Canvas
#define INC_armory__ui__Canvas
typedef struct _armory__ui__$Canvas *armory__ui__$Canvas;
typedef struct _armory__ui__Canvas *armory__ui__Canvas;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <haxe/ds/IntMap.h>
#include <hl/types/ArrayObj.h>
#include <zui/Zui.h>
#include <zui/Handle.h>
#include <kha/graphics2/Graphics.h>
#include <hl/types/ArrayBytes_Int.h>
#include <kha/internal/BytesBlob.h>
#include <hl/types/ArrayBytes_Float.h>


struct _armory__ui__$Canvas {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	haxe__ds__IntMap assetMap;
	hl__types__ArrayObj themes;
	hl__types__ArrayObj events;
	int screenW;
	int screenH;
	int imageScaleQuality;
	zui__Zui _ui;
	zui__Handle h;
	vclosure* draw;
	vclosure* drawElement;
	vclosure* parseCanvasFromBlob;
	vclosure* getAsset;
	vclosure* elemById;
	vclosure* getTheme;
	vclosure* getAnchorOffset;
};
struct _armory__ui__Canvas {
	hl_type *$type;
};
#endif

