// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <kha/audio2/Audio.h>
extern hl_type t$kha_audio2_Buffer;
extern kha__audio2__$Audio g$_kha_audio2_Audio;
void kha_audio2_Buffer_new(kha__audio2__Buffer,int,int,int);
#include <kha/arrays/ByteArrayPrivate.h>
#include <hl/natives.h>

void kha_audio2_Audio__init() {
	kha__audio2__$Audio r6;
	kha__audio2__Buffer r2;
	int r0, r3, r4, r5;
	r0 = 2048;
	r2 = (kha__audio2__Buffer)hl_alloc_obj(&t$kha_audio2_Buffer);
	r4 = 4;
	r3 = r0 * r4;
	r4 = 2;
	r6 = (kha__audio2__$Audio)g$_kha_audio2_Audio;
	r5 = r6->samplesPerSecond;
	kha_audio2_Buffer_new(r2,r3,r4,r5);
	r6 = (kha__audio2__$Audio)g$_kha_audio2_Audio;
	r6->buffer = r2;
	return;
}

void kha_audio2_Audio__callCallback(int r0) {
	kha__audio2__$Audio r3;
	kha__internal__IntBox r5;
	kha__arrays__ByteArrayPrivate r9;
	kha__audio2__Buffer r2;
	float r13;
	vclosure *r4;
	vbyte *r10;
	int r6, r7, r8, r11, r12;
	r3 = (kha__audio2__$Audio)g$_kha_audio2_Audio;
	r2 = r3->buffer;
	if( r2 ) goto label$6ed06f1_2_4;
	return;
	label$6ed06f1_2_4:
	r3 = (kha__audio2__$Audio)g$_kha_audio2_Audio;
	r4 = r3->audioCallback;
	if( !r4 ) goto label$6ed06f1_2_20;
	r3 = (kha__audio2__$Audio)g$_kha_audio2_Audio;
	r5 = r3->intBox;
	if( r5 == NULL ) hl_null_access();
	r5->value = r0;
	r3 = (kha__audio2__$Audio)g$_kha_audio2_Audio;
	r4 = r3->audioCallback;
	if( r4 == NULL ) hl_null_access();
	r3 = (kha__audio2__$Audio)g$_kha_audio2_Audio;
	r5 = r3->intBox;
	r3 = (kha__audio2__$Audio)g$_kha_audio2_Audio;
	r2 = r3->buffer;
	r4->hasValue ? ((void (*)(vdynamic*,kha__internal__IntBox,kha__audio2__Buffer))r4->fun)((vdynamic*)r4->value,r5,r2) : ((void (*)(kha__internal__IntBox,kha__audio2__Buffer))r4->fun)(r5,r2);
	goto label$6ed06f1_2_64;
	label$6ed06f1_2_20:
	r6 = 0;
	r7 = r0;
	label$6ed06f1_2_22:
	if( r6 >= r7 ) goto label$6ed06f1_2_64;
	++r6;
	r3 = (kha__audio2__$Audio)g$_kha_audio2_Audio;
	r2 = r3->buffer;
	if( r2 == NULL ) hl_null_access();
	r9 = r2->data;
	if( r9 == NULL ) hl_null_access();
	r10 = r9->self;
	r8 = r9->byteArrayOffset;
	r3 = (kha__audio2__$Audio)g$_kha_audio2_Audio;
	r2 = r3->buffer;
	if( r2 == NULL ) hl_null_access();
	r11 = r2->writeLocation;
	r12 = 4;
	r11 = r11 * r12;
	r8 = r8 + r11;
	r11 = 0;
	r13 = (float)r11;
	hl_kinc_bytearray_setfloat32(r10,r8,r13);
	r3 = (kha__audio2__$Audio)g$_kha_audio2_Audio;
	r2 = r3->buffer;
	if( r2 == NULL ) hl_null_access();
	r8 = r2->writeLocation;
	r11 = 1;
	r8 = r8 + r11;
	r2->writeLocation = r8;
	r3 = (kha__audio2__$Audio)g$_kha_audio2_Audio;
	r2 = r3->buffer;
	if( r2 == NULL ) hl_null_access();
	r8 = r2->writeLocation;
	r3 = (kha__audio2__$Audio)g$_kha_audio2_Audio;
	r2 = r3->buffer;
	if( r2 == NULL ) hl_null_access();
	r11 = r2->size;
	if( r8 < r11 ) goto label$6ed06f1_2_63;
	r3 = (kha__audio2__$Audio)g$_kha_audio2_Audio;
	r2 = r3->buffer;
	if( r2 == NULL ) hl_null_access();
	r8 = 0;
	r2->writeLocation = r8;
	label$6ed06f1_2_63:
	goto label$6ed06f1_2_22;
	label$6ed06f1_2_64:
	return;
}

float kha_audio2_Audio__readSample() {
	kha__audio2__$Audio r1;
	kha__arrays__ByteArrayPrivate r4;
	kha__audio2__Buffer r0;
	float r3;
	vbyte *r5;
	int r2, r6, r7;
	r1 = (kha__audio2__$Audio)g$_kha_audio2_Audio;
	r0 = r1->buffer;
	if( r0 ) goto label$6ed06f1_3_6;
	r2 = 0;
	r3 = (float)r2;
	return r3;
	label$6ed06f1_3_6:
	r1 = (kha__audio2__$Audio)g$_kha_audio2_Audio;
	r0 = r1->buffer;
	if( r0 == NULL ) hl_null_access();
	r4 = r0->data;
	if( r4 == NULL ) hl_null_access();
	r5 = r4->self;
	r2 = r4->byteArrayOffset;
	r1 = (kha__audio2__$Audio)g$_kha_audio2_Audio;
	r0 = r1->buffer;
	if( r0 == NULL ) hl_null_access();
	r6 = r0->readLocation;
	r7 = 4;
	r6 = r6 * r7;
	r2 = r2 + r6;
	r3 = hl_kinc_bytearray_getfloat32(r5,r2);
	r1 = (kha__audio2__$Audio)g$_kha_audio2_Audio;
	r0 = r1->buffer;
	if( r0 == NULL ) hl_null_access();
	r2 = r0->readLocation;
	++r2;
	r0->readLocation = r2;
	r1 = (kha__audio2__$Audio)g$_kha_audio2_Audio;
	r0 = r1->buffer;
	if( r0 == NULL ) hl_null_access();
	r2 = r0->readLocation;
	r1 = (kha__audio2__$Audio)g$_kha_audio2_Audio;
	r0 = r1->buffer;
	if( r0 == NULL ) hl_null_access();
	r6 = r0->size;
	if( r2 < r6 ) goto label$6ed06f1_3_41;
	r1 = (kha__audio2__$Audio)g$_kha_audio2_Audio;
	r0 = r1->buffer;
	if( r0 == NULL ) hl_null_access();
	r2 = 0;
	r0->readLocation = r2;
	label$6ed06f1_3_41:
	return r3;
}

vvirtual* kha_audio2_Audio_stream(kha__Sound r0,bool* r1) {
	vvirtual *r3;
	bool r2;
	if( r1 ) goto label$6ed06f1_4_3;
	r2 = false;
	goto label$6ed06f1_4_4;
	label$6ed06f1_4_3:
	r2 = *r1;
	label$6ed06f1_4_4:
	r3 = NULL;
	return r3;
}

