// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <kha/audio2/ResamplingAudioChannel.h>
void kha_audio2_AudioChannel_new(kha__audio2__AudioChannel,bool);
#include <hl/natives.h>
void kha_audio2_Audio1__playAgain(kha__audio2__AudioChannel);

void kha_audio2_ResamplingAudioChannel_new(kha__audio2__ResamplingAudioChannel r0,bool r1,int r2) {
	kha_audio2_AudioChannel_new(((kha__audio2__AudioChannel)r0),r1);
	r0->sampleRate = r2;
	return;
}

void kha_audio2_ResamplingAudioChannel_nextSamples(kha__audio2__ResamplingAudioChannel r0,kha__arrays__ByteArrayPrivate r1,int r2,int r3) {
	bool r5;
	kha__arrays__ByteArrayPrivate r11;
	float r14, r27, r29, r31;
	double r15, r16, r17, r22, r30, r32;
	vbyte *r10;
	int r6, r7, r8, r9, r12, r13, r18, r19, r20, r21, r23, r24, r25, r26, r28;
	r5 = r0->paused;
	if( r5 ) goto label$2f9bd3c_2_4;
	r5 = r0->stopped;
	if( !r5 ) goto label$2f9bd3c_2_21;
	label$2f9bd3c_2_4:
	r6 = 0;
	r7 = r2;
	label$2f9bd3c_2_6:
	if( r6 >= r7 ) goto label$2f9bd3c_2_20;
	r8 = r6;
	++r6;
	if( r1 == NULL ) hl_null_access();
	r10 = r1->self;
	r9 = r1->byteArrayOffset;
	r13 = 4;
	r12 = r8 * r13;
	r9 = r9 + r12;
	r12 = 0;
	r14 = (float)r12;
	hl_kinc_bytearray_setfloat32(r10,r9,r14);
	goto label$2f9bd3c_2_6;
	label$2f9bd3c_2_20:
	return;
	label$2f9bd3c_2_21:
	r6 = 0;
	label$2f9bd3c_2_22:
	if( r6 >= r2 ) goto label$2f9bd3c_2_251;
	r7 = 0;
	r11 = r0->data;
	if( r11 == NULL ) hl_null_access();
	r8 = r11->byteArrayLength;
	r9 = 2;
	r8 = r8 >> r9;
	r15 = (double)r8;
	r16 = (double)r3;
	r8 = r0->sampleRate;
	r17 = (double)r8;
	r16 = r16 / r17;
	r15 = r15 * r16;
	r8 = hl_math_ceil(r15);
	r12 = 2;
	r9 = r12 == 0 ? 0 : r8 % r12;
	r12 = 0;
	if( r9 != r12 ) goto label$2f9bd3c_2_43;
	r9 = r8;
	goto label$2f9bd3c_2_45;
	label$2f9bd3c_2_43:
	r12 = 1;
	r9 = r8 + r12;
	label$2f9bd3c_2_45:
	r12 = r0->myPosition;
	r9 = r9 - r12;
	r12 = r2 - r6;
	if( r9 >= r12 ) goto label$2f9bd3c_2_51;
	r13 = r9;
	goto label$2f9bd3c_2_52;
	label$2f9bd3c_2_51:
	r13 = r12;
	label$2f9bd3c_2_52:
	if( r7 >= r13 ) goto label$2f9bd3c_2_221;
	++r7;
	r18 = r6;
	++r6;
	r19 = r0->myPosition;
	r20 = r19;
	++r19;
	r0->myPosition = r19;
	r19 = r20;
	r21 = 2;
	r20 = r21 == 0 ? 0 : r20 % r21;
	r21 = 0;
	if( r20 == r21 ) goto label$2f9bd3c_2_68;
	r5 = false;
	goto label$2f9bd3c_2_69;
	label$2f9bd3c_2_68:
	r5 = true;
	label$2f9bd3c_2_69:
	r20 = r0->sampleRate;
	r15 = (double)r20;
	r16 = (double)r3;
	r15 = r15 / r16;
	if( !r5 ) goto label$2f9bd3c_2_141;
	r21 = 2;
	r20 = r21 == 0 ? 0 : r19 / r21;
	r17 = (double)r20;
	r16 = r15 * r17;
	r20 = hl_math_floor(r16);
	r22 = 1.;
	r17 = r16 + r22;
	r21 = hl_math_floor(r17);
	r24 = 2;
	r23 = r20 * r24;
	r20 = r23;
	r24 = 2;
	r23 = r21 * r24;
	r21 = r23;
	r23 = 0;
	r11 = r0->data;
	if( r11 == NULL ) hl_null_access();
	r24 = r11->byteArrayLength;
	r25 = 2;
	r24 = r24 >> r25;
	r25 = 1;
	r24 = r24 - r25;
	r26 = 2;
	r25 = r26 == 0 ? 0 : r24 % r26;
	r26 = 0;
	if( r25 == r26 ) goto label$2f9bd3c_2_101;
	--r24;
	label$2f9bd3c_2_101:
	if( r20 < r23 ) goto label$2f9bd3c_2_103;
	if( r24 >= r20 ) goto label$2f9bd3c_2_107;
	label$2f9bd3c_2_103:
	r25 = 0;
	r27 = (float)r25;
	r14 = r27;
	goto label$2f9bd3c_2_116;
	label$2f9bd3c_2_107:
	r11 = r0->data;
	if( r11 == NULL ) hl_null_access();
	r10 = r11->self;
	r25 = r11->byteArrayOffset;
	r28 = 4;
	r26 = r20 * r28;
	r25 = r25 + r26;
	r27 = hl_kinc_bytearray_getfloat32(r10,r25);
	r14 = r27;
	label$2f9bd3c_2_116:
	if( r21 < r23 ) goto label$2f9bd3c_2_118;
	if( r24 >= r21 ) goto label$2f9bd3c_2_121;
	label$2f9bd3c_2_118:
	r25 = 0;
	r29 = (float)r25;
	goto label$2f9bd3c_2_129;
	label$2f9bd3c_2_121:
	r11 = r0->data;
	if( r11 == NULL ) hl_null_access();
	r10 = r11->self;
	r25 = r11->byteArrayOffset;
	r28 = 4;
	r26 = r21 * r28;
	r25 = r25 + r26;
	r29 = hl_kinc_bytearray_getfloat32(r10,r25);
	label$2f9bd3c_2_129:
	r25 = hl_math_floor(r16);
	r22 = (double)r25;
	r17 = r16 - r22;
	r22 = 1.;
	r22 = r22 - r17;
	r30 = (double)r14;
	r22 = r22 * r30;
	r32 = (double)r29;
	r30 = r17 * r32;
	r22 = r22 + r30;
	r31 = (float)r22;
	goto label$2f9bd3c_2_213;
	label$2f9bd3c_2_141:
	r21 = 2;
	r20 = r21 == 0 ? 0 : r19 / r21;
	r17 = (double)r20;
	r16 = r15 * r17;
	r20 = hl_math_floor(r16);
	r22 = 1.;
	r17 = r16 + r22;
	r21 = hl_math_floor(r17);
	r24 = 2;
	r23 = r20 * r24;
	r24 = 1;
	r23 = r23 + r24;
	r20 = r23;
	r24 = 2;
	r23 = r21 * r24;
	r24 = 1;
	r23 = r23 + r24;
	r21 = r23;
	r23 = 1;
	r11 = r0->data;
	if( r11 == NULL ) hl_null_access();
	r24 = r11->byteArrayLength;
	r25 = 2;
	r24 = r24 >> r25;
	r25 = 1;
	r24 = r24 - r25;
	r26 = 2;
	r25 = r26 == 0 ? 0 : r24 % r26;
	r26 = 0;
	if( r25 != r26 ) goto label$2f9bd3c_2_172;
	--r24;
	label$2f9bd3c_2_172:
	if( r20 < r23 ) goto label$2f9bd3c_2_174;
	if( r24 >= r20 ) goto label$2f9bd3c_2_178;
	label$2f9bd3c_2_174:
	r25 = 0;
	r27 = (float)r25;
	r14 = r27;
	goto label$2f9bd3c_2_187;
	label$2f9bd3c_2_178:
	r11 = r0->data;
	if( r11 == NULL ) hl_null_access();
	r10 = r11->self;
	r25 = r11->byteArrayOffset;
	r28 = 4;
	r26 = r20 * r28;
	r25 = r25 + r26;
	r27 = hl_kinc_bytearray_getfloat32(r10,r25);
	r14 = r27;
	label$2f9bd3c_2_187:
	if( r21 < r23 ) goto label$2f9bd3c_2_189;
	if( r24 >= r21 ) goto label$2f9bd3c_2_193;
	label$2f9bd3c_2_189:
	r25 = 0;
	r31 = (float)r25;
	r27 = r31;
	goto label$2f9bd3c_2_202;
	label$2f9bd3c_2_193:
	r11 = r0->data;
	if( r11 == NULL ) hl_null_access();
	r10 = r11->self;
	r25 = r11->byteArrayOffset;
	r28 = 4;
	r26 = r21 * r28;
	r25 = r25 + r26;
	r31 = hl_kinc_bytearray_getfloat32(r10,r25);
	r27 = r31;
	label$2f9bd3c_2_202:
	r25 = hl_math_floor(r16);
	r22 = (double)r25;
	r17 = r16 - r22;
	r22 = 1.;
	r22 = r22 - r17;
	r30 = (double)r14;
	r22 = r22 * r30;
	r32 = (double)r27;
	r30 = r17 * r32;
	r22 = r22 + r30;
	r31 = (float)r22;
	label$2f9bd3c_2_213:
	if( r1 == NULL ) hl_null_access();
	r10 = r1->self;
	r20 = r1->byteArrayOffset;
	r23 = 4;
	r21 = r18 * r23;
	r20 = r20 + r21;
	hl_kinc_bytearray_setfloat32(r10,r20,r31);
	goto label$2f9bd3c_2_52;
	label$2f9bd3c_2_221:
	r7 = r0->myPosition;
	r11 = r0->data;
	if( r11 == NULL ) hl_null_access();
	r8 = r11->byteArrayLength;
	r9 = 2;
	r8 = r8 >> r9;
	r15 = (double)r8;
	r16 = (double)r3;
	r8 = r0->sampleRate;
	r17 = (double)r8;
	r16 = r16 / r17;
	r15 = r15 * r16;
	r8 = hl_math_ceil(r15);
	r13 = 2;
	r12 = r13 == 0 ? 0 : r8 % r13;
	r13 = 0;
	if( r12 != r13 ) goto label$2f9bd3c_2_240;
	r12 = r8;
	goto label$2f9bd3c_2_242;
	label$2f9bd3c_2_240:
	r13 = 1;
	r12 = r8 + r13;
	label$2f9bd3c_2_242:
	if( r7 < r12 ) goto label$2f9bd3c_2_250;
	r9 = 0;
	r0->myPosition = r9;
	r5 = r0->looping;
	if( r5 ) goto label$2f9bd3c_2_250;
	r5 = true;
	r0->stopped = r5;
	goto label$2f9bd3c_2_251;
	label$2f9bd3c_2_250:
	goto label$2f9bd3c_2_22;
	label$2f9bd3c_2_251:
	if( r6 >= r2 ) goto label$2f9bd3c_2_265;
	if( r1 == NULL ) hl_null_access();
	r10 = r1->self;
	r7 = r1->byteArrayOffset;
	r8 = r6;
	++r6;
	r9 = 4;
	r8 = r8 * r9;
	r7 = r7 + r8;
	r8 = 0;
	r14 = (float)r8;
	hl_kinc_bytearray_setfloat32(r10,r7,r14);
	goto label$2f9bd3c_2_251;
	label$2f9bd3c_2_265:
	return;
}

void kha_audio2_ResamplingAudioChannel_play(kha__audio2__ResamplingAudioChannel r0) {
	bool r1;
	r1 = false;
	r0->paused = r1;
	r1 = false;
	r0->stopped = r1;
	kha_audio2_Audio1__playAgain(((kha__audio2__AudioChannel)r0));
	return;
}

void kha_audio2_ResamplingAudioChannel_stop(kha__audio2__ResamplingAudioChannel r0) {
	bool r2;
	int r1;
	r1 = 0;
	r0->myPosition = r1;
	r2 = true;
	r0->stopped = r2;
	return;
}

double kha_audio2_ResamplingAudioChannel_get_volume(kha__audio2__ResamplingAudioChannel r0) {
	double r1;
	r1 = r0->myVolume;
	return r1;
}

double kha_audio2_ResamplingAudioChannel_set_volume(kha__audio2__ResamplingAudioChannel r0,double r1) {
	r0->myVolume = r1;
	return r1;
}

bool kha_audio2_ResamplingAudioChannel_get_finished(kha__audio2__ResamplingAudioChannel r0) {
	bool r1;
	r1 = r0->stopped;
	return r1;
}

