// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <kha/audio2/StreamChannel.h>
#include <kha/arrays/ByteArrayPrivate.h>
#include <hl/natives.h>
#include <haxe/io/Bytes.h>
#include <haxe/io/BytesDataImpl.h>
extern hl_type t$haxe_io_BytesDataImpl;
void haxe_io_BytesDataImpl_new(haxe__io__BytesDataImpl,vbyte*,int);

void kha_audio2_StreamChannel_nextSamples(kha__audio2__StreamChannel r0,kha__arrays__ByteArrayPrivate r1,int r2,int r3) {
	bool r5, r15;
	float r13;
	vbyte *r10, *r14;
	int r6, r7, r8, r9, r11, r12;
	r5 = r0->paused;
	if( !r5 ) goto label$90bbcc2_1_19;
	r6 = 0;
	r7 = r2;
	label$90bbcc2_1_4:
	if( r6 >= r7 ) goto label$90bbcc2_1_18;
	r8 = r6;
	++r6;
	if( r1 == NULL ) hl_null_access();
	r10 = r1->self;
	r9 = r1->byteArrayOffset;
	r12 = 4;
	r11 = r8 * r12;
	r9 = r9 + r11;
	r11 = 0;
	r13 = (float)r11;
	hl_kinc_bytearray_setfloat32(r10,r9,r13);
	goto label$90bbcc2_1_4;
	label$90bbcc2_1_18:
	return;
	label$90bbcc2_1_19:
	r10 = r0->_vorbis;
	if( r1 == NULL ) hl_null_access();
	r14 = r1->self;
	r5 = r0->loop;
	r15 = r0->atend;
	r5 = hl_kinc_sound_next_vorbis_samples(r10,r14,r2,r5,r15);
	r0->atend = r5;
	return;
}

void kha_audio2_StreamChannel_play(kha__audio2__StreamChannel r0) {
	bool r1;
	r1 = false;
	r0->paused = r1;
	return;
}

void kha_audio2_StreamChannel_stop(kha__audio2__StreamChannel r0) {
	bool r1;
	r1 = true;
	r0->atend = r1;
	return;
}

double kha_audio2_StreamChannel_get_volume(kha__audio2__StreamChannel r0) {
	double r1;
	r1 = r0->myVolume;
	return r1;
}

double kha_audio2_StreamChannel_set_volume(kha__audio2__StreamChannel r0,double r1) {
	r0->myVolume = r1;
	return r1;
}

bool kha_audio2_StreamChannel_get_finished(kha__audio2__StreamChannel r0) {
	bool r1;
	r1 = r0->atend;
	return r1;
}

void kha_audio2_StreamChannel_new(kha__audio2__StreamChannel r0,haxe__io__Bytes r1,bool r2) {
	bool r3;
	haxe__io__BytesDataImpl r5;
	double r4;
	int r7;
	vbyte *r6;
	r3 = false;
	r0->paused = r3;
	r3 = false;
	r0->atend = r3;
	r4 = 1.;
	r0->myVolume = r4;
	r0->loop = r2;
	r5 = (haxe__io__BytesDataImpl)hl_alloc_obj(&t$haxe_io_BytesDataImpl);
	if( r1 == NULL ) hl_null_access();
	r6 = r1->b;
	r7 = r1->length;
	haxe_io_BytesDataImpl_new(r5,r6,r7);
	r6 = r5->bytes;
	r7 = r1->length;
	r6 = hl_kinc_sound_init_vorbis(r6,r7);
	r0->_vorbis = r6;
	return;
}

