// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/system/Audio.h>
#include <haxe/io/Bytes.h>
#include <kha/arrays/ByteArrayPrivate.h>
vvirtual* kha_audio2_Audio1_stream(kha__Sound,bool*);
vvirtual* kha_audio2_Audio1_play(kha__Sound,bool*);

vvirtual* iron_system_Audio_play(kha__Sound r0,bool* r1,bool* r2) {
	vvirtual *r7;
	haxe__io__Bytes r6;
	bool r3, r4, r5, r9;
	kha__arrays__ByteArrayPrivate r8;
	if( r1 ) goto label$5c15cd7_1_3;
	r3 = false;
	goto label$5c15cd7_1_4;
	label$5c15cd7_1_3:
	r3 = *r1;
	label$5c15cd7_1_4:
	if( r2 ) goto label$5c15cd7_1_7;
	r4 = false;
	goto label$5c15cd7_1_8;
	label$5c15cd7_1_7:
	r4 = *r2;
	label$5c15cd7_1_8:
	if( !r4 ) goto label$5c15cd7_1_16;
	if( r0 == NULL ) hl_null_access();
	r6 = r0->compressedData;
	if( !r6 ) goto label$5c15cd7_1_16;
	r5 = r3;
	r1 = &r5;
	r7 = kha_audio2_Audio1_stream(r0,r1);
	return r7;
	label$5c15cd7_1_16:
	if( r0 == NULL ) hl_null_access();
	r8 = r0->uncompressedData;
	if( !r8 ) goto label$5c15cd7_1_23;
	r9 = r3;
	r1 = &r9;
	r7 = kha_audio2_Audio1_play(r0,r1);
	return r7;
	label$5c15cd7_1_23:
	r7 = NULL;
	return r7;
}

