// Generated by HLC 4.2.5 (HL v4)
#ifndef INC_iron__system__Mouse
#define INC_iron__system__Mouse
typedef struct _iron__system__$Mouse *iron__system__$Mouse;
typedef struct _iron__system__Mouse *iron__system__Mouse;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayObj.h>
#include <iron/system/VirtualInput.h>
#include <haxe/ds/StringMap.h>


struct _iron__system__$Mouse {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	hl__types__ArrayObj buttons;
};
struct _iron__system__Mouse {
	hl_type *$type;
	haxe__ds__StringMap virtualButtons;
	hl__types__ArrayObj buttonsDown;
	hl__types__ArrayObj buttonsStarted;
	hl__types__ArrayObj buttonsReleased;
	double x;
	double y;
	bool moved;
	double movementX;
	double movementY;
	int wheelDelta;
	bool locked;
	bool hidden;
	double lastX;
	double lastY;
};
#endif

