// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/system/Time.h>
extern iron__system__$Time g$_iron_system_Time;
void iron_system_Time_initFrequency(void);
#include <kha/Display.h>
kha__Display kha_Display_get_primary(void);
int kha_Display_get_frequency(kha__Display);
extern hl_type t$_i32;
double kha_Scheduler_realTime(void);

double iron_system_Time_get_delta() {
	double r3, r5;
	vdynamic *r1;
	int r4;
	iron__system__$Time r2;
	r2 = (iron__system__$Time)g$_iron_system_Time;
	r1 = r2->frequency;
	if( r1 ) goto label$4935823_1_4;
	iron_system_Time_initFrequency();
	label$4935823_1_4:
	r3 = 1.;
	r2 = (iron__system__$Time)g$_iron_system_Time;
	r1 = r2->frequency;
	r4 = r1 ? r1->v.i : 0;
	r5 = (double)r4;
	r3 = r3 / r5;
	r2 = (iron__system__$Time)g$_iron_system_Time;
	r5 = r2->scale;
	r3 = r3 * r5;
	return r3;
}

void iron_system_Time_initFrequency() {
	kha__Display r1;
	vdynamic *r0;
	iron__system__$Time r3;
	int r2;
	r1 = kha_Display_get_primary();
	if( !r1 ) goto label$4935823_2_7;
	r1 = kha_Display_get_primary();
	if( r1 == NULL ) hl_null_access();
	r2 = kha_Display_get_frequency(r1);
	r0 = hl_alloc_dynamic(&t$_i32);
	r0->v.i = r2;
	goto label$4935823_2_9;
	label$4935823_2_7:
	r2 = 60;
	r0 = hl_alloc_dynamic(&t$_i32);
	r0->v.i = r2;
	label$4935823_2_9:
	r3 = (iron__system__$Time)g$_iron_system_Time;
	r3->frequency = r0;
	return;
}

void iron_system_Time_update() {
	double r0, r1;
	iron__system__$Time r2;
	r0 = kha_Scheduler_realTime();
	r2 = (iron__system__$Time)g$_iron_system_Time;
	r1 = r2->last;
	r0 = r0 - r1;
	r2 = (iron__system__$Time)g$_iron_system_Time;
	r2->realDelta = r0;
	r0 = kha_Scheduler_realTime();
	r2 = (iron__system__$Time)g$_iron_system_Time;
	r2->last = r0;
	return;
}

