// Generated by HLC 4.2.5 (HL v4)
#ifndef INC_iron__system__Tween
#define INC_iron__system__Tween
typedef struct _iron__system__$Tween *iron__system__$Tween;
typedef struct _iron__system__Tween *iron__system__Tween;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayObj.h>
#include <hl/types/ArrayBytes_Int.h>
#include <hl/types/ArrayBytes_Float.h>


struct _iron__system__$Tween {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	hl__types__ArrayObj eases;
	hl__types__ArrayObj anims;
	bool registered;
	vclosure* to;
	vclosure* timer;
	vclosure* stop;
	vclosure* reset;
	vclosure* update;
	vclosure* easeLinear;
	vclosure* easeSineIn;
	vclosure* easeSineOut;
	vclosure* easeSineInOut;
	vclosure* easeQuadIn;
	vclosure* easeQuadOut;
	vclosure* easeQuadInOut;
	vclosure* easeCubicIn;
	vclosure* easeCubicOut;
	vclosure* easeCubicInOut;
	vclosure* easeQuartIn;
	vclosure* easeQuartOut;
	vclosure* easeQuartInOut;
	vclosure* easeQuintIn;
	vclosure* easeQuintOut;
	vclosure* easeQuintInOut;
	vclosure* easeExpoIn;
	vclosure* easeExpoOut;
	vclosure* easeExpoInOut;
	vclosure* easeCircIn;
	vclosure* easeCircOut;
	vclosure* easeCircInOut;
	vclosure* easeBackIn;
	vclosure* easeBackOut;
	vclosure* easeBackInOut;
	vclosure* easeBounceIn;
	vclosure* easeBounceOut;
	vclosure* easeBounceInOut;
	vclosure* easeElasticIn;
	vclosure* easeElasticOut;
	vclosure* easeElasticInOut;
};
struct _iron__system__Tween {
	hl_type *$type;
};
#endif

