// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <iron/system/VirtualButton.h>

void iron_system_VirtualButton_new(iron__system__VirtualButton r0) {
	bool r1;
	r1 = false;
	r0->down = r1;
	r1 = false;
	r0->released = r1;
	r1 = false;
	r0->started = r1;
	return;
}

