// Generated by HLC 4.2.5 (HL v4)
#ifndef INC_kha__Assets
#define INC_kha__Assets
typedef struct _kha__$Assets *kha__$Assets;
typedef struct _kha__Assets *kha__Assets;
#include <_std/String.h>
#include <hl/types/ArrayDyn.h>
#include <kha/Assets.h>
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <kha/Image.h>
#include <kha/internal/BytesBlob.h>
#include <kha/Sound.h>
#include <kha/Kravur.h>


typedef struct {
	HL__ENUM_CONSTRUCT__
	vvirtual* p0;
	vclosure* p1;
} Enumt$ctx_307f22a;
struct _kha__$Assets {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	vclosure* loadImageFromPath;
	vclosure* loadBlobFromPath;
	vclosure* loadSoundFromPath;
	vclosure* loadFontFromPath;
	vclosure* reporter;
};
struct _kha__Assets {
	hl_type *$type;
};
#endif

