// Generated by HLC 4.2.5 (HL v4)
#define HLC_BOOT
#include <hlc.h>
#include <kha/Scheduler.h>
#include <kha/FrameTask.h>
extern hl_type t$kha_FrameTask;
extern hl_type t$_dyn;
extern hl_type t$hl_types_ArrayBytes_Float;
void hl_types_ArrayBytes_Float_new(hl__types__ArrayBytes_Float);
extern kha__$Scheduler g$_kha_Scheduler;
void hl_types_ArrayBytes_Float___expand(hl__types__ArrayBytes_Float,int);
double kha_Scheduler_realTime(void);
extern hl_type t$kha_TimeTask;
#include <hl/natives.h>
hl__types__ArrayObj hl_types_ArrayObj_alloc(varray*);
#include <kha/Window.h>
#include <kha/Display.h>
kha__Window kha_Window_get(int);
bool kha_Window_get_vSynced(kha__Window);
kha__Display kha_Display_get_primary(void);
int kha_Display_get_frequency(kha__Display);
void kha_Scheduler_resetTime(void);
#include <kha/netsync/Session.h>
kha__netsync__Session kha_netsync_Session_the(void);
void kha_Scheduler_executeTimeTasks(double);
int hl_types_ArrayObj_push(hl__types__ArrayObj,vdynamic*);
bool hl_types_ArrayObj_remove(hl__types__ArrayObj,vdynamic*);
void kha_Scheduler_sortFrameTasks(void);
vdynamic* hl_types_ArrayObj_pop(hl__types__ArrayObj);
void kha_Scheduler_insertSorted(hl__types__ArrayObj,kha__TimeTask);
void kha_Scheduler_archiveTimeTask(kha__TimeTask,double);
double kha_System_get_time(void);
void kha_TimeTask_new(kha__TimeTask);
bool kha_Scheduler_addTimeTaskToGroup__$1(vclosure*);
extern hl_type t$fun_3c2375f;
void hl_types_ArrayObj_insert(hl__types__ArrayObj,int,vdynamic*);
extern hl_type t$fun_5ae4454;
extern hl_type t$fun_dee1a83;
void hl_types_ArrayObj_sort(hl__types__ArrayObj,vclosure*);

int kha_Scheduler_sortFrameTasks__$2(vclosure* r0,vdynamic* r1,vdynamic* r2) {
	int r5;
	kha__FrameTask r3, r4;
	r3 = (kha__FrameTask)hl_dyn_castp(&r1,&t$_dyn,&t$kha_FrameTask);
	r4 = (kha__FrameTask)hl_dyn_castp(&r2,&t$_dyn,&t$kha_FrameTask);
	r5 = r0->hasValue ? ((int (*)(vdynamic*,kha__FrameTask,kha__FrameTask))r0->fun)((vdynamic*)r0->value,r3,r4) : ((int (*)(kha__FrameTask,kha__FrameTask))r0->fun)(r3,r4);
	return r5;
}

void kha_Scheduler_init() {
	hl__types__ArrayObj r10;
	hl_type *r12;
	bool r9;
	kha__$Scheduler r2;
	hl__types__ArrayBytes_Float r0;
	double r6;
	varray *r11;
	vbyte *r8;
	int r3, r4, r5, r7;
	r0 = (hl__types__ArrayBytes_Float)hl_alloc_obj(&t$hl_types_ArrayBytes_Float);
	hl_types_ArrayBytes_Float_new(r0);
	r2 = (kha__$Scheduler)g$_kha_Scheduler;
	r2->deltas = r0;
	r3 = 0;
	r2 = (kha__$Scheduler)g$_kha_Scheduler;
	r4 = r2->DIF_COUNT;
	label$fe4f13c_2_7:
	if( r3 >= r4 ) goto label$fe4f13c_2_23;
	r5 = r3;
	++r3;
	r2 = (kha__$Scheduler)g$_kha_Scheduler;
	r0 = r2->deltas;
	if( r0 == NULL ) hl_null_access();
	r6 = 0.;
	r7 = r0->length;
	if( ((unsigned)r5) < ((unsigned)r7) ) goto label$fe4f13c_2_18;
	hl_types_ArrayBytes_Float___expand(r0,r5);
	label$fe4f13c_2_18:
	r8 = r0->bytes;
	r7 = 3;
	r7 = r5 << r7;
	*(double*)(r8 + r7) = r6;
	goto label$fe4f13c_2_7;
	label$fe4f13c_2_23:
	r9 = true;
	r2 = (kha__$Scheduler)g$_kha_Scheduler;
	r2->stopped = r9;
	r9 = true;
	r2 = (kha__$Scheduler)g$_kha_Scheduler;
	r2->frame_tasks_sorted = r9;
	r6 = kha_Scheduler_realTime();
	r2 = (kha__$Scheduler)g$_kha_Scheduler;
	r2->lastFrameEnd = r6;
	r2 = (kha__$Scheduler)g$_kha_Scheduler;
	r2->lastTime = r6;
	r2 = (kha__$Scheduler)g$_kha_Scheduler;
	r2->current = r6;
	r3 = 0;
	r2 = (kha__$Scheduler)g$_kha_Scheduler;
	r2->currentFrameTaskId = r3;
	r3 = 0;
	r2 = (kha__$Scheduler)g$_kha_Scheduler;
	r2->currentTimeTaskId = r3;
	r3 = 0;
	r2 = (kha__$Scheduler)g$_kha_Scheduler;
	r2->currentGroupId = r3;
	r12 = &t$kha_TimeTask;
	r3 = 0;
	r11 = hl_alloc_array(r12,r3);
	r10 = hl_types_ArrayObj_alloc(r11);
	r2 = (kha__$Scheduler)g$_kha_Scheduler;
	r2->timeTasks = r10;
	r12 = &t$kha_TimeTask;
	r3 = 0;
	r11 = hl_alloc_array(r12,r3);
	r10 = hl_types_ArrayObj_alloc(r11);
	r2 = (kha__$Scheduler)g$_kha_Scheduler;
	r2->pausedTimeTasks = r10;
	r12 = &t$kha_TimeTask;
	r3 = 0;
	r11 = hl_alloc_array(r12,r3);
	r10 = hl_types_ArrayObj_alloc(r11);
	r2 = (kha__$Scheduler)g$_kha_Scheduler;
	r2->outdatedTimeTasks = r10;
	r12 = &t$kha_TimeTask;
	r3 = 0;
	r11 = hl_alloc_array(r12,r3);
	r10 = hl_types_ArrayObj_alloc(r11);
	r2 = (kha__$Scheduler)g$_kha_Scheduler;
	r2->timeTasksScratchpad = r10;
	r12 = &t$kha_FrameTask;
	r3 = 0;
	r11 = hl_alloc_array(r12,r3);
	r10 = hl_types_ArrayObj_alloc(r11);
	r2 = (kha__$Scheduler)g$_kha_Scheduler;
	r2->frameTasks = r10;
	r12 = &t$kha_FrameTask;
	r3 = 0;
	r11 = hl_alloc_array(r12,r3);
	r10 = hl_types_ArrayObj_alloc(r11);
	r2 = (kha__$Scheduler)g$_kha_Scheduler;
	r2->toDeleteFrame = r10;
	return;
}

void kha_Scheduler_start(bool* r0) {
	hl__types__ArrayObj r16;
	kha__$Scheduler r5;
	bool r1, r2;
	kha__Display r6;
	kha__Window r3;
	kha__TimeTask r17;
	hl__types__ArrayBytes_Float r13;
	double r10, r11;
	vdynamic *r18;
	kha__FrameTask r20;
	varray *r19;
	vbyte *r15;
	int r4, r8, r9, r12, r14;
	if( r0 ) goto label$fe4f13c_3_3;
	r1 = false;
	goto label$fe4f13c_3_4;
	label$fe4f13c_3_3:
	r1 = *r0;
	label$fe4f13c_3_4:
	r4 = 0;
	r3 = kha_Window_get(r4);
	if( r3 == NULL ) hl_null_access();
	r2 = kha_Window_get_vSynced(r3);
	r5 = (kha__$Scheduler)g$_kha_Scheduler;
	r5->vsync = r2;
	r6 = kha_Display_get_primary();
	if( !r6 ) goto label$fe4f13c_3_16;
	r6 = kha_Display_get_primary();
	if( r6 == NULL ) hl_null_access();
	r4 = kha_Display_get_frequency(r6);
	goto label$fe4f13c_3_17;
	label$fe4f13c_3_16:
	r4 = 60;
	label$fe4f13c_3_17:
	r9 = 57;
	if( r4 < r9 ) goto label$fe4f13c_3_23;
	r9 = 63;
	if( r9 < r4 ) goto label$fe4f13c_3_23;
	r8 = 60;
	r4 = r8;
	label$fe4f13c_3_23:
	r10 = 1.;
	r11 = (double)r4;
	r10 = r10 / r11;
	r5 = (kha__$Scheduler)g$_kha_Scheduler;
	r5->onedifhz = r10;
	r2 = false;
	r5 = (kha__$Scheduler)g$_kha_Scheduler;
	r5->stopped = r2;
	kha_Scheduler_resetTime();
	r10 = kha_Scheduler_realTime();
	r5 = (kha__$Scheduler)g$_kha_Scheduler;
	r11 = r5->startTime;
	r10 = r10 - r11;
	r5 = (kha__$Scheduler)g$_kha_Scheduler;
	r5->lastTime = r10;
	r8 = 0;
	r5 = (kha__$Scheduler)g$_kha_Scheduler;
	r9 = r5->DIF_COUNT;
	label$fe4f13c_3_41:
	if( r8 >= r9 ) goto label$fe4f13c_3_57;
	r12 = r8;
	++r8;
	r5 = (kha__$Scheduler)g$_kha_Scheduler;
	r13 = r5->deltas;
	if( r13 == NULL ) hl_null_access();
	r10 = 0.;
	r14 = r13->length;
	if( ((unsigned)r12) < ((unsigned)r14) ) goto label$fe4f13c_3_52;
	hl_types_ArrayBytes_Float___expand(r13,r12);
	label$fe4f13c_3_52:
	r15 = r13->bytes;
	r14 = 3;
	r14 = r12 << r14;
	*(double*)(r15 + r14) = r10;
	goto label$fe4f13c_3_41;
	label$fe4f13c_3_57:
	if( !r1 ) goto label$fe4f13c_3_96;
	r8 = 0;
	r5 = (kha__$Scheduler)g$_kha_Scheduler;
	r16 = r5->timeTasks;
	label$fe4f13c_3_61:
	if( r16 == NULL ) hl_null_access();
	r12 = r16->length;
	if( r8 >= r12 ) goto label$fe4f13c_3_77;
	r12 = r16->length;
	if( ((unsigned)r8) < ((unsigned)r12) ) goto label$fe4f13c_3_69;
	r17 = NULL;
	goto label$fe4f13c_3_72;
	label$fe4f13c_3_69:
	r19 = r16->array;
	r18 = ((vdynamic**)(r19 + 1))[r8];
	r17 = (kha__TimeTask)r18;
	label$fe4f13c_3_72:
	++r8;
	if( r17 == NULL ) hl_null_access();
	r2 = false;
	r17->paused = r2;
	goto label$fe4f13c_3_61;
	label$fe4f13c_3_77:
	r8 = 0;
	r5 = (kha__$Scheduler)g$_kha_Scheduler;
	r16 = r5->frameTasks;
	label$fe4f13c_3_80:
	if( r16 == NULL ) hl_null_access();
	r12 = r16->length;
	if( r8 >= r12 ) goto label$fe4f13c_3_96;
	r12 = r16->length;
	if( ((unsigned)r8) < ((unsigned)r12) ) goto label$fe4f13c_3_88;
	r20 = NULL;
	goto label$fe4f13c_3_91;
	label$fe4f13c_3_88:
	r19 = r16->array;
	r18 = ((vdynamic**)(r19 + 1))[r8];
	r20 = (kha__FrameTask)r18;
	label$fe4f13c_3_91:
	++r8;
	if( r20 == NULL ) hl_null_access();
	r2 = false;
	r20->paused = r2;
	goto label$fe4f13c_3_80;
	label$fe4f13c_3_96:
	return;
}

void kha_Scheduler_executeFrame() {
	hl__types__ArrayObj r23, r24;
	bool r11;
	kha__netsync__Session r8;
	kha__$Scheduler r4, r10;
	kha__TimeTask r25;
	hl__types__ArrayBytes_Float r18, r21;
	vclosure *r28;
	double r0, r2, r3, r5, r6, r7, r9;
	vdynamic *r15;
	kha__FrameTask r27;
	varray *r26;
	vbyte *r20;
	int r12, r13, r14, r16, r17, r19, r22;
	r0 = kha_Scheduler_realTime();
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r3 = r4->startTime;
	r2 = r0 - r3;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r5 = r4->lastTime;
	r3 = r2 - r5;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r5 = r4->lastFrameEnd;
	r7 = 0.;
	if( !(r3 >= r7) ) goto label$fe4f13c_4_330;
	r8 = kha_netsync_Session_the();
	if( r8 ) goto label$fe4f13c_4_209;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r7 = r4->maxframetime;
	if( !(r7 < r3) ) goto label$fe4f13c_4_33;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r6 = r4->startTime;
	r10 = (kha__$Scheduler)g$_kha_Scheduler;
	r9 = r10->maxframetime;
	r7 = r3 - r9;
	r6 = r6 + r7;
	r4->startTime = r6;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r7 = r4->startTime;
	r6 = r0 - r7;
	r2 = r6;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r6 = r4->maxframetime;
	r3 = r6;
	r6 = r5 + r3;
	r5 = r6;
	goto label$fe4f13c_4_208;
	label$fe4f13c_4_33:
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r11 = r4->vsync;
	if( !r11 ) goto label$fe4f13c_4_132;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r7 = r4->onedifhz;
	r6 = r3 / r7;
	r12 = hl_math_round(r6);
	r14 = 1;
	if( r12 >= r14 ) goto label$fe4f13c_4_43;
	return;
	label$fe4f13c_4_43:
	r6 = (double)r12;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r7 = r4->onedifhz;
	r6 = r6 * r7;
	r3 = r6;
	r13 = 0;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r14 = r4->DIF_COUNT;
	r16 = 2;
	r14 = r14 - r16;
	label$fe4f13c_4_53:
	if( r13 >= r14 ) goto label$fe4f13c_4_94;
	r16 = r13;
	++r13;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r18 = r4->deltas;
	if( r18 == NULL ) hl_null_access();
	r19 = r18->length;
	if( ((unsigned)r16) < ((unsigned)r19) ) goto label$fe4f13c_4_64;
	r9 = 0.;
	goto label$fe4f13c_4_68;
	label$fe4f13c_4_64:
	r20 = r18->bytes;
	r19 = 3;
	r19 = r16 << r19;
	r9 = *(double*)(r20 + r19);
	label$fe4f13c_4_68:
	r7 = r3 + r9;
	r3 = r7;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r18 = r4->deltas;
	if( r18 == NULL ) hl_null_access();
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r21 = r4->deltas;
	if( r21 == NULL ) hl_null_access();
	r22 = 1;
	r19 = r16 + r22;
	r22 = r21->length;
	if( ((unsigned)r19) < ((unsigned)r22) ) goto label$fe4f13c_4_82;
	r7 = 0.;
	goto label$fe4f13c_4_86;
	label$fe4f13c_4_82:
	r20 = r21->bytes;
	r22 = 3;
	r22 = r19 << r22;
	r7 = *(double*)(r20 + r22);
	label$fe4f13c_4_86:
	r19 = r18->length;
	if( ((unsigned)r16) < ((unsigned)r19) ) goto label$fe4f13c_4_89;
	hl_types_ArrayBytes_Float___expand(r18,r16);
	label$fe4f13c_4_89:
	r20 = r18->bytes;
	r19 = 3;
	r19 = r16 << r19;
	*(double*)(r20 + r19) = r7;
	goto label$fe4f13c_4_53;
	label$fe4f13c_4_94:
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r18 = r4->deltas;
	if( r18 == NULL ) hl_null_access();
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r13 = r4->DIF_COUNT;
	r14 = 2;
	r13 = r13 - r14;
	r14 = r18->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$fe4f13c_4_105;
	r9 = 0.;
	goto label$fe4f13c_4_109;
	label$fe4f13c_4_105:
	r20 = r18->bytes;
	r14 = 3;
	r14 = r13 << r14;
	r9 = *(double*)(r20 + r14);
	label$fe4f13c_4_109:
	r7 = r3 + r9;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r13 = r4->DIF_COUNT;
	r9 = (double)r13;
	r7 = r7 / r9;
	r3 = r7;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r18 = r4->deltas;
	if( r18 == NULL ) hl_null_access();
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r13 = r4->DIF_COUNT;
	r14 = 2;
	r13 = r13 - r14;
	r14 = r18->length;
	if( ((unsigned)r13) < ((unsigned)r14) ) goto label$fe4f13c_4_125;
	hl_types_ArrayBytes_Float___expand(r18,r13);
	label$fe4f13c_4_125:
	r20 = r18->bytes;
	r14 = 3;
	r14 = r13 << r14;
	*(double*)(r20 + r14) = r6;
	r7 = r5 + r3;
	r5 = r7;
	goto label$fe4f13c_4_208;
	label$fe4f13c_4_132:
	r12 = 0;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r13 = r4->DIF_COUNT;
	r14 = 1;
	r13 = r13 - r14;
	label$fe4f13c_4_137:
	if( r12 >= r13 ) goto label$fe4f13c_4_165;
	r14 = r12;
	++r12;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r18 = r4->deltas;
	if( r18 == NULL ) hl_null_access();
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r21 = r4->deltas;
	if( r21 == NULL ) hl_null_access();
	r19 = 1;
	r17 = r14 + r19;
	r19 = r21->length;
	if( ((unsigned)r17) < ((unsigned)r19) ) goto label$fe4f13c_4_153;
	r6 = 0.;
	goto label$fe4f13c_4_157;
	label$fe4f13c_4_153:
	r20 = r21->bytes;
	r19 = 3;
	r19 = r17 << r19;
	r6 = *(double*)(r20 + r19);
	label$fe4f13c_4_157:
	r17 = r18->length;
	if( ((unsigned)r14) < ((unsigned)r17) ) goto label$fe4f13c_4_160;
	hl_types_ArrayBytes_Float___expand(r18,r14);
	label$fe4f13c_4_160:
	r20 = r18->bytes;
	r17 = 3;
	r17 = r14 << r17;
	*(double*)(r20 + r17) = r6;
	goto label$fe4f13c_4_137;
	label$fe4f13c_4_165:
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r18 = r4->deltas;
	if( r18 == NULL ) hl_null_access();
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r12 = r4->DIF_COUNT;
	r13 = 1;
	r12 = r12 - r13;
	r13 = r18->length;
	if( ((unsigned)r12) < ((unsigned)r13) ) goto label$fe4f13c_4_175;
	hl_types_ArrayBytes_Float___expand(r18,r12);
	label$fe4f13c_4_175:
	r20 = r18->bytes;
	r13 = 3;
	r13 = r12 << r13;
	*(double*)(r20 + r13) = r3;
	r6 = 0.;
	r12 = 0;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r13 = r4->DIF_COUNT;
	label$fe4f13c_4_183:
	if( r12 >= r13 ) goto label$fe4f13c_4_201;
	r14 = r12;
	++r12;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r18 = r4->deltas;
	if( r18 == NULL ) hl_null_access();
	r17 = r18->length;
	if( ((unsigned)r14) < ((unsigned)r17) ) goto label$fe4f13c_4_194;
	r9 = 0.;
	goto label$fe4f13c_4_198;
	label$fe4f13c_4_194:
	r20 = r18->bytes;
	r17 = 3;
	r17 = r14 << r17;
	r9 = *(double*)(r20 + r17);
	label$fe4f13c_4_198:
	r7 = r6 + r9;
	r6 = r7;
	goto label$fe4f13c_4_183;
	label$fe4f13c_4_201:
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r12 = r4->DIF_COUNT;
	r9 = (double)r12;
	r7 = r6 / r9;
	r6 = r7;
	r7 = r5 + r6;
	r5 = r7;
	label$fe4f13c_4_208:
	goto label$fe4f13c_4_211;
	label$fe4f13c_4_209:
	r6 = r5 + r3;
	r5 = r6;
	label$fe4f13c_4_211:
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r4->lastTime = r2;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r11 = r4->stopped;
	if( r11 ) goto label$fe4f13c_4_218;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r4->lastFrameEnd = r5;
	label$fe4f13c_4_218:
	r12 = 0;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r23 = r4->pausedTimeTasks;
	label$fe4f13c_4_221:
	if( r23 == NULL ) hl_null_access();
	r14 = r23->length;
	if( r12 >= r14 ) goto label$fe4f13c_4_238;
	r14 = r23->length;
	if( ((unsigned)r12) < ((unsigned)r14) ) goto label$fe4f13c_4_229;
	r25 = NULL;
	goto label$fe4f13c_4_232;
	label$fe4f13c_4_229:
	r26 = r23->array;
	r15 = ((vdynamic**)(r26 + 1))[r12];
	r25 = (kha__TimeTask)r15;
	label$fe4f13c_4_232:
	++r12;
	if( r25 == NULL ) hl_null_access();
	r6 = r25->next;
	r6 = r6 + r3;
	r25->next = r6;
	goto label$fe4f13c_4_221;
	label$fe4f13c_4_238:
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r11 = r4->stopped;
	if( !r11 ) goto label$fe4f13c_4_261;
	r12 = 0;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r23 = r4->timeTasks;
	label$fe4f13c_4_244:
	if( r23 == NULL ) hl_null_access();
	r14 = r23->length;
	if( r12 >= r14 ) goto label$fe4f13c_4_261;
	r14 = r23->length;
	if( ((unsigned)r12) < ((unsigned)r14) ) goto label$fe4f13c_4_252;
	r25 = NULL;
	goto label$fe4f13c_4_255;
	label$fe4f13c_4_252:
	r26 = r23->array;
	r15 = ((vdynamic**)(r26 + 1))[r12];
	r25 = (kha__TimeTask)r15;
	label$fe4f13c_4_255:
	++r12;
	if( r25 == NULL ) hl_null_access();
	r6 = r25->next;
	r6 = r6 + r3;
	r25->next = r6;
	goto label$fe4f13c_4_244;
	label$fe4f13c_4_261:
	kha_Scheduler_executeTimeTasks(r5);
	r12 = 0;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r23 = r4->outdatedTimeTasks;
	label$fe4f13c_4_265:
	if( r23 == NULL ) hl_null_access();
	r14 = r23->length;
	if( r12 >= r14 ) goto label$fe4f13c_4_287;
	r14 = r23->length;
	if( ((unsigned)r12) < ((unsigned)r14) ) goto label$fe4f13c_4_273;
	r25 = NULL;
	goto label$fe4f13c_4_276;
	label$fe4f13c_4_273:
	r26 = r23->array;
	r15 = ((vdynamic**)(r26 + 1))[r12];
	r25 = (kha__TimeTask)r15;
	label$fe4f13c_4_276:
	++r12;
	if( r25 == NULL ) hl_null_access();
	r6 = r25->next;
	r9 = 10.;
	r7 = r5 - r9;
	if( !(r6 < r7) ) goto label$fe4f13c_4_286;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r24 = r4->timeTasksScratchpad;
	if( r24 == NULL ) hl_null_access();
	r13 = hl_types_ArrayObj_push(r24,((vdynamic*)r25));
	label$fe4f13c_4_286:
	goto label$fe4f13c_4_265;
	label$fe4f13c_4_287:
	r12 = 0;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r23 = r4->timeTasksScratchpad;
	label$fe4f13c_4_290:
	if( r23 == NULL ) hl_null_access();
	r14 = r23->length;
	if( r12 >= r14 ) goto label$fe4f13c_4_307;
	r14 = r23->length;
	if( ((unsigned)r12) < ((unsigned)r14) ) goto label$fe4f13c_4_298;
	r25 = NULL;
	goto label$fe4f13c_4_301;
	label$fe4f13c_4_298:
	r26 = r23->array;
	r15 = ((vdynamic**)(r26 + 1))[r12];
	r25 = (kha__TimeTask)r15;
	label$fe4f13c_4_301:
	++r12;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r24 = r4->outdatedTimeTasks;
	if( r24 == NULL ) hl_null_access();
	r11 = hl_types_ArrayObj_remove(r24,((vdynamic*)r25));
	goto label$fe4f13c_4_290;
	label$fe4f13c_4_307:
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r23 = r4->timeTasksScratchpad;
	if( r23 == NULL ) hl_null_access();
	r12 = r23->length;
	r13 = 0;
	if( r13 >= r12 ) goto label$fe4f13c_4_330;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r23 = r4->timeTasksScratchpad;
	if( r23 == NULL ) hl_null_access();
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r24 = r4->timeTasksScratchpad;
	if( r24 == NULL ) hl_null_access();
	r12 = 0;
	r13 = r24->length;
	if( ((unsigned)r12) < ((unsigned)r13) ) goto label$fe4f13c_4_325;
	r25 = NULL;
	goto label$fe4f13c_4_328;
	label$fe4f13c_4_325:
	r26 = r24->array;
	r15 = ((vdynamic**)(r26 + 1))[r12];
	r25 = (kha__TimeTask)r15;
	label$fe4f13c_4_328:
	r11 = hl_types_ArrayObj_remove(r23,((vdynamic*)r25));
	goto label$fe4f13c_4_307;
	label$fe4f13c_4_330:
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r4->current = r5;
	kha_Scheduler_sortFrameTasks();
	r12 = 0;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r23 = r4->frameTasks;
	label$fe4f13c_4_336:
	if( r23 == NULL ) hl_null_access();
	r14 = r23->length;
	if( r12 >= r14 ) goto label$fe4f13c_4_363;
	r14 = r23->length;
	if( ((unsigned)r12) < ((unsigned)r14) ) goto label$fe4f13c_4_344;
	r27 = NULL;
	goto label$fe4f13c_4_347;
	label$fe4f13c_4_344:
	r26 = r23->array;
	r15 = ((vdynamic**)(r26 + 1))[r12];
	r27 = (kha__FrameTask)r15;
	label$fe4f13c_4_347:
	++r12;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r11 = r4->stopped;
	if( r11 ) goto label$fe4f13c_4_362;
	if( r27 == NULL ) hl_null_access();
	r11 = r27->paused;
	if( r11 ) goto label$fe4f13c_4_362;
	r11 = r27->active;
	if( !r11 ) goto label$fe4f13c_4_362;
	r28 = r27->task;
	if( r28 == NULL ) hl_null_access();
	r11 = r28->hasValue ? ((bool (*)(vdynamic*))r28->fun)((vdynamic*)r28->value) : ((bool (*)(void))r28->fun)();
	if( r11 ) goto label$fe4f13c_4_362;
	r11 = false;
	r27->active = r11;
	label$fe4f13c_4_362:
	goto label$fe4f13c_4_336;
	label$fe4f13c_4_363:
	r12 = 0;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r23 = r4->frameTasks;
	label$fe4f13c_4_366:
	if( r23 == NULL ) hl_null_access();
	r14 = r23->length;
	if( r12 >= r14 ) goto label$fe4f13c_4_386;
	r14 = r23->length;
	if( ((unsigned)r12) < ((unsigned)r14) ) goto label$fe4f13c_4_374;
	r27 = NULL;
	goto label$fe4f13c_4_377;
	label$fe4f13c_4_374:
	r26 = r23->array;
	r15 = ((vdynamic**)(r26 + 1))[r12];
	r27 = (kha__FrameTask)r15;
	label$fe4f13c_4_377:
	++r12;
	if( r27 == NULL ) hl_null_access();
	r11 = r27->active;
	if( r11 ) goto label$fe4f13c_4_385;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r24 = r4->toDeleteFrame;
	if( r24 == NULL ) hl_null_access();
	r13 = hl_types_ArrayObj_push(r24,((vdynamic*)r27));
	label$fe4f13c_4_385:
	goto label$fe4f13c_4_366;
	label$fe4f13c_4_386:
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r23 = r4->toDeleteFrame;
	if( r23 == NULL ) hl_null_access();
	r12 = r23->length;
	r13 = 0;
	if( r13 >= r12 ) goto label$fe4f13c_4_403;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r23 = r4->frameTasks;
	if( r23 == NULL ) hl_null_access();
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r24 = r4->toDeleteFrame;
	if( r24 == NULL ) hl_null_access();
	r15 = hl_types_ArrayObj_pop(r24);
	r27 = (kha__FrameTask)r15;
	r11 = hl_types_ArrayObj_remove(r23,((vdynamic*)r27));
	goto label$fe4f13c_4_386;
	label$fe4f13c_4_403:
	return;
}

void kha_Scheduler_executeTimeTasks(double r0) {
	hl__types__ArrayObj r2;
	bool r12;
	kha__$Scheduler r3;
	kha__TimeTask r5, r11;
	vclosure *r13;
	double r9, r10, r14;
	vdynamic *r6;
	varray *r7;
	int r1, r4;
	label$fe4f13c_5_0:
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r2 = r3->timeTasks;
	if( r2 == NULL ) hl_null_access();
	r1 = r2->length;
	r4 = 0;
	if( r4 >= r1 ) goto label$fe4f13c_5_106;
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r2 = r3->timeTasks;
	if( r2 == NULL ) hl_null_access();
	r1 = 0;
	r4 = r2->length;
	if( ((unsigned)r1) < ((unsigned)r4) ) goto label$fe4f13c_5_15;
	r5 = NULL;
	goto label$fe4f13c_5_18;
	label$fe4f13c_5_15:
	r7 = r2->array;
	r6 = ((vdynamic**)(r7 + 1))[r1];
	r5 = (kha__TimeTask)r6;
	label$fe4f13c_5_18:
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r3->activeTimeTask = r5;
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r5 = r3->activeTimeTask;
	if( r5 == NULL ) hl_null_access();
	r9 = r5->next;
	if( !(r0 >= r9) ) goto label$fe4f13c_5_104;
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r5 = r3->activeTimeTask;
	if( r5 == NULL ) hl_null_access();
	r9 = r5->next;
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r3->current = r9;
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r5 = r3->activeTimeTask;
	if( r5 == NULL ) hl_null_access();
	r9 = r5->next;
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r11 = r3->activeTimeTask;
	if( r11 == NULL ) hl_null_access();
	r10 = r11->period;
	r9 = r9 + r10;
	r5->next = r9;
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r2 = r3->timeTasks;
	if( r2 == NULL ) hl_null_access();
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r5 = r3->activeTimeTask;
	r12 = hl_types_ArrayObj_remove(r2,((vdynamic*)r5));
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r5 = r3->activeTimeTask;
	if( r5 == NULL ) hl_null_access();
	r12 = r5->active;
	if( !r12 ) goto label$fe4f13c_5_95;
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r5 = r3->activeTimeTask;
	if( r5 == NULL ) hl_null_access();
	r13 = r5->task;
	if( r13 == NULL ) hl_null_access();
	r12 = r13->hasValue ? ((bool (*)(vdynamic*))r13->fun)((vdynamic*)r13->value) : ((bool (*)(void))r13->fun)();
	if( !r12 ) goto label$fe4f13c_5_95;
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r5 = r3->activeTimeTask;
	if( r5 == NULL ) hl_null_access();
	r9 = r5->period;
	r10 = 0.;
	if( !(r10 < r9) ) goto label$fe4f13c_5_91;
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r5 = r3->activeTimeTask;
	if( r5 == NULL ) hl_null_access();
	r9 = r5->duration;
	r10 = 0.;
	if( r9 == r10 ) goto label$fe4f13c_5_85;
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r5 = r3->activeTimeTask;
	if( r5 == NULL ) hl_null_access();
	r9 = r5->duration;
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r5 = r3->activeTimeTask;
	if( r5 == NULL ) hl_null_access();
	r10 = r5->start;
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r5 = r3->activeTimeTask;
	if( r5 == NULL ) hl_null_access();
	r14 = r5->next;
	r10 = r10 + r14;
	if( !(r9 >= r10) ) goto label$fe4f13c_5_91;
	label$fe4f13c_5_85:
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r2 = r3->timeTasks;
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r5 = r3->activeTimeTask;
	kha_Scheduler_insertSorted(r2,r5);
	goto label$fe4f13c_5_94;
	label$fe4f13c_5_91:
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r5 = r3->activeTimeTask;
	kha_Scheduler_archiveTimeTask(r5,r0);
	label$fe4f13c_5_94:
	goto label$fe4f13c_5_103;
	label$fe4f13c_5_95:
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r5 = r3->activeTimeTask;
	if( r5 == NULL ) hl_null_access();
	r12 = false;
	r5->active = r12;
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r5 = r3->activeTimeTask;
	kha_Scheduler_archiveTimeTask(r5,r0);
	label$fe4f13c_5_103:
	goto label$fe4f13c_5_105;
	label$fe4f13c_5_104:
	goto label$fe4f13c_5_106;
	label$fe4f13c_5_105:
	goto label$fe4f13c_5_0;
	label$fe4f13c_5_106:
	r5 = NULL;
	r3 = (kha__$Scheduler)g$_kha_Scheduler;
	r3->activeTimeTask = r5;
	return;
}

void kha_Scheduler_archiveTimeTask(kha__TimeTask r0,double r1) {
	return;
}

double kha_Scheduler_time() {
	kha__$Scheduler r1;
	double r0;
	r1 = (kha__$Scheduler)g$_kha_Scheduler;
	r0 = r1->current;
	return r0;
}

double kha_Scheduler_realTime() {
	double r0;
	r0 = kha_System_get_time();
	return r0;
}

void kha_Scheduler_resetTime() {
	hl__types__ArrayObj r6;
	kha__$Scheduler r4;
	hl__types__ArrayBytes_Float r12;
	kha__TimeTask r9;
	double r0, r2, r3;
	vdynamic *r10;
	vbyte *r14;
	varray *r11;
	int r5, r7, r8, r13;
	r0 = kha_System_get_time();
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r3 = r4->startTime;
	r2 = r0 - r3;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r4->startTime = r0;
	r5 = 0;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r6 = r4->timeTasks;
	label$fe4f13c_9_9:
	if( r6 == NULL ) hl_null_access();
	r8 = r6->length;
	if( r5 >= r8 ) goto label$fe4f13c_9_29;
	r8 = r6->length;
	if( ((unsigned)r5) < ((unsigned)r8) ) goto label$fe4f13c_9_17;
	r9 = NULL;
	goto label$fe4f13c_9_20;
	label$fe4f13c_9_17:
	r11 = r6->array;
	r10 = ((vdynamic**)(r11 + 1))[r5];
	r9 = (kha__TimeTask)r10;
	label$fe4f13c_9_20:
	++r5;
	if( r9 == NULL ) hl_null_access();
	r3 = r9->start;
	r3 = r3 - r2;
	r9->start = r3;
	r3 = r9->next;
	r3 = r3 - r2;
	r9->next = r3;
	goto label$fe4f13c_9_9;
	label$fe4f13c_9_29:
	r5 = 0;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r7 = r4->DIF_COUNT;
	label$fe4f13c_9_32:
	if( r5 >= r7 ) goto label$fe4f13c_9_48;
	r8 = r5;
	++r5;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r12 = r4->deltas;
	if( r12 == NULL ) hl_null_access();
	r3 = 0.;
	r13 = r12->length;
	if( ((unsigned)r8) < ((unsigned)r13) ) goto label$fe4f13c_9_43;
	hl_types_ArrayBytes_Float___expand(r12,r8);
	label$fe4f13c_9_43:
	r14 = r12->bytes;
	r13 = 3;
	r13 = r8 << r13;
	*(double*)(r14 + r13) = r3;
	goto label$fe4f13c_9_32;
	label$fe4f13c_9_48:
	r3 = 0.;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r4->current = r3;
	r3 = 0.;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r4->lastTime = r3;
	r3 = 0.;
	r4 = (kha__$Scheduler)g$_kha_Scheduler;
	r4->lastFrameEnd = r3;
	return;
}

int kha_Scheduler_addBreakableTimeTaskToGroup(int r0,vclosure* r1,double r2,double* r3,double* r4) {
	hl__types__ArrayObj r14;
	kha__$Scheduler r10;
	bool r9;
	kha__TimeTask r7;
	double r5, r6, r12, r13;
	int r11;
	if( r3 ) goto label$fe4f13c_10_3;
	r5 = 0.;
	goto label$fe4f13c_10_4;
	label$fe4f13c_10_3:
	r5 = *r3;
	label$fe4f13c_10_4:
	if( r4 ) goto label$fe4f13c_10_7;
	r6 = 0.;
	goto label$fe4f13c_10_8;
	label$fe4f13c_10_7:
	r6 = *r4;
	label$fe4f13c_10_8:
	r7 = (kha__TimeTask)hl_alloc_obj(&t$kha_TimeTask);
	kha_TimeTask_new(r7);
	r9 = true;
	r7->active = r9;
	r7->task = r1;
	r10 = (kha__$Scheduler)g$_kha_Scheduler;
	r11 = r10->currentTimeTaskId;
	++r11;
	r10->currentTimeTaskId = r11;
	r7->id = r11;
	r7->groupId = r0;
	r10 = (kha__$Scheduler)g$_kha_Scheduler;
	r12 = r10->current;
	r12 = r12 + r2;
	r7->start = r12;
	r12 = 0.;
	r7->period = r12;
	r13 = 0.;
	if( r5 == r13 ) goto label$fe4f13c_10_28;
	r7->period = r5;
	label$fe4f13c_10_28:
	r12 = 0.;
	r7->duration = r12;
	r13 = 0.;
	if( r6 == r13 ) goto label$fe4f13c_10_35;
	r12 = r7->start;
	r12 = r12 + r6;
	r7->duration = r12;
	label$fe4f13c_10_35:
	r12 = r7->start;
	r7->next = r12;
	r10 = (kha__$Scheduler)g$_kha_Scheduler;
	r14 = r10->timeTasks;
	kha_Scheduler_insertSorted(r14,r7);
	r11 = r7->id;
	return r11;
}

int kha_Scheduler_addTimeTaskToGroup(int r0,vclosure* r1,double r2,double* r3,double* r4) {
	vclosure *r8;
	double r5, r6, r9, r10;
	int r7;
	if( r3 ) goto label$fe4f13c_11_3;
	r5 = 0.;
	goto label$fe4f13c_11_4;
	label$fe4f13c_11_3:
	r5 = *r3;
	label$fe4f13c_11_4:
	if( r4 ) goto label$fe4f13c_11_7;
	r6 = 0.;
	goto label$fe4f13c_11_8;
	label$fe4f13c_11_7:
	r6 = *r4;
	label$fe4f13c_11_8:
	r8 = hl_alloc_closure_ptr(&t$fun_3c2375f,kha_Scheduler_addTimeTaskToGroup__$1,r1);
	r9 = r5;
	r3 = &r9;
	r10 = r6;
	r4 = &r10;
	r7 = kha_Scheduler_addBreakableTimeTaskToGroup(r0,r8,r2,r3,r4);
	return r7;
}

bool kha_Scheduler_addTimeTaskToGroup__$1(vclosure* r0) {
	bool r2;
	if( r0 == NULL ) hl_null_access();
	r0->hasValue ? ((void (*)(vdynamic*))r0->fun)((vdynamic*)r0->value) : ((void (*)(void))r0->fun)();
	r2 = true;
	return r2;
}

int kha_Scheduler_addTimeTask(vclosure* r0,double r1,double* r2,double* r3) {
	double r4, r5, r7, r8;
	int r6;
	if( r2 ) goto label$fe4f13c_13_3;
	r4 = 0.;
	goto label$fe4f13c_13_4;
	label$fe4f13c_13_3:
	r4 = *r2;
	label$fe4f13c_13_4:
	if( r3 ) goto label$fe4f13c_13_7;
	r5 = 0.;
	goto label$fe4f13c_13_8;
	label$fe4f13c_13_7:
	r5 = *r3;
	label$fe4f13c_13_8:
	r6 = 0;
	r7 = r4;
	r2 = &r7;
	r8 = r5;
	r3 = &r8;
	r6 = kha_Scheduler_addTimeTaskToGroup(r6,r0,r1,r2,r3);
	return r6;
}

void kha_Scheduler_insertSorted(hl__types__ArrayObj r0,kha__TimeTask r1) {
	kha__TimeTask r8;
	double r6, r11;
	vdynamic *r9;
	varray *r10;
	int r2, r4, r5, r7;
	r2 = 0;
	if( r0 == NULL ) hl_null_access();
	r4 = r0->length;
	label$fe4f13c_14_3:
	if( r2 >= r4 ) goto label$fe4f13c_14_23;
	r5 = r2;
	++r2;
	if( r0 == NULL ) hl_null_access();
	r7 = r0->length;
	if( ((unsigned)r5) < ((unsigned)r7) ) goto label$fe4f13c_14_12;
	r8 = NULL;
	goto label$fe4f13c_14_15;
	label$fe4f13c_14_12:
	r10 = r0->array;
	r9 = ((vdynamic**)(r10 + 1))[r5];
	r8 = (kha__TimeTask)r9;
	label$fe4f13c_14_15:
	if( r8 == NULL ) hl_null_access();
	r6 = r8->next;
	if( r1 == NULL ) hl_null_access();
	r11 = r1->next;
	if( !(r11 < r6) ) goto label$fe4f13c_14_22;
	hl_types_ArrayObj_insert(r0,r5,((vdynamic*)r1));
	return;
	label$fe4f13c_14_22:
	goto label$fe4f13c_14_3;
	label$fe4f13c_14_23:
	if( r0 == NULL ) hl_null_access();
	r2 = hl_types_ArrayObj_push(r0,((vdynamic*)r1));
	return;
}

int kha_Scheduler_sortFrameTasks__$1(kha__FrameTask r0,kha__FrameTask r1) {
	int r2, r3;
	if( r0 == NULL ) hl_null_access();
	r2 = r0->priority;
	if( r1 == NULL ) hl_null_access();
	r3 = r1->priority;
	if( r3 >= r2 ) goto label$fe4f13c_15_7;
	r2 = 1;
	return r2;
	label$fe4f13c_15_7:
	r2 = r0->priority;
	r3 = r1->priority;
	if( r2 >= r3 ) goto label$fe4f13c_15_12;
	r2 = -1;
	return r2;
	label$fe4f13c_15_12:
	r2 = 0;
	return r2;
}

void kha_Scheduler_sortFrameTasks() {
	hl__types__ArrayObj r3;
	kha__$Scheduler r2;
	bool r1;
	vclosure *r4, *r5;
	static vclosure cl$0 = { &t$fun_5ae4454, kha_Scheduler_sortFrameTasks__$1, 0 };
	r2 = (kha__$Scheduler)g$_kha_Scheduler;
	r1 = r2->frame_tasks_sorted;
	if( !r1 ) goto label$fe4f13c_16_4;
	return;
	label$fe4f13c_16_4:
	r2 = (kha__$Scheduler)g$_kha_Scheduler;
	r3 = r2->frameTasks;
	if( r3 == NULL ) hl_null_access();
	r4 = &cl$0;
	if( r4 ) goto label$fe4f13c_16_11;
	r5 = NULL;
	goto label$fe4f13c_16_12;
	label$fe4f13c_16_11:
	r5 = hl_alloc_closure_ptr(&t$fun_dee1a83,kha_Scheduler_sortFrameTasks__$2,r4);
	label$fe4f13c_16_12:
	hl_types_ArrayObj_sort(r3,r5);
	r1 = true;
	r2 = (kha__$Scheduler)g$_kha_Scheduler;
	r2->frame_tasks_sorted = r1;
	return;
}

