// Generated by HLC 4.2.5 (HL v4)
#ifndef INC_kha__Storage
#define INC_kha__Storage
typedef struct _kha__$Storage *kha__$Storage;
typedef struct _kha__Storage *kha__Storage;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <kha/StorageFile.h>


struct _kha__$Storage {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	vclosure* namedFile;
	vclosure* defaultFile;
};
struct _kha__Storage {
	hl_type *$type;
};
#endif

