// Generated by HLC 4.2.5 (HL v4)
#ifndef INC_kha__System
#define INC_kha__System
typedef struct _kha__$System *kha__$System;
typedef struct _kha__System *kha__System;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <hl/types/ArrayObj.h>
#include <kha/SystemOptions.h>
#include <kha/Window.h>


struct _kha__$System {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	hl__types__ArrayObj renderListeners;
	hl__types__ArrayObj foregroundListeners;
	hl__types__ArrayObj resumeListeners;
	hl__types__ArrayObj pauseListeners;
	hl__types__ArrayObj backgroundListeners;
	hl__types__ArrayObj shutdownListeners;
	hl__types__ArrayObj dropFilesListeners;
	vclosure* cutListener;
	vclosure* copyListener;
	vclosure* pasteListener;
	String theTitle;
	vclosure* start;
	vclosure* notifyOnFrames;
	vclosure* notifyOnApplicationState;
	vclosure* notifyOnCutCopyPaste;
	vclosure* render;
	vclosure* foreground;
	vclosure* resume;
	vclosure* pause;
	vclosure* background;
	vclosure* shutdown;
	vclosure* dropFiles;
	double time;
	vclosure* get_time;
	vclosure* windowWidth;
	vclosure* windowHeight;
};
struct _kha__System {
	hl_type *$type;
};
#endif

