// Generated by HLC 4.2.5 (HL v4)
#ifndef INC_kha__SystemImpl
#define INC_kha__SystemImpl
typedef struct _kha__$SystemImpl *kha__$SystemImpl;
typedef struct _kha__SystemImpl *kha__SystemImpl;
#include <hl/Class.h>
#include <hl/BaseType.h>
#include <_std/String.h>
#include <kha/Framebuffer.h>
#include <kha/input/Keyboard.h>
#include <kha/input/Mouse.h>
#include <kha/input/Pen.h>
#include <hl/types/ArrayObj.h>
#include <kha/input/Surface.h>
#include <kha/SystemOptions.h>
#include <kha/Window.h>


struct _kha__$SystemImpl {
	hl_type *$type;
	hl_type* __type__;
	vdynamic* __meta__;
	varray* __implementedBy__;
	String __name__;
	vdynamic* __constructor__;
	kha__Framebuffer framebuffer;
	kha__input__Keyboard keyboard;
	kha__input__Mouse mouse;
	kha__input__Pen pen;
	hl__types__ArrayObj gamepads;
	kha__input__Surface surface;
	hl__types__ArrayObj mouseLockListeners;
	vclosure* init;
	vclosure* frame;
	vclosure* getTime;
	vclosure* windowWidth;
	vclosure* windowHeight;
	vclosure* getMouse;
	vclosure* getPen;
	vclosure* getKeyboard;
	vclosure* lockMouse;
	vclosure* unlockMouse;
	vclosure* canLockMouse;
	vclosure* isMouseLocked;
	vclosure* notifyOfMouseLockChange;
	vclosure* removeFromMouseLockChange;
	vclosure* hideSystemCursor;
	vclosure* showSystemCursor;
	vclosure* keyDown;
	vclosure* keyUp;
	vclosure* keyPress;
	vclosure* mouseDown;
	vclosure* mouseUp;
	vclosure* mouseMove;
	vclosure* mouseWheel;
	vclosure* penDown;
	vclosure* penUp;
	vclosure* penMove;
	vclosure* gamepadAxis;
	vclosure* gamepadButton;
	vclosure* touchStart;
	vclosure* touchEnd;
	vclosure* touchMove;
	vclosure* foreground;
	vclosure* resume;
	vclosure* pause;
	vclosure* background;
	vclosure* shutdown;
	vclosure* dropFiles;
	vclosure* copy;
	vclosure* cut;
	vclosure* paste;
	vclosure* getGamepadId;
	vclosure* getGamepadVendor;
	vclosure* setGamepadRumble;
};
struct _kha__SystemImpl {
	hl_type *$type;
};
#endif

